/** F07: cdflib owns CDF decoding; cssEarth pins bytes and preserves native TT2000/frequency coordinates. */
import {createHash} from 'node:crypto';import {spawn} from 'node:child_process';import {readFile} from 'node:fs/promises';
import {astroqueryToolchain} from '../../astronomy-packages/toolchain.mts';import type {FamilyHandler,FamilyOperation} from '../family-handlers.mts';import type {DescriptorMember,ProductDescriptor} from '../product-descriptor.mts';import {descriptor,stable} from './common.mts';
export const WIND_RAD1_FIXTURE={url:'https://spdf.gsfc.nasa.gov/pub/data/wind/waves/rad1_l2/2020/wi_l2_wav_rad1_20200101_v01.cdf',variable:'PSD_V2_S'} as const;
export interface CdfPin{readonly path:string} export interface DynamicSpectrum{readonly epochsTt2000:readonly string[];readonly frequencyHz:readonly number[];readonly psd:readonly (readonly (number|null)[])[];readonly unit:string;readonly cdflib:string}
const python=String.raw`import cdflib,json,sys,numpy as np
r=json.load(sys.stdin); c=cdflib.CDF(r['path'])
for n in ('Epoch','FREQUENCY','PSD_V2_S'):
 if n not in c.cdf_info().zVariables: raise ValueError('Missing required CDF variable '+n)
e=np.asarray(c.varget('Epoch')); f=np.asarray(c.varget('FREQUENCY')); p=np.asarray(c.varget('PSD_V2_S'))
if e.ndim!=1 or f.ndim!=1 or p.shape!=(len(e),len(f)): raise ValueError('Epoch/FREQUENCY/PSD_V2_S shape mismatch')
if not np.isfinite(f).all(): raise ValueError('Non-finite native CDF frequency coordinate')
a=c.varattsget('PSD_V2_S'); json.dump({'cdflib':cdflib.__version__,'epochsTt2000':[str(int(x)) for x in e],'frequencyHz':f.astype(float).tolist(),'psd':[[None if not np.isfinite(x) else float(x) for x in row] for row in p],'unit':str(a.get('UNITS',''))},sys.stdout,allow_nan=False)`;
async function run(path:string):Promise<DynamicSpectrum>{const tc=await astroqueryToolchain();return await new Promise((done,fail)=>{const child=spawn(tc.python,['-c',python],{env:{...process.env,...tc.env},stdio:['pipe','pipe','pipe']});let out='',err='';child.stdout.setEncoding('utf8').on('data',s=>out+=s);child.stderr.setEncoding('utf8').on('data',s=>err+=s);child.on('error',fail);child.on('close',code=>{if(code!==0)return fail(new Error(`cdflib CDF decode failed: ${err.slice(-1000)}`));try{const value=JSON.parse(out) as DynamicSpectrum;if(value.cdflib!==tc.cdflibVersion)throw new Error('Unexpected cdflib version.');done(value);}catch(error){fail(error);}});child.stdin.end(JSON.stringify({path}));});}
export async function inspectWindRad1(pin:CdfPin):Promise<DynamicSpectrum>{return run(pin.path);}
export function selectDynamicSpectrum(value:DynamicSpectrum,selection:{readonly time:[number,number];readonly frequency:[number,number]}){const [t0,t1]=selection.time,[f0,f1]=selection.frequency;if(!Number.isInteger(t0)||!Number.isInteger(t1)||!Number.isInteger(f0)||!Number.isInteger(f1)||t0<0||f0<0||t1<=t0||f1<=f0||t1>value.epochsTt2000.length||f1>value.frequencyHz.length)throw new RangeError('Selection must be increasing in-bounds native indices.');return{epochsTt2000:value.epochsTt2000.slice(t0,t1),frequencyHz:value.frequencyHz.slice(f0,f1),psd:value.psd.slice(t0,t1).map(row=>row.slice(f0,f1)),unit:value.unit};}
export function dynamicSpectrumSpectrum(value:DynamicSpectrum,timeIndex:number){if(!Number.isInteger(timeIndex)||timeIndex<0||timeIndex>=value.epochsTt2000.length)throw new RangeError('Spectrum time index is outside the native dynamic spectrum.');return{epochTt2000:value.epochsTt2000[timeIndex]!,frequencyHz:value.frequencyHz,psd:value.psd[timeIndex]!,unit:value.unit};}
export function dynamicSpectrumTimeSeries(value:DynamicSpectrum,frequencyIndex:number){if(!Number.isInteger(frequencyIndex)||frequencyIndex<0||frequencyIndex>=value.frequencyHz.length)throw new RangeError('Time-series frequency index is outside the native dynamic spectrum.');return{frequencyHz:value.frequencyHz[frequencyIndex]!,epochsTt2000:value.epochsTt2000,psd:value.psd.map(row=>row[frequencyIndex]??null),unit:value.unit};}
export function exportDynamicSpectrumCsv(value:ReturnType<typeof selectDynamicSpectrum>):string{return['epoch_tt2000,frequency_hz,psd',...value.epochsTt2000.flatMap((epoch,row)=>value.frequencyHz.map((frequency,column)=>`${epoch},${frequency},${value.psd[row]![column]??''}`))].join('\n')+'\n';}
export function describeWindRad1(input:{readonly id:string;readonly member:DescriptorMember;readonly producingRecord:string;readonly timeLength:number;readonly frequencyLength:number}):ProductDescriptor{return descriptor({schema:'cssearth-telescope-product-descriptor@1',dataset:{id:stable(input.id,'dynamic spectrum id'),acquisition:{kind:'archive',identity:WIND_RAD1_FIXTURE.url},producingRecord:input.producingRecord,sourceClassifications:[{term:'dynamic spectrum',vocabulary:'NASA SPDF CDF',version:'CDF 3.9',status:'source'}],families:['F07'],profiles:[{handlerId:'f07-dynamic-spectrum',profileId:'wind-rad1-cdf@1'}]},members:[input.member],components:[{id:'dynamic-spectrum',name:'Wind/WAVES RAD1 PSD_V2_S',families:['F07'],locations:[{memberId:input.member.id,structure:'PSD_V2_S'}],representation:{kind:'array',shape:[input.timeLength,input.frequencyLength],storageOrder:'native'},axes:[{id:'time',index:0,length:input.timeLength,role:'time',unit:'TT2000 ns',coordinates:{kind:'lookup',memberId:input.member.id,locator:'Epoch',binBounds:false}},{id:'frequency',index:1,length:input.frequencyLength,role:'spectral',unit:'Hz',coordinates:{kind:'lookup',memberId:input.member.id,locator:'FREQUENCY',binBounds:false}}],columns:[],quantity:{name:'power spectral density',semantics:'Native PSD_V2_S; Epoch and FREQUENCY arrays are retained without cadence/grid interpolation.',unit:'V^2/Hz'},calibration:{state:'archive-calibrated',basis:['NASA SPDF Wind/WAVES Level 2 CDF variables.']},flags:[{id:'cdf-fill',meaning:'Source CDF non-finite/fill PSD cell',usableWhen:'Preserve as missing; never turn into zero.'}],dependencyIds:[]}],dependencies:[],issues:[]});}
const op=(id:string,label:string,owner:string,parameters:any[]):FamilyOperation=>({id,label,handlerId:'f07-dynamic-spectrum',componentId:'dynamic-spectrum',owner:{module:'tools/objects/telescopes/families/f07-dynamic-spectrum.mts',export:owner},available:true,reason:'Pinned CDF decoded by cdflib 1.3.12 with native coordinates retained.',fixedArguments:{},parameters:[...parameters,{id:'out',option:'--out',kind:'output-directory',required:true,description:'New output directory.'}],limitations:['No uniform cadence, frequency grid, or calibration beyond source CDF variables is invented.']});
export const F07_DYNAMIC_SPECTRUM_HANDLER:FamilyHandler={id:'f07-dynamic-spectrum',families:['F07'],profiles:[{id:'wind-rad1-cdf@1',format:'NASA CDF Wind/WAVES RAD1 Level 2',version:'cdflib 1.3.12',families:['F07'],publicBaseline:true,evidence:[{path:'tests/fixtures/telescope-families/wind-rad1/wi_l2_wav_rad1_20200101_v01.cdf',establishes:'Pinned authentic Wind/WAVES RAD1 CDF.',status:'complete'}]}],recognizes:m=>m.some(x=>x.path.endsWith('.cdf'))?['wind-rad1-cdf@1']:[],operations:()=>[op('dynamic-spectrum-inspect','Inspect dynamic spectrum','inspectWindRad1',[]),op('dynamic-spectrum-select','Select native time/frequency window','selectDynamicSpectrum',[{id:'selection',option:'--selection',kind:'number-list',required:true,count:4,description:'T0,T1,F0,F1 native indices.'}]),op('dynamic-spectrum-spectrum','Select one native time to spectrum','dynamicSpectrumSpectrum',[{id:'time-index',option:'--time-index',kind:'integer',required:true,minimum:0,description:'Native time index.'}]),op('dynamic-spectrum-time-series','Select one native frequency to time series','dynamicSpectrumTimeSeries',[{id:'frequency-index',option:'--frequency-index',kind:'integer',required:true,minimum:0,description:'Native frequency index.'}]),op('dynamic-spectrum-export','Export selected values','exportDynamicSpectrumCsv',[{id:'selection',option:'--selection',kind:'number-list',required:true,count:4,description:'T0,T1,F0,F1 native indices.'}])]};
