import assert from'node:assert/strict';import{test}from'node:test';import{readFile}from'node:fs/promises';import{resolve}from'node:path';import{member}from'./common.mts';import{astrometryOffsetData,astrometryTrackData,describeAstrometry,positionCovariance,readAstrometryCsv,exportAstrometryCsv,F09_ASTROMETRY_HANDLER,propagateAstrometry,selectAstrometryRows}from'./f09-astrometry.mts';
const root=resolve(import.meta.dirname,'../../../..'),path='src/objects/m1/source/stellar-field.json',bytes=await readFile(resolve(root,path)),source=JSON.parse(bytes.toString()) as any,rows=source.stars.map((star:any)=>({id:star.sourceId,raDeg:star.raDeg,decDeg:star.decDeg,epochJulianYear:source.coordinateEpochJulianYear,pmRaCosDecMasYr:star.pmRaMasYr,pmDecMasYr:star.pmDecMasYr,parallaxMas:star.parallaxMas,parallaxErrorMas:star.parallaxErrorMas}));
test('F09 describes and exports the pinned Gaia field with IDs, frame, epoch and uncertainties',()=>{const product=describeAstrometry({id:'m1-gaia-field',target:'m1',member:member('gaia-field',path,'science',bytes,'application/json'),rows,frame:'ICRS',epochJulianYear:source.coordinateEpochJulianYear,producingRecord:path,calibrationBasis:[source.provenance.catalogue,source.provenance.query]});assert.equal(product.components[0]!.representation.kind,'table');assert.equal(product.components[0]!.frame?.epoch,'J2016');assert.equal(product.issues.some(issue=>/covariance/u.test(issue.reason)),true);assert.match(exportAstrometryCsv(rows.slice(0,1)),new RegExp(rows[0]!.id,'u'));assert.equal(F09_ASTROMETRY_HANDLER.operations(product).find(op=>op.id==='astrometry-propagate')?.available,true);});
test('F09 propagation is explicit and refuses missing prerequisites',()=>{const one=rows[0]!,moved=propagateAstrometry([one],{fromJulianYear:2016,toJulianYear:2026,frame:'ICRS'})[0]!;assert.notEqual(moved.raDeg,one.raDeg);assert.equal(moved.epochJulianYear,2026);assert.throws(()=>propagateAstrometry([{id:'x',raDeg:1,decDeg:2}],{fromJulianYear:2016,toJulianYear:2026,frame:'ICRS'}),/proper-motion/u);assert.throws(()=>propagateAstrometry([one],{fromJulianYear:2016,toJulianYear:2026,frame:'GALACTIC'}),/ICRS/u);});
test('F09 row selection and sky view retain identifiers and stated coordinates',()=>{const selected=selectAstrometryRows(rows,[rows[0]!.id]);assert.equal(selected.length,1);assert.equal(astrometryTrackData(selected)[0]!.id,rows[0]!.id);assert.throws(()=>selectAstrometryRows(rows,['missing']),/absent/u);});

const MAS=180/Math.PI*3.6e6,close=(actual:number,expected:number,tolerance:number,label:string)=>assert.ok(Math.abs(actual-expected)<=tolerance,`${label}: ${actual} differs from ${expected}`);
const inspectRow=(row:Parameters<typeof positionCovariance>[0])=>astrometryTrackData([row]);
test('F09 position covariance reads the α–δ block of a packed matrix, or builds it from errors and correlation',()=>{
  const five=Array.from({length:15},(_,index)=>index===5?1:index+1);assert.deepEqual(positionCovariance({id:'p',raDeg:1,decDeg:1,covariance:[4,1,0,0,0,9,0,0,0,1,0,0,1,0,1]})?.matrix,[4,1,9]);assert.throws(()=>positionCovariance({id:'q',raDeg:1,decDeg:1,covariance:five}),/positive definite/u);
  assert.deepEqual(positionCovariance({id:'e',raDeg:1,decDeg:1,raErrorMas:2,decErrorMas:3,raDecCorrelation:0.5}),{matrix:[4,3,9],source:'errors-and-correlation'});
  assert.equal(positionCovariance({id:'d',raDeg:1,decDeg:1,raErrorMas:2,decErrorMas:3})?.source,'errors-without-correlation');assert.equal(positionCovariance({id:'n',raDeg:1,decDeg:1}),undefined);
  assert.throws(()=>positionCovariance({id:'s',raDeg:1,decDeg:1,raErrorMas:2,decErrorMas:3,raDecCorrelation:1}),/positive definite/u);assert.throws(()=>inspectRow({id:'c',raDeg:1,decDeg:1,covariance:[1,2,3,4]}),/packed upper triangle/u);
});
test('F09 offsets are gnomonic, east positive, wrap RA and keep each row covariance',()=>{
  const step=1/3600,rows=[{id:'star',raDeg:359.9999,decDeg:0,epochJulianYear:2016},{id:'east',raDeg:0.0001,decDeg:0,epochJulianYear:2016,raErrorMas:3,decErrorMas:2,raDecCorrelation:-0.25},{id:'north',raDeg:359.9999,decDeg:step,epochJulianYear:2016}];
  const data=astrometryOffsetData(rows,'star'),east=data.rows.find(row=>row.id==='east')!,north=data.rows.find(row=>row.id==='north')!;
  close(east.eastMas,Math.tan(0.0002*Math.PI/180)*MAS,1e-6,'east offset');close(east.northMas,0,1e-9,'east row north offset');close(north.northMas,Math.tan(step*Math.PI/180)*MAS,1e-6,'north offset');close(north.eastMas,0,1e-9,'north row east offset');
  assert.deepEqual(east.covarianceMas2,[9,-1.5,4]);assert.equal(east.covarianceSource,'errors-and-correlation');assert.equal(north.covarianceMas2,undefined);assert.equal(data.rows.find(row=>row.reference)?.eastMas,0);
  const high=astrometryOffsetData([{id:'a',raDeg:10,decDeg:70},{id:'b',raDeg:10+2/3600,decDeg:70}],'a').rows[1]!;close(high.eastMas,2000*Math.cos(70*Math.PI/180),1e-3,'small-angle east offset at δ 70°');
  assert.deepEqual(astrometryOffsetData(rows,'star',['north']).rows.map(row=>row.id),['star','north']);
  assert.throws(()=>astrometryOffsetData(rows,'missing'),/absent/u);assert.throws(()=>astrometryOffsetData([...rows,{id:'later',raDeg:0,decDeg:0,epochJulianYear:2020}],'star'),/one common epoch/u);assert.throws(()=>astrometryOffsetData([{id:'a',raDeg:0,decDeg:0},{id:'b',raDeg:180,decDeg:0}],'a'),/90°/u);
});
test('F09 propagation carries the stated covariance unchanged',()=>{const moved=propagateAstrometry([{id:'m',raDeg:10,decDeg:10,pmRaCosDecMasYr:5,pmDecMasYr:-5,raErrorMas:1,decErrorMas:2,raDecCorrelation:0.1,covariance:[1,0.2,4]}],{fromJulianYear:2016,toJulianYear:2026,frame:'ICRS'})[0]!;assert.deepEqual(moved.covariance,[1,0.2,4]);assert.equal(moved.raDecCorrelation,0.1);});
test('F09 reads a real Gaia DR3 CSV by archive column names and matches Astropy sky offsets',async()=>{
  const text=await readFile(resolve(root,'tests/fixtures/telescope-families/f09-gaia-hd-189733/gaia-dr3-astrometry.csv'),'utf8'),gaia=readAstrometryCsv(text);assert.equal(gaia.length,36);
  const star=gaia.find(row=>row.id==='1827242816201846144')!;assert.equal(star.raErrorMas,0.009658503);assert.equal(star.raDecCorrelation,0.044162523);assert.equal(star.epochJulianYear,2016);assert.equal(gaia.find(row=>row.id==='1827242816182176512')!.pmRaCosDecMasYr,undefined);
  // Oracle: Astropy 8.0.1 SkyCoord.spherical_offsets_to from HD 189733 A, run once on these rows.
  const data=astrometryOffsetData(gaia,star.id,['1827242816176111360','1827242816176119296']),companion=data.rows.find(row=>row.id==='1827242816176111360')!,faint=data.rows.find(row=>row.id==='1827242816176119296')!;
  close(companion.eastMas,-10314.64354297074,1e-4,'HD 189733 B east');close(companion.northMas,-4953.256160302493,1e-4,'HD 189733 B north');close(faint.eastMas,-10319.332782010026,1e-4,'faint east');close(faint.northMas,8484.569418123752,1e-4,'faint north');
  assert.equal(faint.covarianceSource,'errors-and-correlation');close(faint.covarianceMas2![1],0.97039557*4.0710716*34.24364,1e-9,'faint RA–Dec covariance');
  assert.throws(()=>readAstrometryCsv('ra,dec\n1,2\n'),/source_id or id/u);assert.throws(()=>readAstrometryCsv('id,ra,dec,ra_error\na,1,2,x\n'),/raErrorMas is not a finite number/u);assert.throws(()=>readAstrometryCsv('id,ra,dec\na,1\n'),/2 fields for 3 columns/u);
  assert.deepEqual(readAstrometryCsv('"id",ra,dec,note\n"a1",1,2,"x, y"\n').map(row=>row.id),['a1']);
});
