import assert from'node:assert/strict';import{test}from'node:test';import{readFile}from'node:fs/promises';import{resolve}from'node:path';import{member}from'./common.mts';import{astrometryTrackData,describeAstrometry,readAstrometryCsv,exportAstrometryCsv,F09_ASTROMETRY_HANDLER,propagateAstrometry,selectAstrometryRows}from'./f09-astrometry.mts';
const root=resolve(import.meta.dirname,'../../../..'),path='src/objects/m1/source/stellar-field.json',bytes=await readFile(resolve(root,path)),source=JSON.parse(bytes.toString()) as any,rows=source.stars.map((star:any)=>({id:star.sourceId,raDeg:star.raDeg,decDeg:star.decDeg,epochJulianYear:source.coordinateEpochJulianYear,pmRaCosDecMasYr:star.pmRaMasYr,pmDecMasYr:star.pmDecMasYr,parallaxMas:star.parallaxMas,parallaxErrorMas:star.parallaxErrorMas}));
test('F09 describes and exports the pinned Gaia field with IDs, frame, epoch and uncertainties',()=>{const product=describeAstrometry({id:'m1-gaia-field',target:'m1',member:member('gaia-field',path,'science',bytes,'application/json'),rows,frame:'ICRS',epochJulianYear:source.coordinateEpochJulianYear,producingRecord:path,calibrationBasis:[source.provenance.catalogue,source.provenance.query]});assert.equal(product.components[0]!.representation.kind,'table');assert.equal(product.components[0]!.frame?.epoch,'J2016');assert.equal(product.issues.some(issue=>/covariance/u.test(issue.reason)),true);assert.match(exportAstrometryCsv(rows.slice(0,1)),new RegExp(rows[0]!.id,'u'));assert.equal(F09_ASTROMETRY_HANDLER.operations(product).find(op=>op.id==='astrometry-propagate')?.available,true);});
test('F09 propagation is explicit and refuses missing prerequisites',()=>{const one=rows[0]!,moved=propagateAstrometry([one],{fromJulianYear:2016,toJulianYear:2026,frame:'ICRS'})[0]!;assert.notEqual(moved.raDeg,one.raDeg);assert.equal(moved.epochJulianYear,2026);assert.throws(()=>propagateAstrometry([{id:'x',raDeg:1,decDeg:2}],{fromJulianYear:2016,toJulianYear:2026,frame:'ICRS'}),/proper-motion/u);assert.throws(()=>propagateAstrometry([one],{fromJulianYear:2016,toJulianYear:2026,frame:'GALACTIC'}),/ICRS/u);});
test('F09 row selection and sky view retain identifiers and stated coordinates',()=>{const selected=selectAstrometryRows(rows,[rows[0]!.id]);assert.equal(selected.length,1);assert.equal(astrometryTrackData(selected)[0]!.id,rows[0]!.id);assert.throws(()=>selectAstrometryRows(rows,['missing']),/absent/u);});

const MAS=180/Math.PI*3.6e6,close=(actual:number,expected:number,tolerance:number,label:string)=>assert.ok(Math.abs(actual-expected)<=tolerance,`${label}: ${actual} differs from ${expected}`);
test('F09 reads a real Gaia DR3 CSV by archive column names and matches Astropy sky offsets',async()=>{
  const text=await readFile(resolve(root,'tests/fixtures/telescope-families/f09-gaia-hd-189733/gaia-dr3-astrometry.csv'),'utf8'),gaia=readAstrometryCsv(text);assert.equal(gaia.length,36);
  const star=gaia.find(row=>row.id==='1827242816201846144')!;assert.equal(star.raErrorMas,0.009658503);assert.equal(star.raDecCorrelation,0.044162523);assert.equal(star.epochJulianYear,2016);assert.equal(gaia.find(row=>row.id==='1827242816182176512')!.pmRaCosDecMasYr,undefined);
  const faint=gaia.find(row=>row.id==='1827242816176119296')!;
  close(faint.decErrorMas!,34.24364,1e-9,'faint declination error');close(faint.raDecCorrelation!,0.97039557,1e-9,'faint RA–Dec correlation');
  assert.throws(()=>readAstrometryCsv('ra,dec\n1,2\n'),/source_id or id/u);assert.throws(()=>readAstrometryCsv('id,ra,dec,ra_error\na,1,2,x\n'),/raErrorMas is not a finite number/u);assert.throws(()=>readAstrometryCsv('id,ra,dec\na,1\n'),/2 fields for 3 columns/u);
  assert.deepEqual(readAstrometryCsv('"id",ra,dec,note\n"a1",1,2,"x, y"\n').map(row=>row.id),['a1']);
});
