import assert from 'node:assert/strict';
import { sourceTest } from '../../../../tests/objects/source-test.mts';
const test = sourceTest();
import { member } from './common.mts';
import { describeEvents, F10_EVENTS_HANDLER } from './f10-events.mts';
import { describeOifits, F12_OIFITS_HANDLER } from './f12-oifits.mts';
import { describeCalibrationBundle, F17_CALIBRATION_HANDLER } from './f17-calibration.mts';
import { describeCompound, F18_COMPOUND_HANDLER } from './f18-compound.mts';

const event=member('evt','tools/objects/hst/programs/europa-transit-2014-01-26.timetag.json','science',Buffer.from('EVENTS'));
const gti=member('gti','tools/objects/hst/programs/europa-transit-2014-01-26.timetag.reproduction.json','support',Buffer.from('GTI'));
test('F10 retains GTI and response boundaries for event-derived views',()=>{const product=describeEvents({id:'europa-events',target:'europa',producingRecord:event.path,members:[event,gti],eventMemberId:'evt',gtiMemberId:'gti',rows:54_000_000,timeColumn:'TIME',xColumn:'AXIS1',yColumn:'AXIS2',calibration:'locally-reproduced'});assert.equal(product.components[0]!.representation.kind,'events');assert.equal(product.dependencies[0]!.role,'GTI gates event selection');assert.ok(F10_EVENTS_HANDLER.operations(product).some(op=>op.id==='light-curve'));assert.match(product.issues[0]!.reason,/No response/u);});
test('F12 keeps OIFITS observable tables linked for diagnostics and subsets',()=>{const fits=member('oi','tests/fixtures/fits/binary-table-columns.fits','science',Buffer.from('OIFITS'));const product=describeOifits({id:'pi1-gruis',target:'pi1-gruis',producingRecord:'tools/objects/interferometry/seasons/pi1-gruis-pionier-2014-09/season.json',member:fits,rows:{vis:18,vis2:18,t3:6}});assert.deepEqual(product.components.map(component=>component.id),['vis','vis2','closure']);assert.equal(product.dependencies[0]!.memberIds[0],'oi');assert.equal(F12_OIFITS_HANDLER.operations(product).find(op=>op.id==='oifits-subset')?.available,true);assert.equal(F12_OIFITS_HANDLER.operations(product).find(op=>op.id==='oifits-subset')?.owner.export,'subsetOifits');});
test('F17 exposes exact raw/calibration closure while refusing a generic reducer',()=>{const raw=member('raw','tools/objects/hst/programs/europa-11085.json','science',Buffer.from('raw')),cal=member('cal','tools/objects/hst/toolchain.json','calibration',Buffer.from('cal')),product=member('product','tools/objects/hst/programs/europa-11085.j9xe05e0q_flt.reproduction.json','provenance',Buffer.from('product'));const described=describeCalibrationBundle({id:'hst-11085',target:'europa',producingRecord:product.path,members:[raw,cal,product],rawMemberIds:['raw'],calibrationMemberIds:['cal'],productMemberIds:['product'],reducer:{module:'tools/objects/hst/calibrate.mts',export:'runCalibration',label:'HST calibration'}});assert.equal(described.dependencies[0]!.memberIds.length,3);assert.equal(F17_CALIBRATION_HANDLER.operations(described).find(op=>op.id==='run-reducer')!.available,false);});
test('F18 requires an explicit selected or whole member closure',()=>{const a=member('label','tools/objects/pds/programs/charon-pds-nh_charon_color_mosaic.archive-final.json','label',Buffer.from('label')),b=member('science','tools/objects/pds/programs/charon-pds-nh_charon_color_mosaic.archive-final.product.json','science',Buffer.from('science'));const described=describeCompound({id:'charon-pds',target:'charon',producingRecord:b.path,members:[a,b],groups:[{id:'complete-product',name:'complete PDS product',memberIds:['label','science'],requiredFor:['export-whole']}]});assert.equal(described.components.find(component=>component.id==='complete-product')!.representation.kind,'collection');assert.equal(F18_COMPOUND_HANDLER.operations(described).filter(op=>op.available).length,9);});
