import assert from'node:assert/strict';
import{test}from'node:test';
import{copyFile,mkdtemp,readFile,rm,writeFile}from'node:fs/promises';
import{tmpdir}from'node:os';
import{resolve}from'node:path';
import{readProductRecord}from'../../product-record.mts';
import{executeFamilyOperation}from'../family-operation.mts';
import{member}from'./common.mts';
import{describeChandraEvents,energyHistogram,exportSelectedEventsCsv,F10_CHANDRA_EXAMPLE,gtiLightCurve,inspectChandraEvents,nativeCountImage}from'./f10-events.mts';
const root=resolve(import.meta.dirname,'../../../..'),fixture=resolve(root,F10_CHANDRA_EXAMPLE.member),archive=await readFile(fixture),product=inspectChandraEvents(archive);

test('F10 authentic Chandra EVENTS+GTI baseline preserves event and exposure facts',()=>{assert.equal(product.rows.length,62471);assert.equal(product.gtis.length,9);assert.equal(product.target,'Polaris');assert.equal(product.observationId,'6431');assert.ok(product.exposureSeconds>9_900&&product.exposureSeconds<10_000);const descriptor=describeChandraEvents({id:'polaris-6431-events',target:'polaris',member:member('events',F10_CHANDRA_EXAMPLE.member,'science',archive,'application/gzip'),archiveBytes:archive,producingRecord:'tools/objects/chandra/programs/polaris-vfaint.acisf06431N003_evt2.reproduction.json'});assert.deepEqual(descriptor.dependencies[0]!.memberIds,['events']);assert.deepEqual(descriptor.components[0]!.locations,[{memberId:'events',structure:'EVENTS'}]);assert.match(descriptor.issues[0]!.reason,/No ARF\/RMF/u);});

test('F10 direct operations retain lineage and produce count-domain data only',()=>{const csv=exportSelectedEventsCsv(product,{energyEv:[500,7000],status:0});assert.match(csv,/^source_row,time,x,y,energy_ev,pi,ccd_id,status\n/u);assert.ok(csv.trim().split('\n').length>100);const image=nativeCountImage(product,F10_CHANDRA_EXAMPLE.operations.countImage.image);assert.deepEqual(image.shape,[96,128]);assert.equal(image.counts.reduce((a,b)=>a+b,0),image.included);assert.equal(image.quantity,'counts');const histogram=energyHistogram(product,F10_CHANDRA_EXAMPLE.operations.energyHistogram.histogram);assert.equal(histogram.counts.length,4);assert.match(histogram.energyCoordinate,/no response correction/u);const curve=gtiLightCurve(product,F10_CHANDRA_EXAMPLE.operations.lightCurve.lightCurve);assert.ok(curve.bins.some(bin=>bin.exposureSeconds>0&&bin.rateCountsPerSecond!==null));assert.match(curve.exposurePolicy,/not double-counted/u);});

test('F10 rejects malformed archives and zero-exposure light curves',()=>{assert.throws(()=>inspectChandraEvents(Buffer.from([0x1f,0x8b,0,1,2,3])));assert.throws(()=>gtiLightCurve(product,{range:[1,2],binWidthSeconds:1}),/zero GTI exposure/u);assert.throws(()=>energyHistogram(product,{edgesEv:[1,1]}),/strictly increasing/u);});

test('F10 static public execution writes and reopens authentic outputs and refuses a changed pin',async()=>{const work=await mkdtemp(resolve(tmpdir(),'f10-public-'));try{const local=resolve(work,'events.fits.gz');await copyFile(fixture,local);const bytes=await readFile(local),descriptor=describeChandraEvents({id:'polaris-6431-events',target:'polaris',member:member('events','events.fits.gz','science',bytes,'application/gzip'),archiveBytes:bytes,producingRecord:'pinned Chandra program'}),descriptorPath=resolve(work,'descriptor.json');await writeFile(descriptorPath,JSON.stringify(descriptor));const inspect=await executeFamilyOperation(descriptorPath,{operationId:'event-inspect'},resolve(work,'inspect')),summary=JSON.parse(await readFile(inspect.product,'utf8'));assert.equal(summary.rows,62471);assert.equal((await readProductRecord(inspect.record))?.stage,'telescope-family-operation');const selected=await executeFamilyOperation(descriptorPath,{operationId:'selected-events',selection:{energyEv:[500,7000],status:0}},resolve(work,'selected'));assert.match(await readFile(selected.product,'utf8'),/^source_row/mu);await writeFile(local,Buffer.concat([bytes,Buffer.from('changed')]));await assert.rejects(executeFamilyOperation(descriptorPath,{operationId:'event-inspect'},resolve(work,'tampered')),/pin changed/u);}finally{await rm(work,{recursive:true,force:true});}});
