/** F10 public baseline for a bounded Chandra EVENTS+GTI product. Counts remain counts; no response or flux is inferred. */
import{gunzipSync}from'node:zlib';
import{binaryTable,numbers,readFitsHdus,tableColumn}from'../../interferometry/fits-table.mts';
import{eventTable,requireEventColumn,scalar}from'../../chandra/events.mts';
import type{FamilyHandler,FamilyOperation}from'../family-handlers.mts';
import type{DescriptorMember,ProductDescriptor}from'../product-descriptor.mts';
import{plotNumericPreview}from'../../astronomy-packages/plots.mts';
import{csv,descriptor,finite,stable}from'./common.mts';

const MAX_COMPRESSED=32*1024*1024,MAX_EXPANDED=128*1024*1024,MAX_ROWS=2_000_000;
export const F10_CHANDRA_EXAMPLE={member:'tests/fixtures/telescope-families/chandra-events/acisf06431N003_evt2.fits.gz',target:'polaris',observationId:'6431',operations:{selectedEvents:{selection:{energyEv:[500,7000],status:0}},countImage:{image:{x:[1495,5423],y:[2774,5542],bins:[128,96],selection:{energyEv:[500,7000],status:0}}},energyHistogram:{histogram:{edgesEv:[500,1000,2000,4000,7000],selection:{status:0}}},lightCurve:{lightCurve:{range:[255835700,255845654],binWidthSeconds:500,selection:{energyEv:[500,7000],status:0}}}}}as const;
export interface EventRow{readonly sourceRow:number;readonly time:number;readonly x:number;readonly y:number;readonly energyEv:number;readonly pi:number;readonly ccdId:number;readonly status:number}
export interface GoodTimeInterval{readonly ccdId:number;readonly start:number;readonly stop:number}
export interface EventProduct{readonly rows:readonly EventRow[];readonly gtis:readonly GoodTimeInterval[];readonly time:{readonly scale:string;readonly unit:string};readonly exposureSeconds:number;readonly target?:string;readonly observationId?:string;readonly columns:readonly string[]}
export interface EventSelection{readonly time?:readonly[number,number];readonly energyEv?:readonly[number,number];readonly x?:readonly[number,number];readonly y?:readonly[number,number];readonly ccdIds?:readonly number[];readonly status?:number}
const ordered=(range:readonly[number,number],label:string)=>{if(!range.every(Number.isFinite)||range[1]<range[0])throw new TypeError(`${label} must be finite and ordered.`);return range;};
function expanded(bytes:Buffer){if(bytes.length>MAX_COMPRESSED)throw new RangeError('Compressed event member exceeds the public size bound.');const gzip=bytes[0]===0x1f&&bytes[1]===0x8b;const data=gzip?gunzipSync(bytes,{maxOutputLength:MAX_EXPANDED}):bytes;if(data.length>MAX_EXPANDED)throw new RangeError('Expanded event member exceeds the public size bound.');return data;}
function mergedIntervals(gtis:readonly GoodTimeInterval[]){const sorted=gtis.map(g=>[g.start,g.stop]as[number,number]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]),merged:[number,number][]=[];for(const interval of sorted){const held=merged.at(-1);if(held&&interval[0]<=held[1])held[1]=Math.max(held[1],interval[1]);else merged.push([...interval]);}return merged;}
const overlap=(a:number,b:number,intervals:readonly[number,number][])=>intervals.reduce((sum,[start,stop])=>sum+Math.max(0,Math.min(b,stop)-Math.max(a,start)),0);

export function inspectChandraEvents(archiveBytes:Buffer):EventProduct{
  const bytes=expanded(archiveBytes),table=eventTable(bytes);if(table.rows>MAX_ROWS)throw new RangeError('Event row count exceeds the public bound.');
  const required=['time','x','y','energy','pi','ccd_id','status'] as const,columns=Object.fromEntries(required.map(name=>[name,requireEventColumn(table,name)])) as Record<typeof required[number],ReturnType<typeof requireEventColumn>>;
  const rows=Array.from({length:table.rows},(_,sourceRow):EventRow=>({sourceRow,time:scalar(bytes,table,sourceRow,columns.time),x:scalar(bytes,table,sourceRow,columns.x),y:scalar(bytes,table,sourceRow,columns.y),energyEv:scalar(bytes,table,sourceRow,columns.energy),pi:scalar(bytes,table,sourceRow,columns.pi),ccdId:scalar(bytes,table,sourceRow,columns.ccd_id),status:scalar(bytes,table,sourceRow,columns.status)}));
  const gtis:GoodTimeInterval[]=[];for(const hdu of readFitsHdus(bytes).filter(item=>item.extname.toUpperCase()==='GTI')){const gti=binaryTable(hdu),start=tableColumn(gti,'START'),stop=tableColumn(gti,'STOP'),ccdId=Number(hdu.header.CCD_ID??hdu.header.EXTVER);if(!Number.isSafeInteger(ccdId))throw new TypeError('GTI extension has no CCD identity.');for(let row=0;row<gti.rows;row++){const from=numbers(bytes,gti,row,start)[0]!,to=numbers(bytes,gti,row,stop)[0]!;if(!Number.isFinite(from)||!Number.isFinite(to)||to<=from)throw new TypeError('GTI intervals must be finite, increasing and nonzero.');gtis.push({ccdId,start:from,stop:to});}}
  if(!gtis.length)throw new TypeError('Event product has no GTI intervals.');const intervals=mergedIntervals(gtis),exposureSeconds=overlap(-Infinity,Infinity,intervals);if(!(exposureSeconds>0))throw new TypeError('Event product has zero good-time exposure.');
  const scale=String(table.hdu.header.TIMESYS??''),unit=String(table.hdu.header.TIMEUNIT??'');if(!scale||unit!=='s')throw new TypeError('Event time requires an explicit scale in seconds.');return{rows,gtis,time:{scale,unit},exposureSeconds,...(typeof table.hdu.header.OBJECT==='string'?{target:String(table.hdu.header.OBJECT).trim()}:{}),...(table.hdu.header.OBS_ID===undefined?{}:{observationId:String(table.hdu.header.OBS_ID)}),columns:table.columns.map(column=>column.name)};
}
export function selectEvents(product:EventProduct,selection:EventSelection={}){for(const [name,range]of Object.entries({time:selection.time,energyEv:selection.energyEv,x:selection.x,y:selection.y}))if(range)ordered(range,name);if(selection.status!==undefined&&!Number.isSafeInteger(selection.status))throw new TypeError('Event status must be an integer.');const ccd=selection.ccdIds===undefined?undefined:new Set(selection.ccdIds.map(value=>{if(!Number.isSafeInteger(value))throw new TypeError('CCD ids must be integers.');return value;}));return product.rows.filter(row=>(!selection.time||row.time>=selection.time[0]&&row.time<=selection.time[1])&&(!selection.energyEv||row.energyEv>=selection.energyEv[0]&&row.energyEv<=selection.energyEv[1])&&(!selection.x||row.x>=selection.x[0]&&row.x<=selection.x[1])&&(!selection.y||row.y>=selection.y[0]&&row.y<=selection.y[1])&&(!ccd||ccd.has(row.ccdId))&&(selection.status===undefined||row.status===selection.status));}
export function exportSelectedEventsCsv(product:EventProduct,selection:EventSelection={}){return csv(['source_row','time','x','y','energy_ev','pi','ccd_id','status'],selectEvents(product,selection).map(row=>[row.sourceRow,row.time,row.x,row.y,row.energyEv,row.pi,row.ccdId,row.status]));}
export function nativeCountImage(product:EventProduct,options:{readonly x:readonly[number,number];readonly y:readonly[number,number];readonly bins:readonly[number,number];readonly selection?:EventSelection}){const[x0,x1]=ordered(options.x,'x bounds'),[y0,y1]=ordered(options.y,'y bounds'),[width,height]=options.bins;if(!Number.isSafeInteger(width)||!Number.isSafeInteger(height)||width<1||height<1||width*height>4_000_000||x1<=x0||y1<=y0)throw new RangeError('Count image requires positive bounded bins and nonzero coordinate ranges.');const counts=new Uint32Array(width*height);let included=0,outside=0;for(const row of selectEvents(product,options.selection)){const x=Math.floor((row.x-x0)/(x1-x0)*width),y=Math.floor((row.y-y0)/(y1-y0)*height);if(x<0||x>=width||y<0||y>=height){outside++;continue;}counts[y*width+x]++;included++;}return{coordinate:'native event x/y',bounds:{x:[x0,x1],y:[y0,y1]},shape:[height,width],counts:Array.from(counts),included,outside,quantity:'counts'};}
export function energyHistogram(product:EventProduct,options:{readonly edgesEv:readonly number[];readonly selection?:EventSelection}){if(options.edgesEv.length<2||options.edgesEv.some((value,index)=>!Number.isFinite(value)||(index>0&&value<=options.edgesEv[index-1]!)))throw new TypeError('Energy edges must be finite and strictly increasing.');const counts=new Uint32Array(options.edgesEv.length-1);let outside=0;for(const row of selectEvents(product,options.selection)){const index=options.edgesEv.findIndex((edge,i)=>i<options.edgesEv.length-1&&row.energyEv>=edge&&row.energyEv<options.edgesEv[i+1]!);if(index<0)outside++;else counts[index]++;}return{edgesEv:[...options.edgesEv],counts:Array.from(counts),outside,quantity:'counts',energyCoordinate:'EVENTS energy column; no response correction'};}
export function gtiLightCurve(product:EventProduct,options:{readonly range:readonly[number,number];readonly binWidthSeconds:number;readonly selection?:EventSelection}){const[from,to]=ordered(options.range,'light-curve range'),width=finite(options.binWidthSeconds,'bin width');if(!(to>from)||!(width>0)||Math.ceil((to-from)/width)>1_000_000)throw new RangeError('Light curve requires a nonzero bounded range and positive bin width.');const intervals=mergedIntervals(product.gtis),bins=Array.from({length:Math.ceil((to-from)/width)},(_,index)=>{const start=from+index*width,stop=Math.min(to,start+width);return{index,start,stop,counts:0,exposureSeconds:overlap(start,stop,intervals),rateCountsPerSecond:null as number|null};});for(const row of selectEvents(product,{...options.selection,time:[from,to]})){const index=Math.min(bins.length-1,Math.floor((row.time-from)/width));if(index>=0)bins[index]!.counts++;}const totalExposure=bins.reduce((sum,bin)=>sum+bin.exposureSeconds,0);if(!(totalExposure>0))throw new TypeError('Requested light curve has zero GTI exposure.');for(const bin of bins)bin.rateCountsPerSecond=bin.exposureSeconds>0?bin.counts/bin.exposureSeconds:null;return{timeScale:product.time.scale,timeUnit:'s',quantity:'counts and count rate',exposurePolicy:'union of declared CCD GTIs; overlapping chip livetime is not double-counted',bins};}
export async function previewCountImage(out:string,title:string,image:ReturnType<typeof nativeCountImage>){return plotNumericPreview(out,{kind:'raster',title,xLabel:'Native event x bin',yLabel:'Native event y bin',width:image.shape[1],height:image.shape[0],values:image.counts,colorLabel:'Counts'});}
export async function previewEnergyHistogram(out:string,title:string,histogram:ReturnType<typeof energyHistogram>){return plotNumericPreview(out,{kind:'histogram',title,xLabel:'Energy (eV)',yLabel:'Counts',edges:histogram.edgesEv,counts:histogram.counts});}
export async function previewLightCurve(out:string,title:string,curve:ReturnType<typeof gtiLightCurve>){return plotNumericPreview(out,{kind:'series',title,xLabel:`Time (${curve.timeUnit}, ${curve.timeScale})`,yLabel:'Count rate (s⁻¹)',series:[{label:'GTI-corrected bins',x:curve.bins.map(bin=>(bin.start+bin.stop)/2),y:curve.bins.map(bin=>bin.rateCountsPerSecond??NaN)}]});}

export interface EventDescriptorInput{readonly id:string;readonly target?:string;readonly producingRecord:string;readonly member:DescriptorMember;readonly archiveBytes:Buffer}
export function describeChandraEvents(input:EventDescriptorInput):ProductDescriptor{const inspected=inspectChandraEvents(input.archiveBytes),target=input.target??inspected.target?.toLowerCase();return descriptor({schema:'cssearth-telescope-product-descriptor@1',dataset:{id:stable(input.id,'event dataset id'),...(target?{target}:{}),acquisition:{kind:'repository',identity:input.member.path},producingRecord:input.producingRecord,sourceClassifications:[{term:'event-list',vocabulary:'Chandra ACIS EVENTS+GTI',version:'FITS',status:'source'}],families:['F10'],profiles:[{handlerId:'f10-events',profileId:'chandra-acis-events-gti@1'}]},members:[input.member],components:[{id:'events',name:'Chandra ACIS EVENTS',families:['F10'],locations:[{memberId:input.member.id,structure:'EVENTS'}],representation:{kind:'events',rows:inspected.rows.length},axes:[],columns:[{id:'source-row',name:'source_row',role:'source-row-lineage',datatype:'integer',nullable:false,variableLength:false},{id:'time',name:'time',role:'event-time',datatype:'float64',unit:'s',nullable:false,variableLength:false},{id:'x',name:'x',role:'native-x',datatype:'float64',nullable:false,variableLength:false},{id:'y',name:'y',role:'native-y',datatype:'float64',nullable:false,variableLength:false},{id:'energy',name:'energy_ev',role:'pulse-height-energy-coordinate',datatype:'float64',unit:'eV',nullable:false,variableLength:false},{id:'pi',name:'pi',role:'pulse-invariant-channel',datatype:'integer',nullable:false,variableLength:false},{id:'ccd-id',name:'ccd_id',role:'detector-identity',datatype:'integer',nullable:false,variableLength:false},{id:'status',name:'status',role:'status-bit-field',datatype:'uint32',nullable:false,variableLength:false}],quantity:{name:'detected events',semantics:'One retained source row per detected event. Images, histograms and light curves are explicit count aggregations.'},calibration:{state:'archive-calibrated',basis:['Chandra archive level-2 event product. No response correction is applied.']},flags:[{id:'status',meaning:'Native Chandra EVENTS status bits.',columnId:'status',usableWhen:'Selection must state an exact status value.'}],time:{scale:inspected.time.scale,format:'mission elapsed seconds',exposure:`GTI union ${inspected.exposureSeconds} s`},dependencyIds:['good-time-intervals']}],dependencies:[{id:'good-time-intervals',role:'GTI gates time selection and exposure',memberIds:[input.member.id],componentIds:['events'],requiredFor:['event-inspect','selected-events','count-image','energy-histogram','light-curve'],evidence:'EVENTS and per-CCD GTI extensions are pinned in the same archive member.'}],issues:[{scope:'dataset',identity:'response',state:'missing',reason:'No ARF/RMF response is pinned; outputs are counts and native event coordinates, never flux or response-corrected energy.'}]});}

/** Compatibility constructor for callers that already hold qualified column facts. Public execution requires the Chandra profile above. */
export function describeEvents(input:{readonly id:string;readonly target?:string;readonly producingRecord:string;readonly members:readonly DescriptorMember[];readonly eventMemberId:string;readonly gtiMemberId:string;readonly responseMemberId?:string;readonly rows:number|null;readonly timeColumn:string;readonly energyColumn?:string;readonly xColumn:string;readonly yColumn:string;readonly calibration:'archive-calibrated'|'locally-reproduced'}):ProductDescriptor{const event=input.members.find(item=>item.id===input.eventMemberId),gti=input.members.find(item=>item.id===input.gtiMemberId);if(!event||!gti)throw new TypeError('Event descriptor member is absent.');return descriptor({schema:'cssearth-telescope-product-descriptor@1',dataset:{id:stable(input.id,'event dataset id'),...(input.target?{target:input.target}:{}),acquisition:{kind:'repository',identity:event.path},producingRecord:input.producingRecord,sourceClassifications:[{term:'event-list',vocabulary:'qualified EVENTS+GTI',version:'1',status:'mapped'}],families:['F10'],profiles:[{handlerId:'f10-events',profileId:'qualified-events-provenance@1'}]},members:input.members,components:[{id:'events',name:'EVENTS',families:['F10'],locations:[{memberId:event.id,structure:'EVENTS'}],representation:{kind:'events',rows:input.rows},axes:[],columns:[],quantity:{name:'detected events',semantics:'Qualified event provenance only; this profile has no public byte decoder.'},calibration:{state:input.calibration,basis:['Caller-qualified event product.']},flags:[],time:{scale:'native',format:input.timeColumn},dependencyIds:['good-time-intervals']}],dependencies:[{id:'good-time-intervals',role:'GTI gates event selection',memberIds:[gti.id],componentIds:['events'],requiredFor:[]}],issues:[{scope:'dataset',identity:'public-execution',state:'unsupported',reason:'No response is pinned, and this descriptor-only profile has no public byte decoder. Use the Chandra ACIS EVENTS+GTI profile for public event execution.'}]});}

const operations=(componentId:string):FamilyOperation[]=>[
  ['event-inspect','Inspect event product','inspectChandraEvents',[]],['selected-events','Export selected events','exportSelectedEventsCsv',['selection']],['count-image','Native count image','nativeCountImage',['image']],['count-image-preview','Render native count-image preview','previewCountImage',['image']],['energy-histogram','Energy histogram','energyHistogram',['histogram']],['energy-histogram-preview','Render energy-histogram preview','previewEnergyHistogram',['histogram']],['light-curve','GTI-aware light curve','gtiLightCurve',['lightCurve']],['light-curve-preview','Render GTI-aware light-curve preview','previewLightCurve',['lightCurve']]
].map(([id,label,owner,params])=>({id:id as string,label:label as string,handlerId:'f10-events',componentId,owner:{module:'tools/objects/telescopes/families/f10-events.mts',export:owner as string},available:true,reason:'The pinned Chandra EVENTS+GTI member supports this count-domain operation.',fixedArguments:{},parameters:[...(params as string[]).map(name=>({id:name,option:`--${name}`,kind:'input-path' as const,required:true,description:`Explicit typed ${name} parameters.`})),{id:'out',option:'--out',kind:'output-directory' as const,required:true,description:'New output directory.'}],limitations:['Counts only. No ARF/RMF response, flux, exposure map, sky reprojection or implicit status filtering.']}));
export const F10_EVENTS_HANDLER:FamilyHandler={id:'f10-events',families:['F10'],profiles:[{id:'chandra-acis-events-gti@1',format:'gzip or plain Chandra ACIS FITS EVENTS+GTI',version:'bounded public profile',families:['F10'],publicBaseline:true,evidence:[{path:'tests/fixtures/telescope-families/chandra-events/acisf06431N003_evt2.fits.gz',establishes:'Authentic pinned Chandra ACIS level-2 EVENTS plus per-CCD GTIs.',status:'complete'}]},{id:'qualified-events-provenance@1',format:'Qualified EVENTS+GTI provenance',version:'descriptor-only',families:['F10'],evidence:[]}],recognizes:members=>members.some(member=>/(?:evt|event).*(?:fits|fits\.gz)$/iu.test(member.path))?['chandra-acis-events-gti@1']:[],operations:d=>{const executable=d.dataset.profiles.some(profile=>profile.profileId==='chandra-acis-events-gti@1');return d.components.filter(c=>c.families.includes('F10')).flatMap(c=>operations(c.id).map(operation=>executable?operation:{...operation,available:false,reason:'This descriptor records event provenance but has no public Chandra EVENTS+GTI byte decoder.'}));}};
