/** F11 adapter for a complete, bounded CASA Measurement Set closure. CASA remains the executor. */
import {createHash} from 'node:crypto';
import {parseExecution} from '../../interferometry/alma-execution.mts';
import type { FamilyHandler, FamilyOperation } from '../family-handlers.mts'; import type { DescriptorMember, ProductDescriptor } from '../product-descriptor.mts'; import { csv, descriptor, stable } from './common.mts';
const REQUIRED=['MAIN','FIELD','SPECTRAL_WINDOW','ANTENNA','POLARIZATION'] as const;
export interface MeasurementSetInput {readonly id:string;readonly target?:string;readonly producingRecord:string;readonly members:readonly DescriptorMember[];readonly tables:Readonly<Record<typeof REQUIRED[number],string>>;readonly archiveQualified:boolean;}
export function describeMeasurementSet(input:MeasurementSetInput):ProductDescriptor {for(const table of REQUIRED)if(!input.tables[table]||!input.members.some(member=>member.id===input.tables[table]))throw new TypeError(`Measurement Set requires pinned ${table}.`);const memberIds=REQUIRED.map(table=>input.tables[table]);return descriptor({schema:'cssearth-telescope-product-descriptor@1',dataset:{id:stable(input.id,'measurement set id'),...(input.target?{target:input.target}:{}),acquisition:{kind:'local-import',identity:'bounded local Measurement Set import'},producingRecord:input.producingRecord,sourceClassifications:[{term:'Measurement Set',vocabulary:'CASA MS',version:'2',status:'mapped'}],families:['F11'],profiles:[{handlerId:'f11-measurement-set',profileId:'casa-ms-closure@1'}]},members:input.members,components:[{id:'visibilities',name:'MAIN visibilities',families:['F11'],locations:[{memberId:input.tables.MAIN}],representation:{kind:'complex-samples',rows:null},axes:[],columns:[],quantity:{name:'correlated visibilities',semantics:'Native MAIN rows with FIELD/SPW/ANTENNA/POLARIZATION linkage.'},calibration:{state:input.archiveQualified?'archive-calibrated':'unknown',basis:[input.archiveQualified?'Pinned archive-qualified MS closure.':'Local import pins bytes only; archive origin/calibration are unverified.']},flags:[{id:'flag',meaning:'Native MS FLAG values'}],time:{scale:'UTC',format:'CASA time coordinate'},dependencyIds:['ms-required-tables']}],dependencies:[{id:'ms-required-tables',role:'Measurement Set table closure',memberIds,componentIds:['visibilities'],requiredFor:['inspect-ms','select-ms','export-ms-subset','amplitude-phase-diagnostics','uv-diagnostics'],evidence:'MAIN cannot be interpreted or subset safely without FIELD, SPW, ANTENNA and POLARIZATION tables.'}],issues:input.archiveQualified?[]:[{scope:'dataset',identity:'archive-qualified-closure',state:'unknown',reason:'Only local-import byte integrity is established. No real pinned archive-qualified Measurement Set closure is available.'}]});}
const operation=(componentId:string,id:string,label:string,owner:string,available:boolean,reason:string):FamilyOperation=>({id,label,handlerId:'f11-measurement-set',componentId,owner:{module:'tools/objects/interferometry/alma-restore.mts',export:owner},available,reason,fixedArguments:{},parameters:[{id:'selection',option:'--selection',kind:'input-path',required:id!=='inspect-ms',description:'Explicit CASA field/SPW/time/baseline selection.'},{id:'out',option:'--out',kind:'output-directory',required:true,description:'New output directory.'}],limitations:['CASA owns MS access and selection. This adapter does not parse casacore tables or claim archive calibration from local import.']});

/**
 * A raw ASDM is an authoritative source for an MS, but it is not itself an MS.
 * This deliberately only admits the two early XML members which the established
 * ALMA execution reader consumes. The BDF correlation payload remains remote;
 * CASA's importasdm owns conversion before any complex samples are exported.
 */
export interface AsdmSourceMember {readonly id:'ASDM.xml'|'Main.xml';readonly path:string;readonly bytes:number;readonly sha256:string;}
export interface AsdmVisibilitySourceManifest {readonly schema:'cssearth-f11-asdm-source@1';readonly archive:{readonly facility:'ALMA Science Archive';readonly memberUid:string;readonly proposal:string;readonly access:'public archive download; no source-data redistribution license asserted';readonly termsUrl:string};readonly raw:{readonly uid:string;readonly url:string;readonly bytes:number;readonly contentType:'application/x-tar'};readonly members:readonly AsdmSourceMember[];readonly extraction:{readonly maximumBytes:number;readonly method:'tools/objects/interferometry/alma-execution.mts#peekExecution'};}
export interface AsdmSourceMemberBytes {readonly id:'ASDM.xml'|'Main.xml';readonly bytes:Uint8Array;}
const hash=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');
const sourceMember=(manifest:AsdmVisibilitySourceManifest,id:AsdmSourceMember['id'])=>{const found=manifest.members.filter(member=>member.id===id);if(found.length!==1)throw new TypeError(`ASDM source manifest requires exactly one ${id} pin.`);const member=found[0]!;if(!Number.isSafeInteger(member.bytes)||member.bytes<1||!/^[a-f0-9]{64}$/u.test(member.sha256)||!member.path.endsWith(`/${id}`))throw new TypeError(`ASDM source manifest has an invalid ${id} pin.`);return member;};
/** Read the bounded archive members, verify each pin, and export only execution-level visibility provenance. */
export function inspectAsdmVisibilitySource(manifest:AsdmVisibilitySourceManifest, supplied:readonly AsdmSourceMemberBytes[]){
  if(manifest.schema!=='cssearth-f11-asdm-source@1'||manifest.archive.facility!=='ALMA Science Archive'||!manifest.archive.memberUid.startsWith('uid://A001/')||manifest.archive.access!=='public archive download; no source-data redistribution license asserted'||!manifest.archive.termsUrl.startsWith('https://')||!manifest.raw.uid.startsWith('uid://A002/')||!manifest.raw.url.startsWith('https://almascience.nrao.edu/dataPortal/')||!Number.isSafeInteger(manifest.raw.bytes)||manifest.raw.bytes<1||manifest.raw.contentType!=='application/x-tar'||!Number.isSafeInteger(manifest.extraction.maximumBytes)||manifest.extraction.maximumBytes<1||manifest.extraction.method!=='tools/objects/interferometry/alma-execution.mts#peekExecution')throw new TypeError('Invalid bounded ALMA ASDM source manifest.');
  const memberBytes=new Map(supplied.map(member=>[member.id,member.bytes]));if(memberBytes.size!==2)throw new TypeError('ASDM source inspection requires exactly ASDM.xml and Main.xml.');
  const asdm=sourceMember(manifest,'ASDM.xml'),main=sourceMember(manifest,'Main.xml');for(const pin of [asdm,main]){const bytes=memberBytes.get(pin.id);if(!bytes||bytes.byteLength!==pin.bytes||hash(bytes)!==pin.sha256)throw new Error(`ASDM source member pin changed: ${pin.id}.`);}
  const execution=parseExecution(Buffer.from(memberBytes.get('ASDM.xml')!).toString('utf8'),Buffer.from(memberBytes.get('Main.xml')!).toString('utf8'));
  if(execution.entityId!==manifest.raw.uid)throw new Error('ASDM entity id does not match the pinned raw source.');
  return {schema:'cssearth-f11-asdm-source-inspection@1' as const,source:{memberUid:manifest.archive.memberUid,proposal:manifest.archive.proposal,rawUid:manifest.raw.uid,url:manifest.raw.url,rawBytes:manifest.raw.bytes,archiveAccess:manifest.archive.access},memberPins:[asdm,main],execution:{entityId:execution.entityId,created:execution.created.toISOString(),antennas:execution.antennas,subscans:execution.subscans.length,totalVisibilityBytes:execution.totalDataBytes,fields:[...execution.byField].map(([field,value])=>({field,...value}))},limitations:['This is raw ASDM execution provenance, not a CASA Measurement Set and not decoded complex visibility samples. Run CASA importasdm, then admit and pin the resulting MS closure before selection/export/diagnostics.']};
}

/** Shared dispatcher integration uses this public operation id and this F11-owned executor. */
export const F11_ASDM_SOURCE_INSPECT_OPERATION={id:'asdm-source-inspect',owner:{module:'tools/objects/telescopes/families/f11-measurement-set.mts',export:'inspectAsdmVisibilitySource'},limitations:['The operation verifies only bounded ASDM XML members and exports execution provenance; it never calls an ASDM a Measurement Set.']} as const;

export interface UvfitsVisibility {readonly row:number;readonly timeJulianDate:number;readonly antenna1:number;readonly antenna2:number;readonly uSeconds:number;readonly vSeconds:number;readonly wSeconds:number;readonly frequencyHz:number;readonly polarization:number;readonly real:number;readonly imaginary:number;readonly weight:number;readonly flagged:boolean;}
export interface UvfitsInspection {readonly telescope:string;readonly target:string;readonly rows:number;readonly channels:number;readonly polarizations:readonly number[];readonly samples:number;readonly frequencyHz:{readonly first:number;readonly increment:number};}
const CARD=80,BLOCK=2880;
const uvfitsHeader=(bytes:Buffer)=>{let at=0;const values:Record<string,string|number|boolean>={};for(;;){if(at+BLOCK>bytes.length)throw new TypeError('UVFITS header is truncated.');for(let offset=0;offset<BLOCK;offset+=CARD){const card=bytes.toString('latin1',at+offset,at+offset+CARD),key=card.slice(0,8).trim();if(key==='END')return{values,dataOffset:at+BLOCK};if(card[8]==='='){const raw=card.slice(10).split('/')[0]!.trim();values[key]=raw==='T'?true:raw==='F'?false:raw.startsWith("'")?raw.slice(1,raw.indexOf("'",1)):Number(raw);}}at+=BLOCK;}};
const number=(header:Record<string,string|number|boolean>,key:string)=>{const value=header[key];if(typeof value!=='number'||!Number.isFinite(value))throw new TypeError(`UVFITS ${key} must be finite.`);return value;};
/** Read the bounded IEEE-float random-groups UVFITS layout used by the pinned VLA tutorial fixture. */
export function readUvfitsComplexVisibilities(bytes:Buffer):{readonly inspection:UvfitsInspection;readonly rows:readonly UvfitsVisibility[]}{
  const {values:header,dataOffset}=uvfitsHeader(bytes),axis=(index:number)=>number(header,`NAXIS${index}`),bitpix=number(header,'BITPIX'),groups=number(header,'GCOUNT'),parameters=number(header,'PCOUNT');
  if(header.SIMPLE!==true||header.GROUPS!==true||bitpix!==-32||number(header,'NAXIS')!==7||axis(1)!==0||axis(2)!==3||!Number.isSafeInteger(groups)||groups<1||!Number.isSafeInteger(parameters)||parameters<7)throw new TypeError('Only bounded IEEE-float UVFITS random groups with complex/value/weight triples are supported.');
  const polarizations=axis(3),channels=axis(4),remaining=[axis(5),axis(6),axis(7)];if(!Number.isSafeInteger(polarizations)||!Number.isSafeInteger(channels)||polarizations<1||channels<1||remaining.some(value=>value!==1))throw new TypeError('UVFITS axes are outside the bounded one-IF, one-source profile.');
  const perGroup=parameters+3*polarizations*channels,needed=dataOffset+4*perGroup*groups;if(bytes.length<needed)throw new TypeError('UVFITS random groups are truncated.');
  const ptype=(index:number)=>String(header[`PTYPE${index}`]??'').trim(),required=['UU','VV','WW','DATE','DATE','BASELINE','FREQSEL'];if(required.some((value,index)=>ptype(index+1)!==value))throw new TypeError('UVFITS group parameters do not provide UU/VV/WW, DATE, BASELINE and FREQSEL in the required order.');
  const baseFrequency=number(header,'CRVAL4'),increment=number(header,'CDELT4'),reference=number(header,'CRPIX4'),polarizationBase=number(header,'CRVAL3'),polarizationIncrement=number(header,'CDELT3'),target=String(header.OBJECT??'').trim(),telescope=String(header.TELESCOP??'').trim();if(!target||!telescope||increment===0)throw new TypeError('UVFITS must name a target, telescope and nonzero frequency increment.');
  const rows:UvfitsVisibility[]=[];for(let row=0;row<groups;row++){const group=dataOffset+4*perGroup*row,read=(index:number)=>bytes.readFloatBE(group+4*index),baseline=read(5),antenna1=Math.floor(baseline/256),antenna2=Math.round(baseline-256*antenna1),timeJulianDate=read(3)+read(4);if(!Number.isSafeInteger(antenna1)||!Number.isSafeInteger(antenna2)||antenna1<1||antenna2<1)throw new TypeError('UVFITS BASELINE parameter is invalid.');for(let channel=0;channel<channels;channel++)for(let pol=0;pol<polarizations;pol++){const start=parameters+3*(channel*polarizations+pol),real=read(start),imaginary=read(start+1),weight=read(start+2);if(![real,imaginary,weight].every(Number.isFinite))throw new TypeError('UVFITS visibility has a non-finite value.');rows.push({row,timeJulianDate,antenna1,antenna2,uSeconds:read(0),vSeconds:read(1),wSeconds:read(2),frequencyHz:baseFrequency+(channel+1-reference)*increment,polarization:polarizationBase+pol*polarizationIncrement,real,imaginary,weight,flagged:weight<=0});}}
  return{inspection:{telescope,target,rows:groups,channels,polarizations:Array.from({length:polarizations},(_,index)=>polarizationBase+index*polarizationIncrement),samples:rows.length,frequencyHz:{first:baseFrequency+(1-reference)*increment,increment}},rows};
}
export function inspectUvfitsVisibilities(bytes:Buffer){return readUvfitsComplexVisibilities(bytes).inspection;}
export function exportUvfitsVisibilitySelection(bytes:Buffer,selection:{readonly rowStart:number;readonly rowCount:number;readonly channelStart:number;readonly channelCount:number;readonly polarization:number}){const parsed=readUvfitsComplexVisibilities(bytes),whole=(value:number,label:string)=>{if(!Number.isSafeInteger(value)||value<0)throw new TypeError(`${label} must be a nonnegative integer.`);return value;},rowStart=whole(selection.rowStart,'rowStart'),rowCount=whole(selection.rowCount,'rowCount'),channelStart=whole(selection.channelStart,'channelStart'),channelCount=whole(selection.channelCount,'channelCount'),pol=selection.polarization;if(!Number.isSafeInteger(pol)||!parsed.inspection.polarizations.includes(pol)||rowCount<1||channelCount<1||rowStart+rowCount>parsed.inspection.rows||channelStart+channelCount>parsed.inspection.channels)throw new RangeError('UVFITS visibility selection is outside the pinned native rows, channels or polarizations.');const selected=parsed.rows.filter(row=>row.row>=rowStart&&row.row<rowStart+rowCount&&row.polarization===pol&&row.frequencyHz>=parsed.inspection.frequencyHz.first+channelStart*parsed.inspection.frequencyHz.increment&&row.frequencyHz<parsed.inspection.frequencyHz.first+(channelStart+channelCount)*parsed.inspection.frequencyHz.increment);return csv(['row','time_jd','antenna1','antenna2','u_seconds','v_seconds','w_seconds','frequency_hz','polarization','real','imaginary','weight','flagged'],selected.map(row=>[row.row,row.timeJulianDate,row.antenna1,row.antenna2,row.uSeconds,row.vSeconds,row.wSeconds,row.frequencyHz,row.polarization,row.real,row.imaginary,row.weight,row.flagged]));}
export function describeUvfitsVisibility(input:{readonly id:string;readonly producingRecord:string;readonly member:DescriptorMember;readonly bytes:Buffer}):ProductDescriptor{const info=inspectUvfitsVisibilities(input.bytes);return descriptor({schema:'cssearth-telescope-product-descriptor@1',dataset:{id:stable(input.id,'UVFITS id'),target:info.target,acquisition:{kind:'repository',identity:input.member.path},producingRecord:input.producingRecord,sourceClassifications:[{term:'UVFITS random-groups visibilities',vocabulary:'AIPS UVFITS',version:'IEEE float bounded profile',status:'source'}],families:['F11'],profiles:[{handlerId:'f11-measurement-set',profileId:'uvfits-complex-visibilities@1'}]},members:[input.member],components:[{id:'visibilities',name:'UVFITS complex visibilities',families:['F11'],locations:[{memberId:input.member.id,hdu:0}],representation:{kind:'complex-samples',rows:info.samples},axes:[],columns:[],quantity:{name:'uncalibrated complex visibility',semantics:'Native UVFITS real/imaginary/weight triples; nonpositive weight is retained as flagged.'},calibration:{state:'raw',basis:['UVFITS BUNIT and header state UNCALIB.']},flags:[{id:'weight-nonpositive',meaning:'Native UVFITS nonpositive weight'}],time:{scale:'UTC-like AIPS DATE Julian date coordinate',format:'two random-group DATE parameters'},dependencyIds:['uvfits-primary-random-groups']}],dependencies:[{id:'uvfits-primary-random-groups',role:'UVFITS random groups encode baseline, time, UVW and complex samples together',memberIds:[input.member.id],componentIds:['visibilities'],requiredFor:['uvfits-visibility-inspect','uvfits-visibility-export'],evidence:'The primary HDU declares GROUPS=T and PTYPE UU/VV/WW/DATE/BASELINE.'}],issues:[{scope:'dataset',identity:'casa-ms',state:'unsupported',reason:'This source is UVFITS, not a CASA Measurement Set. CASA importuvfits is a separate conversion whose output must be pinned as a new MS closure.'}]});}
const uvfitsOperation=(componentId:string,id:'uvfits-visibility-inspect'|'uvfits-visibility-export',label:string):FamilyOperation=>({id,label,handlerId:'f11-measurement-set',componentId,owner:{module:'tools/objects/telescopes/families/f11-measurement-set.mts',export:id==='uvfits-visibility-inspect'?'inspectUvfitsVisibilities':'exportUvfitsVisibilitySelection'},available:true,reason:'The pinned UVFITS random groups expose native complex samples, baseline/time/UVW coordinates and weights.',fixedArguments:{},parameters:[...(id==='uvfits-visibility-export'?[{id:'selection',option:'--selection',kind:'input-path' as const,required:true,description:'JSON row/channel/polarization selection bounded to the native UVFITS axes.'}]:[]),{id:'out',option:'--out',kind:'output-directory' as const,required:true,description:'New output directory.'}],limitations:['UVFITS is not a Measurement Set. Values remain uncalibrated; no MS conversion, calibration or imaging is implied.']});
export const F11_MEASUREMENT_SET_HANDLER:FamilyHandler={id:'f11-measurement-set',families:['F11'],profiles:[{id:'casa-ms-closure@1',format:'CASA Measurement Set directory',version:'bounded five-table closure profile',families:['F11'],evidence:[{path:'tools/objects/telescopes/families/f11-measurement-set.test.mts',establishes:'Official ALMA public ASDM member pins are verified and inspected through the existing ASDM owner without calling the source an MS.',status:'complete'},{path:'tools/objects/interferometry/alma-calibration.test.mts',establishes:'Real ALMA calibration records name one MS and its calibration application.',status:'complete'}]},{id:'uvfits-complex-visibilities@1',format:'AIPS UVFITS random groups',version:'bounded IEEE-float VLA tutorial profile',families:['F11'],publicBaseline:true,evidence:[{path:'tests/fixtures/telescope-families/f11-vla-uvfits/day2_TDEM0003_10s_norx_1src_1spw.uvfits',establishes:'Pinned real VLA tutorial complex visibility samples under the RASG datasets BSD-2-Clause license.',status:'complete'}]}],recognizes:members=>members.some(member=>/\.uvfits$/iu.test(member.path))?['uvfits-complex-visibilities@1']:[],operations:d=>d.dataset.profiles.some(profile=>profile.profileId==='uvfits-complex-visibilities@1')?d.components.filter(c=>c.families.includes('F11')).flatMap(c=>[uvfitsOperation(c.id,'uvfits-visibility-inspect','Inspect UVFITS visibilities'),uvfitsOperation(c.id,'uvfits-visibility-export','Export native visibility selection')]):d.components.filter(c=>c.families.includes('F11')).flatMap(c=>{const qualified=c.calibration.state==='archive-calibrated';const blocked='Unavailable: no real pinned archive-qualified Measurement Set closure has been admitted; local imports remain inspection-only.';return [operation(c.id,'inspect-ms','Inspect MS closure','restoreScript',true,'Pinned required-table closure and local-import limits are inspectable.'),operation(c.id,'select-ms','Select Measurement Set','restoreScript',qualified,qualified?'CASA mstransform selection through the existing restore owner.':blocked),operation(c.id,'export-ms-subset','Export exact MS subset','restoreScript',qualified,qualified?'CASA mstransform preserves selected native rows and required metadata.':blocked),operation(c.id,'amplitude-phase-diagnostics','Amplitude/phase diagnostics','restoreScript',qualified,qualified?'Existing CASA owner reads calibrated selected visibilities.':blocked),operation(c.id,'uv-diagnostics','UV diagnostics','discSelfCalibrationScript',qualified,qualified?'Existing CASA self-calibration owner bins fitted visibility diagnostics.':blocked)];})};
