/** Restore and prove the two bounded public family examples; archive bytes are deliberately not committed. */
import { mkdir, readFile, writeFile } from 'node:fs/promises'; import { resolve } from 'node:path'; import { fileURLToPath } from 'node:url';
import { pinFile } from '../../product-record.mts'; import { BETELGEUSE_ZIMPOL_V, exportIntensityDolp } from './f13-polarimetry.mts'; import { MATHILDE_NEAR_MSI_42826360, exportCalibrationBundle, inspectNearMsiBundle } from './f17-calibration.mts';
type Source={readonly id:string;readonly url:string;readonly path:string;readonly file:string;readonly role:'science'|'label'};
const sources:readonly Source[]=[
  {...BETELGEUSE_ZIMPOL_V.intensity,file:'zimpol-intensity.fits',role:'science'},{...BETELGEUSE_ZIMPOL_V.dolp,file:'zimpol-dolp.fits',role:'science'},
  {...MATHILDE_NEAR_MSI_42826360.raw,file:'mathilde-raw.fit',role:'science'},{...MATHILDE_NEAR_MSI_42826360.calibrated,file:'mathilde-iof.fit',role:'science'},{...MATHILDE_NEAR_MSI_42826360.label,file:'mathilde-label.xml',role:'label'},
];
const member=(source:Source)=>({id:source.id,path:source.path,role:source.role});
async function verify(file:string,source:Source){const pin=await pinFile(file);if(!pin.bytes)throw new Error(`${source.id} is empty.`);}
/** Download every public member to `directory`, rejecting an empty archive response. */
export async function restoreF13F17Examples(directory:string){await mkdir(directory,{recursive:true});for(const source of sources){const file=resolve(directory,source.file);const response=await fetch(source.url);if(!response.ok)throw new Error(`Archive download failed for ${source.id}: HTTP ${response.status}.`);await writeFile(file,Buffer.from(await response.arrayBuffer()));await verify(file,source);}return Object.fromEntries(sources.map(source=>[source.id,resolve(directory,source.file)]));}
/** Reopen the restored bytes through the public family operations and leave bounded receipts/previews. */
export async function proveF13F17Examples(directory:string,out:string){const file=(name:string)=>resolve(directory,name),intensity=sources[0]!,dolp=sources[1]!,raw=sources[2]!,calibrated=sources[3]!,label=sources[4]!;for(const source of sources)await verify(file(source.file),source);const rawMember=member(raw),calibratedMember=member(calibrated),f13=await exportIntensityDolp(resolve(out,'f13'),{intensity:{file:file(intensity.file),member:member(intensity)},dolp:{file:file(dolp.file),member:member(dolp)}});const near=inspectNearMsiBundle({calibrated:await readFile(file(calibrated.file)),raw:await readFile(file(raw.file)),label:await readFile(file(label.file),'utf8'),calibratedMember,rawMember});const f17=await exportCalibrationBundle(resolve(out,'f17'),[{file:file(raw.file),member:rawMember},{file:file(calibrated.file),member:calibratedMember},{file:file(label.file),member:member(label)}]);const receipt=resolve(out,'proof.json');await mkdir(out,{recursive:true});await writeFile(receipt,JSON.stringify({schema:'cssearth-f13-f17-live-proof@1',f13:{inspection:f13.inspection,receipt:f13.receipt,preview:f13.preview},f17:{width:near.width,height:near.height,filter:near.filter,startTime:near.startTime,rawMissingPixels:near.qualityReport.rawMissingPixels,rawSaturatedPixels:near.qualityReport.rawSaturatedPixels,receipt:f17.receipt}},null,2)+'\n');return{receipt,f13,f17};}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){const directory=resolve(process.argv[2]??'output/telescope-family-examples/input'),out=resolve(process.argv[3]??'output/telescope-family-examples');await restoreF13F17Examples(directory);console.log(JSON.stringify(await proveF13F17Examples(directory,out),null,2));}
