/** F13 keeps ESO's paired intensity/DOLP products distinct from Stokes products. */
import { cp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { spawn } from 'node:child_process';
import { astroqueryToolchain } from '../../astronomy-packages/toolchain.mts';
import{ plotNumericPreview ,type FigureOptions}from'../../astronomy-packages/plots.mts';
import { resolve } from 'node:path';
import { fileSize } from '../../product-record.mts';
import { readFitsImage } from '../../../fits/fits.mts';
import type { FamilyHandler, FamilyOperation } from '../family-handlers.mts';
import type { DescriptorMember, ProductDescriptor } from '../product-descriptor.mts';
import { descriptor, stable } from './common.mts';

export interface DegreeLinearPolarizationInput { readonly id:string; readonly target?:string; readonly intensity:DescriptorMember; readonly dolp:DescriptorMember; readonly shape:readonly [number,number]; readonly producingRecord:string }
/** Exact Phase 3 entries declared by the Betelgeuse shell author. They are references, not redistributed fixture bytes. */
export const BETELGEUSE_ZIMPOL_V=Object.freeze({
  intensity:{id:'zimpol-v-intensity',path:'observations/SPHERE_ZIMPOL_Betelgeuse_P1_V_phase3.fits',url:'https://dataportal.eso.org/dataPortal/file/ADP.2026-08-19T13:19:07.655'},
  dolp:{id:'zimpol-v-dolp',path:'observations/SPHERE_ZIMPOL_Betelgeuse_P1_V_DOLP.fits',url:'https://dataportal.eso.org/dataPortal/file/ADP.2026-08-19T13:19:07.656'},
  record:'tools/objects/source-authoring/betelgeuse-shell/author.mts',
});
export interface PolarimetryInspection { readonly shape:readonly [number,number]; readonly intensity:{readonly finite:number;readonly nonfinite:number}; readonly dolp:{readonly finite:number;readonly nonfinite:number} }
export interface StokesPin { readonly path:string }
export interface StokesSelection { readonly operation:'stokes-inspect'|'stokes-image'|'stokes-spectrum'|'stokes-series'|'stokes-derived'; readonly component?:'I'|'Q'|'U'|'V'; readonly slice?:Readonly<Record<string,number>>; readonly x?:number; readonly y?:number; readonly derived?:'linear-polarization-fraction'|'polarization-angle'; readonly policy?:'iau-half-arctan2-qu' }
/** Astropy is the FITS/WCS owner. The declared STOKES WCS codes, rather than plane order, select I/Q/U/V. */
const stokesPython=String.raw`import json,sys,numpy as np
from astropy.io import fits
import astropy
r=json.load(sys.stdin); h=fits.open(r['path'],memmap=False)[0]; data=np.asarray(h.data); q=h.header
if data.ndim<3: raise ValueError('Stokes profile requires a native FITS array with a STOKES axis')
axes=[]
for fa in range(1,data.ndim+1):
 c=str(q.get('CTYPE'+str(fa),'')).upper(); idx=data.ndim-fa
 role='stokes' if 'STOKES' in c else 'spectral' if any(x in c for x in ('FREQ','WAVE','VRAD','VOPT','VELO')) else 'time' if 'TIME' in c else 'x' if any(x in c for x in ('RA','GLON','LON')) else 'y' if any(x in c for x in ('DEC','GLAT','LAT')) else 'other'
 axes.append({'id':'axis-'+str(idx),'fitsAxis':fa,'length':int(data.shape[idx]),'role':role,'ctype':c or None,'unit':str(q.get('CUNIT'+str(fa),'')) or None})
axes.sort(key=lambda a:int(a['id'].split('-')[1]))
sa=[a for a in axes if a['role']=='stokes']
if len(sa)!=1: raise ValueError('Stokes profile requires exactly one STOKES axis')
s=sa[0]; crval=float(q.get('CRVAL'+str(s['fitsAxis']),0)); cdelt=float(q.get('CDELT'+str(s['fitsAxis']),0)); crpix=float(q.get('CRPIX'+str(s['fitsAxis']),1)); codes={}
for i in range(s['length']):
 code=round(crval+(i+1-crpix)*cdelt)
 if code in (1,2,3,4): codes[{1:'I',2:'Q',3:'U',4:'V'}[code]]=i
if not codes: raise ValueError('STOKES WCS does not declare I, Q, U or V')
if r['operation']=='stokes-inspect': json.dump({'shape':[int(x) for x in data.shape],'axes':axes,'components':codes,'astropy':astropy.__version__,'conventions':{'basis':'FITS STOKES WCS codes','sign':'as declared by archive FITS/WCS','angle':'undefined unless explicit iau-half-arctan2-qu policy is requested'}},sys.stdout); raise SystemExit
want={'stokes-image':{'x','y'},'stokes-spectrum':{'spectral'},'stokes-series':{'time'}}.get(r['operation'],set())
if r['operation']=='stokes-derived': want={'x','y'}
if not all(any(a['role']==x for a in axes) for x in want): raise ValueError('Requested selected axes are absent')
sl=dict(r.get('slice') or {}); known={a['id'] for a in axes}
if set(sl)-known: raise ValueError('Slice names an unknown axis')
if r['operation']=='stokes-spectrum':
 if not isinstance(r.get('x'),int) or not isinstance(r.get('y'),int): raise ValueError('Spectrum requires explicit x and y')
 sl.update({next(a['id'] for a in axes if a['role']=='x'):r['x'],next(a['id'] for a in axes if a['role']=='y'):r['y']})
if r['operation']!='stokes-derived':
 c=r.get('component')
 if c not in codes: raise ValueError('Requested Stokes component is absent; missing components are never zero')
 sl[s['id']]=codes[c]
for a in axes:
 if r['operation']=='stokes-derived' and a['role']=='stokes': continue
 if a['role'] not in want and a['id'] not in sl: raise ValueError('Every axis outside the requested extraction must be explicitly sliced: '+a['id'])
 if a['id'] in sl and (not isinstance(sl[a['id']],int) or sl[a['id']]<0 or sl[a['id']]>=a['length']): raise ValueError('Slice index is out of bounds: '+a['id'])
if r['operation']=='stokes-derived':
 if r.get('derived') not in ('linear-polarization-fraction','polarization-angle') or r.get('policy')!='iau-half-arctan2-qu': raise ValueError('Derived polarization requires an explicit iau-half-arctan2-qu policy')
 if not all(x in codes for x in ('I','Q','U')): raise ValueError('Derived polarization requires declared I, Q and U; missing components are never zero')
 base=dict(sl); base[s['id']]=codes['I']; I=data[tuple(slice(None) if a['role'] in want else base[a['id']] for a in axes)]
 base[s['id']]=codes['Q']; Q=data[tuple(slice(None) if a['role'] in want else base[a['id']] for a in axes)]
 base[s['id']]=codes['U']; U=data[tuple(slice(None) if a['role'] in want else base[a['id']] for a in axes)]
 p=np.hypot(Q,U)
 if r['derived']=='linear-polarization-fraction':
  out=np.full(p.shape,np.nan,dtype=float); np.divide(p,I,out=out,where=I!=0); semantics='sqrt(Q^2+U^2)/I; undefined where I is zero'
 else:
  out=np.full(p.shape,np.nan,dtype=float); np.copyto(out,0.5*np.arctan2(U,Q),where=p!=0); semantics='0.5 atan2(U,Q) radians; undefined where polarized intensity is zero'
 values=np.asarray(out,dtype=object); values[~np.isfinite(out)]=None
 result={'operation':r['operation'],'derived':r['derived'],'policy':r['policy'],'shape':[int(x) for x in out.shape],'axes':[a for a in axes if a['role'] in want],'selection':sl,'values':values.tolist(),'semantics':semantics,'components':['I','Q','U'],'astropy':astropy.__version__}
else:
 out=data[tuple(slice(None) if a['role'] in want else sl[a['id']] for a in axes)]
 result={'operation':r['operation'],'component':r['component'],'shape':[int(x) for x in out.shape],'axes':[a for a in axes if a['role'] in want],'selection':sl,'values':np.asarray(out,dtype=float).tolist(),'conventions':{'basis':'FITS STOKES WCS codes','sign':'as declared by archive FITS/WCS','frame':str(q.get('RADESYS',q.get('EQUINOX','unspecified')))},'astropy':astropy.__version__}
json.dump(result,sys.stdout,allow_nan=False)`;
async function stokesRun(pin:StokesPin,selection:StokesSelection):Promise<any>{const toolchain=await astroqueryToolchain();return new Promise((done,fail)=>{const child=spawn(toolchain.python,['-c',stokesPython],{env:{...process.env,...toolchain.env},stdio:['pipe','pipe','pipe']});let out='',err='';child.stdout.setEncoding('utf8').on('data',x=>out+=x);child.stderr.setEncoding('utf8').on('data',x=>err+=x);child.on('error',fail);child.on('close',code=>{if(code!==0)return fail(new Error(`Astropy Stokes owner failed: ${err.slice(-1000)}`));try{done(JSON.parse(out));}catch(error){fail(error);}});child.stdin.end(JSON.stringify({path:pin.path,...selection}));});}
export async function inspectStokesFits(pin:StokesPin){return stokesRun(pin,{operation:'stokes-inspect'});}
export async function extractStokesFits(pin:StokesPin,selection:StokesSelection){if(selection.operation==='stokes-inspect')throw new TypeError('Use inspectStokesFits for inspection.');return stokesRun(pin,selection);}
/** Render an already extracted native Stokes image or one-dimensional cut. No component or convention is changed. */
export async function previewStokesExtraction(out:string,title:string,extraction:{readonly shape:readonly number[];readonly values:any},options:FigureOptions={}){
  const shape=extraction.shape;if(shape.length===1){const values=(extraction.values as readonly (number|null)[]).map(value=>value??NaN);return plotNumericPreview(out,{kind:'series',title,xLabel:'Native axis index',yLabel:'Native Stokes value',series:[{label:'selected native samples',x:values.map((_,index)=>index),y:values}]},options);}
  if(shape.length===2){const rows=extraction.values as readonly (readonly (number|null)[])[];const height=shape[0]!,width=shape[1]!;if(rows.length!==height||rows.some(row=>row.length!==width))throw new TypeError('Stokes extraction values disagree with shape.');return plotNumericPreview(out,{kind:'raster',title,xLabel:'Native x index',yLabel:'Native y index',width,height,values:rows.flatMap(row=>row.map(value=>value??NaN)),colorLabel:'Native Stokes value'},options);}
  throw new TypeError('Only selected Stokes image or one-dimensional extraction has a static preview.');
}
export function describeStokesFits(input:{readonly id:string;readonly member:DescriptorMember;readonly inspection:Awaited<ReturnType<typeof inspectStokesFits>>;readonly producingRecord:string;readonly target?:string}):ProductDescriptor{const i=input.inspection,axes=i.axes.map((a:any,index:number)=>({id:a.id,index,length:a.length,role:a.role==='stokes'?'polarization':a.role==='x'||a.role==='y'?'unknown':a.role, ...(a.unit?{unit:a.unit}:{}),coordinates:{kind:'native' as const,convention:a.ctype??'unnamed native axis',binBounds:false}}));const components=Object.keys(i.components).map(id=>({id:`stokes-${id.toLowerCase()}`,name:`Stokes ${id}`,families:['F13' as const],locations:[{memberId:input.member.id,hdu:0}],representation:{kind:'array' as const,shape:i.shape,storageOrder:'native' as const},axes,columns:[],quantity:{name:`Stokes ${id}`,semantics:`Native FITS STOKES WCS component ${id}; basis, sign and frame remain those declared by the archived product.`},calibration:{state:'archive-calibrated' as const,basis:['Pinned archive FITS/WCS header and payload.']},flags:[],dependencyIds:['stokes-fits-member']}));return descriptor({schema:'cssearth-telescope-product-descriptor@1',dataset:{id:stable(input.id,'Stokes FITS id'),...(input.target?{target:input.target}:{}),acquisition:{kind:'archive',identity:input.member.path},producingRecord:input.producingRecord,sourceClassifications:[{term:'Stokes FITS/WCS cube',vocabulary:'FITS WCS STOKES',version:'4.0',status:'source'}],families:['F13'],profiles:[{handlerId:'f13-polarimetry',profileId:'astropy-stokes-fits@1'}]},members:[input.member],components,dependencies:[{id:'stokes-fits-member',role:'Pinned Stokes FITS/WCS member',memberIds:[input.member.id],componentIds:components.map(c=>c.id),requiredFor:['stokes-inspect','stokes-image','stokes-spectrum','stokes-series','stokes-derived'],evidence:'Astropy decodes the declared STOKES WCS codes without assuming plane order.'}],issues:[]});}
const stats=(values:Float64Array)=>{let finite=0;for(const value of values)if(Number.isFinite(value))finite++;return{finite,nonfinite:values.length-finite};};
/** Decode both native arrays and prove the grids match exactly. DOLP is never interpreted as Q/U/V. */
export function inspectIntensityDolp(intensityBytes:Buffer,dolpBytes:Buffer):PolarimetryInspection {const intensity=readFitsImage(intensityBytes),dolp=readFitsImage(dolpBytes);if(intensity.width!==dolp.width||intensity.height!==dolp.height||intensity.planes!==dolp.planes)throw new Error('Intensity and DOLP products do not share an exact native pixel grid.');if(intensity.planes!==1)throw new Error('Paired intensity/DOLP inspection requires one native image plane per product.');return{shape:[intensity.height,intensity.width],intensity:stats(intensity.values),dolp:stats(dolp.values)};}
/** A small portable preview of the native DOLP grid; it is a display aid, never a new measurement product. */
export function dolpPreview(bytes:Buffer){const image=readFitsImage(bytes);if(image.planes!==1)throw new Error('DOLP preview requires one native image plane.');let low=Infinity,high=-Infinity;for(const value of image.values)if(Number.isFinite(value)){low=Math.min(low,value);high=Math.max(high,value);}if(!Number.isFinite(low))throw new Error('DOLP image has no finite samples.');const scale=high===low?0:255/(high-low),pixels=Buffer.alloc(image.values.length);for(let i=0;i<pixels.length;i++){const value=image.values[i]!;pixels[i]=Number.isFinite(value)?Math.max(0,Math.min(255,Math.round((value-low)*scale))):0;}return Buffer.concat([Buffer.from(`P5\n${image.width} ${image.height}\n255\n`,'ascii'),pixels]);}
async function assertMember(file:string,member:DescriptorMember){await fileSize(file).catch(()=>{throw new Error(`Polarimetry member ${member.id} is missing.`);});}
/** Exact reopenable copy plus a paired-grid receipt. No derived Stokes product is written. */
export async function exportIntensityDolp(out:string,input:{readonly intensity:{readonly file:string;readonly member:DescriptorMember};readonly dolp:{readonly file:string;readonly member:DescriptorMember}}){await assertMember(input.intensity.file,input.intensity.member);await assertMember(input.dolp.file,input.dolp.member);const intensity=await readFile(input.intensity.file),dolp=await readFile(input.dolp.file),inspection=inspectIntensityDolp(intensity,dolp);await mkdir(out,{recursive:true});for(const entry of[input.intensity,input.dolp])await cp(entry.file,resolve(out,entry.member.id+'.fits'));const preview=resolve(out,'dolp-preview.pgm');await writeFile(preview,dolpPreview(dolp));const receipt=resolve(out,'polarimetry.json');await writeFile(receipt,JSON.stringify({schema:'cssearth-f13-polarimetry-export@1',members:[input.intensity.member,input.dolp.member],inspection,preview:'dolp-preview.pgm',refusal:'DOLP is retained as degree of linear polarization. This export establishes no Stokes Q/U/V basis, sign convention, or polarization angle.'},null,2)+'\n');return{directory:out,receipt,preview,inspection};}

export function describeDegreeLinearPolarization(input:DegreeLinearPolarizationInput):ProductDescriptor{const axes=input.shape.map((length,index)=>({id:index===0?'y':'x',index,length,role:index===0?'y':'x',coordinates:{kind:'index' as const}}));const component=(id:string,name:string,memberId:string,semantics:string)=>({id,name,families:['F13' as const],locations:[{memberId}],representation:{kind:'array' as const,shape:input.shape,storageOrder:'native' as const},axes,columns:[],quantity:{name,semantics},calibration:{state:'archive-calibrated' as const,basis:['ESO Phase 3 archived product.']},flags:[],dependencyIds:['paired-polarimetry-products']});return descriptor({schema:'cssearth-telescope-product-descriptor@1',dataset:{id:stable(input.id,'polarimetry id'),...(input.target?{target:input.target}:{}),acquisition:{kind:'archive',identity:'ESO Phase 3 ADP products'},producingRecord:input.producingRecord,sourceClassifications:[{term:'degree of linear polarization',vocabulary:'ESO Phase 3 product semantics',version:'1',status:'source'}],families:['F13'],profiles:[{handlerId:'f13-polarimetry',profileId:'fits-intensity-dolp@1'}]},members:[input.intensity,input.dolp],components:[component('intensity','intensity',input.intensity.id,'Intensity companion for the DOLP product.'),component('degree-linear-polarization','degree of linear polarization',input.dolp.id,'Archived degree-linear-polarization image; it is not a Stokes Q/U/V component.')],dependencies:[{id:'paired-polarimetry-products',role:'ESO intensity and DOLP companion products',memberIds:[input.intensity.id,input.dolp.id],componentIds:['intensity','degree-linear-polarization'],requiredFor:['polarimetry-inspect','polarimetry-export'],evidence:'Both exact Phase 3 products are pinned.'}],issues:[{scope:'component',identity:'degree-linear-polarization',state:'unsupported',reason:'No Stokes Q/U/V or polarization-angle claim: DOLP plus intensity does not establish a component basis, sign convention, or angle policy.'}]});}
const ops=(componentId:string):FamilyOperation[]=>[['polarimetry-inspect','Inspect intensity/DOLP','inspectIntensityDolp'],['polarimetry-export','Export intensity/DOLP','exportIntensityDolp']].map(([id,label,owner])=>({id,label,handlerId:'f13-polarimetry',componentId,owner:{module:'tools/objects/telescopes/families/f13-polarimetry.mts',export:owner},available:true,reason:'The exact archive product has an explicitly declared component meaning.',fixedArguments:{},parameters:[{id:'out',option:'--out',kind:'output-directory' as const,required:true,description:'New output directory.'}],limitations:['No Q/U/V synthesis, polarization angle, or unqualified derived quantity.']}));
const stokesOps=(d:ProductDescriptor):FamilyOperation[]=>{const components=d.components.filter(c=>/^stokes-[iquv]$/u.test(c.id));if(!components.length)return[];const componentChoices=components.map(c=>c.id.slice(-1).toUpperCase());const base=(id:string,label:string,parameters:any[]):FamilyOperation=>({id,label,handlerId:'f13-polarimetry',componentId:components[0]!.id,owner:{module:'tools/objects/telescopes/families/f13-polarimetry.mts',export:id==='stokes-inspect'?'inspectStokesFits':'extractStokesFits'},available:true,reason:'Astropy selects declared FITS/WCS Stokes codes and requires every remaining axis explicitly.',fixedArguments:{},parameters:[...parameters,{id:'out',option:'--out',kind:'output-directory',required:true,description:'New output directory.'}],limitations:['Archive basis, sign and frame are retained from FITS/WCS. Derived angle needs I/Q/U and explicit IAU half-arctan2 policy; zero polarized intensity is undefined.']});return[base('stokes-inspect','Inspect declared Stokes axes',[]),base('stokes-image','Extract Stokes image',[{id:'component',option:'--component',kind:'choice',required:true,choices:componentChoices,description:'Declared Stokes component.'},{id:'slice',option:'--slice',kind:'input-path',required:true,description:'JSON object with every non-image axis index.'}]),base('stokes-spectrum','Extract Stokes spectrum',[{id:'component',option:'--component',kind:'choice',required:true,choices:componentChoices,description:'Declared Stokes component.'},{id:'x',option:'--x',kind:'integer',required:true,minimum:0,description:'Native X index.'},{id:'y',option:'--y',kind:'integer',required:true,minimum:0,description:'Native Y index.'},{id:'slice',option:'--slice',kind:'input-path',required:true,description:'JSON object with every remaining axis index.'}]),base('stokes-series','Extract Stokes time series',[{id:'component',option:'--component',kind:'choice',required:true,choices:componentChoices,description:'Declared Stokes component.'},{id:'slice',option:'--slice',kind:'input-path',required:true,description:'JSON object with every non-time axis index.'}]),base('stokes-derived','Derive declared linear polarization',[{id:'derived',option:'--derived',kind:'choice',required:true,choices:['linear-polarization-fraction','polarization-angle'],description:'Derived quantity.'},{id:'policy',option:'--policy',kind:'choice',required:true,choices:['iau-half-arctan2-qu'],description:'Required angle convention.'},{id:'slice',option:'--slice',kind:'input-path',required:true,description:'JSON object with every non-image axis index.'}])];};
function recognizesStokesFits(prefix:Uint8Array):boolean{
 const header=Buffer.from(prefix).toString('latin1');return header.startsWith('SIMPLE  =')&&/CTYPE\d+\s*=\s*['"]?STOKES\b/u.test(header);
}
export const F13_POLARIMETRY_HANDLER:FamilyHandler={id:'f13-polarimetry',families:['F13'],profiles:[{id:'fits-intensity-dolp@1',format:'Paired FITS intensity and DOLP images',version:'ESO Phase 3',families:['F13'],evidence:[{path:'tools/objects/source-authoring/betelgeuse-shell/author.mts',establishes:'Pinned public ESO SPHERE/ZIMPOL intensity and DOLP archive products.',status:'complete'}]},{id:'astropy-stokes-fits@1',format:'FITS/WCS image, spectral or time Stokes array',version:'Astropy pinned toolchain',families:['F13'],evidence:[{path:'tools/objects/telescopes/families/f13-polarimetry.test.mts',establishes:'Pinned, publicly attributable RM-lite FITS/WCS-derived full-Stokes fixture exercises image, spectrum, time and derived extraction.',status:'complete'}],publicBaseline:true}],recognizes:members=>members.some(m=>recognizesStokesFits(m.prefix))?['astropy-stokes-fits@1']:[],operations:d=>d.dataset.profiles.some(p=>p.profileId==='astropy-stokes-fits@1')?stokesOps(d):d.components.filter(c=>c.families.includes('F13')).flatMap(c=>ops(c.id))};
