/** F13 keeps ESO's paired intensity/DOLP products distinct from Stokes products. */
import { cp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pinFile } from '../../product-record.mts';
import { readFitsImage } from '../../../fits.mts';
import type { FamilyHandler, FamilyOperation } from '../family-handlers.mts';
import type { DescriptorMember, ProductDescriptor } from '../product-descriptor.mts';
import { descriptor, stable } from './common.mts';

export interface DegreeLinearPolarizationInput { readonly id:string; readonly target?:string; readonly intensity:DescriptorMember; readonly dolp:DescriptorMember; readonly shape:readonly [number,number]; readonly producingRecord:string }
/** Exact Phase 3 entries declared by the Betelgeuse shell author. They are references, not redistributed fixture bytes. */
export const BETELGEUSE_ZIMPOL_V=Object.freeze({
  intensity:{id:'zimpol-v-intensity',path:'observations/SPHERE_ZIMPOL_Betelgeuse_P1_V_phase3.fits',bytes:8458560,sha256:'b40cfcb32103c99c5de9f77588519bbb6c9322eb250d7bc9756339fee8abd8eb',url:'https://dataportal.eso.org/dataPortal/file/ADP.2026-08-19T13:19:07.655'},
  dolp:{id:'zimpol-v-dolp',path:'observations/SPHERE_ZIMPOL_Betelgeuse_P1_V_DOLP.fits',bytes:8455680,sha256:'0df320dc9406596a9e47e2633cb97ce5bbfe9db3a7a2f1a8fc2437efdf924687',url:'https://dataportal.eso.org/dataPortal/file/ADP.2026-08-19T13:19:07.656'},
  record:'tools/objects/source-authoring/betelgeuse-shell/author.mts',
});
export interface PolarimetryInspection { readonly shape:readonly [number,number]; readonly intensity:{readonly finite:number;readonly nonfinite:number}; readonly dolp:{readonly finite:number;readonly nonfinite:number} }
const stats=(values:Float64Array)=>{let finite=0;for(const value of values)if(Number.isFinite(value))finite++;return{finite,nonfinite:values.length-finite};};
/** Decode both native arrays and prove the grids match exactly. DOLP is never interpreted as Q/U/V. */
export function inspectIntensityDolp(intensityBytes:Buffer,dolpBytes:Buffer):PolarimetryInspection {const intensity=readFitsImage(intensityBytes),dolp=readFitsImage(dolpBytes);if(intensity.width!==dolp.width||intensity.height!==dolp.height||intensity.planes!==dolp.planes)throw new Error('Intensity and DOLP products do not share an exact native pixel grid.');if(intensity.planes!==1)throw new Error('Paired intensity/DOLP inspection requires one native image plane per product.');return{shape:[intensity.height,intensity.width],intensity:stats(intensity.values),dolp:stats(dolp.values)};}
/** A small portable preview of the native DOLP grid; it is a display aid, never a new measurement product. */
export function dolpPreview(bytes:Buffer){const image=readFitsImage(bytes);if(image.planes!==1)throw new Error('DOLP preview requires one native image plane.');let low=Infinity,high=-Infinity;for(const value of image.values)if(Number.isFinite(value)){low=Math.min(low,value);high=Math.max(high,value);}if(!Number.isFinite(low))throw new Error('DOLP image has no finite samples.');const scale=high===low?0:255/(high-low),pixels=Buffer.alloc(image.values.length);for(let i=0;i<pixels.length;i++){const value=image.values[i]!;pixels[i]=Number.isFinite(value)?Math.max(0,Math.min(255,Math.round((value-low)*scale))):0;}return Buffer.concat([Buffer.from(`P5\n${image.width} ${image.height}\n255\n`,'ascii'),pixels]);}
async function assertMember(file:string,member:DescriptorMember){const pin=await pinFile(file);if(pin.bytes!==member.bytes||pin.sha256!==member.sha256)throw new Error(`Pinned polarimetry member ${member.id} changed.`);}
/** Exact reopenable copy plus a paired-grid receipt. No derived Stokes product is written. */
export async function exportIntensityDolp(out:string,input:{readonly intensity:{readonly file:string;readonly member:DescriptorMember};readonly dolp:{readonly file:string;readonly member:DescriptorMember}}){await assertMember(input.intensity.file,input.intensity.member);await assertMember(input.dolp.file,input.dolp.member);const intensity=await readFile(input.intensity.file),dolp=await readFile(input.dolp.file),inspection=inspectIntensityDolp(intensity,dolp);await mkdir(out,{recursive:true});for(const entry of[input.intensity,input.dolp])await cp(entry.file,resolve(out,entry.member.id+'.fits'));const preview=resolve(out,'dolp-preview.pgm');await writeFile(preview,dolpPreview(dolp));const receipt=resolve(out,'polarimetry.json');await writeFile(receipt,JSON.stringify({schema:'cssearth-f13-polarimetry-export@1',members:[input.intensity.member,input.dolp.member],inspection,preview:'dolp-preview.pgm',refusal:'DOLP is retained as degree of linear polarization. This export establishes no Stokes Q/U/V basis, sign convention, or polarization angle.'},null,2)+'\n');return{directory:out,receipt,preview,inspection};}

export function describeDegreeLinearPolarization(input:DegreeLinearPolarizationInput):ProductDescriptor{const axes=input.shape.map((length,index)=>({id:index===0?'y':'x',index,length,role:index===0?'y':'x',coordinates:{kind:'index' as const}}));const component=(id:string,name:string,memberId:string,semantics:string)=>({id,name,families:['F13' as const],locations:[{memberId}],representation:{kind:'array' as const,shape:input.shape,storageOrder:'native' as const},axes,columns:[],quantity:{name,semantics},calibration:{state:'archive-calibrated' as const,basis:['ESO Phase 3 archived product.']},flags:[],dependencyIds:['paired-polarimetry-products']});return descriptor({schema:'cssearth-telescope-product-descriptor@1',dataset:{id:stable(input.id,'polarimetry id'),...(input.target?{target:input.target}:{}),acquisition:{kind:'archive',identity:'ESO Phase 3 ADP products'},producingRecord:input.producingRecord,sourceClassifications:[{term:'degree of linear polarization',vocabulary:'ESO Phase 3 product semantics',version:'1',status:'source'}],families:['F13'],profiles:[{handlerId:'f13-polarimetry',profileId:'fits-intensity-dolp@1'}]},members:[input.intensity,input.dolp],components:[component('intensity','intensity',input.intensity.id,'Intensity companion for the DOLP product.'),component('degree-linear-polarization','degree of linear polarization',input.dolp.id,'Archived degree-linear-polarization image; it is not a Stokes Q/U/V component.')],dependencies:[{id:'paired-polarimetry-products',role:'ESO intensity and DOLP companion products',memberIds:[input.intensity.id,input.dolp.id],componentIds:['intensity','degree-linear-polarization'],requiredFor:['polarimetry-inspect','polarimetry-export'],evidence:'Both exact Phase 3 products are pinned.'}],issues:[{scope:'component',identity:'degree-linear-polarization',state:'unsupported',reason:'No Stokes Q/U/V or polarization-angle claim: DOLP plus intensity does not establish a component basis, sign convention, or angle policy.'}]});}
const ops=(componentId:string):FamilyOperation[]=>[['polarimetry-inspect','Inspect intensity/DOLP','inspectIntensityDolp'],['polarimetry-export','Export intensity/DOLP','exportIntensityDolp']].map(([id,label,owner])=>({id,label,handlerId:'f13-polarimetry',componentId,owner:{module:'tools/objects/telescopes/families/f13-polarimetry.mts',export:owner},available:true,reason:'The exact archive product has an explicitly declared component meaning.',fixedArguments:{},parameters:[{id:'out',option:'--out',kind:'output-directory' as const,required:true,description:'New output directory.'}],limitations:['No Q/U/V synthesis, polarization angle, or unqualified derived quantity.']}));
export const F13_POLARIMETRY_HANDLER:FamilyHandler={id:'f13-polarimetry',families:['F13'],profiles:[{id:'fits-intensity-dolp@1',format:'Paired FITS intensity and DOLP images',version:'ESO Phase 3',families:['F13'],evidence:[{path:'tools/objects/source-authoring/betelgeuse-shell/author.mts',establishes:'Pinned public ESO SPHERE/ZIMPOL intensity and DOLP archive products.',status:'complete'}]}],recognizes:()=>[],operations:d=>d.components.filter(c=>c.families.includes('F13')).flatMap(c=>ops(c.id))};
