/** F15 native delay-Doppler FITS raster: retain radar axes and never promote it to sky geometry. */
import type { FamilyHandler, FamilyOperation } from '../family-handlers.mts';
import type { DescriptorMember, ProductDescriptor } from '../product-descriptor.mts';
import{ plotNumericPreview ,type FigureOptions}from'../../astronomy-packages/plots.mts';
import { descriptor, finite, stable } from './common.mts';
export interface RadarImage {readonly width:number;readonly height:number;readonly bitpix:number;readonly dataOffset:number;readonly bytes:Buffer}
export interface RadarWindow {readonly delay:[number,number];readonly doppler:[number,number]}
export const GEOGRAPHOS_GE007={labelUrl:'https://sbnarchive.psi.edu/pds3/non_mission/EAR_A_GST_3_RDR_GEOGRAPHOS_RADAR_V1_1/data/ge007.lbl',imageUrl:'https://sbnarchive.psi.edu/pds3/non_mission/EAR_A_GST_3_RDR_GEOGRAPHOS_RADAR_V1_1/data/ge007.fit',labelSha256:'e505b5a1f8d9b38d64a55571d0fa14f14b572ad09cffda5d89b3355e732d2f0c',imageSha256:'e26d04af718cd5f98a2ba0b1f3a9beee509f1ae2168ddec33cab24653a8725a2'} as const;
export function inspectDelayDopplerFits(bytes:Buffer):RadarImage{
  // 1998 RDF2FIT product: only parse the mandatory primary cards; full FITS ownership remains Astropy once available.
  if(bytes.length<2880)throw new TypeError('Radar FITS is shorter than one header block.');
  const cards=Array.from({length:36},(_,i)=>bytes.toString('latin1',i*80,(i+1)*80));
  const value=(key:string)=>{const card=cards.find(row=>row.startsWith(key.padEnd(8)));if(!card)throw new TypeError(`Missing FITS ${key}.`);return Number(card.slice(10).trim().split(/[ /]/u,1)[0]);};
  const width=value('NAXIS1'),height=value('NAXIS2'),bitpix=value('BITPIX'),naxis=value('NAXIS');
  if(naxis!==2||!Number.isSafeInteger(width)||!Number.isSafeInteger(height)||width<1||height<1||bitpix!==-64)throw new TypeError('Radar fixture must be a two-dimensional IEEE float64 FITS image.');
  const dataOffset=2880,needed=width*height*8;if(bytes.length<dataOffset+needed)throw new TypeError('Radar FITS data length disagrees with its declared shape.');
  return{width,height,bitpix,dataOffset,bytes};
}
export function validatePds3RadarLabel(label:Buffer,image:RadarImage){
  const text=label.toString('latin1'),field=(name:string)=>{const match=new RegExp(`^\\s*${name}\\s*=\\s*([^\\r\\n]+)`, 'mu').exec(text);if(!match)throw new TypeError(`PDS3 label lacks ${name}.`);return match[1]!.trim();};
  if(!/\^IMAGE\s*=\s*\("?GE007\.FIT/u.test(text))throw new TypeError('PDS3 label does not point to GE007.FIT.');
  if(Number(field('LINES'))!==image.width||Number(field('LINE_SAMPLES'))!==image.height)throw new TypeError('PDS3 image dimensions conflict with FITS payload after the documented column-major ordering.');
  return {productId:field('PRODUCT_ID').replaceAll('\"',''),target:field('TARGET_NAME').replaceAll('\"','')};
}
const at=(image:RadarImage,x:number,y:number)=>{if(!Number.isSafeInteger(x)||!Number.isSafeInteger(y)||x<0||x>=image.width||y<0||y>=image.height)throw new RangeError('Delay-Doppler pixel is outside the native image.');return image.bytes.readDoubleBE(image.dataOffset+8*(y*image.width+x));};
export function delayDopplerProfile(image:RadarImage,window:RadarWindow){for(const value of [...window.delay,...window.doppler])finite(value,'window coordinate');const [x0,x1]=window.delay,[y0,y1]=window.doppler;if(!Number.isInteger(x0)||!Number.isInteger(x1)||!Number.isInteger(y0)||!Number.isInteger(y1)||x0<0||y0<0||x1>image.width||y1>image.height||x1<=x0||y1<=y0)throw new RangeError('Window must use increasing in-bounds native delay and Doppler pixel indices.');const delay=Array.from({length:x1-x0},(_,x)=>{let sum=0;for(let y=y0;y<y1;y++)sum+=at(image,x+x0,y);return sum;});const doppler=Array.from({length:y1-y0},(_,y)=>{let sum=0;for(let x=x0;x<x1;x++)sum+=at(image,x,y+y0);return sum;});return{window,delay,doppler};}
export function delayDopplerCoordinateView(image:RadarImage){return{shape:[image.height,image.width] as const,axes:[{id:'doppler',length:image.height,coordinate:'native row index'},{id:'delay',length:image.width,coordinate:'native column index'}],orientation:'row-major FITS payload addressed as [doppler,delay]'};}
export async function previewDelayDoppler(out:string,title:string,image:RadarImage,options:FigureOptions={}){return plotNumericPreview(out,{kind:'raster',title,xLabel:'Native delay pixel',yLabel:'Native Doppler pixel',width:image.width,height:image.height,values:Array.from({length:image.width*image.height},(_,index)=>at(image,index%image.width,Math.floor(index/image.width))),colorLabel:'Radar echo power'},options);}
export function describeDelayDoppler(input:{readonly id:string;readonly target?:string;readonly image:DescriptorMember;readonly label:DescriptorMember;readonly bytes:Buffer;readonly labelBytes:Buffer;readonly producingRecord:string}):ProductDescriptor{const native=inspectDelayDopplerFits(input.bytes);validatePds3RadarLabel(input.labelBytes,native);return descriptor({schema:'cssearth-telescope-product-descriptor@1',dataset:{id:stable(input.id,'radar id'),...(input.target?{target:input.target}:{}),acquisition:{kind:'archive',identity:'EAR-A-GST-3-RDR-GEOGRAPHOS-RADAR-V1.1'},producingRecord:input.producingRecord,sourceClassifications:[{term:'delay-Doppler radar image',vocabulary:'NASA PDS3',version:'3',status:'source'}],families:['F15'],profiles:[{handlerId:'f15-radar',profileId:'pds3-delay-doppler-fits@1'}]},members:[input.image,input.label],components:[{id:'delay-doppler',name:'Geographos radar individual run 007',families:['F15'],locations:[{memberId:input.image.id,hdu:0}],representation:{kind:'array',shape:[native.height,native.width],storageOrder:'native'},axes:[{id:'doppler',index:0,length:native.height,role:'doppler-index',coordinates:{kind:'native',convention:'PDS3 label/run-indexed native Doppler coordinate',binBounds:false}},{id:'delay',index:1,length:native.width,role:'delay-index',coordinates:{kind:'native',convention:'PDS3 label/run-indexed native delay coordinate',binBounds:false}}],columns:[],quantity:{name:'radar echo power image',semantics:'Native delay-Doppler raster. It is neither a sky image nor a three-dimensional shape.'},calibration:{state:'archive-calibrated',basis:['PDS3 GE007 label and FITS image.']},flags:[],dependencyIds:['pds3-label']}],dependencies:[{id:'pds3-label',role:'PDS3 label identifies target, observing run and FITS image',memberIds:[input.label.id,input.image.id],componentIds:['delay-doppler'],requiredFor:['radar-inspect','radar-profile','radar-export'],evidence:'PDS3 ^IMAGE points at GE007.FIT.'}],issues:[{scope:'axis',identity:'delay',state:'unknown',reason:'The compact individual-run label establishes native image dimensions but no calibrated physical delay/Doppler coordinate scale is inferred.'}]});}
const ops=(componentId:string):FamilyOperation[]=>[['radar-inspect','Inspect native delay-Doppler image','inspectDelayDopplerFits'],['radar-coordinate-view','Prepare native delay-Doppler coordinate view','delayDopplerCoordinateView'],['radar-preview','Render native delay-Doppler preview','previewDelayDoppler'],['radar-profile','Profile native window','delayDopplerProfile'],['radar-export','Export native delay-Doppler raster','inspectDelayDopplerFits']].map(([id,label,owner])=>({id,label,handlerId:'f15-radar',componentId,owner:{module:'tools/objects/telescopes/families/f15-radar.mts',export:owner},available:true,reason:'Preserves the archive delay-Doppler raster and explicit native windows.',fixedArguments:{},parameters:[...(id==='radar-profile'?[{id:'window',option:'--window',kind:'number-list' as const,required:true,count:4,description:'X0,X1,Y0,Y1 native delay/Doppler pixel window.'}]:[]),{id:'out',option:'--out',kind:'output-directory' as const,required:true,description:'New output directory.'}],limitations:['No sky projection, body shape, or physical coordinate calibration is inferred.']}));
export const F15_RADAR_HANDLER:FamilyHandler={id:'f15-radar',families:['F15'],profiles:[{id:'pds3-delay-doppler-fits@1',format:'PDS3 label plus delay-Doppler FITS image',version:'PDS3/FITS',families:['F15'],publicBaseline:true,evidence:[{path:'tests/fixtures/telescope-families/geographos-radar/ge007.lbl',establishes:'NASA PDS Geographos run identity, target and native 64x127 IEEE image declaration.',status:'complete'},{path:'tests/fixtures/telescope-families/geographos-radar/ge007.fit',establishes:'Pinned authentic PDS delay-Doppler raster.',status:'complete'}]}],recognizes:members=>members.some(member=>/\.fit$/iu.test(member.path))&&members.some(member=>/\.lbl$/iu.test(member.path))?['pds3-delay-doppler-fits@1']:[],operations:d=>d.components.filter(c=>c.families.includes('F15')).flatMap(c=>ops(c.id))};
