import assert from 'node:assert/strict';
import { test } from 'node:test';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createSourceManifest } from '../../../../src/platform/source-manifest.mts';
import { requireArray, requireRecord, requireString, requireFiniteNumber } from '../../../../tools/sources/source-values.mts';
import { loadPdsRadiusTable } from '../../../../tools/objects/terrestrial-layers/obj-shape.mts';
import { uniformDiscTable } from '../../../../tools/objects/source-authoring/betelgeuse/author.mts';
import { readChannelRows } from '../../../../tools/objects/interferometry/oifits-rows.mts';

const root = resolve(import.meta.dirname, '../../../../src/objects/pi1-gruis/source');
const read = async (path: string) => JSON.parse(await readFile(resolve(root, path), 'utf8')) as unknown;
const RADIUS_M = 219710723000, PARSEC_M = 3.085677581491367e16, MAS_RAD = Math.PI / 180 / 3.6e6;

test('π¹ Gruis retains source pins and acquisition closure', async () => {
  const source = await createSourceManifest({ planetId: 'pi1-gruis', planetName: 'π¹ Gruis', sourceRoot: root });
  await source.verify();
  const plan = requireRecord(await read('preparation/acquisition.json')), operations = requireArray(plan.operations).map(value => requireRecord(value));
  const downloaded = new Set(operations.map(operation => requireString(operation.path)));
  for (const input of source.manifest.inputs) {
    if (downloaded.has(input.path)) continue;
    const authored = /^(preparation|presentation)\/.*\.json$/u.test(input.path) && input.acquisition === 'checked repository source';
    if (authored) continue;
    assert.match(input.acquisition, /author\.mts|squeeze-command\.txt/u, `${input.path} is neither downloaded, generated by a named tool nor an authored record`);
  }
  assert.equal(operations.filter(operation => requireString(operation.path).startsWith('observations/')).length, 1, 'the plan restores the one PIONIER file');
  assert.equal(source.manifest.inputs.filter(input => input.consumers.includes('reconstruction-input')).length, 1);
  assert.equal(source.manifest.inputs.filter(input => input.consumers.includes('sphere-photograph')).length, 1);
});

test('the reference sphere is the fitted radius on the stated grid', async () => {
  const measurements = requireRecord(await read('measurements.json')), shape = requireRecord(measurements.shape);
  const text = await readFile(resolve(root, requireString(shape.path)), 'utf8');
  assert.equal(text, uniformDiscTable(Number(measurements.radiusKm), Number(shape.stepDegrees)), 'the table is the authoring tool\'s output');
  const raster = requireRecord(await read('preparation/raster.json')), terrain = requireRecord(requireRecord(requireRecord(requireArray(raster.surfaces)[0]).science).shape);
  const mesh = await loadPdsRadiusTable(resolve(root, requireString(terrain.path)), terrain.grid);
  assert.equal(mesh.positions.length, 2522); assert.equal(mesh.indices.length, 5040);
  const radii = mesh.positions.map(position => Math.hypot(...position));
  assert.ok(radii.every(radius => Math.abs(radius - RADIUS_M) < 1), 'every vertex sits at the fitted radius in metres');
  // The radius is the fitted disc at the Gaia distance, and the display GM is 1.5 solar masses.
  const star = requireRecord(requireRecord(JSON.parse(await readFile(resolve(root, '../../../../packages/astronomy/data/bodies/pi1-gruis.json'), 'utf8')) as unknown));
  const distanceM = requireFiniteNumber(requireRecord(star.star).distanceParsecs) * PARSEC_M;
  const implied = requireFiniteNumber(measurements.angularDiameterMas) * MAS_RAD / 2 * distanceM;
  assert.ok(Math.abs(implied - RADIUS_M) / RADIUS_M < 1e-6, `the radius is the fitted diameter at the stated distance: ${implied} against ${RADIUS_M}`);
  assert.equal(requireFiniteNumber(requireRecord(star.physical).meanRadiusKm), RADIUS_M / 1000);
});

test('the pinned PIONIER file is what the recipe states, and a uniform disc of the fitted diameter fits it poorly', async () => {
  const rows = readChannelRows(await readFile(resolve(root, 'observations/PI_GRU_forImage.fits')));
  assert.equal(rows.vis2.length, 909); assert.equal(rows.t3.length, 603); assert.equal(rows.flagged, 0);
  assert.equal(rows.wavelengthsMetres.length, 6, 'three channels in each of two instrument settings');
  assert.ok(rows.wavelengthsMetres.every(wl => wl > 1.62e-6 && wl < 1.73e-6), 'H band');
  let longest = 0;
  for (const row of rows.vis2) longest = Math.max(longest, Math.hypot(row.u, row.v));
  assert.ok(Math.abs(longest - 82.3) < 0.1, `longest projected baseline ${longest.toFixed(1)} m`);
  // Uniform-disc fit by grid search, the number measurements.json records.
  const j1 = (x: number) => { let sum = 0, term = x / 2, k = 0; while (Math.abs(term) > 1e-15 && k < 200) { sum += term; k++; term *= -(x * x / 4) / (k * (k + 1)); } return sum; };
  let best = { theta: 0, chi2: Infinity };
  for (let theta = 15; theta <= 22; theta += 0.01) {
    const radius = theta * MAS_RAD; let chi2 = 0;
    for (const row of rows.vis2) { const x = Math.PI * Math.hypot(row.u, row.v) / row.wavelengthMetres * radius; const v = x === 0 ? 1 : 2 * j1(x) / x; chi2 += ((row.vis2 - v * v) / Math.max(row.error, 1e-4)) ** 2; }
    if (chi2 < best.chi2) best = { theta, chi2 };
  }
  const measurements = requireRecord(await read('measurements.json'));
  assert.ok(Math.abs(best.theta - requireFiniteNumber(measurements.angularDiameterMas)) < 0.015, `uniform disc ${best.theta.toFixed(2)} mas`);
  assert.ok(best.chi2 / rows.vis2.length > 20, `a uniform disc does not fit these visibilities: reduced chi-squared ${(best.chi2 / rows.vis2.length).toFixed(1)}`);
});
