import type { Connect, Plugin, ViteDevServer } from 'vite';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import searchRoute from './search-route.mts';
import { handleSearchRequest } from './search-response.mts';
import { handleFindRequest } from './find.mts';
import { FIND_PATH } from '../search/find-protocol.mts';
import { parseFeaturePin } from '../search/feature-search.mts';
import { builtSearchData, readPublicFile, type SearchData } from './search-data.mts';
import type { CatalogueIndexEntry } from '../search/catalogue-index.mts';

/** Exercise the Worker's exact routing and handlers in Astro dev and static preview. Dev has no built catalogue, so it
 * computes the one the build would write, under Vite; a static preview reads the built file like the deploy. */
export function searchServer(): Plugin {
  const middleware = (data: () => Promise<SearchData>): Connect.NextHandleFunction => (request, response, next) => {
    if (!request.url || !request.headers.host) return next();
    const url = new URL(request.url, `http://${request.headers.host}`);
    const send = (result: Promise<Response>) => void result.then(async answer => {
      response.writeHead(answer.status, Object.fromEntries(answer.headers));
      response.end(Buffer.from(await answer.arrayBuffer()));
    }).catch(next);
    if (url.pathname === FIND_PATH) { send(data().then(search => handleFindRequest(new Request(url, { method: request.method }), search))); return; }
    const route = searchRoute(new Request(url));
    if (!route) return next();
    send(data().then(search => handleSearchRequest(new Request(route, { method: request.method }), search)));
  };
  // Read at request time: the pin is regenerated by prepare-feature-index while dev runs.
  const readPin = async () => parseFeaturePin(await readFile(resolve(import.meta.dirname, '../prepared/prepared-feature-index.json'), 'utf8'));
  const devData = (server: ViteDevServer) => async (): Promise<SearchData> => ({
    pin: await readPin(),
    read: readPublicFile,
    async catalogue() {
      const module = await server.ssrLoadModule('/site/search/prepared-catalogue-index.mts') as { PREPARED_CATALOGUE_INDEX: { entries: readonly CatalogueIndexEntry[] } };
      return module.PREPARED_CATALOGUE_INDEX.entries;
    },
  });
  return { name: 'cssearth-native-search', configureServer(server) { server.middlewares.use(middleware(devData(server))); },
    configurePreviewServer(server) { server.middlewares.use(middleware(async () => builtSearchData(await readPin()))); } };
}
