import { readFileSync } from 'node:fs';
import { expect, it } from 'vitest';
import { prepareBodyRecords } from '../body-records.mts';
import { HEADER } from './sources.mts';

it('preserves historical generator paths in emitted headers', async () => {
  const header = HEADER('source', 'generator.mts');
  expect(header).toContain('// Generator: packages/astronomy/tools/generator.mts');
  expect(header).toContain('node tools/generator.mts');

  await prepareBodyRecords();
  const bodySource = readFileSync(new URL('../../src/data/generated/bodies.ts', import.meta.url), 'utf8');
  expect(bodySource).toContain('// Generated by tools/body-records.mts from data/. Do not edit.');
});
