import {readJsonSource,requireRecord,requireArray,requireString} from '../../../tools/source-values.mts';
import {parseRuntimeManifest} from '../../../tools/objects/dist/operations.js';
import {requireObjectRuntimeDefinition} from '../../../tools/object-runtime-contract.mts';
import {parseBandReplayScene,parseReplayMinimaps} from '../../../tools/prepared-replay-source.mts';
import {requireObjectControls} from '../../../site/scene-contract.mts';
import {parseBandLenses,parseSurfaceRaster,parseSurfaceGeometry,parseSurfaceContent} from '../../../tools/objects/static-surface/source-contract.mts';
import {validatePreparedCubicSky} from '../../../src/platform/cubic-sky-contract.mts';
import {validateDirectionalSunPlan} from '../../../src/platform/directional-sun-contract.mts';
// Replay the shared static-material preparer against the accepted Moon scene.
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,cp,copyFile,mkdtemp} from 'node:fs/promises';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {createSourceManifest} from '../../../src/platform/source-manifest.mts';
import {prepareObservationLenses} from '../../../tools/objects/static-surface/raster.mts';
import {prepareBandSurfacePresentation} from '../../../tools/objects/static-surface/presentation.mts';
import {prepareRuntimeManifest} from '../../../tools/objects/dist/operations.js';
import {prepareSurfaceMinimaps} from '../../../tools/prepare-surface-minimaps.mts';
import {prepareObjectProvenance} from '../../../tools/objects/provenance.mts';
const read=readJsonSource;
const write=async(p:string|URL,x:unknown)=>writeFile(p,JSON.stringify(x)+'\n');
const hash=(b:Uint8Array)=>createHash('sha256').update(b).digest('hex');
const selected=new Set(requireArray(requireRecord(await read(new URL('./selected-views.json',import.meta.url))).moon).map(value=>requireString(value)));
const objectDirectory=resolve('src/planets/moon'),sourceDirectory=resolve(objectDirectory,'source');
const frozen=requireRecord(await read(new URL('./source-review/baseline.json',import.meta.url)));
const baseline=parseRuntimeManifest(await read(resolve(objectDirectory,'runtime-assets.json')),'moon');
const old=requireObjectRuntimeDefinition(await read(resolve(objectDirectory,'prepared/runtime.json')));
assert.equal(hash(await readFile(resolve(objectDirectory,'prepared/scene.json'))),requireRecord(requireRecord(frozen.files)['prepared/scene.json']).sha256);
const source=await createSourceManifest({planetId:'moon',planetName:'Moon',sourceRoot:sourceDirectory});await source.verify();
await mkdir('output/b10-preparation',{recursive:true});
const stage=await mkdtemp(resolve('output/b10-preparation/moon-')),publicDirectory=resolve(stage,'public'),outputDirectory=resolve(stage,'prepared');
await mkdir(publicDirectory,{recursive:true});await cp(resolve(objectDirectory,'prepared'),outputDirectory,{recursive:true});
for(const a of baseline.assets){const path=resolve('public/scenes/moon',a.filename),bytes=await readFile(path);assert.equal(bytes.length,a.bytes);assert.equal(hash(bytes),a.sha256);await copyFile(path,resolve(publicDirectory,a.filename));}
const scene=parseBandReplayScene(await read(resolve(outputDirectory,'scene.json')));
const raster=parseSurfaceRaster(await read(resolve(sourceDirectory,'preparation/raster.json'))),geometry=parseSurfaceGeometry(await read(resolve(sourceDirectory,'preparation/geometry.json'))),content=parseSurfaceContent(await read(resolve(sourceDirectory,'content/static.json')));
if(raster.kind!=='observation-lenses'||geometry.kind!=='disc-poles')throw new TypeError('Moon thermal replay requires the authored band surface.');
const controls=requireObjectControls(content.controls,'moon'),lenses=parseBandLenses(content.lenses);
if(!controls.lenses)throw new TypeError('Moon thermal replay requires its lens controls.');
await prepareObservationLenses({sourceDirectory,publicDirectory,config:{...raster,lenses:raster.lenses.filter(x=>selected.has(x.id))},geometry});
const sky=validatePreparedCubicSky(await read(resolve(outputDirectory,'sky.json')),{requireSun:false}),sun=validateDirectionalSunPlan(await read(resolve(outputDirectory,'sun.json')));
const presentation=await prepareBandSurfacePresentation({namespace:'moon',plan:scene,lenses,sky,sun});
// The finalizer adds activation groups and world-camera bindings. Verify every
// raw tree field, then keep that accepted enrichment byte for byte.
for(const [key,value] of Object.entries(presentation.tree))assert.deepEqual(value,requireRecord(old.tree)[key],'Fixed tree field differs: '+key);
for(const variant of old.variants)assert.deepEqual(presentation.variants.find(x=>x.when.lensId===variant.when.lensId),variant,'Existing lens binding differs');
const definition={...old,assets:presentation.assets,variants:presentation.variants,controls:content.controls};
for(const name of ['controls','lenses','panel'] as const)await write(resolve(outputDirectory,name+'.json'),content[name]);
const preparedContent=requireRecord(await read(resolve(outputDirectory,'content.json')));preparedContent.provenance=content.provenance;preparedContent.resources=content.resources;
await write(resolve(outputDirectory,'content.json'),preparedContent);await write(resolve(outputDirectory,'runtime.json'),definition);
const authoring=requireRecord(await read(resolve(outputDirectory,'authored-preparation.json')));
authoring.sources=requireRecord(requireRecord(requireRecord(await read(resolve(objectDirectory,'object.json'))).properties).recipe).sources;
await write(resolve(outputDirectory,'authored-preparation.json'),authoring);
const previewObject=resolve(stage,'preview-object'),previewOutput=resolve(stage,'preview-prepared');
await mkdir(resolve(previewObject,'source/preparation'),{recursive:true});await mkdir(previewOutput,{recursive:true});
const previousMinimaps=parseReplayMinimaps(await read(resolve(outputDirectory,'minimaps.json')));
await write(resolve(previewOutput,'controls.json'),{...controls,lenses:{...controls.lenses,controls:controls.lenses.controls.filter(x=>selected.has(x.id))}});
await write(resolve(previewObject,'source/preparation/raster.json'),{...raster,lenses:raster.lenses.filter(x=>selected.has(x.id))});
const minimaps=await prepareSurfaceMinimaps({objectDirectory:previewObject,publicDirectory,outputDirectory:previewOutput});
await cp(resolve(previewOutput,'minimaps'),resolve(outputDirectory,'minimaps'),{recursive:true});
const combined=[...previousMinimaps.images.filter(x=>!selected.has(x.id)),...minimaps];
const order=controls.lenses.controls.map(x=>x.id);combined.sort((a,b)=>order.indexOf(a.id)-order.indexOf(b.id));
await write(resolve(outputDirectory,'minimaps.json'),{images:combined});
const values=[];for(const n of ['runtime','controls','content','lenses','scene','sky','sun'])values.push(await read(resolve(outputDirectory,n+'.json')));
await prepareRuntimeManifest({id:'moon',publicRoot:publicDirectory,manifestPath:resolve(outputDirectory,'runtime-assets.json'),values,allowPreparationArtifacts:true});
await prepareObjectProvenance({objectDirectory,publicDirectory,outputDirectory,basis:'prepared'});
const inventory=parseRuntimeManifest(await read(resolve(outputDirectory,'runtime-assets.json')),'moon');
for(const a of baseline.assets){
 if([...selected].some(id=>a.filename.startsWith('moon-'+id)))continue;
 const now=inventory.assets.find(x=>x.filename===a.filename);assert.ok(now,'Unchanged asset disappeared');assert.equal(now.sha256,a.sha256,'Unchanged image differs');
}
assert.equal(hash(await readFile(resolve(outputDirectory,'scene.json'))),requireRecord(requireRecord(frozen.files)['prepared/scene.json']).sha256);
for(const a of inventory.assets)await copyFile(resolve(publicDirectory,a.filename),resolve('public/scenes/moon',a.filename));
await cp(outputDirectory,resolve(objectDirectory,'prepared'),{recursive:true});
await copyFile(resolve(outputDirectory,'runtime-assets.json'),resolve(objectDirectory,'runtime-assets.json'));
await write(resolve(stage,'receipt.json'),{selected:[...selected],stage,assetCount:inventory.assets.length,sceneSha256:requireRecord(requireRecord(frozen.files)['prepared/scene.json']).sha256});
console.log(stage);
