import assert from 'node:assert/strict';import test from 'node:test';import type {CapabilityRequest} from './query.mts';import {assessFamilyRequest,normalizeFamilyRequest} from './family-request.mts';import {describeDegreeLinearPolarization} from './families/f13-polarimetry.mts';
const legacy:CapabilityRequest={target:'betelgeuse',wavelengthMicrometres:[0.5,0.6]};
const pin=(id:string)=>({id,path:`${id}.fits`,role:'science' as const,bytes:1,sha256:'a'.repeat(64)});
const polar=()=>describeDegreeLinearPolarization({id:'polar',target:'betelgeuse',intensity:pin('intensity'),dolp:pin('dolp'),shape:[2,3],producingRecord:'ESO Phase 3'});
test('legacy capability request is normalized once and family criteria stay optional',()=>{const normalized=normalizeFamilyRequest(legacy);assert.deepEqual(normalized.criteria.spectral?.intervalMicrometres,[0.5,0.6]);assert.equal(normalized.criteria.polarization,undefined);assert.throws(()=>normalizeFamilyRequest({...legacy,angularResolutionArcsec:1},{family:'F15'}),/spatial is physically inapplicable/);});
test('family assessment answers only source-backed requested facts',()=>{const answer=assessFamilyRequest({legacy,family:'F13',criteria:{quantity:'degree linear polarization',polarization:{components:['degree-linear-polarization']},spatial:true}},polar());assert.equal(answer.verdicts.family?.answer,'yes');assert.equal(answer.verdicts.quantity?.answer,'yes');assert.equal(answer.verdicts.polarization?.answer,'yes');assert.equal(answer.verdicts.spectral?.answer,'unknown');assert.equal(answer.verdicts.spatial?.answer,'yes');});
test('explicitly absent Stokes claims are no while omitted time evidence stays unknown',()=>{const answer=assessFamilyRequest({legacy,family:'F13',criteria:{polarization:{components:['Q']}}},polar());assert.equal(answer.verdicts.polarization?.answer,'no');assert.equal(answer.verdicts.time,undefined);});
test('typed table criteria reject a known missing column without turning missing tables into negatives',()=>{const p={...polar(),dataset:{...polar().dataset,families:['F08' as const],profiles:[{handlerId:'f08-table',profileId:'fits-binary-table@1'}]},dependencies:[],components:[{...polar().components[0]!,dependencyIds:[],families:['F08' as const],representation:{kind:'table' as const,rows:1},axes:[],columns:[{id:'flux',name:'flux',role:'measurement',datatype:'float64',nullable:false,variableLength:false}]}],issues:[]};const answer=assessFamilyRequest({legacy,family:'F08',criteria:{table:{columns:['flux','error']}}},p);assert.equal(answer.verdicts.table?.answer,'no');});
test('time, spectral, table and visibility criteria are assessed from explicit descriptor facts',()=>{const base=polar(),component={...base.components[0]!,id:'visibility',families:['F12' as const],dependencyIds:[],representation:{kind:'complex-samples' as const,rows:2},axes:[{id:'spectral',index:0,length:2,role:'spectral',unit:'um',coordinates:{kind:'linear' as const,referenceValue:1,referenceIndex:0,increment:0.5}}],columns:[{id:'amp',name:'amplitude',role:'amplitude',datatype:'float64',nullable:false,variableLength:false}],quantity:{name:'complex visibility',semantics:'Calibrated visibility samples.'},time:{scale:'UTC',format:'ISO-8601'}};const product={...base,dataset:{...base.dataset,families:['F12' as const],profiles:[{handlerId:'f12-oifits',profileId:'oifits-observables@1'}]},components:[component],dependencies:[],issues:[]};const answer=assessFamilyRequest({legacy,family:'F12',criteria:{quantity:'complex visibility',time:true,spectral:{intervalMicrometres:[1,1.5]},table:{columns:['amplitude']},visibility:true}},product);for(const key of ['family','quantity','time','spectral','table','visibility'] as const)assert.equal(answer.verdicts[key]?.answer,'yes');});
