/** Family-aware request adapter. It translates legacy telescope criteria once, then evaluates only retained descriptor facts. */
import type { CapabilityRequest } from './recipe-request.mts';
import type { ConstraintAnswer, ConstraintVerdict } from './query.mts';
import type { AxisDescriptor, DepthDescriptor, FamilyId, InferenceDescriptor, ObservabilityDescriptor, ProductComponent, ProductDescriptor, ResolutionDescriptor, SupportClass } from './product-descriptor.mts';
import { parseProductDescriptor } from './product-descriptor.mts';
import { sciencePackage } from '../astronomy-packages/science.mts';
import { requireArray, requireFiniteNumber } from '@cssearth/core';

export type FamilyCriterionName='target'|'family'|'quantity'|'time'|'spectral'|'spatial'|'table'|'polarization'|'visibility'|'support'|'depth'|'observability'|'resolution'|'inference';
export interface FamilyCriteria {
  readonly quantity?: string;
  readonly time?: true;
  readonly spectral?: { readonly intervalMicrometres?: readonly [number,number] };
  readonly spatial?: true;
  readonly table?: { readonly columns:readonly string[] };
  readonly polarization?: { readonly components:readonly string[] };
  readonly visibility?: true;
  readonly support?: { readonly classes:readonly SupportClass[] };
  readonly depth?: { readonly coordinate:DepthDescriptor['coordinate']; readonly conversionState?:DepthDescriptor['conversion']['state'] };
  readonly observability?: { readonly measurementOperator:ObservabilityDescriptor['measurementOperator']; readonly localization?:ObservabilityDescriptor['localization'] };
  readonly resolution?: { readonly states:readonly ResolutionDescriptor['state'][]; readonly axisIds?:readonly string[]; readonly maxima?:readonly {readonly axisId?:string;readonly value:number;readonly unit:string}[] };
  readonly inference?: { readonly kinds:readonly InferenceDescriptor['kind'][] };
}
export interface FamilyScientificRequest {readonly legacy:CapabilityRequest;readonly family?:FamilyId;readonly criteria?:FamilyCriteria}
export interface NormalizedFamilyRequest {readonly legacy:CapabilityRequest;readonly family?:FamilyId;readonly criteria:FamilyCriteria}
export type FamilyAssessmentVerdictName=FamilyCriterionName|'component';
export interface FamilyRequestAssessment {readonly scope:'descriptor-compatibility';readonly request:NormalizedFamilyRequest;readonly selectedComponentId?:string;readonly verdicts:Readonly<Partial<Record<FamilyAssessmentVerdictName,ConstraintVerdict>>>}
const verdict=(answer:ConstraintAnswer,reason:string):ConstraintVerdict=>({answer,reason});
const norm=(text:string)=>text.trim().toLowerCase().replaceAll(/[^a-z0-9]+/gu,'-').replaceAll(/^-|-$/gu,'');
const supported:Readonly<Record<FamilyCriterionName,readonly FamilyId[]>>={
  target:['F01','F02','F03','F04','F05','F06','F07','F08','F09','F10','F11','F12','F13','F14','F15','F16','F17','F18'],
  family:['F01','F02','F03','F04','F05','F06','F07','F08','F09','F10','F11','F12','F13','F14','F15','F16','F17','F18'],
  quantity:['F01','F02','F03','F04','F05','F06','F07','F08','F09','F10','F11','F12','F13','F14','F15','F16','F17','F18'],
  time:['F06','F07','F10','F11','F12','F15'], spectral:['F01','F02','F03','F05','F07','F08','F11','F12','F13','F15'], spatial:['F01','F02','F13'],
  table:['F03','F05','F06','F08','F09','F10','F11','F12','F17'], polarization:['F11','F12','F13'], visibility:['F11','F12'],
  support:['F01','F02','F03','F04','F05','F06','F07','F08','F09','F10','F11','F12','F13','F14','F15','F16','F17','F18'],
  depth:['F02','F04','F15','F16','F18'],
  observability:['F01','F02','F03','F04','F05','F06','F07','F08','F09','F10','F11','F12','F13','F14','F15','F16','F17','F18'],
  resolution:['F01','F02','F03','F04','F05','F06','F07','F08','F09','F10','F11','F12','F13','F14','F15','F16','F17','F18'],
  inference:['F01','F02','F03','F04','F05','F06','F07','F08','F09','F10','F11','F12','F13','F14','F15','F16','F17','F18']
};
function assertCriterionFamily(family:FamilyId|undefined,criteria:FamilyCriteria){if(!family)return;for(const key of Object.keys(criteria) as (keyof FamilyCriteria)[]){if(criteria[key]!==undefined&&!supported[key].includes(family))throw new TypeError(`${key} is physically inapplicable to ${family}.`);}}
/** Legacy wavelengths/time/resolution are translated exactly once. More specific family criteria remain optional. */
export function normalizeFamilyRequest(request:CapabilityRequest,extra:{readonly family?:FamilyId;readonly criteria?:FamilyCriteria}={}):NormalizedFamilyRequest{
  if(!request.target)throw new TypeError('Legacy request target is required.');
  const applies=(criterion:FamilyCriterionName)=>extra.family===undefined||supported[criterion].includes(extra.family);
  const criteria:FamilyCriteria={...(extra.criteria??{}),...(extra.criteria?.spectral===undefined&&applies('spectral')?{spectral:{intervalMicrometres:request.wavelengthMicrometres}}:{}),...(extra.criteria?.time===undefined&&request.time!==undefined&&applies('time')?{time:true}:{}),...(extra.criteria?.spatial===undefined&&(request.angularResolutionArcsec!==undefined||request.surfaceResolutionKm!==undefined||request.resolutionElements!==undefined)&&applies('spatial')?{spatial:true}:{})};
  if(criteria.quantity!==undefined&&!criteria.quantity.trim())throw new TypeError('Quantity criterion cannot be blank.');
  if(criteria.spectral?.intervalMicrometres!==undefined){const [a,b]=criteria.spectral.intervalMicrometres;if(!Number.isFinite(a)||!Number.isFinite(b)||a<=0||b<a)throw new TypeError('Spectral criterion must be an increasing positive interval.');}
  if(criteria.table?.columns.some(column=>!column.trim()))throw new TypeError('Table criterion columns cannot be blank.');
  if(criteria.polarization?.components.some(component=>!component.trim()))throw new TypeError('Polarization components cannot be blank.');
  if(criteria.support!==undefined&&criteria.support.classes.length===0)throw new TypeError('Support criterion needs at least one accepted class.');
  if(criteria.resolution!==undefined&&criteria.resolution.states.length===0)throw new TypeError('Resolution criterion needs at least one accepted state.');
  for(const [index,maximum] of (criteria.resolution?.maxima??[]).entries())if(!Number.isFinite(maximum.value)||maximum.value<=0||!maximum.unit.trim())throw new TypeError(`Resolution maximum ${index} needs a positive value and unit.`);
  if(criteria.inference!==undefined&&criteria.inference.kinds.length===0)throw new TypeError('Inference criterion needs at least one accepted kind.');
  assertCriterionFamily(extra.family,criteria);return{legacy:request,family:extra.family,criteria};
}
const hasAxes=(product:ProductDescriptor,roles:readonly string[])=>product.components.some(component=>roles.every(role=>component.axes.some(axis=>axis.role===role)));
async function spectralRange(axis:AxisDescriptor):Promise<readonly[number,number]|null>{if(axis.coordinates.kind!=='linear'||!axis.unit)return null;const start=axis.coordinates.referenceValue-axis.coordinates.referenceIndex*axis.coordinates.increment,end=start+(axis.length-1)*axis.coordinates.increment,result=await sciencePackage({operation:'spectral-convert',values:[start,end],unit:axis.unit}),values=requireArray(result.valuesMicrometres,'converted spectral values').map((value,index)=>requireFiniteNumber(value,`converted spectral value ${index}`));return[Math.min(values[0]!,values[1]!),Math.max(values[0]!,values[1]!)];}
async function evaluateSpectral(product:ProductDescriptor,criterion:NonNullable<FamilyCriteria['spectral']>):Promise<ConstraintVerdict>{const candidates=product.components.flatMap(component=>component.axes.filter(axis=>axis.role==='spectral').map(axis=>({component:component.id,axis})));if(!candidates.length)return verdict('unknown','No spectral coordinate is retained in this descriptor.');if(!criterion.intervalMicrometres)return verdict('yes',`A spectral axis is retained by component ${candidates[0]!.component}.`);const decisions:ConstraintVerdict[]=[];for(const candidate of candidates){let range:readonly[number,number]|null;try{range=await spectralRange(candidate.axis);}catch(error){decisions.push(verdict('unknown',`Component ${candidate.component} spectral unit cannot be normalized by Astropy: ${error instanceof Error?error.message:String(error)}`));continue;}if(!range){decisions.push(verdict('unknown',`Component ${candidate.component} does not retain a linear spectral coordinate with a supported unit.`));continue;}const[a,b]=criterion.intervalMicrometres;decisions.push(a>=range[0]&&b<=range[1]?verdict('yes',`Component ${candidate.component} covers the requested interval after Astropy unit conversion.`):verdict('no',`Component ${candidate.component} does not cover the requested interval after Astropy unit conversion.`));}return decisions.find(item=>item.answer==='yes')??(decisions.every(item=>item.answer==='no')?verdict('no','No spectral component covers the requested interval after Astropy unit conversion.'):verdict('unknown','No spectral component has enough supported coordinate evidence to establish the requested interval.'));}
function evaluateQuantity(product:ProductDescriptor,quantity:string):ConstraintVerdict{const wanted=norm(quantity),matches=product.components.some(component=>norm(component.quantity.name)===wanted||norm(component.id)===wanted||norm(component.quantity.semantics).includes(wanted));return matches?verdict('yes','A retained component declares the requested quantity.'):verdict('no','No retained component declares the requested quantity.');}
function evaluateTable(product:ProductDescriptor,columns:readonly string[]):ConstraintVerdict{const tables=product.components.filter(component=>component.representation.kind==='table'||component.representation.kind==='events'||component.representation.kind==='complex-samples');if(!tables.length)return verdict('unknown','No typed table columns are retained in this descriptor.');const known=new Set(tables.flatMap(table=>table.columns.map(column=>norm(column.name))));const missing=columns.filter(column=>!known.has(norm(column)));return missing.length?verdict('no',`Retained table columns do not include ${missing.join(', ')}.`):verdict('yes','Retained typed table columns include every requested column.');}
function evaluatePolarization(product:ProductDescriptor,components:readonly string[]):ConstraintVerdict{const known=new Set(product.components.flatMap(component=>[component.id,component.name,component.quantity.name]).map(norm));const missing=components.filter(component=>!known.has(norm(component))&&!known.has(`stokes-${norm(component)}`));if(!missing.length)return verdict('yes','The requested polarization components are explicitly retained.');const explicit=product.issues.some(issue=>/stokes|polarization/i.test(issue.reason));return explicit?verdict('no',`The descriptor explicitly does not establish ${missing.join(', ')}.`):verdict('unknown',`No retained component establishes ${missing.join(', ')}.`);}
function linkedPolarizationGroups(product:ProductDescriptor,component:ProductComponent){return [[component],...product.dependencies.filter(dependency=>component.dependencyIds.includes(dependency.id)&&dependency.componentIds.includes(component.id)).map(dependency=>product.components.filter(candidate=>dependency.componentIds.includes(candidate.id)))];}
function evaluatePolarizationGroups(product:ProductDescriptor,groups:readonly (readonly ProductComponent[])[],components:readonly string[]):ConstraintVerdict{const decisions=groups.map(group=>evaluatePolarization({...product,components:group},components));return decisions.find(decision=>decision.answer==='yes')??(decisions.every(decision=>decision.answer==='no')?verdict('no','No explicitly linked polarization component group establishes every requested component.'):verdict('unknown','No explicitly linked polarization component group establishes every requested component.'));}
function requestedComponents(product:ProductDescriptor,family:FamilyId|undefined){return family===undefined?product.components:product.components.filter(component=>component.families.includes(family));}
function evaluateSupport(product:ProductDescriptor,family:FamilyId|undefined,classes:readonly SupportClass[]):ConstraintVerdict{const components=requestedComponents(product,family),declared=components.flatMap(component=>component.support?[component.support.class]:[]);if(!declared.length)return verdict('unknown','No applicable component retains a support classification.');if(declared.some(value=>classes.includes(value)))return verdict('yes',`A retained component has accepted support class ${declared.find(value=>classes.includes(value))}.`);return declared.length===components.length?verdict('no',`Applicable components have support classes ${[...new Set(declared)].join(', ')}, outside the accepted set.`):verdict('unknown','Some applicable components lack a support classification and none of the declared classes is accepted.');}
function evaluateDepth(product:ProductDescriptor,family:FamilyId|undefined,criterion:NonNullable<FamilyCriteria['depth']>):ConstraintVerdict{const components=requestedComponents(product,family),declared=components.flatMap(component=>component.depth?[component.depth]:[]);if(!declared.length)return verdict('unknown','No applicable component retains a depth coordinate.');const coordinate=declared.filter(value=>value.coordinate===criterion.coordinate);if(!coordinate.length)return declared.length===components.length?verdict('no',`Applicable components retain ${[...new Set(declared.map(value=>value.coordinate))].join(', ')}, not ${criterion.coordinate}.`):verdict('unknown',`No declared component retains ${criterion.coordinate}, and some components lack depth semantics.`);if(criterion.conversionState===undefined||coordinate.some(value=>value.conversion.state===criterion.conversionState))return verdict('yes',`A retained component establishes ${criterion.coordinate}${criterion.conversionState?` with ${criterion.conversionState} conversion`:''}.`);return verdict('no',`${criterion.coordinate} is retained, but no matching component has ${criterion.conversionState} conversion.`);}
function evaluateObservability(product:ProductDescriptor,family:FamilyId|undefined,criterion:NonNullable<FamilyCriteria['observability']>):ConstraintVerdict{const components=requestedComponents(product,family),declared=components.flatMap(component=>component.observability?[component.observability]:[]);if(!declared.length)return verdict('unknown','No applicable component retains a measurement operator.');const operator=declared.filter(value=>value.measurementOperator===criterion.measurementOperator);if(operator.length&&(criterion.localization===undefined||operator.some(value=>value.localization===criterion.localization)))return verdict('yes',`A retained component establishes ${criterion.measurementOperator}${criterion.localization?` with ${criterion.localization} localization`:''}.`);if(declared.length===components.length)return verdict('no','Every applicable component declares a different measurement operator or localization.');return verdict('unknown','No declared component matches, and some applicable components lack observability semantics.');}
function evaluateResolution(product:ProductDescriptor,family:FamilyId|undefined,criterion:NonNullable<FamilyCriteria['resolution']>):ConstraintVerdict{const components=requestedComponents(product,family),declared=components.flatMap(component=>component.resolution?[component.resolution]:[]);if(!declared.length)return verdict('unknown','No applicable component retains resolution evidence; coordinate spacing is sampling only.');const matching=declared.filter(value=>criterion.states.includes(value.state));if(!matching.length)return declared.length===components.length?verdict('no',`Applicable components declare resolution states ${[...new Set(declared.map(value=>value.state))].join(', ')}, outside the accepted set.`):verdict('unknown','No declared resolution state is accepted and some components lack resolution evidence.');const axes=criterion.axisIds??[];if(axes.length&&!matching.some(value=>axes.every(axisId=>value.elements.some(element=>element.axisId===axisId))))return verdict('no','Accepted resolution evidence does not cover every requested axis.');for(const maximum of criterion.maxima??[]){const comparable=matching.flatMap(value=>value.elements).filter(element=>(maximum.axisId===undefined||element.axisId===maximum.axisId)&&element.unit===maximum.unit&&(element.value!==undefined||element.range!==undefined));if(!comparable.length)return verdict('unknown',`No accepted resolution evidence is numerically comparable to ${maximum.axisId??'the requested quantity'} in ${maximum.unit}; sampling is not used as a substitute.`);const best=Math.min(...comparable.map(element=>element.value??element.range![1]));if(best>maximum.value)return verdict('no',`Best retained ${maximum.axisId??'resolution'} evidence is ${best} ${maximum.unit}, coarser than the requested maximum ${maximum.value} ${maximum.unit}.`);}return verdict('yes',`Retained resolution evidence satisfies the requested state${(criterion.maxima?.length??0)>0?' and numeric maxima':''}.`);}
function evaluateInference(product:ProductDescriptor,family:FamilyId|undefined,criterion:NonNullable<FamilyCriteria['inference']>):ConstraintVerdict{const components=requestedComponents(product,family),declared=components.flatMap(component=>component.inference?[component.inference]:[]);if(!declared.length)return verdict('unknown','No applicable component retains an inference method.');if(declared.some(value=>criterion.kinds.includes(value.kind)))return verdict('yes',`A retained component has accepted inference kind ${declared.find(value=>criterion.kinds.includes(value.kind))!.kind}.`);return declared.length===components.length?verdict('no',`Applicable components use ${[...new Set(declared.map(value=>value.kind))].join(', ')}, outside the accepted set.`):verdict('unknown','No declared inference kind is accepted and some components lack inference evidence.');}
async function assessScientificCriteria(product:ProductDescriptor,request:NormalizedFamilyRequest,polarizationGroups:readonly (readonly ProductComponent[])[]=[product.components]):Promise<Partial<Record<FamilyCriterionName,ConstraintVerdict>>>{
  const c=request.criteria,out:Partial<Record<FamilyCriterionName,ConstraintVerdict>>={};
  if(c.quantity!==undefined)out.quantity=evaluateQuantity(product,c.quantity);
  if(c.time!==undefined)out.time=request.legacy.time&&!('any'in request.legacy.time)?verdict('unknown','The descriptor does not retain observation bounds that can satisfy the requested interval.'):product.components.some(component=>component.time!==undefined)?verdict('yes','A retained component declares time metadata.'):verdict('unknown','No component retains time metadata.');
  if(c.spectral!==undefined)out.spectral=await evaluateSpectral(product,c.spectral);
  if(c.spatial!==undefined)out.spatial=request.legacy.angularResolutionArcsec!==undefined||request.legacy.surfaceResolutionKm!==undefined||request.legacy.resolutionElements!==undefined?verdict('unknown','Spatial axes do not establish measured resolution evidence for the requested threshold.'):hasAxes(product,['x','y'])?verdict('yes','A retained component declares two spatial axes.'):verdict('unknown','No component retains both spatial axes.');
  if(c.table!==undefined)out.table=evaluateTable(product,c.table.columns);
  if(c.polarization!==undefined)out.polarization=evaluatePolarizationGroups(product,polarizationGroups,c.polarization.components);
  if(c.visibility!==undefined)out.visibility=product.components.some(component=>component.representation.kind==='complex-samples'||/visibility/i.test(component.quantity.name))?verdict('yes','A retained component declares visibility samples.'):verdict('unknown','No retained component establishes complex visibility samples.');
  if(c.support!==undefined)out.support=evaluateSupport(product,request.family,c.support.classes);
  if(c.depth!==undefined)out.depth=evaluateDepth(product,request.family,c.depth);
  if(c.observability!==undefined)out.observability=evaluateObservability(product,request.family,c.observability);
  if(c.resolution!==undefined)out.resolution=evaluateResolution(product,request.family,c.resolution);
  if(c.inference!==undefined)out.inference=evaluateInference(product,request.family,c.inference);
  return out;
}
async function assessComponent(product:ProductDescriptor,request:NormalizedFamilyRequest):Promise<{readonly verdict?:ConstraintVerdict;readonly selectedComponentId?:string;readonly verdicts?:Partial<Record<FamilyCriterionName,ConstraintVerdict>>}> {
  const names=(Object.keys(request.criteria) as FamilyCriterionName[]).filter(name=>request.criteria[name as keyof FamilyCriteria]!==undefined);
  if(!names.length)return{};
  const candidates=await Promise.all(requestedComponents(product,request.family).map(async component=>({id:component.id,verdicts:await assessScientificCriteria({...product,components:[component]},request,linkedPolarizationGroups(product,component))})));
  const selected=candidates.find(candidate=>names.every(name=>candidate.verdicts[name]?.answer==='yes'));
  if(selected)return{selectedComponentId:selected.id,verdicts:selected.verdicts,verdict:verdict('yes',`Component ${selected.id} satisfies every requested component-scoped scientific criterion.`)};
  const score=(candidate:typeof candidates[number])=>[names.filter(name=>candidate.verdicts[name]?.answer==='no').length,names.filter(name=>candidate.verdicts[name]?.answer==='unknown').length] as const,best=candidates.reduce<typeof candidates[number]|undefined>((chosen,candidate)=>{if(!chosen)return candidate;const[a,b]=score(chosen),[c,d]=score(candidate);return c<a||c===a&&d<b?candidate:chosen;},undefined),answer=candidates.length&&candidates.every(candidate=>score(candidate)[0]>0)?'no':'unknown';
  return{verdicts:best?.verdicts,selectedComponentId:best?.id,verdict:verdict(answer,answer==='no'?'No single applicable component satisfies every requested scientific criterion.':'No single applicable component establishes every requested scientific criterion.')};
}
/** Assess only requested criteria. Descriptor absence is unknown unless the descriptor explicitly rules the fact out. */
export async function assessFamilyRequest(input:FamilyScientificRequest,descriptorValue:unknown):Promise<FamilyRequestAssessment>{
  const request=normalizeFamilyRequest(input.legacy,{family:input.family,criteria:input.criteria}),product=parseProductDescriptor(descriptorValue),out:Partial<Record<FamilyAssessmentVerdictName,ConstraintVerdict>>={};
  out.target=product.dataset.target===undefined?verdict('unknown','The descriptor does not declare a target.'):norm(product.dataset.target)===norm(request.legacy.target)?verdict('yes','Descriptor target matches the requested target.'):verdict('no',`Descriptor target ${product.dataset.target} does not match requested target ${request.legacy.target}.`);
  if(request.family)out.family=product.dataset.families.includes(request.family)?verdict('yes',`Descriptor declares ${request.family}.`):verdict('no',`Descriptor families are ${product.dataset.families.join(', ')}.`);
  const component=await assessComponent(product,request);
  Object.assign(out,component.verdicts);
  if(component.verdict)out.component=component.verdict;
  return{scope:'descriptor-compatibility',request,...(component.selectedComponentId?{selectedComponentId:component.selectedComponentId}:{}),verdicts:out};
}
