/** Public, static execution boundary for operations backed by a verified product descriptor. */
import {randomUUID} from 'node:crypto';
import {constants} from 'node:fs';
import {copyFile,mkdir,readFile,rename,rm,stat,writeFile} from 'node:fs/promises';
import {basename,dirname,isAbsolute,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {pinFile,writeProductRecord,type ProductInput} from '../product-record.mts';
import {sha256} from '../../../src/platform/sha256.mts';
import {operationsForDescriptor,type FamilyOperation} from './family-handlers.mts';
import {parseProductDescriptor,type ProductDescriptor} from './product-descriptor.mts';
import {filterTableRows,inspectFitsTable,previewTableHistogram,previewTableScatter,readFitsTableRows,exportTableCsv,tableHistogram,tableScatterData,type TableFilter} from './families/f08-table.mts';
import {exportSpectrumCsv,previewSpectrum,selectSpectrumRange,spectrumChartData,type SpectrumSample} from './families/f03-spectrum.mts';
import {exportPhotometryCsv,previewSed,sedPlotData,sedTable,type PhotometryPoint} from './families/f05-photometry.mts';
import {binTimeSeries,exportTimeSeriesCsv,foldTimeSeries,previewTimeSeries,selectTimeSeries,timeSeriesPlotData,type TimeSample} from './families/f06-time-series.mts';
import {astrometryTrackData,exportAstrometryCsv,inspectAstrometry,previewAstrometryTrack,propagateAstrometry,selectAstrometryRows,type AstrometryRow} from './families/f09-astrometry.mts';
import {energyHistogram,exportSelectedEventsCsv,gtiLightCurve,inspectChandraEvents,nativeCountImage,previewCountImage,previewEnergyHistogram,previewLightCurve,type EventSelection} from './families/f10-events.mts';
import {readTessLightCurve} from '../eclipse-map/transit-limb-darkening.mts';
import {dynamicSpectrumSpectrum,dynamicSpectrumTimeSeries,exportDynamicSpectrumCsv,inspectWindRad1,selectDynamicSpectrum} from './families/f07-dynamic-spectrum.mts';
import {extractSlitRegionSpectrum,slitProfileTable,slitScanSummary} from './families/f04-slit-profile.mts';
import {dolpPreview,extractStokesFits,inspectIntensityDolp,inspectStokesFits,previewStokesExtraction} from './families/f13-polarimetry.mts';
import {readChannelRows} from '../interferometry/oifits-rows.mts';
import {subsetOifits,type OifitsRowSelection} from '../interferometry/oifits-concat.mts';
import {delayDopplerCoordinateView,delayDopplerProfile,inspectDelayDopplerFits,previewDelayDoppler} from './families/f15-radar.mts';
import {selectSpatialComponents} from './families/f16-spatial-physical.mts';
import {contextFromPhysicalGridDescriptor,cropPhysicalCartesianGrid,exportPhysicalCartesianNative,inspectPhysicalCartesianGrid,preparePhysicalCartesianVolume,slicePhysicalCartesianGrid,type GridCrop,type GridSlice,type PhysicalGridPlacement,type PhysicalGridTransfer} from './families/f16-cartesian-grid.mts';
import {contextFromSphericalGridDescriptor,inspectPhysicalSphericalGrid,preparePhysicalSphericalVolume,type SphericalDisplayFill,type SphericalDisplayWeight} from './families/f16-spherical-grid.mts';
import {inspectNearMsiBundle} from './families/f17-calibration.mts';
import {exportSpatialObject,inspectSpatialObject} from './spatial-handoff.mts';
import {extractMixedNd,inspectMixedNd} from './families/f02-mixed-nd.mts';
import {inspectHealpix,selectHealpix} from './families/f14-healpix.mts';
import {previewUvfitsSelection} from './families/f11-measurement-set.mts';
import {pyuvdataUvfits,type PyuvdataUvfitsRequest} from '../astronomy-packages/client.mts';
import {implementationFingerprint} from './implementation-dependencies.mts';
import {verifiedProduct} from './projection.mts';

export const FAMILY_OPERATION_STAGE='telescope-family-operation' as const;
type FamilyOperationArguments=
  |{readonly operationId:'spectrum-export'|'spectrum-chart-data'|'photometry-export'|'sed-table'|'sed-plot-data'|'time-series-export'|'time-series-plot-data'|'astrometry-inspect'|'astrometry-export'|'astrometry-track-data'|'slit-profile-table'|'radar-coordinate-view'}
  |{readonly operationId:'spectrum-preview'|'sed-preview'|'time-series-preview'|'astrometry-track-preview'|'radar-preview'}
  |{readonly operationId:'spectrum-select-range';readonly range:readonly [number,number]}
  |{readonly operationId:'time-series-select';readonly range:readonly [number,number]}
  |{readonly operationId:'time-series-bin';readonly bin:readonly [number,number]}
  |{readonly operationId:'time-series-fold';readonly fold:readonly [number,number]}
  |{readonly operationId:'astrometry-propagate';readonly epoch:readonly [number,number]}
  |{readonly operationId:'event-inspect'}
  |{readonly operationId:'selected-events';readonly selection:EventSelection}
  |{readonly operationId:'count-image';readonly image:{readonly x:readonly[number,number];readonly y:readonly[number,number];readonly bins:readonly[number,number];readonly selection?:EventSelection}}
  |{readonly operationId:'energy-histogram';readonly histogram:{readonly edgesEv:readonly number[];readonly selection?:EventSelection}}
  |{readonly operationId:'light-curve';readonly lightCurve:{readonly range:readonly[number,number];readonly binWidthSeconds:number;readonly selection?:EventSelection}}
  |{readonly operationId:'count-image-preview';readonly image:{readonly x:readonly[number,number];readonly y:readonly[number,number];readonly bins:readonly[number,number];readonly selection?:EventSelection}}
  |{readonly operationId:'energy-histogram-preview';readonly histogram:{readonly edgesEv:readonly number[];readonly selection?:EventSelection}}
  |{readonly operationId:'light-curve-preview';readonly lightCurve:{readonly range:readonly[number,number];readonly binWidthSeconds:number;readonly selection?:EventSelection}}
  |{readonly operationId:'slit-scan-inspect'|'polarimetry-inspect'|'polarimetry-export'}
  |{readonly operationId:'dynamic-spectrum-inspect'}
  |{readonly operationId:'stokes-inspect'}
  |{readonly operationId:'stokes-image'|'stokes-series';readonly component:'I'|'Q'|'U'|'V';readonly slice:Readonly<Record<string,number>>}
  |{readonly operationId:'stokes-spectrum';readonly component:'I'|'Q'|'U'|'V';readonly slice:Readonly<Record<string,number>>;readonly x:number;readonly y:number}
  |{readonly operationId:'stokes-derived';readonly derived:'linear-polarization-fraction'|'polarization-angle';readonly policy:'iau-half-arctan2-qu';readonly slice:Readonly<Record<string,number>>}
  |{readonly operationId:'slit-region-spectrum';readonly directory:string;readonly frame:string;readonly row:number}
  |{readonly operationId:'dynamic-spectrum-select'|'dynamic-spectrum-export';readonly selection:readonly[number,number,number,number]}
  |{readonly operationId:'dynamic-spectrum-spectrum';readonly timeIndex:number}
  |{readonly operationId:'dynamic-spectrum-time-series';readonly frequencyIndex:number}
  |{readonly operationId:'table-inspect';readonly columns?:readonly string[]}
  |{readonly operationId:'table-export';readonly columns?:readonly string[]}
  |{readonly operationId:'table-filter';readonly filter:TableFilter;readonly columns?:readonly string[]}
  |{readonly operationId:'table-scatter-data';readonly columns:readonly [string,string]}
  |{readonly operationId:'table-histogram';readonly histogram:{readonly column:string;readonly edges:readonly number[]}}
  |{readonly operationId:'table-scatter-preview';readonly columns:readonly [string,string]}
  |{readonly operationId:'table-histogram-preview';readonly histogram:{readonly column:string;readonly edges:readonly number[]}}
  |{readonly operationId:'astrometry-select-rows';readonly rows:readonly string[]}
  |{readonly operationId:'visibility-diagnostics'|'v2-diagnostics'|'closure-diagnostics'}
  |{readonly operationId:'oifits-subset';readonly subset:OifitsRowSelection}
  |{readonly operationId:'radar-inspect'|'radar-export'}
  |{readonly operationId:'radar-profile';readonly window:readonly [number,number,number,number]}
  |{readonly operationId:'spatial-inspect'|'spatial-export-points'|'spatial-export-volume'|'spatial-export-volume-lens-bank'}
  |{readonly operationId:'spatial-select-components';readonly components:readonly string[]}
  |{readonly operationId:'physical-grid-inspect'}
  |{readonly operationId:'spherical-grid-inspect'}
  |{readonly operationId:'spherical-grid-prepare-volume';readonly size:number;readonly transfer:PhysicalGridTransfer;readonly displayWeight?:SphericalDisplayWeight;readonly displayFill?:SphericalDisplayFill}
  |{readonly operationId:'physical-grid-crop';readonly crop:GridCrop}
  |{readonly operationId:'physical-grid-native'}
  |{readonly operationId:'physical-grid-slice';readonly slice:GridSlice}
  |{readonly operationId:'physical-grid-prepare-volume';readonly crop:GridCrop;readonly transfer:PhysicalGridTransfer;readonly placement:PhysicalGridPlacement}
  |{readonly operationId:'inspect-components'|'near-msi-inspect'|'export-bundle'|'run-reducer'}
  |{readonly operationId:'enumerate-members'|'export-whole'}
  |{readonly operationId:'export-selected';readonly memberIds:readonly string[]}
  |{readonly operationId:'nd-inspect'|'healpix-inspect'}
  |{readonly operationId:'nd-image'|'nd-time-series';readonly slice:Readonly<Record<string,number>>}
  |{readonly operationId:'nd-spectrum';readonly slice:Readonly<Record<string,number>>;readonly x:number;readonly y:number}
  |{readonly operationId:'healpix-select';readonly pixels:readonly number[];readonly components?:readonly string[]}
  |{readonly operationId:'uvfits-visibility-inspect'}
  |{readonly operationId:'uvfits-visibility-export'|'uvfits-amplitude-phase-diagnostics'|'uvfits-uv-coverage-diagnostics';readonly selection:NonNullable<PyuvdataUvfitsRequest['selection']>};
type WithComponent<T>=T extends unknown?T&{readonly componentId?:string}:never;
export type FamilyOperationParameters=WithComponent<FamilyOperationArguments>;
export interface FamilyOperationResult{readonly directory:string;readonly product:string;readonly record:string;readonly operation:FamilyOperation}

const ALLOWED=new Set<FamilyOperationParameters['operationId']>(['nd-inspect','nd-image','nd-spectrum','nd-time-series','healpix-inspect','healpix-select','uvfits-visibility-inspect','uvfits-visibility-export','uvfits-amplitude-phase-diagnostics','uvfits-uv-coverage-diagnostics','spectrum-export','spectrum-select-range','spectrum-chart-data','spectrum-preview','slit-scan-inspect','slit-profile-table','slit-region-spectrum','photometry-export','sed-table','sed-plot-data','sed-preview','time-series-export','time-series-select','time-series-bin','time-series-fold','time-series-plot-data','time-series-preview','dynamic-spectrum-inspect','dynamic-spectrum-select','dynamic-spectrum-spectrum','dynamic-spectrum-time-series','dynamic-spectrum-export','table-inspect','table-export','table-filter','table-scatter-data','table-scatter-preview','table-histogram','table-histogram-preview','astrometry-inspect','astrometry-export','astrometry-propagate','astrometry-select-rows','astrometry-track-data','astrometry-track-preview','event-inspect','selected-events','count-image','count-image-preview','energy-histogram','energy-histogram-preview','light-curve','light-curve-preview','visibility-diagnostics','v2-diagnostics','closure-diagnostics','oifits-subset','polarimetry-inspect','polarimetry-export','stokes-inspect','stokes-image','stokes-spectrum','stokes-series','stokes-derived','radar-inspect','radar-profile','radar-coordinate-view','radar-preview','radar-export','spatial-inspect','spatial-select-components','spatial-export-points','spatial-export-volume','spatial-export-volume-lens-bank','physical-grid-inspect','physical-grid-crop','physical-grid-native','physical-grid-slice','physical-grid-prepare-volume','spherical-grid-inspect','spherical-grid-prepare-volume','inspect-components','near-msi-inspect','export-bundle','run-reducer','enumerate-members','export-selected','export-whole']);
const NEEDS_PARAMETERS=new Set<FamilyOperationParameters['operationId']>(['nd-image','nd-spectrum','nd-time-series','healpix-select','uvfits-visibility-export','uvfits-amplitude-phase-diagnostics','uvfits-uv-coverage-diagnostics','stokes-image','stokes-spectrum','stokes-series','stokes-derived','spectrum-select-range','slit-region-spectrum','time-series-select','time-series-bin','time-series-fold','dynamic-spectrum-select','dynamic-spectrum-spectrum','dynamic-spectrum-time-series','dynamic-spectrum-export','table-filter','table-scatter-data','table-scatter-preview','table-histogram','table-histogram-preview','astrometry-propagate','astrometry-select-rows','selected-events','count-image','count-image-preview','energy-histogram','energy-histogram-preview','light-curve','light-curve-preview','oifits-subset','radar-profile','spatial-select-components','physical-grid-crop','physical-grid-slice','physical-grid-prepare-volume','spherical-grid-prepare-volume','export-selected']);
export function familyOperationNeedsParameters(operationId:string):boolean{if(!ALLOWED.has(operationId as FamilyOperationParameters['operationId']))throw new TypeError(`Unknown public family operation ${operationId}.`);return NEEDS_PARAMETERS.has(operationId as FamilyOperationParameters['operationId']);}
const exact=(value:Record<string,unknown>,keys:readonly string[])=>{for(const key of Object.keys(value))if(key!=='componentId'&&!keys.includes(key))throw new TypeError(`Unsupported operation parameter ${key}.`);};
const strings=(value:unknown,label:string)=>{if(!Array.isArray(value)||value.some(item=>typeof item!=='string'||!item))throw new TypeError(`${label} must be a list of names.`);return value as string[];};
function parameters(value:FamilyOperationParameters):FamilyOperationParameters{
  if(!value||typeof value!=='object'||typeof value.operationId!=='string'||!ALLOWED.has(value.operationId as FamilyOperationParameters['operationId']))throw new TypeError('Unknown public family operation.');
  const row=value as unknown as Record<string,unknown>,id=value.operationId;
  if(row.componentId!==undefined&&(typeof row.componentId!=='string'||!row.componentId))throw new TypeError('componentId must be a nonempty stable component identifier.');
  if(id==='table-inspect'||id==='table-export'){exact(row,['operationId','columns']);return {...value,...(row.columns===undefined?{}:{columns:strings(row.columns,'columns')})} as FamilyOperationParameters;}
  if(id==='table-filter'){
    exact(row,['operationId','filter','columns']);if(!row.filter||typeof row.filter!=='object'||Array.isArray(row.filter))throw new TypeError('table-filter requires a typed filter.');
    const filter=row.filter as Record<string,unknown>;exact(filter,['column','operator','value']);if(typeof filter.column!=='string'||!['eq','ne','lt','lte','gt','gte','is-null'].includes(String(filter.operator))||(filter.value!==undefined&&typeof filter.value!=='string'&&typeof filter.value!=='number'))throw new TypeError('Invalid typed table filter.');
    return {operationId:id,filter:filter as unknown as TableFilter,...(row.columns===undefined?{}:{columns:strings(row.columns,'columns')})};
  }
  if(id==='radar-profile'){
    exact(row,['operationId','window']);if(!Array.isArray(row.window)||row.window.length!==4||row.window.some(item=>typeof item!=='number'||!Number.isFinite(item)))throw new TypeError('radar-profile requires four finite window coordinates.');return value;
  }
  if(id==='nd-image'||id==='nd-time-series'||id==='nd-spectrum'){
    exact(row,id==='nd-spectrum'?['operationId','slice','x','y']:['operationId','slice']);if(!row.slice||typeof row.slice!=='object'||Array.isArray(row.slice)||Object.values(row.slice as Record<string,unknown>).some(item=>!Number.isInteger(item)))throw new TypeError(`${id} requires integer axis slices.`);if(id==='nd-spectrum'&&(!Number.isInteger(row.x)||!Number.isInteger(row.y)))throw new TypeError('nd-spectrum requires integer x and y.');return value;
  }
  if(id==='stokes-image'||id==='stokes-series'||id==='stokes-spectrum'||id==='stokes-derived'){
    const derived=id==='stokes-derived';exact(row,derived?['operationId','derived','policy','slice']:id==='stokes-spectrum'?['operationId','component','slice','x','y']:['operationId','component','slice']);if(!row.slice||typeof row.slice!=='object'||Array.isArray(row.slice)||Object.values(row.slice as Record<string,unknown>).some(item=>!Number.isInteger(item)))throw new TypeError(`${id} requires integer axis slices.`);if(derived){if(!['linear-polarization-fraction','polarization-angle'].includes(String(row.derived))||row.policy!=='iau-half-arctan2-qu')throw new TypeError('stokes-derived requires an explicit supported policy.');}else{if(!['I','Q','U','V'].includes(String(row.component)))throw new TypeError(`${id} requires declared I, Q, U or V component.`);if(id==='stokes-spectrum'&&(!Number.isInteger(row.x)||!Number.isInteger(row.y)))throw new TypeError('stokes-spectrum requires integer x and y.');}return value;
  }
  if(id==='healpix-select'){exact(row,['operationId','pixels','components']);if(!Array.isArray(row.pixels)||!row.pixels.length||row.pixels.some(item=>!Number.isInteger(item)))throw new TypeError('healpix-select requires native integer pixels.');return {operationId:id,pixels:row.pixels as number[],...(row.components===undefined?{}:{components:strings(row.components,'components')})};}
  if(id==='uvfits-visibility-export'||id==='uvfits-amplitude-phase-diagnostics'||id==='uvfits-uv-coverage-diagnostics'){exact(row,['operationId','selection']);if(!row.selection||typeof row.selection!=='object'||Array.isArray(row.selection))throw new TypeError(`${id} requires a typed selection.`);return value;}
  if(id==='dynamic-spectrum-select'||id==='dynamic-spectrum-export'){exact(row,['operationId','selection']);if(!Array.isArray(row.selection)||row.selection.length!==4||row.selection.some(item=>typeof item!=='number'||!Number.isFinite(item)))throw new TypeError(`${id} requires four finite native indices.`);return value;}
  if(id==='dynamic-spectrum-spectrum'||id==='dynamic-spectrum-time-series'){const key=id==='dynamic-spectrum-spectrum'?'timeIndex':'frequencyIndex';exact(row,['operationId',key]);if(!Number.isInteger(row[key])||Number(row[key])<0)throw new TypeError(`${id} requires a nonnegative integer ${key}.`);return value;}
  if(id==='table-scatter-data'||id==='table-scatter-preview'){exact(row,['operationId','columns']);if(!Array.isArray(row.columns)||row.columns.length!==2||row.columns.some(item=>typeof item!=='string'||!item))throw new TypeError(`${id} requires two column names.`);return value;}
  if(id==='table-histogram'||id==='table-histogram-preview'){exact(row,['operationId','histogram']);if(!row.histogram||typeof row.histogram!=='object'||Array.isArray(row.histogram))throw new TypeError(`${id} requires typed histogram parameters.`);const histogram=row.histogram as Record<string,unknown>;exact(histogram,['column','edges']);if(typeof histogram.column!=='string'||!histogram.column||!Array.isArray(histogram.edges)||histogram.edges.length<2||histogram.edges.some(item=>typeof item!=='number'||!Number.isFinite(item)))throw new TypeError(`${id} requires a column and finite bin edges.`);return value;}
  if(id==='astrometry-select-rows'){exact(row,['operationId','rows']);return{operationId:id,rows:strings(row.rows,'rows')};}
  if(id==='spatial-select-components'){exact(row,['operationId','components']);return{operationId:id,components:strings(row.components,'components')};}
  const gridCrop=(value:unknown)=>{if(!value||typeof value!=='object'||Array.isArray(value))throw new TypeError('Physical-grid crop requires coordinates.');const crop=value as Record<string,unknown>;exact(crop,['start','shape']);const vector=(value:unknown,label:string,positive=false)=>{if(!Array.isArray(value)||value.length!==3||value.some(item=>!Number.isSafeInteger(item)||Number(item)<(positive?1:0)))throw new TypeError(`${label} must have three ${positive?'positive':'nonnegative'} integers.`);return value as [number,number,number];};return{start:vector(crop.start,'crop start'),shape:vector(crop.shape,'crop shape',true)} as GridCrop;};
  if(id==='physical-grid-crop'){exact(row,['operationId','crop']);return{operationId:id,crop:gridCrop(row.crop)};}
  if(id==='physical-grid-slice'){exact(row,['operationId','slice']);if(!row.slice||typeof row.slice!=='object'||Array.isArray(row.slice))throw new TypeError('physical-grid-slice requires axis and index.');const slice=row.slice as Record<string,unknown>;exact(slice,['axis','index']);if(!['x','y','z'].includes(String(slice.axis))||!Number.isSafeInteger(slice.index)||Number(slice.index)<0)throw new TypeError('physical-grid-slice requires canonical axis and nonnegative index.');return{operationId:id,slice:{axis:slice.axis as GridSlice['axis'],index:Number(slice.index)}};}
  if(id==='physical-grid-prepare-volume'){exact(row,['operationId','crop','transfer','placement']);const transfer=row.transfer,placement=row.placement;if(!transfer||typeof transfer!=='object'||Array.isArray(transfer)||!placement||typeof placement!=='object'||Array.isArray(placement))throw new TypeError('physical-grid-prepare-volume requires crop, transfer and placement.');const t=transfer as Record<string,unknown>,p=placement as Record<string,unknown>;exact(t,['kind','range','color','strength','clipping','invalid']);exact(p,['referenceFrame','epochJdTt','sourceOriginM','sourceToReferenceXyzw']);const finite=(value:unknown,count:number,label:string)=>{if(!Array.isArray(value)||value.length!==count||value.some(item=>typeof item!=='number'||!Number.isFinite(item)))throw new TypeError(`${label} must contain ${count} finite numbers.`);return value as number[];},range=finite(t.range,2,'display range'),color=finite(t.color,3,'display color'),origin=finite(p.sourceOriginM,3,'source origin'),quaternion=finite(p.sourceToReferenceXyzw,4,'source rotation');if((t.kind!=='linear'&&t.kind!=='sqrt'&&t.kind!=='log10')||!(range[0]!<range[1]!)||color.some(value=>value<0)||typeof t.strength!=='number'||!Number.isFinite(t.strength)||t.strength<=0||t.clipping!=='clamp'||t.invalid!=='transparent')throw new TypeError('Invalid explicit physical display transfer.');if(typeof p.referenceFrame!=='string'||!p.referenceFrame||typeof p.epochJdTt!=='number'||!Number.isFinite(p.epochJdTt)||Math.abs(Math.hypot(...quaternion)-1)>1e-9)throw new TypeError('Invalid explicit physical placement.');return{operationId:id,crop:gridCrop(row.crop),transfer:{kind:t.kind,range:range as [number,number],color:color as [number,number,number],strength:t.strength,clipping:'clamp',invalid:'transparent'},placement:{referenceFrame:p.referenceFrame,epochJdTt:p.epochJdTt,sourceOriginM:origin as [number,number,number],sourceToReferenceXyzw:quaternion as [number,number,number,number]}};}
  if(id==='spherical-grid-prepare-volume'){exact(row,['operationId','size','transfer','displayWeight','displayFill']);if(!Number.isSafeInteger(row.size)||Number(row.size)<32||Number(row.size)>192)throw new TypeError('spherical-grid-prepare-volume size must be an integer from 32 to 192.');const t=row.transfer;if(!t||typeof t!=='object'||Array.isArray(t))throw new TypeError('spherical-grid-prepare-volume requires an explicit transfer.');const transfer=t as Record<string,unknown>;exact(transfer,['kind','range','color','strength','clipping','invalid']);const finite=(value:unknown,count:number,label:string)=>{if(!Array.isArray(value)||value.length!==count||value.some(item=>typeof item!=='number'||!Number.isFinite(item)))throw new TypeError(`${label} must contain ${count} finite numbers.`);return value as number[];},range=finite(transfer.range,2,'display range'),color=finite(transfer.color,3,'display color');if((transfer.kind!=='linear'&&transfer.kind!=='sqrt'&&transfer.kind!=='log10')||!(range[0]!<range[1]!)||(transfer.kind==='log10'&&range[0]!<=0)||color.some(value=>value<0)||typeof transfer.strength!=='number'||!Number.isFinite(transfer.strength)||transfer.strength<=0||transfer.clipping!=='clamp'||transfer.invalid!=='transparent')throw new TypeError('Invalid explicit physical display transfer.');let displayWeight:SphericalDisplayWeight|undefined;if(row.displayWeight!==undefined){if(!row.displayWeight||typeof row.displayWeight!=='object'||Array.isArray(row.displayWeight))throw new TypeError('Invalid spherical display weight.');const d=row.displayWeight as Record<string,unknown>;exact(d,['kind','unit','inner','outer']);const inner=finite(d.inner,2,'display-weight inner range'),outer=finite(d.outer,2,'display-weight outer range');displayWeight={kind:String(d.kind) as SphericalDisplayWeight['kind'],unit:String(d.unit) as SphericalDisplayWeight['unit'],inner:inner as [number,number],outer:outer as [number,number]};}let displayFill:SphericalDisplayFill|undefined;if(row.displayFill!==undefined){if(!row.displayFill||typeof row.displayFill!=='object'||Array.isArray(row.displayFill))throw new TypeError('Invalid spherical display fill.');const d=row.displayFill as Record<string,unknown>;exact(d,['kind','unit','innerRadius','measuredRadius']);if(typeof d.innerRadius!=='number'||!Number.isFinite(d.innerRadius)||typeof d.measuredRadius!=='number'||!Number.isFinite(d.measuredRadius))throw new TypeError('Spherical display-fill radii must be finite.');displayFill={kind:String(d.kind) as SphericalDisplayFill['kind'],unit:String(d.unit) as SphericalDisplayFill['unit'],innerRadius:d.innerRadius,measuredRadius:d.measuredRadius as 1.5};}return{operationId:id,size:Number(row.size),transfer:{kind:transfer.kind as PhysicalGridTransfer['kind'],range:range as [number,number],color:color as [number,number,number],strength:transfer.strength,clipping:'clamp',invalid:'transparent'},...(displayWeight===undefined?{}:{displayWeight}),...(displayFill===undefined?{}:{displayFill})};}
  if(id==='slit-region-spectrum'){exact(row,['operationId','directory','frame','row']);if(typeof row.directory!=='string'||!row.directory||typeof row.frame!=='string'||!row.frame||!Number.isSafeInteger(row.row)||Number(row.row)<0)throw new TypeError('slit-region-spectrum requires a directory, frame identity and nonnegative detector row.');return value;}
  if(id==='oifits-subset'){exact(row,['operationId','subset']);if(!row.subset||typeof row.subset!=='object'||Array.isArray(row.subset))throw new TypeError('oifits-subset requires explicit observable-row selection.');const subset=row.subset as Record<string,unknown>;exact(subset,['OI_VIS','OI_VIS2','OI_T3']);for(const [key,rows] of Object.entries(subset))if(!Array.isArray(rows)||!rows.length||rows.some(item=>!Number.isSafeInteger(item)||Number(item)<0))throw new TypeError(`oifits-subset ${key} rows must be nonnegative integers.`);return value;}
  if(id==='spectrum-select-range'||id==='time-series-select'||id==='time-series-bin'||id==='time-series-fold'||id==='astrometry-propagate'){
    const key=id==='spectrum-select-range'||id==='time-series-select'?'range':id==='time-series-bin'?'bin':id==='time-series-fold'?'fold':'epoch';exact(row,['operationId',key]);const pair=row[key];if(!Array.isArray(pair)||pair.length!==2||pair.some(item=>typeof item!=='number'||!Number.isFinite(item)))throw new TypeError(`${id} requires two finite numeric parameters.`);return value;
  }
  if(id==='export-selected'){exact(row,['operationId','memberIds']);return{operationId:id,memberIds:strings(row.memberIds,'memberIds')};}
  if(id==='selected-events'||id==='count-image'||id==='count-image-preview'||id==='energy-histogram'||id==='energy-histogram-preview'||id==='light-curve'||id==='light-curve-preview'){const key=id==='selected-events'?'selection':id==='count-image'||id==='count-image-preview'?'image':id==='energy-histogram'||id==='energy-histogram-preview'?'histogram':'lightCurve';exact(row,['operationId',key]);if(!row[key]||typeof row[key]!=='object'||Array.isArray(row[key]))throw new TypeError(`${id} requires typed ${key} parameters.`);return value;}
  exact(row,['operationId']);return value;
}
function executableOperation(descriptor:ProductDescriptor,id:string,componentId?:string):FamilyOperation{
  const matches=operationsForDescriptor(descriptor).filter(operation=>operation.id===id&&operation.available&&(componentId===undefined||operation.componentId===componentId));
  if(!matches.length)throw new TypeError(`Family operation ${id} is unavailable for this descriptor.`);
  if(matches.length!==1)throw new TypeError(`Family operation ${id} is ambiguous for this descriptor; state componentId explicitly.`);
  return matches[0]!;
}
const memberPath=(descriptorPath:string,path:string)=>isAbsolute(path)?resolve(path):resolve(dirname(descriptorPath),path);
async function loadDescriptor(path:string){
  const file=resolve(path),bytes=await readFile(file),descriptor=parseProductDescriptor(JSON.parse(bytes.toString()));
  const files=new Map<string,string>();for(const member of descriptor.members){const location=memberPath(file,member.path),pin=await pinFile(location);if(pin.bytes!==member.bytes||pin.sha256!==member.sha256)throw new Error(`Descriptor member pin changed: ${member.id}.`);files.set(member.id,location);}
  return{file,bytes,descriptor,files};
}
async function familyImplementation(operation:FamilyOperation){const root=resolve(import.meta.dirname,'../../..'),owner=isAbsolute(operation.owner.module)?operation.owner.module:resolve(root,operation.owner.module),graph=await implementationFingerprint(root,[fileURLToPath(new URL('family-operation.mts',import.meta.url)),owner]),toolchain=await readFile(resolve(root,'tools/objects/astronomy-packages/requirements.lock'));return{software:{name:`cssEarth family operation ${operation.handlerId}`,version:graph.sha256},toolchainDigest:sha256(toolchain)};}
const componentMember=(descriptor:ProductDescriptor,files:ReadonlyMap<string,string>,operation:FamilyOperation)=>{const component=descriptor.components.find(item=>item.id===operation.componentId);if(!component)throw new TypeError(`Operation component ${operation.componentId} is absent.`);const location=component.locations[0];if(!location)throw new TypeError(`Operation component ${operation.componentId} has no member.`);const file=files.get(location.memberId);if(!file)throw new TypeError(`Operation member ${location.memberId} is absent.`);return{component,location,file};};
const json=(value:unknown)=>`${JSON.stringify(value,null,2)}\n`;
const object=(value:unknown,label:string)=>{if(!value||typeof value!=='object'||Array.isArray(value))throw new TypeError(`${label} must be an object.`);return value as Record<string,unknown>;};
const numericArray=(value:unknown,label:string)=>{if(!Array.isArray(value)||value.some(item=>typeof item!=='number'||!Number.isFinite(item)))throw new TypeError(`${label} must be a finite numeric array.`);return value as number[];};
function spectrumSamples(bytes:Buffer):SpectrumSample[]{const source=object(JSON.parse(bytes.toString()),'spectrum member');if(source.schema!=='cssmercury-mascs-global-spectrum@1')throw new TypeError('The public spectrum executor currently supports the pinned MASCS global-spectrum schema.');const wavelength=numericArray(source.wavelengthNanometers,'wavelengthNanometers'),values=numericArray(source.reflectanceIOverF,'reflectanceIOverF');if(wavelength.length!==values.length)throw new TypeError('Spectrum coordinate and value lengths differ.');return wavelength.map((item,index)=>({id:String(index),segment:'visible',wavelength:item,value:values[index]!}));}
function photometryPoints(bytes:Buffer):PhotometryPoint[]{const source=object(JSON.parse(bytes.toString()),'photometry member');if(source.schema!=='cssearth-disc-integrated-color@1')throw new TypeError('The public photometry executor currently supports the pinned disc-integrated-color schema.');const albedo=object(source.geometricAlbedo,'geometricAlbedo'),body=object(source.object,'object'),waves=object(object(source.effectiveWavelengths,'effectiveWavelengths').nanometres,'effective wavelengths'),band=String(albedo.band),value=Number(albedo.value),uncertainty=Number(albedo.uncertainty),effectiveWavelength=Number(waves[band]);return[{id:`geometric-albedo-${band.toLowerCase()}`,band,system:String(body.system),effectiveWavelength,value,uncertainty,segment:'occultation-area'}];}
function timeSamples(bytes:Buffer):TimeSample[]{const curve=readTessLightCurve(bytes);return Array.from(curve.time,(time,index)=>({id:String(index),segment:`sector-${curve.sector}`,time,value:curve.flux[index]!,uncertainty:curve.error[index]!}));}
function astrometryRows(bytes:Buffer):AstrometryRow[]{const source=object(JSON.parse(bytes.toString()),'astrometry member');if(source.schema!=='cssearth-gaia-nebula-field@1'||!Array.isArray(source.stars))throw new TypeError('The public astrometry executor currently supports the pinned Gaia nebula-field schema.');const epoch=Number(source.coordinateEpochJulianYear);return source.stars.map((raw,index)=>{const row=object(raw,`star ${index}`);return{id:String(row.sourceId),raDeg:Number(row.raDeg),decDeg:Number(row.decDeg),epochJulianYear:epoch,pmRaCosDecMasYr:Number(row.pmRaMasYr),pmDecMasYr:Number(row.pmDecMasYr),...(row.parallaxMas===undefined?{}:{parallaxMas:Number(row.parallaxMas)}),...(row.parallaxErrorMas===undefined?{}:{parallaxErrorMas:Number(row.parallaxErrorMas)})};});}
async function absent(path:string){if(await stat(path).then(()=>true,error=>{if((error as NodeJS.ErrnoException).code==='ENOENT')return false;throw error;}))throw new Error(`Output directory already exists: ${path}.`);}
async function customOutput(loaded:Awaited<ReturnType<typeof loadDescriptor>>,operation:FamilyOperation,params:FamilyOperationParameters,outputDirectory:string){
  const destination=resolve(outputDirectory),staging=`${destination}.${randomUUID()}.partial`;await absent(destination);await mkdir(dirname(destination),{recursive:true});await mkdir(staging);
  try{
    const selected=componentMember(loaded.descriptor,loaded.files,operation),bytes=await readFile(selected.file);let name:string,content:Buffer,ownedSoftware:{name:string;version:string}[]=[],extraOutputs:{path:string;file:string}[]=[];
    if(params.operationId==='nd-inspect'||params.operationId==='nd-image'||params.operationId==='nd-spectrum'||params.operationId==='nd-time-series'){
      const pin={path:selected.file,bytes:loaded.descriptor.members.find(member=>member.id===selected.location.memberId)!.bytes,sha256:loaded.descriptor.members.find(member=>member.id===selected.location.memberId)!.sha256},result=params.operationId==='nd-inspect'?await inspectMixedNd(pin):await extractMixedNd(pin,{operation:params.operationId,slice:(params as any).slice,...(params.operationId==='nd-spectrum'?{x:(params as any).x,y:(params as any).y}:{})});name='mixed-nd.json';content=Buffer.from(json(result));
    }else if(params.operationId==='stokes-inspect'||params.operationId==='stokes-image'||params.operationId==='stokes-spectrum'||params.operationId==='stokes-series'||params.operationId==='stokes-derived'){
      const pin={path:selected.file,bytes:loaded.descriptor.members.find(member=>member.id===selected.location.memberId)!.bytes,sha256:loaded.descriptor.members.find(member=>member.id===selected.location.memberId)!.sha256},result=params.operationId==='stokes-inspect'?await inspectStokesFits(pin):await extractStokesFits(pin,{operation:params.operationId,component:(params as any).component,slice:(params as any).slice,x:(params as any).x,y:(params as any).y,derived:(params as any).derived,policy:(params as any).policy});name='stokes.json';content=Buffer.from(json(result));if(params.operationId!=='stokes-inspect'){const preview=await previewStokesExtraction(staging,`${loaded.descriptor.dataset.target??loaded.descriptor.dataset.id} · ${params.operationId}`,result as any);extraOutputs=preview.files.map(path=>({path,file:resolve(staging,path)}));ownedSoftware.push({name:'Astropy',version:preview.astropy},{name:'Matplotlib',version:preview.matplotlib});}
    }else if(params.operationId==='healpix-inspect'||params.operationId==='healpix-select'){
      const pin={path:selected.file,bytes:loaded.descriptor.members.find(member=>member.id===selected.location.memberId)!.bytes,sha256:loaded.descriptor.members.find(member=>member.id===selected.location.memberId)!.sha256},result=params.operationId==='healpix-inspect'?await inspectHealpix(pin):await selectHealpix(pin,{pixels:(params as any).pixels,components:(params as any).components});name='healpix.json';content=Buffer.from(json(result));ownedSoftware=[{name:'Astropy',version:result.astropy},{name:'astropy-healpix',version:result.astropyHealpix}];
    }else if(params.operationId==='uvfits-visibility-inspect'||params.operationId==='uvfits-visibility-export'||params.operationId==='uvfits-amplitude-phase-diagnostics'||params.operationId==='uvfits-uv-coverage-diagnostics'){
      const member=loaded.descriptor.members.find(item=>item.id===selected.location.memberId)!,result=await pyuvdataUvfits({operation:params.operationId,file:{path:selected.file,bytes:member.bytes,sha256:member.sha256},...(params.operationId==='uvfits-visibility-inspect'?{}:{selection:params.selection})});name=params.operationId==='uvfits-visibility-export'?'visibilities.json':params.operationId==='uvfits-amplitude-phase-diagnostics'?'amplitude-phase.json':params.operationId==='uvfits-uv-coverage-diagnostics'?'uv-coverage.json':'visibility-inspection.json';content=Buffer.from(json(result));ownedSoftware=[{name:'pyuvdata',version:result.pyuvdata}];if(params.operationId==='uvfits-visibility-export'&&result.rows){const preview=await previewUvfitsSelection(staging,`${loaded.descriptor.dataset.target??loaded.descriptor.dataset.id} · UV coverage`,result.rows);extraOutputs=preview.files.map(path=>({path,file:resolve(staging,path)}));ownedSoftware.push({name:'Astropy',version:preview.astropy},{name:'Matplotlib',version:preview.matplotlib});}
    }else if(params.operationId==='spectrum-export'||params.operationId==='spectrum-select-range'||params.operationId==='spectrum-chart-data'){let samples=spectrumSamples(bytes);if(params.operationId==='spectrum-select-range')samples=selectSpectrumRange(samples,{from:params.range[0],to:params.range[1]});if(params.operationId==='spectrum-chart-data'){name='spectrum-chart.json';content=Buffer.from(json(spectrumChartData(samples)));}else{name='spectrum.csv';content=Buffer.from(exportSpectrumCsv(samples));}}
    else if(params.operationId==='slit-scan-inspect'||params.operationId==='slit-profile-table'||params.operationId==='slit-region-spectrum'){const receiptLocation=selected.component.locations[1],receiptFile=receiptLocation&&loaded.files.get(receiptLocation.memberId);if(!receiptFile)throw new TypeError('Slit-scan operation requires its pinned reproduction receipt.');const definition=JSON.parse(bytes.toString()),receipt=JSON.parse((await readFile(receiptFile)).toString());if(params.operationId==='slit-region-spectrum'){name='slit-region-spectrum.json';content=Buffer.from(json(await extractSlitRegionSpectrum(definition,receipt,{directory:resolve(params.directory),frame:params.frame,row:params.row})));}else{name=params.operationId==='slit-profile-table'?'slit-profile.json':'slit-scan.json';content=Buffer.from(json(params.operationId==='slit-profile-table'?slitProfileTable(definition,receipt):slitScanSummary(definition,receipt)));}}
    else if(params.operationId==='photometry-export'||params.operationId==='sed-table'||params.operationId==='sed-plot-data'){const points=photometryPoints(bytes);if(params.operationId==='photometry-export'){name='photometry.csv';content=Buffer.from(exportPhotometryCsv(points));}else{name=params.operationId==='sed-table'?'sed-table.json':'sed-plot.json';content=Buffer.from(json(params.operationId==='sed-table'?sedTable(points):sedPlotData(points)));}}
    else if(params.operationId.startsWith('time-series-')){let samples=timeSamples(bytes);if(params.operationId==='time-series-select')samples=selectTimeSeries(samples,{from:params.range[0],to:params.range[1]});else if(params.operationId==='time-series-bin')samples=binTimeSeries(samples,{width:params.bin[0],origin:params.bin[1]});if(params.operationId==='time-series-fold'){name='time-series.json';content=Buffer.from(json(foldTimeSeries(samples,{epoch:params.fold[0],period:params.fold[1]})));}else if(params.operationId==='time-series-plot-data'){name='time-series-plot.json';content=Buffer.from(json(timeSeriesPlotData(samples)));}else{name='time-series.csv';content=Buffer.from(exportTimeSeriesCsv(samples));}}
    else if(params.operationId==='dynamic-spectrum-inspect'||params.operationId==='dynamic-spectrum-select'||params.operationId==='dynamic-spectrum-spectrum'||params.operationId==='dynamic-spectrum-time-series'||params.operationId==='dynamic-spectrum-export'){const source=await inspectWindRad1({path:selected.file,bytes:loaded.descriptor.members.find(member=>member.id===selected.location.memberId)!.bytes,sha256:loaded.descriptor.members.find(member=>member.id===selected.location.memberId)!.sha256});if(params.operationId==='dynamic-spectrum-inspect'){name='dynamic-spectrum.json';content=Buffer.from(json({shape:[source.epochsTt2000.length,source.frequencyHz.length],time:{first:source.epochsTt2000[0],last:source.epochsTt2000.at(-1),scale:'TT2000'},frequencyHz:{first:source.frequencyHz[0],last:source.frequencyHz.at(-1)},unit:source.unit,decoder:{cdflib:source.cdflib}}));}else if(params.operationId==='dynamic-spectrum-spectrum'){name='dynamic-spectrum-spectrum.json';content=Buffer.from(json(dynamicSpectrumSpectrum(source,params.timeIndex)));}else if(params.operationId==='dynamic-spectrum-time-series'){name='dynamic-spectrum-time-series.json';content=Buffer.from(json(dynamicSpectrumTimeSeries(source,params.frequencyIndex)));}else{const rawSelection=(params as Extract<FamilyOperationParameters,{operationId:'dynamic-spectrum-select'|'dynamic-spectrum-export'}>).selection,selection={time:[rawSelection[0],rawSelection[1]]as[number,number],frequency:[rawSelection[2],rawSelection[3]]as[number,number]},selected=selectDynamicSpectrum(source,selection);name=params.operationId==='dynamic-spectrum-export'?'dynamic-spectrum.csv':'dynamic-spectrum.json';content=Buffer.from(params.operationId==='dynamic-spectrum-export'?exportDynamicSpectrumCsv(selected):json(selected));}}
    else if(params.operationId==='astrometry-inspect'||params.operationId==='astrometry-export'||params.operationId==='astrometry-propagate'||params.operationId==='astrometry-select-rows'||params.operationId==='astrometry-track-data'){let rows=astrometryRows(bytes);if(params.operationId==='astrometry-propagate')rows=propagateAstrometry(rows,{fromJulianYear:params.epoch[0],toJulianYear:params.epoch[1],frame:'ICRS'});else if(params.operationId==='astrometry-select-rows')rows=selectAstrometryRows(rows,params.rows);if(params.operationId==='astrometry-inspect'){name='astrometry.json';content=Buffer.from(json(inspectAstrometry(rows)));}else if(params.operationId==='astrometry-track-data'){name='astrometry-track.json';content=Buffer.from(json(astrometryTrackData(rows)));}else{name='astrometry.csv';content=Buffer.from(exportAstrometryCsv(rows));}}
    else if(params.operationId==='event-inspect'||params.operationId==='selected-events'||params.operationId==='count-image'||params.operationId==='energy-histogram'||params.operationId==='light-curve'){const product=inspectChandraEvents(bytes);if(params.operationId==='event-inspect'){name='events.json';content=Buffer.from(json({rows:product.rows.length,gtis:product.gtis,time:product.time,exposureSeconds:product.exposureSeconds,target:product.target,observationId:product.observationId,columns:product.columns}));}else if(params.operationId==='selected-events'){name='events.csv';content=Buffer.from(exportSelectedEventsCsv(product,params.selection));}else if(params.operationId==='count-image'){name='count-image.json';content=Buffer.from(json(nativeCountImage(product,params.image)));}else if(params.operationId==='energy-histogram'){name='energy-histogram.json';content=Buffer.from(json(energyHistogram(product,params.histogram)));}else{name='light-curve.json';content=Buffer.from(json(gtiLightCurve(product,params.lightCurve)));}}
    else if(params.operationId==='table-inspect'||params.operationId==='table-export'||params.operationId==='table-filter'||params.operationId==='table-scatter-data'||params.operationId==='table-histogram'){
      const extension=selected.location.hdu??selected.location.structure;if(extension===undefined)throw new TypeError('Table operation requires an HDU or structure locator.');
      if(params.operationId==='table-inspect'){name='table.json';content=Buffer.from(json(inspectFitsTable(bytes,extension)));}
      else if(params.operationId==='table-scatter-data'){const rows=readFitsTableRows(bytes,extension,params.columns);name='table-scatter.json';content=Buffer.from(json(tableScatterData(rows,params.columns[0],params.columns[1])));}
      else if(params.operationId==='table-histogram'){const rows=readFitsTableRows(bytes,extension,[params.histogram.column]);name='table-histogram.json';content=Buffer.from(json(tableHistogram(rows,params.histogram.column,params.histogram.edges)));}
      else {let rows=readFitsTableRows(bytes,extension,params.columns);if(params.operationId==='table-filter')rows=filterTableRows(rows,params.filter);name='table.csv';content=Buffer.from(exportTableCsv(rows,params.columns));}
    }else if(params.operationId==='oifits-subset'){name='subset.oifits';content=subsetOifits(bytes,params.subset);}
    else if(params.operationId.endsWith('-diagnostics')){
      const rows=readChannelRows(bytes),data=params.operationId==='visibility-diagnostics'?{vis:rows.vis,wavelengthsMetres:rows.wavelengthsMetres,flagged:rows.flagged}:params.operationId==='v2-diagnostics'?{vis2:rows.vis2,wavelengthsMetres:rows.wavelengthsMetres,flagged:rows.flagged}:{t3:rows.t3,wavelengthsMetres:rows.wavelengthsMetres,flagged:rows.flagged};name='diagnostics.json';content=Buffer.from(json(data));
    }else if(params.operationId==='inspect-components'){name='calibration-components.json';content=Buffer.from(json({dataset:loaded.descriptor.dataset.id,members:loaded.descriptor.members,components:loaded.descriptor.components,dependencies:loaded.descriptor.dependencies}));}
    else if(params.operationId==='near-msi-inspect'||params.operationId==='run-reducer'){
      const entry=(id:string)=>{const member=loaded.descriptor.members.find(item=>item.id===id),file=member&&loaded.files.get(id);if(!member||!file)throw new TypeError(`NEAR MSI calibration closure requires ${id}.`);return{member,file};},raw=entry('raw'),calibrated=entry('calibrated'),label=entry('label'),decoded=inspectNearMsiBundle({raw:await readFile(raw.file),calibrated:await readFile(calibrated.file),label:await readFile(label.file,'utf8'),rawMember:raw.member,calibratedMember:calibrated.member}),accepted=decoded.planes.IMAGE.reduce((count,_value,index)=>count+(decoded.acceptPixel(index)?1:0),0);name=params.operationId==='run-reducer'?'near-msi-reducer.json':'near-msi-inspection.json';content=Buffer.from(json({width:decoded.width,height:decoded.height,startTime:decoded.startTime,filter:decoded.filter,unit:decoded.header.BUNIT,acceptedPixels:accepted,totalPixels:decoded.planes.IMAGE.length,qualityReport:decoded.qualityReport,sourceMembers:{raw:raw.member.id,calibrated:calibrated.member.id,label:label.member.id}}));
    }else if(params.operationId.startsWith('radar-')){
      const image=inspectDelayDopplerFits(bytes);
      if(params.operationId==='radar-export'){name='delay-doppler.fits';await copyFile(selected.file,resolve(staging,name),constants.COPYFILE_EXCL);content=await readFile(resolve(staging,name));}
      else {const data=params.operationId==='radar-profile'?delayDopplerProfile(image,{delay:[params.window[0],params.window[1]],doppler:[params.window[2],params.window[3]]}):params.operationId==='radar-coordinate-view'?delayDopplerCoordinateView(image):{width:image.width,height:image.height,bitpix:image.bitpix,dataOffset:image.dataOffset};name=params.operationId==='radar-profile'?'profile.json':params.operationId==='radar-coordinate-view'?'radar-coordinates.json':'radar.json';content=Buffer.from(json(data));}
    }else if(params.operationId==='spatial-inspect'){name='spatial.json';content=Buffer.from(json(await inspectSpatialObject(selected.file)));}
    else if(params.operationId==='spatial-select-components'){name='spatial-components.json';content=Buffer.from(json(selectSpatialComponents(loaded.descriptor,params.components)));}
    else if(params.operationId==='physical-grid-inspect'||params.operationId==='physical-grid-crop'||params.operationId==='physical-grid-native'||params.operationId==='physical-grid-slice'||params.operationId==='physical-grid-prepare-volume'){
      const member=loaded.descriptor.members.find(item=>item.id===selected.location.memberId)!,context=contextFromPhysicalGridDescriptor(loaded.descriptor),pin={path:selected.file,bytes:member.bytes,sha256:member.sha256};
      if(params.operationId==='physical-grid-native'){const native=await exportPhysicalCartesianNative(pin,resolve(staging,'physical-grid-native.fits'));name='physical-grid-native.json';content=Buffer.from(json({schema:'cssearth-physical-grid-native-export@1',context,pin:native}));extraOutputs=[{path:'physical-grid-native.fits',file:native.path}];}
      else if(params.operationId==='physical-grid-slice'){const slice=await slicePhysicalCartesianGrid(pin,context,params.slice,resolve(staging,'physical-grid-slice.fits'));name='physical-grid-slice.json';content=Buffer.from(json(slice));ownedSoftware=[{name:'Astropy',version:slice.astropy}];extraOutputs=[{path:'physical-grid-slice.fits',file:resolve(staging,'physical-grid-slice.fits')}];}
      else if(params.operationId==='physical-grid-prepare-volume'){const prepared=await preparePhysicalCartesianVolume({id:`${loaded.descriptor.dataset.id}-volume`,pin,context,crop:params.crop,transfer:params.transfer,placement:params.placement,destination:resolve(staging,'physical-volume')});name='physical-grid-volume.json';content=Buffer.from(json({schema:'cssearth-physical-grid-volume@1',object:'physical-volume/object.json',prepared:'physical-volume/prepared/volume.json',native:'physical-volume/source/native-grid.fits',inspection:prepared.inspection,transfer:prepared.transfer,frame:prepared.frame}));ownedSoftware=[{name:'Astropy',version:prepared.inspection.astropy},{name:'cssEarth density-volume preparer',version:sha256(await readFile(new URL('../../../src/preparation/volume/prepare.ts',import.meta.url)))}];extraOutputs=prepared.files.map(path=>({path:`physical-volume/${path}`,file:resolve(staging,'physical-volume',path)}));}
      else {const result=params.operationId==='physical-grid-inspect'?await inspectPhysicalCartesianGrid(pin,context):await cropPhysicalCartesianGrid(pin,context,params.crop,resolve(staging,'physical-grid.fits'));name='physical-grid.json';content=Buffer.from(json(result));ownedSoftware=[{name:'Astropy',version:result.astropy}];if(params.operationId==='physical-grid-crop')extraOutputs=[{path:'physical-grid.fits',file:resolve(staging,'physical-grid.fits')}];}
    }
    else if(params.operationId==='spherical-grid-inspect'||params.operationId==='spherical-grid-prepare-volume'){
      const member=loaded.descriptor.members.find(item=>item.id===selected.location.memberId)!,context=contextFromSphericalGridDescriptor(loaded.descriptor),pin={path:selected.file,bytes:member.bytes,sha256:member.sha256};
      if(params.operationId==='spherical-grid-inspect'){const result=await inspectPhysicalSphericalGrid(pin,context);name='spherical-grid.json';content=Buffer.from(json(result));ownedSoftware=[{name:'Astropy',version:result.astropy},{name:'SciPy',version:result.scipy}];}
      else {const prepared=await preparePhysicalSphericalVolume({id:`${loaded.descriptor.dataset.id}-volume`,pin,context,size:params.size,transfer:params.transfer,...(params.displayWeight===undefined?{}:{displayWeight:params.displayWeight}),...(params.displayFill===undefined?{}:{displayFill:params.displayFill}),destination:resolve(staging,'physical-volume')});name='physical-grid-volume.json';content=Buffer.from(json({schema:'cssearth-physical-grid-volume@1',object:'physical-volume/object.json',prepared:'physical-volume/prepared/volume.json',native:'physical-volume/source/cartesian-grid.fits',inspection:prepared.inspection,resampling:prepared.resampling,transfer:prepared.transfer,...(prepared.displayWeight===undefined?{}:{displayWeight:prepared.displayWeight}),...(prepared.displayFill===undefined?{}:{displayFill:prepared.displayFill}),frame:prepared.frame}));ownedSoftware=[{name:'Astropy',version:prepared.inspection.astropy},{name:'SciPy',version:prepared.inspection.scipy},{name:'cssEarth density-volume preparer',version:sha256(await readFile(new URL('../../../src/preparation/volume/prepare.ts',import.meta.url)))}];extraOutputs=prepared.files.map(path=>({path:`physical-volume/${path}`,file:resolve(staging,'physical-volume',path)}));}
    }
    else throw new TypeError(`No custom executor for ${params.operationId}.`);
    const output=resolve(staging,name);if(params.operationId!=='radar-export')await writeFile(output,content,{flag:'wx'});
    const descriptorPin={bytes:loaded.bytes.length,sha256:sha256(loaded.bytes)},inputs:ProductInput[]=[{role:'product descriptor',identity:loaded.file,...descriptorPin},...loaded.descriptor.members.map(member=>({role:`descriptor ${member.role}: ${member.id}`,identity:loaded.files.get(member.id)!,bytes:member.bytes,sha256:member.sha256}))];
    const implementation=await familyImplementation(operation),recordPath=resolve(staging,'output.product.json');
    await writeProductRecord(recordPath,{telescope:'cssEarth family operation',stage:FAMILY_OPERATION_STAGE,inputs,parameters:{dataset:loaded.descriptor.dataset.id,...(loaded.descriptor.dataset.target?{target:loaded.descriptor.dataset.target}:{}),operationId:params.operationId,handlerId:operation.handlerId,componentIds:[operation.componentId],arguments:params},software:[implementation.software,...ownedSoftware],toolchainDigest:implementation.toolchainDigest},[{path:name,file:output},...extraOutputs]);
    await rename(staging,destination);const finalRecord=resolve(destination,'output.product.json');await verifiedProduct(finalRecord);return{directory:destination,product:resolve(destination,name),record:finalRecord,operation};
  }catch(error){await rm(staging,{recursive:true,force:true});throw error;}
}

const PREVIEW_OPERATIONS=new Set<FamilyOperationParameters['operationId']>(['spectrum-preview','sed-preview','time-series-preview','table-scatter-preview','table-histogram-preview','astrometry-track-preview','count-image-preview','energy-histogram-preview','light-curve-preview','radar-preview']);
async function previewOutput(loaded:Awaited<ReturnType<typeof loadDescriptor>>,operation:FamilyOperation,params:FamilyOperationParameters,outputDirectory:string):Promise<FamilyOperationResult>{
  const destination=resolve(outputDirectory),staging=`${destination}.${randomUUID()}.partial`;await absent(destination);await mkdir(dirname(destination),{recursive:true});await mkdir(staging);
  try{
    const selected=componentMember(loaded.descriptor,loaded.files,operation),bytes=await readFile(selected.file),title=`${loaded.descriptor.dataset.target??loaded.descriptor.dataset.id} · ${selected.component.name}`;let rendered:{readonly astropy:string;readonly matplotlib:string;readonly files:readonly string[]};
    if(params.operationId==='spectrum-preview')rendered=await previewSpectrum(staging,title,spectrumSamples(bytes),selected.component.axes[0]?.unit??'Wavelength',selected.component.quantity.unit??'Value');
    else if(params.operationId==='sed-preview')rendered=await previewSed(staging,title,photometryPoints(bytes),selected.component.axes[0]?.unit??'Effective wavelength',selected.component.quantity.unit??'Photometric value');
    else if(params.operationId==='time-series-preview')rendered=await previewTimeSeries(staging,title,timeSamples(bytes),selected.component.axes[0]?.unit??'Time',selected.component.quantity.unit??'Value');
    else if(params.operationId==='astrometry-track-preview')rendered=await previewAstrometryTrack(staging,title,astrometryRows(bytes));
    else if(params.operationId==='radar-preview')rendered=await previewDelayDoppler(staging,title,inspectDelayDopplerFits(bytes));
    else if(params.operationId==='table-scatter-preview'||params.operationId==='table-histogram-preview'){
      const extension=selected.location.hdu??selected.location.structure;if(extension===undefined)throw new TypeError('Table preview requires an HDU or structure locator.');
      if(params.operationId==='table-scatter-preview'){const rows=readFitsTableRows(bytes,extension,params.columns);rendered=await previewTableScatter(staging,title,rows,params.columns[0],params.columns[1]);}
      else {const rows=readFitsTableRows(bytes,extension,[params.histogram.column]);rendered=await previewTableHistogram(staging,title,rows,params.histogram.column,params.histogram.edges);}
    }else{
      const events=inspectChandraEvents(bytes);
      rendered=params.operationId==='count-image-preview'?await previewCountImage(staging,title,nativeCountImage(events,params.image)):params.operationId==='energy-histogram-preview'?await previewEnergyHistogram(staging,title,energyHistogram(events,params.histogram)):params.operationId==='light-curve-preview'?await previewLightCurve(staging,title,gtiLightCurve(events,params.lightCurve)):(()=>{throw new TypeError(`No preview executor for ${(params as any).operationId}.`);})();
    }
    const outputs=rendered.files.map(path=>({path,file:resolve(staging,path)})),inputs:ProductInput[]=[{role:'product descriptor',identity:loaded.file,bytes:loaded.bytes.length,sha256:sha256(loaded.bytes)},...loaded.descriptor.members.map(member=>({role:`descriptor ${member.role}: ${member.id}`,identity:loaded.files.get(member.id)!,bytes:member.bytes,sha256:member.sha256}))],implementation=await familyImplementation(operation);
    await writeProductRecord(resolve(staging,'output.product.json'),{telescope:'cssEarth family operation',stage:FAMILY_OPERATION_STAGE,inputs,parameters:{dataset:loaded.descriptor.dataset.id,...(loaded.descriptor.dataset.target?{target:loaded.descriptor.dataset.target}:{}),operationId:params.operationId,handlerId:operation.handlerId,componentIds:[operation.componentId],arguments:params},software:[implementation.software,{name:'Astropy',version:rendered.astropy},{name:'Matplotlib',version:rendered.matplotlib}],toolchainDigest:implementation.toolchainDigest},outputs);
    await rename(staging,destination);const record=resolve(destination,'output.product.json'),reopened=await verifiedProduct(record);return{directory:destination,product:resolve(destination,reopened.record.outputs[0]!.path),record,operation};
  }catch(error){await rm(staging,{recursive:true,force:true});throw error;}
}

async function calibrationBundleOutput(loaded:Awaited<ReturnType<typeof loadDescriptor>>,operation:FamilyOperation,outputDirectory:string):Promise<FamilyOperationResult>{
  const destination=resolve(outputDirectory),staging=`${destination}.${randomUUID()}.partial`;await absent(destination);await mkdir(dirname(destination),{recursive:true});await mkdir(staging);
  try{
    const outputs:{path:string;file:string}[]=[],manifest:{id:string;path:string;bytes:number;sha256:string;role:string}[]=[];
    for(const [index,member] of loaded.descriptor.members.entries()){const path=`members/${String(index+1).padStart(4,'0')}-${member.id}-${basename(member.path)}`,file=resolve(staging,path);await mkdir(dirname(file),{recursive:true});await copyFile(loaded.files.get(member.id)!,file,constants.COPYFILE_EXCL);outputs.push({path,file});manifest.push({id:member.id,path,bytes:member.bytes,sha256:member.sha256,role:member.role});}
    const manifestPath='calibration-bundle.json',manifestFile=resolve(staging,manifestPath);await writeFile(manifestFile,json({schema:'cssearth-f17-calibration-export@1',dataset:loaded.descriptor.dataset.id,members:manifest}));outputs.push({path:manifestPath,file:manifestFile});
    const inputs:ProductInput[]=[{role:'product descriptor',identity:loaded.file,bytes:loaded.bytes.length,sha256:sha256(loaded.bytes)},...loaded.descriptor.members.map(member=>({role:`descriptor ${member.role}: ${member.id}`,identity:loaded.files.get(member.id)!,bytes:member.bytes,sha256:member.sha256}))],implementation=await familyImplementation(operation);
    await writeProductRecord(resolve(staging,'output.product.json'),{telescope:'cssEarth family operation',stage:FAMILY_OPERATION_STAGE,inputs,parameters:{dataset:loaded.descriptor.dataset.id,...(loaded.descriptor.dataset.target?{target:loaded.descriptor.dataset.target}:{}),operationId:'export-bundle',handlerId:operation.handlerId,componentIds:[operation.componentId]},software:[implementation.software],toolchainDigest:implementation.toolchainDigest},outputs);
    await rename(staging,destination);const record=resolve(destination,'output.product.json'),reopened=await verifiedProduct(record);return{directory:destination,product:resolve(destination,reopened.record.outputs.at(-1)!.path),record,operation};
  }catch(error){await rm(staging,{recursive:true,force:true});throw error;}
}

async function compoundOutput(loaded:Awaited<ReturnType<typeof loadDescriptor>>,operation:FamilyOperation,params:Extract<FamilyOperationParameters,{operationId:'enumerate-members'|'export-selected'|'export-whole'}>,outputDirectory:string):Promise<FamilyOperationResult>{
  const destination=resolve(outputDirectory),staging=`${destination}.${randomUUID()}.partial`;await absent(destination);await mkdir(dirname(destination),{recursive:true});await mkdir(staging);
  try{
    const selected=params.operationId==='export-whole'?loaded.descriptor.members.map(member=>member.id):params.operationId==='export-selected'?[...params.memberIds]:[];if(new Set(selected).size!==selected.length)throw new TypeError('Selected compound member ids must be unique.');const known=new Set(loaded.descriptor.members.map(member=>member.id));for(const id of selected)if(!known.has(id))throw new TypeError(`Unknown compound member ${id}.`);
    for(const dependency of loaded.descriptor.dependencies){const overlap=dependency.memberIds.some(id=>selected.includes(id));if(overlap&&!dependency.memberIds.every(id=>selected.includes(id)))throw new TypeError(`Selected members do not close dependency ${dependency.id}.`);}
    const outputs:{path:string;file:string}[]=[];
    if(params.operationId==='enumerate-members'){const path='members.json',file=resolve(staging,path);await writeFile(file,json({dataset:loaded.descriptor.dataset.id,members:loaded.descriptor.members,dependencies:loaded.descriptor.dependencies}));outputs.push({path,file});}
    else for(const [index,id] of selected.entries()){const member=loaded.descriptor.members.find(item=>item.id===id)!,path=`members/${String(index+1).padStart(4,'0')}-${id}`,file=resolve(staging,path);await mkdir(dirname(file),{recursive:true});await copyFile(loaded.files.get(id)!,file,constants.COPYFILE_EXCL);outputs.push({path,file});}
    const inputs:ProductInput[]=[{role:'product descriptor',identity:loaded.file,bytes:loaded.bytes.length,sha256:sha256(loaded.bytes)},...loaded.descriptor.members.map(member=>({role:`descriptor ${member.role}: ${member.id}`,identity:loaded.files.get(member.id)!,bytes:member.bytes,sha256:member.sha256}))],implementation=await familyImplementation(operation);
    await writeProductRecord(resolve(staging,'output.product.json'),{telescope:'cssEarth family operation',stage:FAMILY_OPERATION_STAGE,inputs,parameters:{dataset:loaded.descriptor.dataset.id,...(loaded.descriptor.dataset.target?{target:loaded.descriptor.dataset.target}:{}),operationId:params.operationId,handlerId:operation.handlerId,componentIds:[operation.componentId],arguments:params},software:[implementation.software],toolchainDigest:implementation.toolchainDigest},outputs);
    await rename(staging,destination);const record=resolve(destination,'output.product.json');const reopened=await verifiedProduct(record);return{directory:destination,product:resolve(destination,reopened.record.outputs[0]!.path),record,operation};
  }catch(error){await rm(staging,{recursive:true,force:true});throw error;}
}

async function polarimetryOutput(loaded:Awaited<ReturnType<typeof loadDescriptor>>,operation:FamilyOperation,operationId:'polarimetry-inspect'|'polarimetry-export',outputDirectory:string):Promise<FamilyOperationResult>{
  const destination=resolve(outputDirectory),staging=`${destination}.${randomUUID()}.partial`;await absent(destination);await mkdir(dirname(destination),{recursive:true});await mkdir(staging);
  try{
    const intensityComponent=loaded.descriptor.components.find(component=>component.id==='intensity'),dolpComponent=loaded.descriptor.components.find(component=>component.id==='degree-linear-polarization'),intensityId=intensityComponent?.locations[0]?.memberId,dolpId=dolpComponent?.locations[0]?.memberId;
    if(!intensityId||!dolpId||intensityId===dolpId)throw new TypeError('Polarimetry requires distinct intensity and DOLP members.');const intensityMember=loaded.descriptor.members.find(member=>member.id===intensityId)!,dolpMember=loaded.descriptor.members.find(member=>member.id===dolpId)!,intensityFile=loaded.files.get(intensityId)!,dolpFile=loaded.files.get(dolpId)!,intensity=await readFile(intensityFile),dolp=await readFile(dolpFile),inspection=inspectIntensityDolp(intensity,dolp),outputs:{path:string;file:string}[]=[];
    if(operationId==='polarimetry-inspect'){const path='polarimetry.json',file=resolve(staging,path);await writeFile(file,json({schema:'cssearth-f13-polarimetry-inspection@1',inspection,refusal:'DOLP is not a Stokes Q/U/V component and does not establish a polarization angle.'}));outputs.push({path,file});}
    else {for(const [path,file]of[['intensity.fits',intensityFile],['dolp.fits',dolpFile]]as const){const target=resolve(staging,path);await copyFile(file,target,constants.COPYFILE_EXCL);outputs.push({path,file:target});}const previewPath='dolp-preview.pgm',preview=resolve(staging,previewPath);await writeFile(preview,dolpPreview(dolp),{flag:'wx'});outputs.push({path:previewPath,file:preview});const receiptPath='polarimetry.json',receipt=resolve(staging,receiptPath);await writeFile(receipt,json({schema:'cssearth-f13-polarimetry-export@1',members:[intensityMember,dolpMember],inspection,refusal:'DOLP is retained as degree of linear polarization; no Stokes basis or angle is inferred.'}));outputs.push({path:receiptPath,file:receipt});}
    const inputs:ProductInput[]=[{role:'product descriptor',identity:loaded.file,bytes:loaded.bytes.length,sha256:sha256(loaded.bytes)},...loaded.descriptor.members.map(member=>({role:`descriptor ${member.role}: ${member.id}`,identity:loaded.files.get(member.id)!,bytes:member.bytes,sha256:member.sha256}))],implementation=await familyImplementation(operation),componentIds=[intensityComponent.id,dolpComponent.id];
    await writeProductRecord(resolve(staging,'output.product.json'),{telescope:'cssEarth family operation',stage:FAMILY_OPERATION_STAGE,inputs,parameters:{dataset:loaded.descriptor.dataset.id,...(loaded.descriptor.dataset.target?{target:loaded.descriptor.dataset.target}:{}),operationId,handlerId:operation.handlerId,componentIds,arguments:{operationId}},software:[implementation.software,{name:'cssEarth FITS image owner',version:sha256(await readFile(new URL('../fits.mts',import.meta.url)))}],toolchainDigest:implementation.toolchainDigest},outputs);
    await rename(staging,destination);const record=resolve(destination,'output.product.json'),reopened=await verifiedProduct(record);return{directory:destination,product:resolve(destination,reopened.record.outputs[0]!.path),record,operation};
  }catch(error){await rm(staging,{recursive:true,force:true});throw error;}
}

/** Execute only a compile-time allowlisted owner. The descriptor and every member are re-pinned before dispatch. */
export async function executeFamilyOperation(descriptorPath:string,rawParameters:FamilyOperationParameters,outputDirectory:string):Promise<FamilyOperationResult>{
  const params=parameters(rawParameters),loaded=await loadDescriptor(descriptorPath),operation=executableOperation(loaded.descriptor,params.operationId,rawParameters.componentId);
  if(PREVIEW_OPERATIONS.has(params.operationId))return previewOutput(loaded,operation,params,outputDirectory);
  if(params.operationId==='export-bundle')return calibrationBundleOutput(loaded,operation,outputDirectory);
  if(params.operationId==='enumerate-members'||params.operationId==='export-selected'||params.operationId==='export-whole')return compoundOutput(loaded,operation,params,outputDirectory);
  if(params.operationId==='polarimetry-inspect'||params.operationId==='polarimetry-export')return polarimetryOutput(loaded,operation,params.operationId,outputDirectory);
  if(params.operationId==='spatial-export-points'||params.operationId==='spatial-export-volume'||params.operationId==='spatial-export-volume-lens-bank'){
    const selected=componentMember(loaded.descriptor,loaded.files,operation),kind=params.operationId==='spatial-export-points'?'points':params.operationId==='spatial-export-volume'?'volume':'volume-lens-bank';await absent(resolve(outputDirectory));const result=await exportSpatialObject(selected.file,kind,outputDirectory);await verifiedProduct(result.receipt);return{directory:result.directory,product:result.object,record:result.receipt,operation};
  }
  return customOutput(loaded,operation,params,outputDirectory);
}

/** Operation view used by the public execution seam; advertised metadata without an executor is explicit. */
export function executableFamilyOperations(value:unknown):readonly FamilyOperation[]{const descriptor=parseProductDescriptor(value);return operationsForDescriptor(descriptor).map(operation=>ALLOWED.has(operation.id as FamilyOperationParameters['operationId'])?operation:{...operation,available:false,reason:'No static descriptor-backed public executor is registered for this operation.'});}
export async function verifiedExecutableFamilyOperations(path:string):Promise<readonly FamilyOperation[]>{const loaded=await loadDescriptor(path);return executableFamilyOperations(loaded.descriptor);}
