import assert from'node:assert/strict';
import{test}from'node:test';
import{copyFile,mkdtemp,readFile,rm,writeFile}from'node:fs/promises';
import{tmpdir}from'node:os';
import{resolve}from'node:path';
import{readProductRecord}from'../product-record.mts';
import{member}from'./families/common.mts';
import{describeFitsTable}from'./families/f08-table.mts';
import{describeStandaloneSpectrum}from'./families/f03-spectrum.mts';
import{describePhotometry}from'./families/f05-photometry.mts';
import{describeTimeSeries}from'./families/f06-time-series.mts';
import{describeWindRad1,WIND_RAD1_FIXTURE}from'./families/f07-dynamic-spectrum.mts';
import{describeAstrometry}from'./families/f09-astrometry.mts';
import{describeCompound}from'./families/f18-compound.mts';
import{readTessLightCurve}from'../eclipse-map/transit-limb-darkening.mts';
import{describeDelayDoppler}from'./families/f15-radar.mts';
import{describeOifits}from'./families/f12-oifits.mts';
import{describeSpatialPhysicalObject}from'./families/f16-spatial-physical.mts';
import{describeUvfitsVisibility}from'./families/f11-measurement-set.mts';
import{executeFamilyOperation,executableFamilyOperations}from'./family-operation.mts';
import{listArtifactOutputs}from'./artifact-outputs.mts';
import{binaryTableHdu,primaryHdu}from'../interferometry/fits-table.mts';
const root=resolve(import.meta.dirname,'../../..');
const temporary=async()=>mkdtemp(resolve(tmpdir(),'family-operation-'));
async function save(root:string,value:unknown){const path=resolve(root,'descriptor.json');await writeFile(path,`${JSON.stringify(value,null,2)}\n`);return path;}

test('F08 dispatch rechecks pins, emits typed data and reopens its product record',async()=>{const work=await temporary();try{
  const source=resolve(root,'tests/fixtures/fits/binary-table-columns.fits'),file=resolve(work,'table.fits');await copyFile(source,file);const bytes=await readFile(file),descriptor=describeFitsTable({id:'typed-table',member:member('fits','table.fits','science',bytes,'application/fits'),bytes,extension:'OI_TEST',producingRecord:'independent Astropy oracle'}),path=await save(work,descriptor);
  const advertised=await listArtifactOutputs(path);assert.ok(advertised.familyOperations?.some(operation=>operation.id==='table-export'));
  const result=await executeFamilyOperation(path,{operationId:'table-export',columns:['TARGET_ID','STA_INDEX']},resolve(work,'result'));assert.match(await readFile(result.product,'utf8'),/^TARGET_ID,STA_INDEX/mu);const record=await readProductRecord(result.record);assert.equal(record?.stage,'telescope-family-operation');assert.deepEqual(record?.parameters.componentIds,[descriptor.components[0]!.id]);assert.ok(record?.software.some(item=>item.name.includes('f08-table')));assert.equal(typeof record?.toolchainDigest,'string');const reopened=await listArtifactOutputs(result.record);assert.equal(reopened.terminal,true);assert.equal(reopened.artifact,'telescope-family-operation');
  
}finally{await rm(work,{recursive:true,force:true});}});

test('multi-component operations require the caller to choose the component',async()=>{const work=await temporary();try{const source=resolve(root,'tests/fixtures/fits/binary-table-columns.fits'),file=resolve(work,'table.fits');await copyFile(source,file);const bytes=await readFile(file),base=describeFitsTable({id:'typed-table',member:member('fits','table.fits','science',bytes,'application/fits'),bytes,extension:'OI_TEST',producingRecord:'independent Astropy oracle'}),second={...base.components[0]!,id:'second-table'},descriptor={...base,components:[base.components[0]!,second]},path=await save(work,descriptor);await assert.rejects(executeFamilyOperation(path,{operationId:'table-export',columns:['TARGET_ID']},resolve(work,'ambiguous')),/ambiguous/u);const result=await executeFamilyOperation(path,{operationId:'table-export',componentId:second.id,columns:['TARGET_ID']},resolve(work,'selected')),record=await readProductRecord(result.record);assert.deepEqual(record?.parameters.componentIds,[second.id]);}finally{await rm(work,{recursive:true,force:true});}});

test('F15 profile uses an explicit native window and validates the full declared dependency closure',async()=>{const work=await temporary();try{
  const imageSource=resolve(root,'tests/fixtures/telescope-families/geographos-radar/ge007.fit'),labelSource=resolve(root,'tests/fixtures/telescope-families/geographos-radar/ge007.lbl'),imagePath=resolve(work,'ge007.fit'),labelPath=resolve(work,'ge007.lbl');await copyFile(imageSource,imagePath);await copyFile(labelSource,labelPath);const image=await readFile(imagePath),label=await readFile(labelPath),descriptor=describeDelayDoppler({id:'ge007',image:member('image','ge007.fit','science',image),label:member('label','ge007.lbl','label',label),bytes:image,labelBytes:label,producingRecord:'PDS3 archive'}),path=await save(work,descriptor);
  const result=await executeFamilyOperation(path,{operationId:'radar-profile',window:[0,2,0,2]},resolve(work,'profile')),profile=JSON.parse(await readFile(result.product,'utf8'));assert.deepEqual(profile.window,{delay:[0,2],doppler:[0,2]});assert.equal(profile.delay.length,2);
  await writeFile(labelPath,'changed');await assert.rejects(executeFamilyOperation(path,{operationId:'radar-inspect'},resolve(work,'bad')),/label/u);
}finally{await rm(work,{recursive:true,force:true});}});

test('F12 diagnostics and F16 inspection dispatch through static existing owners',async()=>{const work=await temporary();try{
  const wavelengths=[2.28e-6,2.29e-6],oi=Buffer.concat([primaryHdu(),binaryTableHdu('OI_WAVELENGTH',[{name:'EFF_WAVE',form:'D'},{name:'EFF_BAND',form:'D'}],wavelengths.map(w=>[w,1e-8]),[['INSNAME','TEST']]),binaryTableHdu('OI_VIS',[{name:'VISAMP',form:'2D'},{name:'VISAMPERR',form:'2D'},{name:'VISPHI',form:'2D'},{name:'VISPHIERR',form:'2D'},{name:'UCOORD',form:'D'},{name:'VCOORD',form:'D'},{name:'FLAG',form:'2L'}],[[[.8,.7],[.1,.1],[1,2],[.5,.5],20,5,[false,false]]],[['INSNAME','TEST'],['AMPTYP','absolute'],['PHITYP','absolute']])]),oiPath=resolve(work,'observation.fits');await writeFile(oiPath,oi);const oiDescriptor=describeOifits({id:'oifits-fixture',member:member('oi','observation.fits','science',oi,'application/fits'),producingRecord:'focused OIFITS owner fixture',rows:{vis:1,vis2:0,t3:0}}),oiDescriptorPath=await save(work,oiDescriptor),diagnostics=await executeFamilyOperation(oiDescriptorPath,{operationId:'visibility-diagnostics',componentId:'vis'},resolve(work,'diagnostics')),rows=JSON.parse(await readFile(diagnostics.product,'utf8'));assert.equal(rows.vis.length,1);
  const objectPath=resolve(root,'src/objects/stellar-neighbourhood/object.json'),spatial=await describeSpatialPhysicalObject(objectPath),spatialPath=resolve(work,'spatial-descriptor.json');await writeFile(spatialPath,JSON.stringify(spatial));const inspected=await executeFamilyOperation(spatialPath,{operationId:'spatial-inspect'},resolve(work,'spatial')),value=JSON.parse(await readFile(inspected.product,'utf8'));assert.equal(value.kind,'points');
}finally{await rm(work,{recursive:true,force:true});}});

test('public execution view exposes only allowlisted ids and refuses mismatched operations',async()=>{const work=await temporary();try{const bytes=Buffer.from('samples'),descriptor=describeStandaloneSpectrum({id:'spectrum',member:member('samples','samples.json','science',bytes),samples:[{wavelength:1,value:2}],wavelengthUnit:'um',valueName:'flux',producingRecord:'test',calibrationBasis:[]});await writeFile(resolve(work,'samples.json'),bytes);const path=await save(work,descriptor),operation=executableFamilyOperations(descriptor)[0]!;assert.equal(operation.available,true);await assert.rejects(executeFamilyOperation(path,{operationId:'radar-inspect'},resolve(work,'wrong')),/unavailable/u);}finally{await rm(work,{recursive:true,force:true});}});

test('F03, F05 and F09 public writers reopen real pinned JSON members',async()=>{const work=await temporary();try{
  const spectrumSource=resolve(root,'src/objects/mercury/source/spectrum/mascs-global-area-weighted-mean.json'),spectrumBytes=await readFile(spectrumSource),spectrumRaw=JSON.parse(spectrumBytes.toString()),spectrumFile=resolve(work,'spectrum.json');await writeFile(spectrumFile,spectrumBytes);const spectrumSamples=spectrumRaw.wavelengthNanometers.map((wavelength:number,index:number)=>({id:String(index),segment:'visible',wavelength,value:spectrumRaw.reflectanceIOverF[index]})),spectrum=describeStandaloneSpectrum({id:'mercury-mascs',member:member('spectrum','spectrum.json','science',spectrumBytes),samples:spectrumSamples,wavelengthUnit:'nm',valueName:'reflectance',producingRecord:'pinned MASCS',calibrationBasis:[]}),spectrumPath=await save(work,spectrum),spectrumResult=await executeFamilyOperation(spectrumPath,{operationId:'spectrum-export'},resolve(work,'spectrum-out'));assert.match(await readFile(spectrumResult.product,'utf8'),/0,visible,350/u);
  const photoSource=resolve(root,'src/objects/haumea/source/photometry/disc-color.json'),photoBytes=await readFile(photoSource),photoRaw=JSON.parse(photoBytes.toString()),photoFile=resolve(work,'photometry.json');await writeFile(photoFile,photoBytes);const point={id:'geometric-albedo-v',band:photoRaw.geometricAlbedo.band,system:photoRaw.object.system,effectiveWavelength:photoRaw.effectiveWavelengths.nanometres.V,value:photoRaw.geometricAlbedo.value,uncertainty:photoRaw.geometricAlbedo.uncertainty},photo=describePhotometry({id:'haumea',member:member('photo','photometry.json','science',photoBytes),points:[point],wavelengthUnit:'nm',quantity:'geometric albedo',unit:'1',producingRecord:'pinned photometry',calibrationBasis:[]}),photoPath=resolve(work,'photo-descriptor.json');await writeFile(photoPath,JSON.stringify(photo));const photoResult=await executeFamilyOperation(photoPath,{operationId:'photometry-export'},resolve(work,'photo-out'));assert.match(await readFile(photoResult.product,'utf8'),/0\.51,0\.02/u);
  const starsSource=resolve(root,'src/objects/m1/source/stellar-field.json'),starsBytes=await readFile(starsSource),starsRaw=JSON.parse(starsBytes.toString()),starsFile=resolve(work,'stars.json');await writeFile(starsFile,starsBytes);const rows=starsRaw.stars.map((star:any)=>({id:star.sourceId,raDeg:star.raDeg,decDeg:star.decDeg,epochJulianYear:starsRaw.coordinateEpochJulianYear,pmRaCosDecMasYr:star.pmRaMasYr,pmDecMasYr:star.pmDecMasYr,parallaxMas:star.parallaxMas,parallaxErrorMas:star.parallaxErrorMas})),stars=describeAstrometry({id:'m1',member:member('stars','stars.json','science',starsBytes),rows,frame:'ICRS',epochJulianYear:2016,producingRecord:'pinned Gaia',calibrationBasis:[]}),starsPath=resolve(work,'stars-descriptor.json');await writeFile(starsPath,JSON.stringify(stars));const moved=await executeFamilyOperation(starsPath,{operationId:'astrometry-propagate',epoch:[2016,2026]},resolve(work,'stars-out'));assert.match(await readFile(moved.product,'utf8'),/2026/u);
}finally{await rm(work,{recursive:true,force:true});}});

test('F06 explicit selection and F18 whole closure write reusable pinned products',async()=>{const work=await temporary();try{
  const tessSource=resolve(root,'src/objects/hd-189733/source/photometry/tess/tess2021204101404-s0041-0000000256364928-0212-s_lc.fits'),tessBytes=await readFile(tessSource),tessFile=resolve(work,'curve.fits');await writeFile(tessFile,tessBytes);const curve=readTessLightCurve(tessBytes),samples=Array.from(curve.time,(time,index)=>({id:String(index),segment:`sector-${curve.sector}`,time,value:curve.flux[index]!,uncertainty:curve.error[index]!})),series=describeTimeSeries({id:'tess',member:member('curve','curve.fits','science',tessBytes),samples,timeUnit:'d',timeScale:'BMJD_TDB',quantity:'PDCSAP flux',producingRecord:'pinned TESS',calibrationBasis:[]}),seriesPath=await save(work,series),selected=await executeFamilyOperation(seriesPath,{operationId:'time-series-select',range:[samples[5]!.time,samples[9]!.time]},resolve(work,'series-out'));assert.equal((await readFile(selected.product,'utf8')).trim().split('\n').length,6);
  const a=Buffer.from('science bytes'),b=Buffer.from('label bytes');await writeFile(resolve(work,'a.bin'),a);await writeFile(resolve(work,'b.lbl'),b);const compound=describeCompound({id:'compound',producingRecord:'fixture',members:[member('a','a.bin','science',a),member('b','b.lbl','label',b)],groups:[{id:'complete',name:'complete',memberIds:['a','b'],requiredFor:['export-whole']}]}),compoundPath=resolve(work,'compound.json'),componentId=compound.components[0]!.id;await writeFile(compoundPath,JSON.stringify(compound));await assert.rejects(executeFamilyOperation(compoundPath,{operationId:'export-selected',componentId,memberIds:['a']},resolve(work,'partial')),/close dependency/u);const whole=await executeFamilyOperation(compoundPath,{operationId:'export-whole',componentId},resolve(work,'whole'));const record=await readProductRecord(whole.record);assert.equal(record?.outputs.length,2);assert.deepEqual(await readFile(resolve(whole.directory,record!.outputs[1]!.path)),b);
}finally{await rm(work,{recursive:true,force:true});}});

test('F07 public selection runs the pinned cdflib owner and writes native coordinates',async()=>{const work=await temporary();try{const source=resolve(root,'tests/fixtures/telescope-families/wind-rad1/wi_l2_wav_rad1_20200101_v01.cdf'),file=resolve(work,'wind.cdf');await copyFile(source,file);const bytes=await readFile(file);const descriptor=describeWindRad1({id:'wind-rad1',member:member('cdf','wind.cdf','science',bytes),producingRecord:'NASA SPDF fixture',timeLength:1856,frequencyLength:256}),path=await save(work,descriptor),result=await executeFamilyOperation(path,{operationId:'dynamic-spectrum-export',selection:[0,2,0,3]},resolve(work,'selected')),csv=await readFile(result.product,'utf8');assert.match(csv,/^epoch_tt2000,frequency_hz,psd\n631108815985012754,20000,/u);assert.equal(csv.trim().split('\n').length,7);}finally{await rm(work,{recursive:true,force:true});}});

test('F11 public dispatcher delegates bounded real UVFITS work to pyuvdata and attaches its package-owned preview',async()=>{const work=await temporary();try{const source=resolve(root,'tests/fixtures/telescope-families/f11-vla-uvfits/day2_TDEM0003_10s_norx_1src_1spw.uvfits'),bytes=await readFile(source),descriptor=describeUvfitsVisibility({id:'vla-day2-tdem0003',producingRecord:'RASG datasets v0.0.5 BSD-2-Clause',member:member('uvfits',source,'science',bytes,'application/fits'),inspection:{telescope:'EVLA',target:'J1008+0730',rows:1360,channels:64,polarizations:[-1,-2,-3,-4],samples:348160,frequencyHz:{first:36304541952.42,increment:125000}}}),path=await save(work,descriptor),selection={field:'J1008+0730',timeStartJulianDate:2455312.64022,timeEndJulianDate:2455312.64024,antenna1:4,antenna2:8,rowOffset:0,rowCount:1,channelStart:0,channelCount:2,polarization:-1},result=await executeFamilyOperation(path,{operationId:'uvfits-amplitude-phase-diagnostics',selection},resolve(work,'diagnostic')),value=JSON.parse(await readFile(result.product,'utf8')),record=await readProductRecord(result.record);assert.equal(value.pyuvdata,'3.2.4');assert.equal(value.amplitudePhase.unflaggedSamples,2);assert.equal(record?.software.some(item=>item.name==='pyuvdata'&&item.version==='3.2.4'),true);const exported=await executeFamilyOperation(path,{operationId:'uvfits-visibility-export',selection},resolve(work,'export')),exportRecord=await readProductRecord(exported.record);assert.deepEqual(exportRecord?.outputs.map(item=>item.path),['visibilities.json','preview.png','preview.svg']);assert.equal((await readFile(resolve(exported.directory,'preview.png'))).subarray(1,4).toString(),'PNG');}finally{await rm(work,{recursive:true,force:true});}});

test('remaining family baseline operations execute through the public dispatcher on pinned examples',async()=>{const work=await temporary();try{
  const descriptor=(family:string)=>resolve(root,'tests/fixtures/telescope-family-examples/descriptors',`${family}.json`),run=async(family:string,parameters:any,name:string)=>{const path=descriptor(family),value=JSON.parse(await readFile(path,'utf8')),matches=executableFamilyOperations(value).filter(operation=>operation.id===parameters.operationId&&operation.available);return executeFamilyOperation(path,{...parameters,...(matches.length>1?{componentId:matches[0]!.componentId}:{})},resolve(work,name));};
  const range=await readFile((await run('F03',{operationId:'spectrum-select-range',range:[350,355]},'spectrum-range')).product,'utf8');assert.match(range,/350/u);const chart=JSON.parse(await readFile((await run('F03',{operationId:'spectrum-chart-data'},'spectrum-chart')).product,'utf8'));assert.ok(chart.length>1);const preview=await run('F03',{operationId:'spectrum-preview'},'spectrum-preview');assert.equal((await readFile(preview.product)).subarray(1,4).toString(),'PNG');
  const profile=JSON.parse(await readFile((await run('F04',{operationId:'slit-profile-table'},'slit-profile')).product,'utf8'));assert.equal(profile.length,4);const slit=JSON.parse(await readFile((await run('F04',{operationId:'slit-region-spectrum',directory:resolve(root,'tests/fixtures/telescope-families/f04-europa-stis'),frame:'od9l12010_x2d.fits',row:125},'slit-spectrum')).product,'utf8'));assert.equal(slit.row,125);assert.equal(slit.wavelengthAngstrom.length,slit.flux.length);
  const sed=JSON.parse(await readFile((await run('F05',{operationId:'sed-plot-data'},'sed')).product,'utf8'));assert.equal(sed[0].band,'V');
  const series=JSON.parse(await readFile((await run('F06',{operationId:'time-series-plot-data'},'series')).product,'utf8'));assert.ok(series.length>1000);
  const spectrum=JSON.parse(await readFile((await run('F07',{operationId:'dynamic-spectrum-spectrum',timeIndex:0},'dynamic-spectrum')).product,'utf8'));assert.equal(spectrum.frequencyHz.length,256);const time=JSON.parse(await readFile((await run('F07',{operationId:'dynamic-spectrum-time-series',frequencyIndex:0},'dynamic-time')).product,'utf8'));assert.equal(time.epochsTt2000.length,1856);
  const scatter=JSON.parse(await readFile((await run('F08',{operationId:'table-scatter-data',columns:['TIME','PDCSAP_FLUX']},'scatter')).product,'utf8'));assert.ok(scatter.length>1000);const histogram=JSON.parse(await readFile((await run('F08',{operationId:'table-histogram',histogram:{column:'PDCSAP_FLUX',edges:[0,10000,20000,30000]}},'histogram')).product,'utf8'));assert.equal(histogram.counts.length,3);
  const stars=JSON.parse(await readFile(resolve(root,'src/objects/m1/source/stellar-field.json'),'utf8')),id=String(stars.stars[0].sourceId),selected=await readFile((await run('F09',{operationId:'astrometry-select-rows',rows:[id]},'selected-star')).product,'utf8');assert.match(selected,new RegExp(id,'u'));const track=JSON.parse(await readFile((await run('F09',{operationId:'astrometry-track-data'},'track')).product,'utf8'));assert.ok(track.length>100);
  const subset=await readFile((await run('F12',{operationId:'oifits-subset',subset:{OI_VIS2:[0],OI_T3:[0]}},'oifits-subset')).product);assert.equal(subset.subarray(0,6).toString(),'SIMPLE');
  const radar=JSON.parse(await readFile((await run('F15',{operationId:'radar-coordinate-view'},'radar-coordinates')).product,'utf8'));assert.deepEqual(radar.shape,[127,64]);const spatial=JSON.parse(await readFile((await run('F16',{operationId:'spatial-select-components',components:['points']},'spatial-components')).product,'utf8'));assert.equal(spatial[0].id,'points');
  const calibration=JSON.parse(await readFile((await run('F17',{operationId:'near-msi-inspect'},'near-msi')).product,'utf8'));assert.equal(calibration.unit,'I/F');assert.ok(calibration.acceptedPixels>100000);const bundle=await run('F17',{operationId:'export-bundle'},'near-msi-bundle'),bundleRecord=await readProductRecord(bundle.record);assert.equal(bundleRecord?.outputs.length,4);
}finally{await rm(work,{recursive:true,force:true});}});
