/** Scientific output policy for planetary depth-like products. It performs no inversion or rendering. */
import type {AxisDescriptor,PlanetaryPlacementDescriptor,ProductComponent} from './product-descriptor.mts';

export type PlanetaryOutputKind='native'|'slice'|'profile'|'coverage'|'isosurface'|'interactive-html'|'body-attachment';
export interface PlanetaryOutputVerdict {readonly output:PlanetaryOutputKind;readonly available:boolean;readonly reason:string;readonly labelRequirement?:string}
const answer=(output:PlanetaryOutputKind,available:boolean,reason:string,labelRequirement?:string):PlanetaryOutputVerdict=>({output,available,reason,...(labelRequirement?{labelRequirement}:{})});
const depthAxis=(component:ProductComponent)=>component.depth&&component.depth.coordinate!=='none'?component.axes.find(axis=>axis.role===component.depth!.coordinate):undefined;
const rolePhysicalType:Record<string,AxisDescriptor['physicalType']>={'projected-x':'length','projected-y':'length','geometric-depth':'length',altitude:'length',radius:'length','body-fixed-x':'length','body-fixed-y':'length','body-fixed-z':'length','path-distance':'length',delay:'time',pressure:'pressure',longitude:'angle',latitude:'angle'};
const placementAxes=(placement:PlanetaryPlacementDescriptor)=>placement.kind==='cartesian'?[['body-fixed-x',placement.xAxisId],['body-fixed-y',placement.yAxisId],['body-fixed-z',placement.zAxisId]]:placement.kind==='spherical'?[['longitude',placement.longitudeAxisId],['latitude',placement.latitudeAxisId],['radius',placement.radiusAxisId]]:placement.kind==='projected-vertical'?[['projected-x',placement.projectedXAxisId],['projected-y',placement.projectedYAxisId],[undefined,placement.verticalAxisId]]:placement.kind==='located-profile'?[ [undefined,placement.verticalAxisId] ]:placement.symmetry==='spherical'?[['radius',placement.radialAxisId]]:[[ 'radius',placement.radialAxisId ],[undefined,placement.axialAxisId!]];
const hasPlacement=(component:ProductComponent)=>{const placement=component.placement;if(!placement)return false;return placementAxes(placement).every(([role,id])=>component.axes.some(axis=>axis.id===id&&(role===undefined||axis.role===role)));};
const inferenceLabel=(component:ProductComponent)=>component.inference?`Label as an inferred ${component.support!.class} product using ${component.inference.method}; retain its assumptions and validation.`:undefined;

/** Enforce the minimum scientific contract before an adapter can publish a planetary product. */
export function assertPlanetaryProductSemantics(component:ProductComponent):void{
  if(!component.support||!component.depth||!component.observability)throw new TypeError('Planetary products require support, depth, and observability semantics.');
  if(!component.sampling||new Set(component.sampling.axes.map(axis=>axis.axisId)).size!==component.axes.length||component.axes.some(axis=>!component.sampling!.axes.some(sample=>sample.axisId===axis.id)))throw new TypeError('Planetary products require one sampling declaration for every axis.');
  if(!component.resolution)throw new TypeError('Planetary products require an explicit resolution state; sampling cannot substitute for it.');
  if(!component.uncertainty)throw new TypeError('Planetary products require an explicit uncertainty state, including none-supplied or unknown.');
  if(!component.quantity.unit)throw new TypeError('Planetary products require an explicit quantity unit, including 1 for dimensionless quantities.');
  if(!component.frame)throw new TypeError('Planetary products require an explicit coordinate frame.');
  for(const axis of component.axes){if(!axis.unit||!axis.reference||!axis.derivation)throw new TypeError(`Planetary axis ${axis.id} requires unit, reference, and derivation evidence.`);const expected=rolePhysicalType[axis.role];if(!expected)throw new TypeError(`Planetary axis ${axis.id} has unsupported role ${axis.role}.`);if(axis.physicalType!==expected)throw new TypeError(`Planetary axis ${axis.id} role ${axis.role} requires physical type ${expected}.`);}
  if(component.support.class!=='observed-samples'&&!component.inference)throw new TypeError(`${component.support.class} requires a retained inference method.`);
  if(component.depth.coordinate==='pressure'&&component.observability.measurementOperator==='microwave-radiative-transfer'&&component.support.class==='observed-samples')throw new TypeError('Microwave observations may retain channel brightness temperatures, but a pressure-coordinate field requires an explicit retrieval or reconstruction.');
  if((component.observability.measurementOperator==='gravity-integral'||component.observability.measurementOperator==='magnetic-induction')&&component.observability.localization!=='non-unique')throw new TypeError('Gravity and magnetic integral responses must retain non-unique localization.');
  if(['geometric-depth','altitude','radius'].includes(component.depth.coordinate)&&component.depth.conversion.state==='unavailable')throw new TypeError(`${component.depth.coordinate} requires a native or derived physical-coordinate basis.`);
  if(component.placement?.kind==='symmetry'&&!component.inference)throw new TypeError('A symmetry placement requires an explicit inference method and assumptions.');
}

/** Decide outputs only from retained descriptor facts. Coordinate spacing never becomes resolution evidence here. */
export function planetaryOutputPolicy(component:ProductComponent):readonly PlanetaryOutputVerdict[]{
  try{assertPlanetaryProductSemantics(component);}catch(error){const reason=error instanceof Error?error.message:String(error);return(['native','slice','profile','coverage','isosurface','interactive-html','body-attachment'] as const).map(output=>answer(output,false,reason));}
  const depth=component.depth!,observability=component.observability!,fieldGrid=component.representation.kind==='physical-field'&&component.representation.topology==='grid',grid=fieldGrid&&component.support!.domain.kind==='full-grid'&&component.support!.unsupportedRegions.length===0,dimensions=component.axes.length,vertical=depthAxis(component),coverage=observability.coverage.memberIds.length>0;
  const native=answer('native',true,'Native members preserve the qualified quantity, coordinates, support, and evidence closure.');
  const slice=answer('slice',grid&&dimensions>=2,grid&&dimensions>=2?'A qualified fully supported grid has at least two retained semantic axes.':'Slices require a qualified full grid with no unhandled support geometry and at least two semantic axes.');
  const profile=answer('profile',vertical!==undefined&&(grid||component.support!.domain.kind==='profiles'),vertical!==undefined&&(grid||component.support!.domain.kind==='profiles')?'The requested depth-like coordinate is retained explicitly with matching support.':'Profiles require an explicit depth-like axis with fully handled grid or profile support.');
  const coverageOutput=answer('coverage',coverage,coverage?'The exact observed tracks, rays, stations, channels, trajectories, cells, or profiles remain linked.':'No exact measurement-support members are retained.');
  const surfaceLabel=['Label every surface as a threshold of the retained quantity; never as composition, density, or a geologic boundary unless that is the qualified quantity.',inferenceLabel(component)].filter(Boolean).join(' ');
  const htmlLabel=['Show unsupported regions and the native depth coordinate; cosmetic filling cannot become support.',inferenceLabel(component)].filter(Boolean).join(' ');
  const surface=answer('isosurface',grid&&dimensions===3,grid&&dimensions===3?'A three-axis scalar grid can produce quantity-threshold surfaces.':'Isosurfaces require a qualified three-axis scalar grid.',surfaceLabel);
  const html=answer('interactive-html',(grid&&dimensions>=2)||coverage,(grid&&dimensions>=2)||coverage?'A support-aware grid or exact coverage geometry has a faithful interactive view.':'Interactive output requires a qualified grid or exact coverage geometry.',htmlLabel);
  const coordinate=depth.coordinate,placementKind=component.placement?.kind,absolutePlacement=placementKind==='cartesian'||placementKind==='spherical'||placementKind==='symmetry',convertible=absolutePlacement||depth.conversion.state!=='unavailable',bodyCoordinate=absolutePlacement||['geometric-depth','altitude','radius'].includes(coordinate),localized=observability.localization!=='non-unique',labelledModel=!localized&&component.support!.class!=='observed-samples'&&component.inference!==undefined,body=grid&&hasPlacement(component)&&bodyCoordinate&&convertible&&(localized||labelledModel);
  const bodyReason=!grid?'Body attachment requires a qualified full grid with no unhandled support geometry.':!hasPlacement(component)?'Body attachment requires an explicit validated planetary placement descriptor.':!bodyCoordinate?`${coordinate} is not a body-placement coordinate.`:!convertible?'The coordinate has no qualified physical conversion.':!localized&&!labelledModel?'A non-unique integral response cannot be attached as measured localized matter.':'The coordinate, placement, conversion, support class, inference, and frame permit a labelled body attachment.';
  const bodyLabel=body?[inferenceLabel(component),'Retain datum, conversion method, parameters, uncertainty, frame, and unsupported mask.'].filter(Boolean).join(' '):undefined;
  return[native,slice,profile,coverageOutput,surface,html,answer('body-attachment',body,bodyReason,bodyLabel)];
}
export function requirePlanetaryOutput(component:ProductComponent,output:PlanetaryOutputKind):PlanetaryOutputVerdict{const found=planetaryOutputPolicy(component).find(value=>value.output===output)!;if(!found.available)throw new TypeError(`${output} refused: ${found.reason}`);return found;}
