/** Versioned semantic description of pinned observational bytes. Data remain in members; this file only describes them. */
import { spawnSync } from 'node:child_process';
import { requireArray, requireFiniteNumber, requireRecord, requireString } from '../../source-values.mts';
import { astroqueryToolchainSync } from '../astronomy-packages/toolchain.mts';

export const PRODUCT_DESCRIPTOR_SCHEMA='cssearth-telescope-product-descriptor@1' as const;
export const FAMILY_IDS=['F01','F02','F03','F04','F05','F06','F07','F08','F09','F10','F11','F12','F13','F14','F15','F16','F17','F18'] as const;
export const PLANETARY_AXIS_ROLES=['projected-x','projected-y','delay','geometric-depth','altitude','pressure','longitude','latitude','radius','body-fixed-x','body-fixed-y','body-fixed-z','path-distance'] as const;
export type FamilyId=typeof FAMILY_IDS[number];
export type PlanetaryAxisRole=typeof PLANETARY_AXIS_ROLES[number];
export type CalibrationState='raw'|'archive-calibrated'|'locally-reproduced'|'reconstructed'|'model-derived'|'unknown';
export type MemberRole='science'|'support'|'label'|'coordinates'|'quality'|'uncertainty'|'calibration'|'response'|'provenance';

export interface DescriptorMember {readonly id:string;readonly path:string;readonly role:MemberRole;readonly bytes:number;readonly sha256:string;readonly mediaType?:string}
export type CoordinateDescriptor=
  |{readonly kind:'index'}
  |{readonly kind:'linear';readonly referenceValue:number;readonly referenceIndex:number;readonly increment:number}
  |{readonly kind:'native';readonly convention:string;readonly coupledGroup?:string;readonly binBounds:boolean}
  |{readonly kind:'lookup';readonly memberId:string;readonly locator:string;readonly binBounds:boolean};
export interface AxisDerivationDescriptor {readonly state:'observed'|'archive-derived'|'reconstruction-derived';readonly assumptions:readonly string[]}
export type AxisPhysicalType='length'|'time'|'pressure'|'angle';
export interface AxisDescriptor {readonly id:string;readonly index:number;readonly length:number;readonly role:string;readonly physicalType?:AxisPhysicalType;readonly unit?:string;readonly coordinates:CoordinateDescriptor;readonly frame?:string;readonly reference?:string;readonly derivation?:AxisDerivationDescriptor}
export interface ColumnDescriptor {readonly id:string;readonly name:string;readonly role:string;readonly datatype:string;readonly unit?:string;readonly nullable:boolean;readonly variableLength:boolean;readonly shape?:readonly number[]}
export type RepresentationDescriptor=
  |{readonly kind:'array';readonly shape:readonly number[];readonly storageOrder:'row-major'|'column-major'|'native'}
  |{readonly kind:'table'|'events'|'complex-samples';readonly rows:number|null}
  |{readonly kind:'physical-field';readonly topology:'points'|'grid'|'mesh'|'other';readonly samples:number|null}
  |{readonly kind:'collection';readonly componentIds:readonly string[]};
export interface ComponentLocator {readonly memberId:string;readonly path?:string;readonly hdu?:number;readonly structure?:string}
export interface QuantityDescriptor {readonly name:string;readonly semantics:string;readonly unit?:string}
export interface CalibrationDescriptor {readonly state:CalibrationState;readonly basis:readonly string[]}
export interface UncertaintyDescriptor {readonly form:'standard-deviation'|'variance'|'inverse-variance'|'covariance'|'limits'|'unknown'|'none-supplied';readonly componentId?:string;readonly columnId?:string;readonly basis:string}
export interface FlagDescriptor {readonly id:string;readonly meaning:string;readonly componentId?:string;readonly columnId?:string;readonly usableWhen?:string}
export interface TimeDescriptor {readonly scale:string;readonly format:string;readonly referenceEpoch?:string;readonly observer?:string;readonly exposure?:string}
export interface FrameDescriptor {readonly kind:string;readonly name:string;readonly referencePosition?:string;readonly epoch?:string}
export type SupportClass='observed-samples'|'published-reconstruction'|'model-conditioned'|'model-ensemble';
export interface SupportDomainDescriptor {readonly kind:'full-grid'|'mask'|'tracks'|'rays'|'profiles'|'shells'|'regions';readonly description:string;readonly memberIds:readonly string[]}
export interface SupportDescriptor {readonly class:SupportClass;readonly domain:SupportDomainDescriptor;readonly unsupportedRegions:readonly {readonly kind:'mask'|'geometric'|'unobserved';readonly description:string;readonly memberId?:string}[]}
export interface DepthDescriptor {readonly coordinate:'delay'|'geometric-depth'|'pressure'|'altitude'|'radius'|'none';readonly positiveDirection:'up'|'down'|'outward';readonly datum:string;readonly conversion:{readonly state:'native'|'derived'|'unavailable';readonly method?:string;readonly parameters:readonly {readonly name:string;readonly value:string;readonly unit?:string;readonly source?:string}[];readonly uncertainty:string}}
export interface ObservabilityDescriptor {readonly measurementOperator:'radar-propagation'|'microwave-radiative-transfer'|'seismic-wave-propagation'|'occultation-line-integral'|'in-situ-trajectory'|'gravity-integral'|'magnetic-induction';readonly coverage:{readonly kind:'tracks'|'rays'|'stations'|'angles'|'channels'|'trajectories'|'grid-cells'|'profiles';readonly description:string;readonly memberIds:readonly string[]};readonly localization:'direct'|'inversion-dependent'|'non-unique'}
export interface SamplingDescriptor {readonly axes:readonly {readonly axisId:string;readonly kind:'regular'|'irregular'|'categorical';readonly interval?:number;readonly unit?:string;readonly memberId?:string;readonly basis:string}[]}
export interface ResolutionDescriptor {readonly state:'measured'|'estimated'|'model-kernel'|'unknown';readonly elements:readonly {readonly axisId?:string;readonly value?:number;readonly range?:readonly [number,number];readonly unit?:string;readonly description:string}[];readonly basis:string;readonly memberIds:readonly string[]}
export interface InferenceDescriptor {readonly kind:'archive-published'|'source-backed-implementation'|'published-result';readonly method:string;readonly implementation?:{readonly identity:string;readonly version:string};readonly assumptions:readonly string[];readonly validation:string;readonly memberIds:readonly string[]}
/** Explicit coordinate-to-body placement. Axis ids avoid inferring geometry from order. */
export type PlanetaryPlacementDescriptor=
  |{readonly kind:'cartesian';readonly xAxisId:string;readonly yAxisId:string;readonly zAxisId:string;readonly basis:string}
  |{readonly kind:'spherical';readonly longitudeAxisId:string;readonly latitudeAxisId:string;readonly radiusAxisId:string;readonly basis:string}
  |{readonly kind:'projected-vertical';readonly projectedXAxisId:string;readonly projectedYAxisId:string;readonly verticalAxisId:string;readonly projection:string;readonly verticalDatum:string;readonly basis:string}
  |{readonly kind:'located-profile';readonly verticalAxisId:string;readonly anchor:{readonly kind:'body-fixed-cartesian';readonly x:number;readonly y:number;readonly z:number;readonly unit:string}|{readonly kind:'longitude-latitude';readonly longitude:number;readonly latitude:number;readonly unit:string};readonly basis:string}
  |{readonly kind:'symmetry';readonly symmetry:'spherical'|'axial';readonly radialAxisId:string;readonly axialAxisId?:string;readonly basis:string};
export interface ProductComponent {
  readonly id:string;readonly name:string;readonly families:readonly FamilyId[];readonly locations:readonly ComponentLocator[];
  readonly representation:RepresentationDescriptor;readonly axes:readonly AxisDescriptor[];readonly columns:readonly ColumnDescriptor[];
  readonly quantity:QuantityDescriptor;readonly calibration:CalibrationDescriptor;readonly uncertainty?:UncertaintyDescriptor;
  readonly flags:readonly FlagDescriptor[];readonly time?:TimeDescriptor;readonly frame?:FrameDescriptor;readonly support?:SupportDescriptor;readonly depth?:DepthDescriptor;readonly placement?:PlanetaryPlacementDescriptor;readonly observability?:ObservabilityDescriptor;readonly sampling?:SamplingDescriptor;readonly resolution?:ResolutionDescriptor;readonly inference?:InferenceDescriptor;readonly dependencyIds:readonly string[];
}
export interface ProductDependency {readonly id:string;readonly role:string;readonly memberIds:readonly string[];readonly componentIds:readonly string[];readonly requiredFor:readonly string[];readonly evidence?:string}
export interface DescriptorIssue {readonly scope:'dataset'|'member'|'component'|'axis'|'column'|'dependency';readonly identity:string;readonly state:'missing'|'conflicting'|'unsupported'|'unknown';readonly reason:string}
export interface ProductDescriptor {
  readonly schema:typeof PRODUCT_DESCRIPTOR_SCHEMA;
  readonly dataset:{readonly id:string;readonly target?:string;readonly acquisition:{readonly kind:'archive'|'local-import'|'repository';readonly identity:string};readonly producingRecord:string;readonly sourceClassifications:readonly {readonly term:string;readonly vocabulary:string;readonly version:string;readonly status:'source'|'mapped'|'preliminary'}[];readonly families:readonly FamilyId[];readonly profiles:readonly {readonly handlerId:string;readonly profileId:string}[]};
  readonly members:readonly DescriptorMember[];readonly components:readonly ProductComponent[];readonly dependencies:readonly ProductDependency[];readonly issues:readonly DescriptorIssue[];
}

const HEX=/^[a-f0-9]{64}$/u,ID=/^[A-Za-z0-9][A-Za-z0-9._:@-]*$/u;
const exact=(value:Record<string,unknown>,keys:readonly string[],label:string)=>{for(const key of Object.keys(value))if(!keys.includes(key))throw new TypeError(`${label} has unsupported field ${key}.`);};
const id=(value:unknown,label:string)=>{const text=requireString(value,label);if(!ID.test(text))throw new TypeError(`${label} must be a stable identifier.`);return text;};
const list=(value:unknown,label:string)=>requireArray(value,label).map((entry,index)=>requireString(entry,`${label} ${index}`));
const finite=(value:unknown,label:string)=>requireFiniteNumber(value,label);
const whole=(value:unknown,label:string,minimum=0)=>{const number=finite(value,label);if(!Number.isSafeInteger(number)||number<minimum)throw new TypeError(`${label} must be a whole number at least ${minimum}.`);return number;};
const family=(value:unknown,label:string)=>{const name=requireString(value,label);if(!(FAMILY_IDS as readonly string[]).includes(name))throw new TypeError(`${label} is not an observational family.`);return name as FamilyId;};
const unique=<T,>(values:readonly T[],label:string)=>{if(new Set(values).size!==values.length)throw new TypeError(`${label} must be unique.`);return values;};
const nonemptyUnique=<T,>(values:readonly T[],label:string)=>{if(!values.length)throw new TypeError(`${label} must be nonempty.`);return unique(values,label);};
const optional=(value:unknown,label:string)=>value===undefined?undefined:requireString(value,label);

function parseCoordinate(value:unknown):CoordinateDescriptor{
  const row=requireRecord(value,'axis coordinates'),kind=requireString(row.kind,'coordinate kind');
  if(kind==='index'){exact(row,['kind'],'index coordinates');return {kind};}
  if(kind==='linear'){exact(row,['kind','referenceValue','referenceIndex','increment'],'linear coordinates');const increment=finite(row.increment,'coordinate increment');if(increment===0)throw new TypeError('Coordinate increment cannot be zero.');return {kind,referenceValue:finite(row.referenceValue,'coordinate reference value'),referenceIndex:finite(row.referenceIndex,'coordinate reference index'),increment};}
  if(kind==='native'){exact(row,['kind','convention','coupledGroup','binBounds'],'native coordinates');if(typeof row.binBounds!=='boolean')throw new TypeError('Native binBounds must be boolean.');return {kind,convention:requireString(row.convention,'native coordinate convention'),binBounds:row.binBounds,...(row.coupledGroup===undefined?{}:{coupledGroup:id(row.coupledGroup,'coupled coordinate group')})};}
  if(kind==='lookup'){exact(row,['kind','memberId','locator','binBounds'],'lookup coordinates');if(typeof row.binBounds!=='boolean')throw new TypeError('Lookup binBounds must be boolean.');return {kind,memberId:id(row.memberId,'coordinate member'),locator:requireString(row.locator,'coordinate locator'),binBounds:row.binBounds};}
  throw new TypeError(`Unsupported coordinate representation ${kind}.`);
}
function parseRepresentation(value:unknown):RepresentationDescriptor{
  const row=requireRecord(value,'representation'),kind=requireString(row.kind,'representation kind');
  if(kind==='array'){exact(row,['kind','shape','storageOrder'],'array representation');const shape=requireArray(row.shape,'array shape').map((n,index)=>whole(n,`shape ${index}`,1));if(!shape.length)throw new TypeError('Array shape cannot be empty.');if(!['row-major','column-major','native'].includes(String(row.storageOrder)))throw new TypeError('Unsupported array storage order.');return {kind,shape,storageOrder:row.storageOrder as 'row-major'|'column-major'|'native'};}
  if(kind==='table'||kind==='events'||kind==='complex-samples'){exact(row,['kind','rows'],`${kind} representation`);return {kind,rows:row.rows===null?null:whole(row.rows,'row count')};}
  if(kind==='physical-field'){exact(row,['kind','topology','samples'],'physical field representation');if(!['points','grid','mesh','other'].includes(String(row.topology)))throw new TypeError('Unsupported physical topology.');return {kind,topology:row.topology as 'points'|'grid'|'mesh'|'other',samples:row.samples===null?null:whole(row.samples,'sample count')};}
  if(kind==='collection'){exact(row,['kind','componentIds'],'collection representation');return {kind,componentIds:nonemptyUnique(list(row.componentIds,'collection components').map((entry,index)=>id(entry,`collection component ${index}`)),'collection components')};}
  throw new TypeError(`Unsupported representation ${kind}.`);
}
function parseAxis(value:unknown):AxisDescriptor{
  const row=requireRecord(value,'axis');exact(row,['id','index','length','role','physicalType','unit','coordinates','frame','reference','derivation'],'axis');
  let derivation:AxisDerivationDescriptor|undefined;if(row.derivation!==undefined){const raw=requireRecord(row.derivation,'axis derivation');exact(raw,['state','assumptions'],'axis derivation');if(!['observed','archive-derived','reconstruction-derived'].includes(String(raw.state)))throw new TypeError('Unsupported axis derivation state.');derivation={state:raw.state as AxisDerivationDescriptor['state'],assumptions:list(raw.assumptions,'axis derivation assumptions')};}
  const physicalType=optional(row.physicalType,'axis physical type');if(physicalType!==undefined&&!['length','time','pressure','angle'].includes(physicalType))throw new TypeError('Unsupported axis physical type.');
  return {id:id(row.id,'axis id'),index:whole(row.index,'axis index'),length:whole(row.length,'axis length',1),role:requireString(row.role,'axis role'),...(physicalType?{physicalType:physicalType as AxisPhysicalType}:{}),coordinates:parseCoordinate(row.coordinates),...(optional(row.unit,'axis unit')?{unit:optional(row.unit,'axis unit')}:{}),...(optional(row.frame,'axis frame')?{frame:optional(row.frame,'axis frame')}: {}),...(optional(row.reference,'axis reference')?{reference:optional(row.reference,'axis reference')}:{}),...(derivation?{derivation}:{})};
}

export function parseSupportDescriptor(value:unknown):SupportDescriptor{const row=requireRecord(value,'support');exact(row,['class','domain','unsupportedRegions'],'support');if(!['observed-samples','published-reconstruction','model-conditioned','model-ensemble'].includes(String(row.class)))throw new TypeError('Unsupported support class.');const rawDomain=requireRecord(row.domain,'support domain');exact(rawDomain,['kind','description','memberIds'],'support domain');if(!['full-grid','mask','tracks','rays','profiles','shells','regions'].includes(String(rawDomain.kind)))throw new TypeError('Unsupported support domain kind.');const domain={kind:rawDomain.kind as SupportDomainDescriptor['kind'],description:requireString(rawDomain.description,'support domain description'),memberIds:nonemptyUnique(list(rawDomain.memberIds,'support domain members').map((entry,index)=>id(entry,`support domain member ${index}`)),'support domain members')};const unsupportedRegions=requireArray(row.unsupportedRegions,'unsupported regions').map((value,index)=>{const raw=requireRecord(value,`unsupported region ${index}`);exact(raw,['kind','description','memberId'],`unsupported region ${index}`);if(!['mask','geometric','unobserved'].includes(String(raw.kind)))throw new TypeError('Unsupported region kind.');return{kind:raw.kind as SupportDescriptor['unsupportedRegions'][number]['kind'],description:requireString(raw.description,'unsupported region description'),...(raw.memberId===undefined?{}:{memberId:id(raw.memberId,'unsupported region member')})};});return{class:row.class as SupportClass,domain,unsupportedRegions};}
export function parseDepthDescriptor(value:unknown):DepthDescriptor{const row=requireRecord(value,'depth');exact(row,['coordinate','positiveDirection','datum','conversion'],'depth');if(!['delay','geometric-depth','pressure','altitude','radius','none'].includes(String(row.coordinate)))throw new TypeError('Unsupported depth coordinate.');if(!['up','down','outward'].includes(String(row.positiveDirection)))throw new TypeError('Unsupported depth positive direction.');const raw=requireRecord(row.conversion,'depth conversion');exact(raw,['state','method','parameters','uncertainty'],'depth conversion');if(!['native','derived','unavailable'].includes(String(raw.state)))throw new TypeError('Unsupported depth conversion state.');const method=optional(raw.method,'depth conversion method'),parameters=requireArray(raw.parameters,'depth conversion parameters').map((value,index)=>{const parameter=requireRecord(value,`depth conversion parameter ${index}`);exact(parameter,['name','value','unit','source'],`depth conversion parameter ${index}`);return{name:requireString(parameter.name,'depth conversion parameter name'),value:requireString(parameter.value,'depth conversion parameter value'),...(optional(parameter.unit,'depth conversion parameter unit')?{unit:optional(parameter.unit,'depth conversion parameter unit')}:{}),...(optional(parameter.source,'depth conversion parameter source')?{source:optional(parameter.source,'depth conversion parameter source')}: {})};});if(raw.state==='derived'&&(!method||!parameters.length))throw new TypeError('Derived depth conversion requires a method and explicit parameters.');if(raw.state!=='derived'&&(method||parameters.length))throw new TypeError(`${String(raw.state)} depth conversion cannot carry a derived method or parameters.`);return{coordinate:row.coordinate as DepthDescriptor['coordinate'],positiveDirection:row.positiveDirection as DepthDescriptor['positiveDirection'],datum:requireString(row.datum,'depth datum'),conversion:{state:raw.state as DepthDescriptor['conversion']['state'],...(method?{method}:{}),parameters,uncertainty:requireString(raw.uncertainty,'depth conversion uncertainty')}};}
export function parseObservabilityDescriptor(value:unknown):ObservabilityDescriptor{const row=requireRecord(value,'observability');exact(row,['measurementOperator','coverage','localization'],'observability');if(!['radar-propagation','microwave-radiative-transfer','seismic-wave-propagation','occultation-line-integral','in-situ-trajectory','gravity-integral','magnetic-induction'].includes(String(row.measurementOperator)))throw new TypeError('Unsupported measurement operator.');if(!['direct','inversion-dependent','non-unique'].includes(String(row.localization)))throw new TypeError('Unsupported localization.');const raw=requireRecord(row.coverage,'observability coverage');exact(raw,['kind','description','memberIds'],'observability coverage');if(!['tracks','rays','stations','angles','channels','trajectories','grid-cells','profiles'].includes(String(raw.kind)))throw new TypeError('Unsupported observability coverage kind.');return{measurementOperator:row.measurementOperator as ObservabilityDescriptor['measurementOperator'],coverage:{kind:raw.kind as ObservabilityDescriptor['coverage']['kind'],description:requireString(raw.description,'observability coverage description'),memberIds:nonemptyUnique(list(raw.memberIds,'observability coverage members').map((entry,index)=>id(entry,`observability coverage member ${index}`)),'observability coverage members')},localization:row.localization as ObservabilityDescriptor['localization']};}
export function parseSamplingDescriptor(value:unknown):SamplingDescriptor{const row=requireRecord(value,'sampling');exact(row,['axes'],'sampling');const axes=nonemptyUnique(requireArray(row.axes,'sampling axes').map((value,index)=>{const raw=requireRecord(value,`sampling axis ${index}`);exact(raw,['axisId','kind','interval','unit','memberId','basis'],`sampling axis ${index}`);if(!['regular','irregular','categorical'].includes(String(raw.kind)))throw new TypeError('Unsupported sampling kind.');const interval=raw.interval===undefined?undefined:finite(raw.interval,'sampling interval');if(raw.kind==='regular'&&(!(interval!>0)||optional(raw.unit,'sampling unit')===undefined))throw new TypeError('Regular sampling requires a positive interval and unit.');if(raw.kind!=='regular'&&interval!==undefined)throw new TypeError('Only regular sampling can declare one interval.');return{axisId:id(raw.axisId,'sampling axis id'),kind:raw.kind as SamplingDescriptor['axes'][number]['kind'],...(interval===undefined?{}:{interval}),...(optional(raw.unit,'sampling unit')?{unit:optional(raw.unit,'sampling unit')}:{}),...(raw.memberId===undefined?{}:{memberId:id(raw.memberId,'sampling member')}),basis:requireString(raw.basis,'sampling basis')};}), 'sampling axis declarations');return{axes};}
export function parseResolutionDescriptor(value:unknown):ResolutionDescriptor{const row=requireRecord(value,'resolution');exact(row,['state','elements','basis','memberIds'],'resolution');if(!['measured','estimated','model-kernel','unknown'].includes(String(row.state)))throw new TypeError('Unsupported resolution state.');const elements=requireArray(row.elements,'resolution elements').map((value,index)=>{const raw=requireRecord(value,`resolution element ${index}`);exact(raw,['axisId','value','range','unit','description'],`resolution element ${index}`);const scalar=raw.value===undefined?undefined:finite(raw.value,'resolution value'),range=raw.range===undefined?undefined:requireArray(raw.range,'resolution range').map((v,i)=>finite(v,`resolution range ${i}`));if(scalar!==undefined&&(!(scalar>0)||range!==undefined))throw new TypeError('Resolution value must be positive and cannot accompany a range.');if(range!==undefined&&(range.length!==2||!(range[0]!>0)||range[1]!<range[0]!))throw new TypeError('Resolution range must contain two increasing positive values.');if(row.state!=='unknown'&&scalar===undefined&&range===undefined)throw new TypeError('Established resolution elements require a value or range.');return{...(raw.axisId===undefined?{}:{axisId:id(raw.axisId,'resolution axis')}),...(scalar===undefined?{}:{value:scalar}),...(range===undefined?{}:{range:range as [number,number]}),...(optional(raw.unit,'resolution unit')?{unit:optional(raw.unit,'resolution unit')}:{}),description:requireString(raw.description,'resolution description')};});const memberIds=list(row.memberIds,'resolution members').map((entry,index)=>id(entry,`resolution member ${index}`));if(row.state!=='unknown'&&(!elements.length||!memberIds.length))throw new TypeError('Established resolution requires at least one element and one evidence member.');if(row.state==='unknown'&&elements.length)throw new TypeError('Unknown resolution cannot declare numeric resolution elements.');return{state:row.state as ResolutionDescriptor['state'],elements,basis:requireString(row.basis,'resolution basis'),memberIds};}
export function parseInferenceDescriptor(value:unknown):InferenceDescriptor{const row=requireRecord(value,'inference');exact(row,['kind','method','implementation','assumptions','validation','memberIds'],'inference');if(!['archive-published','source-backed-implementation','published-result'].includes(String(row.kind)))throw new TypeError('Unsupported inference kind.');let implementation:InferenceDescriptor['implementation'];if(row.implementation!==undefined){const raw=requireRecord(row.implementation,'inference implementation');exact(raw,['identity','version'],'inference implementation');implementation={identity:requireString(raw.identity,'inference implementation identity'),version:requireString(raw.version,'inference implementation version')};}if(row.kind==='source-backed-implementation'&&!implementation)throw new TypeError('Source-backed inference requires implementation identity and version.');return{kind:row.kind as InferenceDescriptor['kind'],method:requireString(row.method,'inference method'),...(implementation?{implementation}:{}),assumptions:list(row.assumptions,'inference assumptions'),validation:requireString(row.validation,'inference validation'),memberIds:nonemptyUnique(list(row.memberIds,'inference members').map((entry,index)=>id(entry,`inference member ${index}`)),'inference members')};}
const validateAnchorUnit=(unit:string,dimension:'length'|'angle',label:string)=>{const toolchain=astroqueryToolchainSync(),wanted=dimension==='length'?'m':'rad',result=spawnSync(toolchain.python,['-c',"import sys;from astropy import units as u\ntry: ok=u.Unit(sys.argv[1]).is_equivalent(u.Unit(sys.argv[2]))\nexcept Exception: ok=False\nsys.exit(0 if ok else 1)",unit,wanted],{env:{...process.env,...toolchain.env}});if(result.status!==0)throw new TypeError(`${label} must be an Astropy-valid ${dimension} unit.`);};
export function parsePlanetaryPlacementDescriptor(value:unknown):PlanetaryPlacementDescriptor{
  const row=requireRecord(value,'planetary placement'),kind=requireString(row.kind,'planetary placement kind');
  const basis=()=>requireString(row.basis,'planetary placement basis');
  if(kind==='cartesian'){exact(row,['kind','xAxisId','yAxisId','zAxisId','basis'],'cartesian placement');return{kind,xAxisId:id(row.xAxisId,'cartesian x axis'),yAxisId:id(row.yAxisId,'cartesian y axis'),zAxisId:id(row.zAxisId,'cartesian z axis'),basis:basis()};}
  if(kind==='spherical'){exact(row,['kind','longitudeAxisId','latitudeAxisId','radiusAxisId','basis'],'spherical placement');return{kind,longitudeAxisId:id(row.longitudeAxisId,'spherical longitude axis'),latitudeAxisId:id(row.latitudeAxisId,'spherical latitude axis'),radiusAxisId:id(row.radiusAxisId,'spherical radius axis'),basis:basis()};}
  if(kind==='projected-vertical'){exact(row,['kind','projectedXAxisId','projectedYAxisId','verticalAxisId','projection','verticalDatum','basis'],'projected vertical placement');return{kind,projectedXAxisId:id(row.projectedXAxisId,'projected x axis'),projectedYAxisId:id(row.projectedYAxisId,'projected y axis'),verticalAxisId:id(row.verticalAxisId,'projected vertical axis'),projection:requireString(row.projection,'placement projection'),verticalDatum:requireString(row.verticalDatum,'placement vertical datum'),basis:basis()};}
  if(kind==='located-profile'){exact(row,['kind','verticalAxisId','anchor','basis'],'located profile placement');const anchor=requireRecord(row.anchor,'profile anchor'),anchorKind=requireString(anchor.kind,'profile anchor kind');if(anchorKind==='body-fixed-cartesian'){exact(anchor,['kind','x','y','z','unit'],'Cartesian profile anchor');const unit=requireString(anchor.unit,'profile anchor unit');validateAnchorUnit(unit,'length','Cartesian profile anchor unit');return{kind,verticalAxisId:id(row.verticalAxisId,'profile vertical axis'),anchor:{kind:anchorKind,x:finite(anchor.x,'profile anchor x'),y:finite(anchor.y,'profile anchor y'),z:finite(anchor.z,'profile anchor z'),unit},basis:basis()};}if(anchorKind==='longitude-latitude'){exact(anchor,['kind','longitude','latitude','unit'],'longitude latitude profile anchor');const unit=requireString(anchor.unit,'profile anchor unit');validateAnchorUnit(unit,'angle','longitude latitude profile anchor unit');return{kind,verticalAxisId:id(row.verticalAxisId,'profile vertical axis'),anchor:{kind:anchorKind,longitude:finite(anchor.longitude,'profile anchor longitude'),latitude:finite(anchor.latitude,'profile anchor latitude'),unit},basis:basis()};}throw new TypeError(`Unsupported profile anchor ${anchorKind}.`);}
  if(kind==='symmetry'){exact(row,['kind','symmetry','radialAxisId','axialAxisId','basis'],'symmetric placement');if(!['spherical','axial'].includes(String(row.symmetry)))throw new TypeError('Unsupported planetary symmetry.');const axialAxisId=row.axialAxisId===undefined?undefined:id(row.axialAxisId,'symmetric axial axis');if(row.symmetry==='axial'&&!axialAxisId)throw new TypeError('Axial symmetry requires an axial axis.');return{kind,symmetry:row.symmetry as 'spherical'|'axial',radialAxisId:id(row.radialAxisId,'symmetric radial axis'),...(axialAxisId?{axialAxisId}:{}),basis:basis()};}
  throw new TypeError(`Unsupported planetary placement ${kind}.`);
}
function parseColumn(value:unknown):ColumnDescriptor{
  const row=requireRecord(value,'column');exact(row,['id','name','role','datatype','unit','nullable','variableLength','shape'],'column');
  if(typeof row.nullable!=='boolean'||typeof row.variableLength!=='boolean')throw new TypeError('Column nullable and variableLength must be boolean.');
  return {id:id(row.id,'column id'),name:requireString(row.name,'column name'),role:requireString(row.role,'column role'),datatype:requireString(row.datatype,'column datatype'),nullable:row.nullable,variableLength:row.variableLength,...(optional(row.unit,'column unit')?{unit:optional(row.unit,'column unit')}:{}),...(row.shape===undefined?{}:{shape:requireArray(row.shape,'column shape').map((n,index)=>whole(n,`column shape ${index}`,1))})};
}
function parseComponent(value:unknown):ProductComponent{
  const row=requireRecord(value,'component');exact(row,['id','name','families','locations','representation','axes','columns','quantity','calibration','uncertainty','flags','time','frame','support','depth','placement','observability','sampling','resolution','inference','dependencyIds'],'component');
  const representation=parseRepresentation(row.representation),axes=requireArray(row.axes,'component axes').map(parseAxis),columns=requireArray(row.columns,'component columns').map(parseColumn);
  unique(axes.map(axis=>axis.id),'axis ids');if(new Set(axes.map(axis=>axis.index)).size!==axes.length)throw new TypeError('Axis indices must be unique.');
  if(representation.kind==='array'&&(axes.length!==representation.shape.length||axes.some(axis=>representation.shape[axis.index]!==axis.length)))throw new TypeError('Array axes must cover the declared shape exactly.');
  unique(columns.map(column=>column.id),'column ids');
  const locations=requireArray(row.locations,'component locations').map(raw=>{const at=requireRecord(raw,'component location');exact(at,['memberId','path','hdu','structure'],'component location');return {memberId:id(at.memberId,'location member'),...(optional(at.path,'location path')?{path:optional(at.path,'location path')}:{}),...(at.hdu===undefined?{}:{hdu:whole(at.hdu,'location HDU')}),...(optional(at.structure,'location structure')?{structure:optional(at.structure,'location structure')}: {})};});
  const quantity=requireRecord(row.quantity,'quantity');exact(quantity,['name','semantics','unit'],'quantity');
  const calibration=requireRecord(row.calibration,'calibration');exact(calibration,['state','basis'],'calibration');if(!['raw','archive-calibrated','locally-reproduced','reconstructed','model-derived','unknown'].includes(String(calibration.state)))throw new TypeError('Unsupported calibration state.');
  let uncertainty:UncertaintyDescriptor|undefined;if(row.uncertainty!==undefined){const raw=requireRecord(row.uncertainty,'uncertainty');exact(raw,['form','componentId','columnId','basis'],'uncertainty');if(!['standard-deviation','variance','inverse-variance','covariance','limits','unknown','none-supplied'].includes(String(raw.form)))throw new TypeError('Unsupported uncertainty form.');uncertainty={form:raw.form as UncertaintyDescriptor['form'],basis:requireString(raw.basis,'uncertainty basis'),...(raw.componentId===undefined?{}:{componentId:id(raw.componentId,'uncertainty component')}),...(raw.columnId===undefined?{}:{columnId:id(raw.columnId,'uncertainty column')})};}
  const flags=requireArray(row.flags,'flags').map(raw=>{const flag=requireRecord(raw,'flag');exact(flag,['id','meaning','componentId','columnId','usableWhen'],'flag');return {id:id(flag.id,'flag id'),meaning:requireString(flag.meaning,'flag meaning'),...(flag.componentId===undefined?{}:{componentId:id(flag.componentId,'flag component')}),...(flag.columnId===undefined?{}:{columnId:id(flag.columnId,'flag column')}),...(optional(flag.usableWhen,'flag policy')?{usableWhen:optional(flag.usableWhen,'flag policy')}: {})};});
  const time=row.time===undefined?undefined:requireRecord(row.time,'time'),frame=row.frame===undefined?undefined:requireRecord(row.frame,'frame'),support=row.support===undefined?undefined:parseSupportDescriptor(row.support),depth=row.depth===undefined?undefined:parseDepthDescriptor(row.depth),placement=row.placement===undefined?undefined:parsePlanetaryPlacementDescriptor(row.placement),observability=row.observability===undefined?undefined:parseObservabilityDescriptor(row.observability),sampling=row.sampling===undefined?undefined:parseSamplingDescriptor(row.sampling),resolution=row.resolution===undefined?undefined:parseResolutionDescriptor(row.resolution),inference=row.inference===undefined?undefined:parseInferenceDescriptor(row.inference);
  if(time)exact(time,['scale','format','referenceEpoch','observer','exposure'],'time');if(frame)exact(frame,['kind','name','referencePosition','epoch'],'frame');
  return {id:id(row.id,'component id'),name:requireString(row.name,'component name'),families:nonemptyUnique(requireArray(row.families,'component families').map((entry,index)=>family(entry,`component family ${index}`)),'component families'),locations:nonemptyUnique(locations.map(location=>JSON.stringify(location)),'component locations').map(text=>JSON.parse(text) as ComponentLocator),representation,axes,columns,
    quantity:{name:requireString(quantity.name,'quantity name'),semantics:requireString(quantity.semantics,'quantity semantics'),...(optional(quantity.unit,'quantity unit')?{unit:optional(quantity.unit,'quantity unit')}: {})},calibration:{state:calibration.state as CalibrationState,basis:list(calibration.basis,'calibration basis')},...(uncertainty?{uncertainty}:{}),flags,
    ...(time?{time:{scale:requireString(time.scale,'time scale'),format:requireString(time.format,'time format'),...(optional(time.referenceEpoch,'time epoch')?{referenceEpoch:optional(time.referenceEpoch,'time epoch')}:{}),...(optional(time.observer,'time observer')?{observer:optional(time.observer,'time observer')}:{}),...(optional(time.exposure,'exposure')?{exposure:optional(time.exposure,'exposure')}: {})}}:{}),
    ...(frame?{frame:{kind:requireString(frame.kind,'frame kind'),name:requireString(frame.name,'frame name'),...(optional(frame.referencePosition,'reference position')?{referencePosition:optional(frame.referencePosition,'reference position')}:{}),...(optional(frame.epoch,'frame epoch')?{epoch:optional(frame.epoch,'frame epoch')}: {})}}:{}),...(support?{support}:{}),...(depth?{depth}:{}),...(placement?{placement}:{}),...(observability?{observability}:{}),...(sampling?{sampling}:{}),...(resolution?{resolution}:{}),...(inference?{inference}:{}),dependencyIds:list(row.dependencyIds,'component dependencies').map((entry,index)=>id(entry,`component dependency ${index}`))};
}

export function parseProductDescriptor(value:unknown):ProductDescriptor{
  const root=requireRecord(value,'product descriptor');exact(root,['schema','dataset','members','components','dependencies','issues'],'product descriptor');if(root.schema!==PRODUCT_DESCRIPTOR_SCHEMA)throw new TypeError(`Unsupported product descriptor schema ${String(root.schema)}.`);
  const dataset=requireRecord(root.dataset,'dataset');exact(dataset,['id','target','acquisition','producingRecord','sourceClassifications','families','profiles'],'dataset');const acquisition=requireRecord(dataset.acquisition,'acquisition');exact(acquisition,['kind','identity'],'acquisition');if(!['archive','local-import','repository'].includes(String(acquisition.kind)))throw new TypeError('Unsupported acquisition kind.');
  const members=requireArray(root.members,'members').map(raw=>{const row=requireRecord(raw,'member');exact(row,['id','path','role','bytes','sha256','mediaType'],'member');const bytes=whole(row.bytes,'member bytes'),sha256=requireString(row.sha256,'member sha256'),role=requireString(row.role,'member role');if(!HEX.test(sha256)||!['science','support','label','coordinates','quality','uncertainty','calibration','response','provenance'].includes(role))throw new TypeError('Invalid member pin or role.');return {id:id(row.id,'member id'),path:requireString(row.path,'member path'),role:role as MemberRole,bytes,sha256,...(optional(row.mediaType,'member media type')?{mediaType:optional(row.mediaType,'member media type')}: {})};});
  nonemptyUnique(members.map(member=>member.id),'member ids');const memberIds=new Set(members.map(member=>member.id));
  const components=requireArray(root.components,'components').map(parseComponent);nonemptyUnique(components.map(component=>component.id),'component ids');const componentIds=new Set(components.map(component=>component.id));
  const dependencies=requireArray(root.dependencies,'dependencies').map(raw=>{const row=requireRecord(raw,'dependency');exact(row,['id','role','memberIds','componentIds','requiredFor','evidence'],'dependency');return {id:id(row.id,'dependency id'),role:requireString(row.role,'dependency role'),memberIds:list(row.memberIds,'dependency members').map((entry,index)=>id(entry,`dependency member ${index}`)),componentIds:list(row.componentIds,'dependency components').map((entry,index)=>id(entry,`dependency component ${index}`)),requiredFor:list(row.requiredFor,'dependency operations'),...(optional(row.evidence,'dependency evidence')?{evidence:optional(row.evidence,'dependency evidence')}: {})};});
  unique(dependencies.map(dependency=>dependency.id),'dependency ids');const dependencyIds=new Set(dependencies.map(dependency=>dependency.id));
  for(const component of components){
    for(const location of component.locations)if(!memberIds.has(location.memberId))throw new TypeError(`Component ${component.id} references missing member ${location.memberId}.`);
    for(const axis of component.axes)if(axis.coordinates.kind==='lookup'&&!memberIds.has(axis.coordinates.memberId))throw new TypeError(`Axis ${axis.id} references missing member ${axis.coordinates.memberId}.`);
    for(const memberId of component.support?.domain.memberIds??[])if(!memberIds.has(memberId))throw new TypeError(`Component ${component.id} support references missing member ${memberId}.`);
    for(const region of component.support?.unsupportedRegions??[])if(region.memberId&&!memberIds.has(region.memberId))throw new TypeError(`Component ${component.id} unsupported region references missing member ${region.memberId}.`);
    for(const memberId of component.observability?.coverage.memberIds??[])if(!memberIds.has(memberId))throw new TypeError(`Component ${component.id} observability references missing member ${memberId}.`);
    for(const sample of component.sampling?.axes??[]){if(!component.axes.some(axis=>axis.id===sample.axisId))throw new TypeError(`Component ${component.id} sampling references missing axis ${sample.axisId}.`);if(sample.memberId&&!memberIds.has(sample.memberId))throw new TypeError(`Component ${component.id} sampling references missing member ${sample.memberId}.`);}
    for(const element of component.resolution?.elements??[])if(element.axisId&&!component.axes.some(axis=>axis.id===element.axisId))throw new TypeError(`Component ${component.id} resolution references missing axis ${element.axisId}.`);
    for(const memberId of component.resolution?.memberIds??[])if(!memberIds.has(memberId))throw new TypeError(`Component ${component.id} resolution references missing member ${memberId}.`);
    for(const memberId of component.inference?.memberIds??[])if(!memberIds.has(memberId))throw new TypeError(`Component ${component.id} inference references missing member ${memberId}.`);
    if(component.placement){const axes=new Map(component.axes.map(axis=>[axis.id,axis]));const requireAxis=(axisId:string,role?:string,physicalType?:AxisPhysicalType)=>{const axis=axes.get(axisId);if(!axis||(role!==undefined&&axis.role!==role)||(physicalType!==undefined&&axis.physicalType!==physicalType))throw new TypeError(`Component ${component.id} placement axis ${axisId} does not carry required ${[role,physicalType].filter(Boolean).join(' ' )||'declared coordinate'}.`);return axis;};const distinct=(axisIds:readonly string[])=>{if(new Set(axisIds).size!==axisIds.length)throw new TypeError(`Component ${component.id} placement axes must be unique.`);};const placement=component.placement;if(placement.kind==='cartesian'){distinct([placement.xAxisId,placement.yAxisId,placement.zAxisId]);requireAxis(placement.xAxisId,'body-fixed-x','length');requireAxis(placement.yAxisId,'body-fixed-y','length');requireAxis(placement.zAxisId,'body-fixed-z','length');}else if(placement.kind==='spherical'){distinct([placement.longitudeAxisId,placement.latitudeAxisId,placement.radiusAxisId]);requireAxis(placement.longitudeAxisId,'longitude','angle');requireAxis(placement.latitudeAxisId,'latitude','angle');requireAxis(placement.radiusAxisId,'radius','length');}else if(placement.kind==='projected-vertical'){distinct([placement.projectedXAxisId,placement.projectedYAxisId,placement.verticalAxisId]);requireAxis(placement.projectedXAxisId,'projected-x','length');requireAxis(placement.projectedYAxisId,'projected-y','length');const vertical=requireAxis(placement.verticalAxisId,undefined,'length');if(!component.depth||component.depth.coordinate==='none'||vertical.role!==component.depth.coordinate)throw new TypeError(`Component ${component.id} projected vertical placement must reference the declared physical depth coordinate.`);}else if(placement.kind==='located-profile'){requireAxis(placement.verticalAxisId);}else{if(!component.depth||component.depth.coordinate!=='radius')throw new TypeError(`Component ${component.id} symmetry placement requires radius as the declared depth coordinate.`);if(placement.symmetry==='spherical'){requireAxis(placement.radialAxisId,'radius','length');}else{distinct([placement.radialAxisId,placement.axialAxisId!]);requireAxis(placement.radialAxisId,'radius','length');requireAxis(placement.axialAxisId!,'body-fixed-z','length');}}}
    if(component.support&&component.support.class!=='observed-samples'&&!component.inference)throw new TypeError(`Component ${component.id} support class ${component.support.class} requires inference method and assumptions.`);
    if(component.depth&&component.depth.coordinate!=='none'&&!component.axes.some(axis=>axis.role===component.depth!.coordinate))throw new TypeError(`Component ${component.id} depth coordinate ${component.depth.coordinate} has no matching axis.`);
    for(const dependency of component.dependencyIds)if(!dependencyIds.has(dependency))throw new TypeError(`Component ${component.id} references missing dependency ${dependency}.`);
    if(component.uncertainty?.componentId&&!componentIds.has(component.uncertainty.componentId))throw new TypeError(`Component ${component.id} uncertainty references missing component ${component.uncertainty.componentId}.`);
    if(component.uncertainty?.columnId&&!component.columns.some(column=>column.id===component.uncertainty!.columnId))throw new TypeError(`Component ${component.id} uncertainty references missing column ${component.uncertainty.columnId}.`);
    for(const flag of component.flags){if(flag.componentId&&!componentIds.has(flag.componentId))throw new TypeError(`Flag ${flag.id} references missing component ${flag.componentId}.`);if(flag.columnId&&!component.columns.some(column=>column.id===flag.columnId))throw new TypeError(`Flag ${flag.id} references missing column ${flag.columnId}.`);}
    if(component.representation.kind==='collection')for(const child of component.representation.componentIds)if(!componentIds.has(child)||child===component.id)throw new TypeError(`Collection ${component.id} has an invalid child ${child}.`);
  }
  for(const dependency of dependencies){for(const member of dependency.memberIds)if(!memberIds.has(member))throw new TypeError(`Dependency ${dependency.id} references missing member ${member}.`);for(const component of dependency.componentIds)if(!componentIds.has(component))throw new TypeError(`Dependency ${dependency.id} references missing component ${component}.`);}
  const classifications=requireArray(dataset.sourceClassifications,'source classifications').map(raw=>{const row=requireRecord(raw,'source classification');exact(row,['term','vocabulary','version','status'],'source classification');if(!['source','mapped','preliminary'].includes(String(row.status)))throw new TypeError('Invalid classification status.');return {term:requireString(row.term,'classification term'),vocabulary:requireString(row.vocabulary,'classification vocabulary'),version:requireString(row.version,'classification version'),status:row.status as 'source'|'mapped'|'preliminary'};});
  const families=nonemptyUnique(requireArray(dataset.families,'dataset families').map((entry,index)=>family(entry,`dataset family ${index}`)),'dataset families');for(const component of components)for(const found of component.families)if(!families.includes(found))throw new TypeError(`Component ${component.id} family ${found} is absent from the dataset.`);
  const profiles=requireArray(dataset.profiles,'validated profiles').map((raw,index)=>{const row=requireRecord(raw,`validated profile ${index}`);exact(row,['handlerId','profileId'],`validated profile ${index}`);return {handlerId:id(row.handlerId,'profile handler'),profileId:id(row.profileId,'profile id')};});nonemptyUnique(profiles.map(profile=>`${profile.handlerId}:${profile.profileId}`),'validated profiles');
  const issues=requireArray(root.issues,'issues').map(raw=>{const row=requireRecord(raw,'issue');exact(row,['scope','identity','state','reason'],'issue');if(!['dataset','member','component','axis','column','dependency'].includes(String(row.scope))||!['missing','conflicting','unsupported','unknown'].includes(String(row.state)))throw new TypeError('Invalid descriptor issue.');return {scope:row.scope as DescriptorIssue['scope'],identity:requireString(row.identity,'issue identity'),state:row.state as DescriptorIssue['state'],reason:requireString(row.reason,'issue reason')};});
  return {schema:PRODUCT_DESCRIPTOR_SCHEMA,dataset:{id:id(dataset.id,'dataset id'),...(optional(dataset.target,'dataset target')?{target:optional(dataset.target,'dataset target')}:{}),acquisition:{kind:acquisition.kind as 'archive'|'local-import'|'repository',identity:requireString(acquisition.identity,'acquisition identity')},producingRecord:requireString(dataset.producingRecord,'producing record'),sourceClassifications:classifications,families,profiles},members,components,dependencies,issues};
}
