import assert from 'node:assert/strict';
import { test } from 'node:test';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createSourceManifest } from '../../../../src/platform/source-manifest.mts';
import { requireArray, requireRecord, requireString } from '../../../../tools/source-values.mts';
import { loadPdsRadiusTable } from '../../../../tools/objects/terrestrial-layers/obj-shape.mts';
import { uniformDiscTable } from '../../../../tools/objects/source-authoring/betelgeuse/author.mts';

const root = resolve(import.meta.dirname, '../../../../src/objects/betelgeuse/source');
const read = async (path: string) => JSON.parse(await readFile(resolve(root, path), 'utf8')) as unknown;

test('Betelgeuse retains source pins and acquisition closure', async () => {
  const source = await createSourceManifest({ planetId: 'betelgeuse', planetName: 'Betelgeuse', sourceRoot: root });
  await source.verify();
  const plan = requireRecord(await read('preparation/acquisition.json')), operations = requireArray(plan.operations).map(value => requireRecord(value));
  const downloaded = new Set(operations.map(operation => requireString(operation.path)));
  // Every pinned input is either restored by the plan, produced in this repository from pinned inputs by a named tool,
  // or an authored preparation record checked into the repository.
  for (const input of source.manifest.inputs) {
    if (downloaded.has(input.path)) continue;
    const authored = (/^(preparation|presentation)\/.*\.json$/u.test(input.path) && input.acquisition === 'checked repository source')
      || (/^photometry\/.*\.json$/u.test(input.path) && input.acquisition.startsWith('Authored method record'))
      // Small published reference tables are checked in unchanged.
      || (input.path.startsWith('reference/') && input.acquisition.startsWith('Downloaded unchanged'));
    if (authored) continue;
    assert.match(input.acquisition, /author\.mts|squeeze-command\.txt/u, `${input.path} is neither downloaded, generated by a named tool nor an authored record`);
  }
  // Three MATISSE epochs: December 2018 (111 files), February 2020 (29) and December 2020 (48).
  assert.equal(operations.filter(operation => requireString(operation.path).startsWith('observations/oifits/')).length, 111 + 29 + 48, 'the plan restores every MATISSE file');
  assert.equal(source.manifest.inputs.filter(input => input.consumers.includes('continuum-visibilities')).length, 111 + 29 + 48);
  for (const group of ['sphere-photograph', 'sphere-photograph-2018-12', 'sphere-photograph-2020-12']) {
    assert.equal(source.manifest.inputs.filter(input => input.consumers.includes(group)).length, 1, group);
  }
});

test('the reference sphere is the published radius on the stated grid', async () => {
  const measurements = requireRecord(await read('measurements.json')), shape = requireRecord(measurements.shape);
  const text = await readFile(resolve(root, requireString(shape.path)), 'utf8');
  assert.equal(text, uniformDiscTable(Number(measurements.radiusKm), Number(shape.stepDegrees)), 'the table is the authoring tool\'s output');
  const raster = requireRecord(await read('preparation/raster.json')), terrain = requireRecord(requireRecord(requireRecord(requireArray(raster.surfaces)[0]).science).shape);
  const mesh = await loadPdsRadiusTable(resolve(root, requireString(terrain.path)), terrain.grid);
  assert.equal(mesh.positions.length, 2522); assert.equal(mesh.indices.length, 5040);
  const radii = mesh.positions.map(position => Math.hypot(...position));
  assert.ok(radii.every(radius => Math.abs(radius - 531514800000) < 1), 'every vertex sits at the published radius in metres');
  // 764 solar radii, and the pinned 42.45 mas disc at 168 pc within half a percent of it.
  assert.ok(Math.abs(531514800 / 695700 - 764) < 0.01);
  const discRadiusKm = 42.45 / 2 * Math.PI / 180 / 3.6e6 * 168 * 3.085677581491367e13;
  assert.ok(Math.abs(discRadiusKm / 531514800 - 1) < 0.005, `disc radius ${discRadiusKm} km against the published ${531514800} km`);
});
