import assert from 'node:assert/strict';
import { test } from 'node:test';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createSourceManifest } from '../../../../src/platform/source-manifest.mts';
import { requireArray, requireRecord, requireString } from '../../../../tools/source-values.mts';
import { loadPdsRadiusTable } from '../../../../tools/objects/terrestrial-layers/obj-shape.mts';
import { uniformDiscTable } from '../../../../tools/objects/source-authoring/betelgeuse/author.mts';

const root = resolve(import.meta.dirname, '../../../../src/objects/betelgeuse/source');
const read = async (path: string) => JSON.parse(await readFile(resolve(root, path), 'utf8')) as unknown;

test('Betelgeuse retains source pins and acquisition closure', async () => {
  const source = await createSourceManifest({ planetId: 'betelgeuse', planetName: 'Betelgeuse', sourceRoot: root });
  await source.verify();
  const plan = requireRecord(await read('preparation/acquisition.json')), operations = requireArray(plan.operations).map(value => requireRecord(value));
  const downloaded = new Set(operations.map(operation => requireString(operation.path)));
  // Every pinned input is either restored by the plan or produced in this repository from pinned inputs and says so.
  for (const input of source.manifest.inputs) {
    if (downloaded.has(input.path)) continue;
    assert.match(input.acquisition, /author\.mts|squeeze-command\.txt/u, `${input.path} is neither downloaded nor generated by a named tool`);
  }
  assert.equal(operations.filter(operation => requireString(operation.path).startsWith('observations/oifits/')).length, 29, 'the plan restores the 29 MATISSE files');
  assert.equal(source.manifest.inputs.filter(input => input.consumers.includes('continuum-visibilities')).length, 29);
  assert.equal(source.manifest.inputs.filter(input => input.consumers.includes('sphere-photograph')).length, 1);
});

test('the reference sphere is the published radius on the stated grid', async () => {
  const measurements = requireRecord(await read('measurements.json')), shape = requireRecord(measurements.shape);
  const text = await readFile(resolve(root, requireString(shape.path)), 'utf8');
  assert.equal(text, uniformDiscTable(Number(measurements.radiusKm), Number(shape.stepDegrees)), 'the table is the authoring tool\'s output');
  const config = requireRecord(await read('preparation/terrestrial.json')), terrain = requireRecord(requireRecord(config.geometry).radialTerrain);
  const mesh = await loadPdsRadiusTable(resolve(root, requireString(terrain.path)), terrain.grid);
  assert.equal(mesh.positions.length, 2522); assert.equal(mesh.indices.length, 5040);
  const radii = mesh.positions.map(position => Math.hypot(...position));
  assert.ok(radii.every(radius => Math.abs(radius - 531514800000) < 1), 'every vertex sits at the published radius in metres');
  // 764 solar radii, and the pinned 42.45 mas disc at 168 pc within half a percent of it.
  assert.ok(Math.abs(531514800 / 695700 - 764) < 0.01);
  const discRadiusKm = 42.45 / 2 * Math.PI / 180 / 3.6e6 * 168 * 3.085677581491367e13;
  assert.ok(Math.abs(discRadiusKm / 531514800 - 1) < 0.005, `disc radius ${discRadiusKm} km against the published ${531514800} km`);
});
