import {requireRecord} from '../../../../tools/sources/source-values.mts';
import {requireClosedTerrain} from '../../fixtures/source-fixture.mts';
import {required} from '../../../../tools/contract/test-values.mts';
import assert from 'node:assert/strict';
import { sourceTest } from '../../source-test.mts';
const test = sourceTest('donaldjohanson');
import {readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {createSourceManifest} from '../../../../src/platform/source-manifest.mts';
import {readAuthoredRotation} from '../../../../tools/objects/authored-rotation.mts';
import {loadObjShape,createShapeSurfaceSampler} from '../../../../tools/objects/terrestrial-layers/obj-shape.mts';
import {loadRadialTerrain} from '../../../../tools/objects/terrestrial-layers/radial-terrain.mts';
const root=resolve(import.meta.dirname,'../../../../src/objects/donaldjohanson/source');
const read=async (path: string)=>JSON.parse(await readFile(resolve(root,path),'utf8'));
test('Donaldjohanson retains original source pins and DSK acquisition closure',async()=>{
 const source=await createSourceManifest({planetId:'donaldjohanson',planetName:'Donaldjohanson',sourceRoot:root});await source.verify();
 const plan=await read('preparation/acquisition.json');
 for(const input of source.manifest.inputs)if(!input.path.endsWith('.obj.gz')&&!['preparation/camera.json','observations/llorri-camera.json','preparation/llorri-overlap.json','observations/llorri-approach-camera.json'].includes(input.path))assert.ok(plan.operations.some((step: { path: string; })=>step.path===input.path));
 const dsk=await read('reference/dsk-inspection.json');assert.deepEqual([dsk.center,dsk.frame,dsk.surface,dsk.type],[20052246,20052246,200522461,2]);
});
test('Donaldjohanson preserves the Lucy mesh scale and assigns elevation to distinct overlapping surfaces',async()=>{
 const config=await read('preparation/terrestrial.json'),p=config.geometry.radialTerrain;
 const mesh=await loadObjShape(resolve(root,p.path),p.grid);
 assert.deepEqual([mesh.vertices,mesh.faces],[274000,547996]);assert.deepEqual(mesh.positions[0],[3.5343599324631003,-13.500515735165198,-1315.900964425746]);assert.deepEqual(mesh.indices[0],[0,2,5]);
 const extents=mesh.bounds[1].map((v,i)=>(v-mesh.bounds[0][i])/1000);for(const[i,expected]of[8.821631717505912,4.4112336571227555,3.09636843889667].entries())assert.ok(Math.abs(extents[i]-expected)<1e-9);
 const sampler=createShapeSurfaceSampler(mesh,config.raster.scientific.find((lens:{id:string})=>lens.id==='elevation'));
 const point=[-3015.316737275648,503.08981936143385,1365.356208179241],outer=required(sampler.samplePoint(point));
 assert.equal(outer.faceId,487421);assert.ok(Math.abs(outer.value-942.7239792793316)<1e-7);
 const radius=Math.hypot(...point),first=required(mesh.intersect([0,0,0],point.map(n=>n/radius)));
 assert.ok(Math.abs(radius-first.radius-400.1240753512784)<1e-7,'A first-ray map assigns the wrong overlapping surface');
 assert.equal(sampler.samplePoint([0,0,0]),null,'Out-of-bound transfers stay missing');
 assert.deepEqual(config.raster.shapeViews.map((v:unknown)=>requireRecord(v).id),['shape']);
 const rotation=await read('preparation/rotation.json');assert.equal(rotation.schema,'cssearth-display-orientation@1');assert.equal(rotation.periodHours,undefined);
 const descriptor=JSON.parse(await readFile(resolve(root,'../object.json'),'utf8'));const frame=await readAuthoredRotation(resolve(root,'..'),descriptor.properties.recipe.sources.find((s: { id: string; })=>s.id==='rotation'),2461286.5);assert.equal(frame.spinRateRadPerDay,0);
});
test('Donaldjohanson keeps the closed Lucy surface within the retained raster budget',async()=>{
 const config=await read('preparation/terrestrial.json'),source=await createSourceManifest({planetId:'donaldjohanson',planetName:'Donaldjohanson',sourceRoot:root});
 const radial=requireClosedTerrain(await loadRadialTerrain({config,sourceDirectory:root,source}));
 assert.equal(radial.faces.length,800);assert.equal(required(radial.simplification).sourceFaces,547996);assert.equal(required(radial.simplification).removedOppositeFaces,0);
 assert.equal(required(radial.simplification).topology.eulerCharacteristic,2);assert.equal(required(radial.simplification).topology.components,1);assert.ok(required(radial.simplification).estimatedErrorMeters<=56);
 assert.ok(radial.leaves.every(l=>l.tag==='u'&&l.attributes['data-polycss-texture-leaf-sizing']==='raster'));
 assert.ok(radial.plans.reduce((sum,p)=>sum+p.rect.width*p.rect.height,0)<=16384*radial.faces.length);
});
