/** Generated by `pnpm prepare:catalog` (`preparedCatalogueModule` in `@cssearth/objects/node`); consumers decode each entry
 * with `catalogueObject`. */
export const CATALOGUE_ENTRIES: readonly unknown[];
