import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { chromium } from 'playwright';
import { conformanceBrowserLaunch } from './conformance-browser-launch.mts';
const directory = 'output/playwright/native-scroll';
const origin = process.argv[2] ?? 'http://127.0.0.1:4350';
await mkdir(directory, { recursive: true });
const browser = await chromium.launch((await conformanceBrowserLaunch({ evidenceDirectory: directory })).options);
try {
  const context = await browser.newContext({ javaScriptEnabled: false, viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const page = await context.newPage();
  await page.goto(new URL('/saturn/', origin).href);
  await page.waitForTimeout(500);
  const state = () => page.locator('.planet-input-surface').evaluate(node => ({ scroll: node.scrollTop,
    translate: getComputedStyle(document.querySelector('.polycss-scene')!).translate }));
  const initial = await state(); assert.equal(initial.scroll, 400);
  await page.screenshot({ path: `${directory}/phone-initial.png` });
  const cdp = await context.newCDPSession(page);
  await cdp.send('Input.synthesizeScrollGesture', { x: 200, y: 240, yDistance: -100, speed: 200, gestureSourceType: 'touch' });
  await page.waitForTimeout(500);
  const zoomed = await state();
  assert.ok(zoomed.scroll > initial.scroll); assert.notEqual(zoomed.translate, initial.translate);
  await page.locator('.planet-sheet-handle').check();
  await page.waitForTimeout(500);
  const panelBefore = await page.locator('.planet-sidebar').evaluate(node => node.scrollTop);
  const beforePanel = await state();
  await cdp.send('Input.synthesizeScrollGesture', { x: 180, y: 720, yDistance: -280, speed: 350, gestureSourceType: 'touch' });
  await page.waitForTimeout(500);
  assert.equal((await state()).scroll, beforePanel.scroll);
  const panelAfter = await page.locator('.planet-sidebar').evaluate(node => node.scrollTop);
  assert.ok(panelAfter > panelBefore, `The information panel must scroll: ${panelBefore} -> ${panelAfter}`);
  await page.locator('.planet-sheet-handle').uncheck();
  await page.waitForTimeout(300);
  for (let i = 0; i < 12; i++) await cdp.send('Input.synthesizeScrollGesture', { x: 375, y: 450, yDistance: -300, speed: 1200, gestureSourceType: 'touch' });
  await page.waitForTimeout(500);
  const solar = await state(); assert.equal(solar.scroll, 4000);
  await page.screenshot({ path: `${directory}/phone-solar.png` });
  await page.locator('a[data-native-destination="neptune"]').tap();
  await page.waitForURL('**/neptune/'); await page.waitForTimeout(500);
  assert.equal(await page.locator('.planet-stage').getAttribute('data-object-id'), 'neptune');
  assert.equal(await page.locator('.polycss-scene').count(), 1);
  assert.equal(await page.locator('.prepared-celestial-sky').count(), 1);
  await page.screenshot({ path: `${directory}/phone-neptune.png` });
  await writeFile(`${directory}/touch-report.json`, JSON.stringify({ initial, zoomed, solar, panelBefore, panelAfter, arrival: await state() }, null, 2));
  console.log('Native touch zoom, independent information panel and Saturn-to-Neptune navigation: passed');
  await context.close();
} finally { await browser.close(); }
