import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { chromium } from 'playwright';
import { conformanceBrowserLaunch } from './conformance-browser-launch.mts';

declare global { interface Window { __searchNodes: Element[]; __searchControls: Element[]; } }
const origin = process.argv[2] ?? 'http://127.0.0.1:4210';
const output = resolve('output/playwright/search');
await mkdir(output, { recursive: true });
const browser = await chromium.launch((await conformanceBrowserLaunch({ evidenceDirectory: output })).options);
const cases: string[] = [];
try {
  for (const viewport of [{ width: 1280, height: 900 }, { width: 390, height: 844 }]) {
    const context = await browser.newContext({ javaScriptEnabled: false, viewport });
    const page = await context.newPage();
    const scripts: string[] = [];
    page.on('request', request => { if (request.resourceType() === 'script') scripts.push(request.url()); });
    await page.goto(`${origin}/saturn/`, { waitUntil: 'domcontentloaded' });
    const scene = await page.locator('.planet-stage').innerHTML();
    const search = page.getByRole('searchbox');
    await search.fill('Titan');
    await search.press('Enter');
    await page.waitForURL(url => url.searchParams.get('q') === 'Titan');
    const results = page.locator('.planet-object-browser');
    const titan = results.locator('.planet-object-link[data-object-id="titan"]');
    assert.equal(await titan.isVisible(), true);
    assert.deepEqual(await results.locator('.planet-object-item:not([hidden]) .planet-object-name').allTextContents(), ['Titan', 'Titania']);
    assert.equal(await page.locator('.planet-stage').innerHTML(), scene);
    assert.equal(await page.locator('.polycss-scene').count(), 1);
    assert.equal(await page.locator('.planet-information-panel').isVisible(), false);
    await page.screenshot({ path: `${output}/native-${viewport.width}.png` });
    await page.getByRole('link', { name: 'Clear search', exact: true }).click();
    await page.waitForURL(`${origin}/saturn/`);
    await page.getByRole('button', { name: 'Moons', exact: true }).click();
    await page.waitForURL(url => url.searchParams.get('browse') === 'Moons');
    assert.equal(await search.inputValue(), 'Moons');
    assert.ok(await results.locator('.planet-object-item:not([hidden])').count() > 20);
    await search.fill('');
    await page.getByRole('button', { name: 'Browse celestial objects', exact: true }).click();
    await page.waitForURL(url => url.searchParams.get('q') === '' && !url.searchParams.has('browse'));
    assert.ok(await results.locator('.planet-object-item:not([hidden])').count() > 450);
    await search.fill('m42');
    await search.press('Enter');
    await page.waitForURL(url => url.searchParams.get('q') === 'm42');
    assert.equal(await results.locator('a[data-prepared-focus-id="m42"]').isVisible(), true);
    await search.fill('Tycho');
    await search.press('Enter');
    await page.waitForURL(url => url.searchParams.get('q') === 'Tycho');
    const feature = page.locator('.planet-feature-results a[href^="/moon/?feature="]').first();
    assert.equal(await feature.isVisible(), true);
    await feature.click();
    await page.waitForURL(url => url.pathname === '/moon/' && url.searchParams.has('feature'));
    assert.equal(await page.locator('.planet-stage').getAttribute('data-object-id'), 'moon');
    await page.goto(`${origin}/earth/`, { waitUntil: 'domcontentloaded' });
    await search.fill('Buenos Aires');
    await search.press('Enter');
    await page.waitForURL(url => url.searchParams.get('q') === 'Buenos Aires');
    const city = page.locator('.planet-feature-results a[href="/earth/?feature=1159151559"]');
    assert.equal(await city.isVisible(), true);
    await city.click();
    await page.waitForURL(url => url.searchParams.get('feature') === '1159151559');
    assert.equal(await page.locator('.planet-stage').getAttribute('data-object-id'), 'earth');
    assert.equal(scripts.length, 0);
    cases.push(`No JS at ${viewport.width}px: submit, clear, pills, empty query, categories, aliases, feature/city links; one unchanged scene`);
    console.log(cases.at(-1));
    await context.close();
  }
  const context = await browser.newContext({ viewport: { width: 1280, height: 900 } });
  const page = await context.newPage();
  let release!: () => void;
  const gate = new Promise<void>(resolve => { release = resolve; });
  await page.route('**/*', async route => {
    if (route.request().resourceType() === 'script') await gate;
    await route.continue();
  });
  await page.goto(`${origin}/saturn/?q=Titan`, { waitUntil: 'commit' });
  const titan = page.locator('.planet-object-browser a[data-object-id="titan"]');
  await titan.waitFor({ state: 'visible' });
  await page.evaluate(() => {
    window.__searchNodes = [...document.querySelectorAll('.planet-stage [data-prepared-node]')];
    window.__searchControls = [...document.querySelectorAll('.planet-sidebar-search-card, .planet-object-browser .planet-object-link')];
  });
  const style = () => titan.evaluate(node => {
    const style = getComputedStyle(node);
    return { font: style.font, color: style.color, background: style.background, padding: style.padding, height: style.height };
  });
  const before = await style();
  release();
  await page.waitForFunction(() => document.documentElement.dataset.ready === 'true', undefined, { timeout: 90_000 });
  assert.equal(await titan.isVisible(), true);
  assert.equal(await page.getByRole('searchbox').inputValue(), 'Titan');
  assert.deepEqual(await style(), before);
  assert.equal(await page.evaluate(() => [...window.__searchNodes, ...window.__searchControls].every(node => node.isConnected)), true);
  assert.equal(await page.locator('.polycss-scene').count(), 1);
  let navigations = 0;
  page.on('request', request => { if (request.isNavigationRequest() && request.frame() === page.mainFrame()) navigations++; });
  await page.getByRole('searchbox').fill('Jupiter');
  const jupiter = page.locator('.planet-object-browser a[data-object-id="jupiter"]');
  await jupiter.waitFor({ state: 'visible' });
  assert.equal(await titan.isVisible(), false);
  assert.equal(navigations, 0);
  await page.getByRole('button', { name: 'Collapse celestial objects', exact: true }).click();
  assert.equal(navigations, 0);
  await page.screenshot({ path: `${output}/enhanced.png` });
  cases.push('Delayed JS retains the same scene, form and rows, preserves the query/styles, then filters without navigation');
  console.log(cases.at(-1));
  await context.close();
  const featureContext = await browser.newContext({ viewport: { width: 1280, height: 900 } });
  const featurePage = await featureContext.newPage();
  let releaseScripts!: () => void, releaseIndex!: () => void;
  const scriptsReady = new Promise<void>(resolve => { releaseScripts = resolve; });
  const indexReady = new Promise<void>(resolve => { releaseIndex = resolve; });
  await featurePage.route('**/*', async route => {
    if (route.request().resourceType() === 'script') await scriptsReady;
    if (new URL(route.request().url()).pathname === '/features/index.json') await indexReady;
    await route.continue();
  });
  await featurePage.goto(`${origin}/saturn/?q=Tycho`, { waitUntil: 'commit' });
  const tycho = featurePage.locator('.planet-feature-results a[href^="/moon/?feature="]').first();
  await tycho.waitFor({ state: 'visible' });
  await featurePage.evaluate(() => { window.__searchControls = [...document.querySelectorAll('.planet-feature-results a')]; });
  const label = await tycho.getAttribute('aria-label');
  releaseScripts();
  await featurePage.waitForFunction(() => document.documentElement.dataset.ready === 'true', undefined, { timeout: 90_000 });
  assert.equal(await tycho.isVisible(), true, 'Native results stay usable while the live index is still loading');
  assert.equal(await tycho.getAttribute('aria-label'), label);
  assert.equal(await featurePage.evaluate(() => window.__searchControls.every(node => node.isConnected)), true);
  await tycho.click();
  await featurePage.waitForURL(url => url.pathname === '/moon/' && url.searchParams.has('feature'), { waitUntil: 'commit' });
  releaseIndex();
  cases.push('Native feature links remain visible and navigable while JS waits for its search index');
  console.log(cases.at(-1));
  await featureContext.close();
} finally {
  await writeFile(`${output}/report.json`, JSON.stringify({ origin, cases }, null, 2) + '\n');
  await browser.close();
}
