import assert from 'node:assert/strict';
import { test } from 'node:test';
import { parseHTML } from 'linkedom';
import { createWorldViewport, stageSized } from './world-viewport.mts';
const rect = (width: number, height: number, top = 0): DOMRect => ({ x: 0, y: top, width, height, top, left: 0, right: width, bottom: top + height, toJSON() { return {}; } });
test('world viewport reads search band, sidebar and header even when a desktop band is empty', () => {
  const { document, window } = parseHTML('<html><body><header class="explorer-shell-header"></header><aside class="object-sidebar"></aside><div class="object-viewport-search-band"></div><main></main></body></html>');
  Object.assign(window, { ResizeObserver: class { observe() {} disconnect() {} }, getComputedStyle: () => ({ perspective: '600px' }) });
  const stage = document.querySelector<HTMLElement>('main')!, band = document.querySelector<HTMLElement>('.object-viewport-search-band')!;
  stage.getBoundingClientRect = () => rect(800, 600); band.getBoundingClientRect = () => rect(800, 50, 450);
  document.querySelector<HTMLElement>('header')!.getBoundingClientRect = () => rect(800, 40);
  document.querySelector<HTMLElement>('aside')!.getBoundingClientRect = () => rect(800, 100, 500);
  const viewport = createWorldViewport(stage); const read = viewport.read('600px');
  assert.deepEqual(read.openArea, { top: 0, bottom: 450 });
  assert.equal(read.coveredTopPixels, 40);
  assert.equal(read.previewTop, 500); viewport.destroy();
  band.getBoundingClientRect = () => rect(0, 0);
  const desktop = createWorldViewport(stage);
  assert.equal(desktop.read('600px').openArea, null); desktop.destroy();
});
test('unsized stages wait for a positive box or abort and release their observer', async () => {
  const { document, window } = parseHTML('<main></main>'); const stage = document.querySelector<HTMLElement>('main')!;
  let notify = () => {}; let disconnected = false; const observed: Element[] = [];
  Object.assign(window, { ResizeObserver: class { constructor(callback: () => void) { notify = callback; } observe(element: Element) { observed.push(element); } disconnect() { disconnected = true; } } });
  let width = 0, height = 0; stage.getBoundingClientRect = () => rect(width, height);
  const controller = new AbortController(); let done = false;
  const pending = stageSized(stage, controller.signal)!; pending.then(() => { done = true; });
  assert.deepEqual(observed, [stage]); notify(); await Promise.resolve();
  assert.equal(done, false);
  width = 20; notify(); await Promise.resolve();
  assert.equal(done, false);
  height = 10; notify(); await Promise.resolve();
  assert.equal(done, true); await pending;
  assert.equal(done, true);
  assert.equal(disconnected, true);
  assert.equal(stageSized(stage, controller.signal), null); width = 0; disconnected = false;
  const aborted = stageSized(stage, controller.signal)!; controller.abort(); await aborted;
  assert.equal(disconnected, true);
  assert.equal(stageSized(stage, controller.signal), null);
});
