#!/usr/bin/env node
import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { normalizeDestinationQuery } from "../../../../site/destination-search.mjs";
import { PREPARED_EARTH_SCENE } from "../runtime/preparedScene.mjs";
import { prepareCityPageGeometry } from "./city/page-geometry.mjs";
import { pageCoordinates, prepareLocationPoint, prepareLocationCamera } from "./city/prepare-location.mjs";
import { readWorldCoverCatalog } from "./city/worldcover-catalog.mjs";
import { prepareWmtsCoverage } from "./city/wmts-coverage.mjs";
import { coverageLookup } from "./city/prepare-wmts-tree.mjs";
import { wmtsAddress } from "./city/wmts-page-geometry.mjs";
import { EARTH_PUBLIC_ROOT, ensureEarthPreparationDirectories } from "./preparation-paths.mjs";

const source = new URL("../source/places/", import.meta.url);
const manifest = JSON.parse(await readFile(new URL("manifest.json", source), "utf8"));
for (const entry of manifest.inputs) {
  const bytes = await readFile(new URL(entry.path, source));
  if (bytes.length !== entry.bytes || createHash("sha256").update(bytes).digest("hex") !== entry.sha256) {
    throw new Error(`GeoNames source snapshot drifted: ${entry.path}`);
  }
}
if (process.argv.includes("--verify-only")) {
  console.log("Verified pinned GeoNames place sources.");
  process.exit(0);
}
const lines = value => value.split(/\r?\n/u).filter(line => line && !line.startsWith("#")).map(line => line.split("\t"));
const countries = new Map(lines(await readFile(new URL("countryInfo.txt", source), "utf8")).map(row => [row[0], row[4]]));
const regions = new Map(lines(await readFile(new URL("admin1CodesASCII.txt", source), "utf8")).map(row => [row[0], row[1]]));
const worldcover = await readWorldCoverCatalog();
const hasTile=coverageLookup([prepareWmtsCoverage([...worldcover.entries.values()],14,{includePolar:true})]);
const rows = lines(execFileSync("unzip", ["-p", fileURLToPath(new URL("cities15000.zip", source)), "cities15000.txt"], { encoding: "utf8", maxBuffer: 40 * 1024 * 1024 }));
const places = rows.map(row => {
  if (row.length !== 19 || row[6] !== "P") throw new Error("Invalid GeoNames city record.");
  const latitude = Number(row[4]), longitude = Number(row[5]);
  const country = countries.get(row[8]) ?? row[8];
  const region = regions.get(`${row[8]}.${row[10]}`);
  const context = [...new Set([region, country].filter(Boolean))].join(", ");
  const point = prepareLocationPoint(PREPARED_EARTH_SCENE, longitude, latitude);
  const coverage = Math.abs(latitude)<=85.0511287798066 && hasTile(wmtsAddress(longitude,latitude,14)) ? "detail" : "overview";
  return {
    id: row[0], name: row[1], context,
    names: [...new Set([row[1], row[2], ...row[3].split(",")].map(normalizeDestinationQuery).filter(Boolean))],
    searchContext: normalizeDestinationQuery(`${context} ${row[8]}`),
    population: Number(row[14]), latitude, longitude,
    camera: prepareLocationCamera(PREPARED_EARTH_SCENE, point, coverage === "detail" ? 1024 : 8),
    coverage,
  };
}).sort((a, b) => b.population - a.population || Number(a.id) - Number(b.id));
if (new Set(places.map(place => place.id)).size !== places.length || places.length < 20000) throw new Error("Incomplete city catalogue.");
const catalog = { schema: "cssearth-prepared-destinations@1", source: manifest.source,
  snapshotDate: manifest.snapshotDate, qualification: manifest.qualification, places };
const bytes = Buffer.from(JSON.stringify(catalog) + "\n");
const descriptor = { url: "/scenes/earth/earth-places.json", bytes: bytes.length,
  sha256: createHash("sha256").update(bytes).digest("hex"), count: places.length,
  sourcePage: manifest.sourcePage, license: manifest.license, snapshotDate: manifest.snapshotDate };
await ensureEarthPreparationDirectories();
await writeFile(`${EARTH_PUBLIC_ROOT}/earth-places.json`, bytes);
await writeFile(new URL("../runtime/preparedPlaces.mjs", import.meta.url),
  `// Generated by prepare-places.mjs from the pinned GeoNames snapshot.\nexport const PREPARED_EARTH_PLACES = Object.freeze(${JSON.stringify(descriptor)});\n`);
console.log(`Prepared ${places.length} city destinations (${bytes.length} bytes).`);
