import { readdir, unlink, writeFile } from "node:fs/promises";
import { worldPositionToCss } from "@layoutit/polycss";

import { PREPARED_JUPITER_SCENE } from "../runtime/preparedScene.mjs";

const PUBLIC_OUTPUT_ROOT_URL = new URL(
  "../../../../public/scenes/jupiter/",
  import.meta.url,
);
const responsiveFit = Object.freeze({
  model: "continuous-aspect-smoothstep",
  portraitBaseWidthShare: 0.34,
  narrowPortraitWidthShareGain: 0.08,
  landscapeWidthShareGain: 0.02,
  narrowPortraitAspectRatio: 0.46,
  portraitAspectRatio: 0.75,
  squareAspectRatio: 1,
  maximumHeightShare: 0.61,
  maximumMobilePreviewShare: 0.925,
  minimumZoom: 0.42,
  maximumZoom: 2,
});
const materialDepthPresentation = prepareMaterialDepthPresentation();
const output = Object.freeze({
  schema: "cssjupiter-prepared-camera@6",
  model: "shared-cubic-sky-unbounded-accumulated-matrix3d",
  cameraModel: "accumulated-matrix3d",
  minimumControlPitchDegrees: 0,
  maximumControlPitchDegrees: 89,
  defaultControlPitchDegrees: 34.230769230769226,
  defaultControlYawDegrees: 0,
  materialReferenceControlPitchDegrees: 34.230769230769226,
  materialReferenceControlYawDegrees: 0,
  initialScenePitchDegrees: 40,
  maximumScenePitchDegrees: 65,
  minimumZoom: 0.42,
  maximumZoom: 4,
  defaultZoom: 1.1,
  sceneScale: 0.022,
  logicalBodyDiameter: 460,
  pitchBounded: false,
  yawBounded: false,
  horizontalOrbit: true,
  responsiveFit,
  runtimeMatrixFormatting: true,
  materialDepthPresentation,
});

function prepareMaterialDepthPresentation() {
  const frameSize = 512;
  const rasterSurfaceRadius = 238;
  const depthBias = 0.5;
  const scenePitchDegrees = 40;
  const systemRotationXDegrees =
    PREPARED_JUPITER_SCENE.materialProjection.cssSystemRotationXDegrees;
  const bodyRotationZDegrees =
    PREPARED_JUPITER_SCENE.materialProjection.bodyInitialRotationZDegrees;
  const equatorialRadius = PREPARED_JUPITER_SCENE.geometry.equatorialRadius;
  const polarRadius = PREPARED_JUPITER_SCENE.geometry.polarRadius;
  const screenToObject = (screenVector) => {
    let cssVector = rotateX(screenVector, -scenePitchDegrees);
    cssVector = rotateX(cssVector, -systemRotationXDegrees);
    cssVector = rotateZ(cssVector, -bodyRotationZDegrees);
    return normalize([cssVector[1], cssVector[0], cssVector[2]]);
  };
  const right = screenToObject([1, 0, 0]);
  const down = screenToObject([0, 1, 0]);
  const view = screenToObject([0, 0, 1]);
  const projectedRadius = (direction) => Math.sqrt(
    equatorialRadius ** 2 *
      (direction[0] ** 2 + direction[1] ** 2) +
    polarRadius ** 2 * direction[2] ** 2,
  );
  const frontDepth = projectedRadius(view);
  const texelScale = equatorialRadius / rasterSurfaceRadius;
  const halfExtent = frameSize / 2 * texelScale;
  const basisX = worldPositionToCss(scale(right, texelScale));
  const basisY = worldPositionToCss(scale(down, texelScale));
  const basisZ = worldPositionToCss(view);
  const origin = worldPositionToCss(add(
    scale(right, -halfExtent),
    scale(down, -halfExtent),
    scale(view, frontDepth + depthBias),
  ));
  const leafMatrix = [
    ...basisX, 0,
    ...basisY, 0,
    ...basisZ, 0,
    ...origin, 1,
  ].map(round);
  return Object.freeze({
    model: "prepared-front-depth-biased-camera-facing-material-plane",
    materialSystemTransform: PREPARED_JUPITER_SCENE.systemTransform,
    materialMeshTransform: PREPARED_JUPITER_SCENE.bodyTransform,
    leafTransform: `matrix3d(${leafMatrix.join(",")})`,
    cameraPerspectivePx: 1_000_000,
    frameSize,
    rasterSurfaceRadius,
    scenePitchDegrees,
    frontDepth: Number(frontDepth.toFixed(6)),
    depthBias,
    right: Object.freeze(right.map(round)),
    down: Object.freeze(down.map(round)),
    view: Object.freeze(view.map(round)),
    runtimeDepthMath: false,
    runtimeZoomTransformWrites: false,
  });
}

function rotateX([x, y, z], degrees) {
  const radians = degrees * Math.PI / 180;
  const cosine = Math.cos(radians);
  const sine = Math.sin(radians);
  return [x, y * cosine - z * sine, y * sine + z * cosine];
}

function rotateZ([x, y, z], degrees) {
  const radians = degrees * Math.PI / 180;
  const cosine = Math.cos(radians);
  const sine = Math.sin(radians);
  return [x * cosine - y * sine, x * sine + y * cosine, z];
}

function normalize(vector) {
  const length = Math.hypot(...vector);
  return vector.map((value) => value / length);
}

function scale(vector, amount) {
  return vector.map((value) => value * amount);
}

function add(...vectors) {
  return [0, 1, 2].map((axis) =>
    vectors.reduce((total, vector) => total + vector[axis], 0));
}

function round(value) {
  return Number(value.toFixed(12));
}

await writeFile(
  new URL("../runtime/preparedCamera.mjs", import.meta.url),
  "// Generated by tools/prepare-camera.mjs. Do not edit by hand.\n" +
    `export const PREPARED_JUPITER_CAMERA = ${JSON.stringify(output)};\n`,
);

for (const filename of await readdir(PUBLIC_OUTPUT_ROOT_URL)) {
  if (filename.startsWith("jupiter-camera-orbit-") &&
      filename.endsWith(".bin")) {
    await unlink(new URL(filename, PUBLIC_OUTPUT_ROOT_URL));
  }
}

console.log("Prepared Jupiter shared cubic-sky camera contract.");
