import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import sharp from "sharp";
import { packProjectiveSurfaceRaster } from
  "../../../platform/projective-surface-raster.mjs";

import {
  ensureJupiterPreparationDirectories,
  JUPITER_PUBLIC_ROOT,
  JUPITER_SOURCE_ROOT,
} from "./preparation-paths.mjs";
import { preparePolarContinuationAtlas } from "./prepare-polar-continuation.mjs";
import {
  JUPITER_BODY_LATITUDE_BOUNDS_DEGREES,
  jupiterBodyRasterBands,
} from "./body-raster.mjs";
import { validateJupiterSourceGroup } from "./source-manifest.mjs";

await validateJupiterSourceGroup("lenses");
await ensureJupiterPreparationDirectories();

const OUTPUT_MODULE = new URL("../runtime/preparedLenses.mjs", import.meta.url);
const BODY_WIDTH = 2_048;
const BODY_HEIGHT = 1_024;
const BODY_2X_WIDTH = 4_096;
const BODY_2X_HEIGHT = 2_048;
const POLAR_TILE_SIZE = 256;
const POLAR_OVERLAP = 1.035;
const POLAR_BOUNDARY_LATITUDE_DEGREES = 64;
const NORTH_POLAR_STRUCTURE_PATH = resolve(
  JUPITER_SOURCE_ROOT,
  "surface/juno-pia23808-north-polar-projection.jpg",
);
const SOUTH_POLAR_STRUCTURE_PATH = resolve(
  JUPITER_SOURCE_ROOT,
  "surface/juno-pia23556-south-polar-cyclones.jpg",
);
const BODY_LATITUDE_BOUNDS_DEGREES = JUPITER_BODY_LATITUDE_BOUNDS_DEGREES;
const plans = Object.freeze([
  Object.freeze({
    id: "ultraviolet",
    label: "Ultraviolet",
    shortLabel: "UV",
    filter: "F275W",
    wavelength: "275 nm",
    source: "lenses/hlsp_opal_hst_wfc3-uvis_jupiter-2025a_f275w_v1_globalmap.fits",
    measurement: "Hubble WFC3 F275W ultraviolet reflectance",
    palette: Object.freeze([[8, 7, 31], [78, 50, 143], [229, 216, 255]]),
    qualification: "F275W single-band Hubble OPAL data with declared false color and Juno-structured continuation beyond measured polar coverage",
  }),
  Object.freeze({
    id: "methane",
    label: "Methane",
    shortLabel: "CH4",
    filter: "FQ889N",
    wavelength: "889 nm",
    source: "lenses/hlsp_opal_hst_wfc3-uvis_jupiter-2025a_fq889n_v1_globalmap.fits",
    measurement: "Hubble WFC3 FQ889N methane-band reflectance",
    palette: Object.freeze([[2, 15, 19], [18, 89, 100], [201, 248, 239]]),
    qualification: "FQ889N single-band Hubble OPAL data with declared false color and Juno-structured continuation beyond measured polar coverage",
  }),
]);

const controls = [Object.freeze({
  id: "normal",
  label: "Normal",
  shortLabel: "RGB",
  measurement: "Hubble WFC3 visible-color global map",
  thumbnailUrl: "/scenes/jupiter/jupiter-lens-normal.webp",
  surfaceUrl: "/scenes/jupiter/jupiter-surface.webp",
  surface2xUrl: "/scenes/jupiter/jupiter-surface@2x.webp",
  polesUrl: "/scenes/jupiter/jupiter-poles.webp",
  poles2xUrl: "/scenes/jupiter/jupiter-poles@2x.webp",
  falseColor: false,
  qualification: "NASA/ESA Hubble WFC3 395, 502, and 631 nm visible-color map",
})];
const spectralPolarStructures = Object.freeze({
  north: await sharp(NORTH_POLAR_STRUCTURE_PATH)
    .removeAlpha()
    .resize(POLAR_TILE_SIZE * 2, POLAR_TILE_SIZE * 2, { fit: "fill" })
    .raw()
    .toBuffer({ resolveWithObject: true }),
  south: await sharp(SOUTH_POLAR_STRUCTURE_PATH)
    .removeAlpha()
    .extract({ left: 875, top: 0, width: 2_249, height: 2_249 })
    .resize(POLAR_TILE_SIZE * 2, POLAR_TILE_SIZE * 2, { fit: "fill" })
    .raw()
    .toBuffer({ resolveWithObject: true }),
});
await prepareThumbnail(
  resolve(JUPITER_PUBLIC_ROOT, "jupiter-surface.webp"),
  resolve(JUPITER_PUBLIC_ROOT, "jupiter-lens-normal.webp"),
);
for (const plan of plans) controls.push(await prepareLens(plan));

const descriptor = Object.freeze({
  schema: "cssjupiter-prepared-lenses@1",
  defaultLens: "normal",
  runtimeFilters: false,
  runtimeRasterization: false,
  controls: Object.freeze(controls),
  provenance: Object.freeze({
    normalAuthority: "NASA/ESA Hubble WFC3 Jupiter global map, 27 June 2019",
    spectralAuthority: "Hubble OPAL Cycle 32 Jupiter global maps, 11 December 2025",
    spectralSourceUrl: "https://archive.stsci.edu/hlsp/opal/opal-jupiter-cycle-32",
    falseColorMethod: "prepared percentile stretch into declared three-stop palettes",
    runtimeAuthorityRequests: false,
  }),
});
await writeFile(
  OUTPUT_MODULE,
  "// Generated by tools/prepare-lenses.mjs. Do not edit by hand.\n" +
    `export const PREPARED_JUPITER_LENSES = ${JSON.stringify(descriptor)};\n`,
);
console.log(`Prepared ${controls.length} Jupiter surface lenses.`);

async function prepareLens(plan) {
  const sourceBytes = await readFile(resolve(JUPITER_SOURCE_ROOT, plan.source));
  const source = readFitsPrimary(sourceBytes);
  if (source.width !== 3_600 || source.height !== 1_800) {
    throw new Error(`${plan.label} Jupiter OPAL map dimensions changed.`);
  }
  const complete = fillCoverage(source);
  const [minimum, maximum] = finitePercentiles(complete.values, 0.01, 0.995);
  const rgba = falseColorMap(complete, plan.palette, minimum, maximum);
  const source2x = await sharp(rgba, {
    raw: { width: complete.width, height: complete.height, channels: 4 },
  }).resize(BODY_2X_WIDTH, BODY_2X_HEIGHT, { fit: "fill" })
    .raw().toBuffer({ resolveWithObject: true });
  const source1x = await sharp(source2x.data, { raw: source2x.info })
    .resize(BODY_WIDTH, BODY_HEIGHT, { fit: "fill" })
    .raw().toBuffer({ resolveWithObject: true });
  const surfacePath = resolve(JUPITER_PUBLIC_ROOT, `jupiter-lens-${plan.id}.webp`);
  const surface2xPath = resolve(
    JUPITER_PUBLIC_ROOT,
    `jupiter-lens-${plan.id}@2x.webp`,
  );
  await Promise.all([
    writeProjectiveSurface(source1x, surfacePath),
    writeProjectiveSurface(source2x, surface2xPath),
  ]);
  const polar = preparePolarContinuationAtlas({
    source: source2x,
    tileSize: POLAR_TILE_SIZE * 2,
    firstMeasuredRow: complete.firstMeasuredRow,
    lastMeasuredRow: complete.lastMeasuredRow,
    measuredHeight: complete.height,
    overlap: POLAR_OVERLAP,
    measuredProjectionEdgeLatitudeDegrees: POLAR_BOUNDARY_LATITUDE_DEGREES,
    polarDetails: Object.freeze({
      north: Object.freeze({
        structure: spectralPolarStructures.north,
        palette: source2x,
        contrast: 0.2,
        tint: 0,
        structureRadius: 0.9,
      }),
      south: Object.freeze({
        structure: spectralPolarStructures.south,
        palette: source2x,
        contrast: 0.18,
        tint: 0,
        structureRadius: 0.9,
      }),
    }),
    detailBlendStartRadius: 0.08,
    detailBlendEndRadius: 0.96,
    edgeStructureWeight: 0.3,
    alphaOpaqueRadius: 0.43,
    alphaTransparentRadius: 0.96,
  });
  const polesPath = resolve(JUPITER_PUBLIC_ROOT, `jupiter-lens-${plan.id}-poles.webp`);
  const poles2xPath = resolve(
    JUPITER_PUBLIC_ROOT,
    `jupiter-lens-${plan.id}-poles@2x.webp`,
  );
  await Promise.all([
    sharp(polar.data, {
      raw: { width: polar.width, height: polar.height, channels: 4 },
    }).resize(POLAR_TILE_SIZE * 2, POLAR_TILE_SIZE)
      .webp({ quality: 90, alphaQuality: 100, effort: 6, smartSubsample: true })
      .toFile(polesPath),
    sharp(polar.data, {
      raw: { width: polar.width, height: polar.height, channels: 4 },
    }).webp({ quality: 90, alphaQuality: 100, effort: 6, smartSubsample: true })
      .toFile(poles2xPath),
  ]);
  const thumbnailPath = resolve(
    JUPITER_PUBLIC_ROOT,
    `jupiter-lens-${plan.id}-thumbnail.webp`,
  );
  await prepareThumbnail(surfacePath, thumbnailPath);
  const assets = await Promise.all([
    surfacePath,
    surface2xPath,
    polesPath,
    poles2xPath,
    thumbnailPath,
  ].map((path) => readFile(path)));
  return Object.freeze({
    id: plan.id,
    label: plan.label,
    shortLabel: plan.shortLabel,
    filter: plan.filter,
    wavelength: plan.wavelength,
    measurement: plan.measurement,
    thumbnailUrl: `/scenes/jupiter/jupiter-lens-${plan.id}-thumbnail.webp`,
    surfaceUrl: `/scenes/jupiter/jupiter-lens-${plan.id}.webp`,
    surface2xUrl: `/scenes/jupiter/jupiter-lens-${plan.id}@2x.webp`,
    polesUrl: `/scenes/jupiter/jupiter-lens-${plan.id}-poles.webp`,
    poles2xUrl: `/scenes/jupiter/jupiter-lens-${plan.id}-poles@2x.webp`,
    falseColor: true,
    qualification: plan.qualification,
    coveragePreparation: Object.freeze({
      model: polar.model,
      firstMeasuredRow: complete.firstMeasuredRow,
      lastMeasuredRow: complete.lastMeasuredRow,
      projectionEdgeLatitudeDegrees:
        polar.measuredProjectionEdgeLatitudeDegrees,
      bodyLatitudeBoundsDegrees: BODY_LATITUDE_BOUNDS_DEGREES,
      unmeasuredCoreRadius: polar.unmeasuredCoreRadius,
      polarProjectionAngularSamples: polar.polarProjectionAngularSamples,
      unmeasuredCoreHarmonicOrder: polar.unmeasuredCoreHarmonicOrder,
      detailedPoles: polar.detailedPoles,
      structuralAuthority: Object.freeze({
        north: "NASA Juno PIA23808",
        south: "NASA Juno JIRAM PIA23556",
      }),
      structuralDetailMeasurement: false,
      spectralColorAuthority: plan.measurement,
      runtimeCoverageRepair: false,
    }),
    sourceFile: plan.source,
    sourceSha256: createHash("sha256").update(sourceBytes).digest("hex"),
    sourceRange: Object.freeze([minimum, maximum].map((value) =>
      Number(value.toPrecision(8)))),
    assetSha256: Object.freeze({
      surface: digest(assets[0]),
      surface2x: digest(assets[1]),
      poles: digest(assets[2]),
      poles2x: digest(assets[3]),
      thumbnail: digest(assets[4]),
    }),
  });
}

function readFitsPrimary(bytes) {
  let offset = 0;
  const header = new Map();
  while (offset + 80 <= bytes.length) {
    const card = bytes.subarray(offset, offset + 80).toString("ascii");
    offset += 80;
    const key = card.slice(0, 8).trim();
    if (key === "END") break;
    if (card.slice(8, 10) !== "= ") continue;
    header.set(key, card.slice(10).split("/")[0].trim().replace(/^'|'$/gu, ""));
  }
  offset = Math.ceil(offset / 2_880) * 2_880;
  const bitpix = Number(header.get("BITPIX"));
  const width = Number(header.get("NAXIS1"));
  const height = Number(header.get("NAXIS2"));
  if (bitpix !== -32 || !Number.isSafeInteger(width) || !Number.isSafeInteger(height)) {
    throw new Error("Hubble OPAL FITS primary image schema changed.");
  }
  const values = new Float32Array(width * height);
  const view = new DataView(bytes.buffer, bytes.byteOffset + offset, values.length * 4);
  for (let index = 0; index < values.length; index += 1) {
    values[index] = view.getFloat32(index * 4, false);
  }
  return Object.freeze({ width, height, values });
}

function fillCoverage(source) {
  const values = new Float32Array(source.values);
  const rowValid = new Uint8Array(source.height);
  for (let row = 0; row < source.height; row += 1) {
    let validCount = 0;
    for (let column = 0; column < source.width; column += 1) {
      const value = values[row * source.width + column];
      if (Number.isFinite(value) && value > 0) validCount += 1;
    }
    rowValid[row] = Number(validCount === source.width);
  }
  let first = 0;
  while (first < source.height && !rowValid[first]) first += 1;
  let last = source.height - 1;
  while (last >= 0 && !rowValid[last]) last -= 1;
  if (first >= last) throw new Error("Hubble OPAL map lost global coverage.");
  for (let row = first; row <= last; row += 1) {
    const validColumns = [];
    for (let column = 0; column < source.width; column += 1) {
      const index = row * source.width + column;
      if (Number.isFinite(values[index]) && values[index] > 0) {
        validColumns.push(column);
      }
    }
    if (validColumns.length === 0) continue;
    for (let validIndex = 0;
      validIndex < validColumns.length;
      validIndex += 1) {
      const left = validColumns[validIndex];
      const right = validColumns[(validIndex + 1) % validColumns.length];
      const span = (right - left + source.width) % source.width;
      if (span <= 1) continue;
      const leftValue = values[row * source.width + left];
      const rightValue = values[row * source.width + right];
      for (let offset = 1; offset < span; offset += 1) {
        const amount = offset / span;
        const column = (left + offset) % source.width;
        values[row * source.width + column] =
          leftValue * (1 - amount) + rightValue * amount;
      }
    }
  }
  convergePolarCoverage(values, source.width, source.height, first, true);
  convergePolarCoverage(values, source.width, source.height, last, false);
  return Object.freeze({
    width: source.width,
    height: source.height,
    values,
    firstMeasuredRow: first,
    lastMeasuredRow: last,
  });
}

function convergePolarCoverage(values, width, height, measuredRow, north) {
  const poleRow = north ? 0 : height - 1;
  const distance = Math.abs(measuredRow - poleRow);
  const inwardDirection = north ? 1 : -1;
  const lookbackRows = Math.max(1, Math.round(height * 0.5 / 180));
  const longitudeBand = new Float64Array(width);
  let bandRows = 0;
  for (let offset = 0; offset <= lookbackRows; offset += 1) {
    const row = measuredRow + offset * inwardDirection;
    if (row < 0 || row >= height) continue;
    for (let column = 0; column < width; column += 1) {
      longitudeBand[column] += values[row * width + column];
    }
    bandRows += 1;
  }
  for (let column = 0; column < width; column += 1) {
    longitudeBand[column] /= bandRows;
  }
  const prefix = new Float64Array(width * 2 + 1);
  for (let index = 0; index < width * 2; index += 1) {
    prefix[index + 1] = prefix[index] + longitudeBand[index % width];
  }
  const start = north ? 0 : measuredRow + 1;
  const end = north ? measuredRow : height;
  for (let row = start; row < end; row += 1) {
    const normalized = distance === 0
      ? 1
      : Math.abs(row - poleRow) / distance;
    const windowRadius = Math.min(
      Math.floor((width - 1) / 2),
      Math.round((1 - normalized ** 2) * (width - 1) / 2),
    );
    for (let column = 0; column < width; column += 1) {
      let sampleStart = column - windowRadius;
      while (sampleStart < 0) sampleStart += width;
      const sampleEnd = sampleStart + windowRadius * 2 + 1;
      values[row * width + column] =
        (prefix[sampleEnd] - prefix[sampleStart]) /
        (sampleEnd - sampleStart);
    }
  }
  const edgeTransitionRows = 24;
  for (let offset = 0; offset < edgeTransitionRows; offset += 1) {
    const row = measuredRow + offset * inwardDirection;
    const measuredWeight = smootherStep(offset / (edgeTransitionRows - 1));
    for (let column = 0; column < width; column += 1) {
      const index = row * width + column;
      values[index] = longitudeBand[column] * (1 - measuredWeight) +
        values[index] * measuredWeight;
    }
  }

  function smootherStep(value) {
    const amount = Math.max(0, Math.min(1, value));
    return amount * amount * amount * (amount * (amount * 6 - 15) + 10);
  }
}

function finitePercentiles(values, lower, upper) {
  const finite = [...values].filter((value) => Number.isFinite(value) && value > 0)
    .sort((left, right) => left - right);
  if (finite.length < values.length * 0.5) throw new Error("OPAL coverage is incomplete.");
  return [
    finite[Math.floor((finite.length - 1) * lower)],
    finite[Math.floor((finite.length - 1) * upper)],
  ];
}

function falseColorMap(source, palette, minimum, maximum) {
  const output = Buffer.alloc(source.width * source.height * 4);
  for (let index = 0; index < source.values.length; index += 1) {
    const amount = Math.max(0, Math.min(1,
      (source.values[index] - minimum) / (maximum - minimum)));
    const color = samplePalette(palette, Math.sqrt(amount));
    const offset = index * 4;
    output[offset] = color[0];
    output[offset + 1] = color[1];
    output[offset + 2] = color[2];
    output[offset + 3] = 255;
  }
  return output;
}

function samplePalette(palette, amount) {
  const scaled = amount * (palette.length - 1);
  const index = Math.min(palette.length - 2, Math.floor(scaled));
  const local = scaled - index;
  return [0, 1, 2].map((channel) => Math.round(
    palette[index][channel] * (1 - local) + palette[index + 1][channel] * local,
  ));
}

async function writeProjectiveSurface(source, outputPath) {
  const { width, height, channels } = source.info;
  const packed = packProjectiveSurfaceRaster(source.data, {
    width,
    height,
    channels,
    bands: jupiterBodyRasterBands(height),
    gutter: 16 * height / BODY_HEIGHT,
  });
  await sharp(packed.data, { raw: {
    width: packed.packedWidth,
    height: packed.packedHeight,
    channels,
  } })
    .webp({ quality: 90, effort: 6, smartSubsample: true })
    .toFile(outputPath);
}

async function prepareThumbnail(inputPath, outputPath) {
  await sharp(inputPath)
    .resize(132, 72, { fit: "cover", position: "centre" })
    .webp({ quality: 82, effort: 6 })
    .toFile(outputPath);
}

function digest(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}
