import assert from'node:assert/strict';
import{sourceTest}from'../../../../../tests/objects/source-test.mts';import { astroqueryToolchain } from '@cssearth/telescope/node';const test=sourceTest();test.before(async()=>{await astroqueryToolchain();});
import{mkdtemp,readFile,rm,writeFile}from'node:fs/promises';
import{tmpdir}from'node:os';
import{resolve}from'node:path';
import{executeFamilyOperation}from'../../family-operation.mts';
import{operationsForDescriptor}from'../../family-handlers.mts';
import{planetaryOutputPolicy}from'../../planetary-depth-policy.mts';
import{member}from'../common.mts';
import{describePlanetaryDepthGrid,inspectPlanetaryDepthGrid,parsePlanetaryGridQualification,PLANETARY_GRID_QUALIFICATION_SCHEMA}from'./f16-planetary-depth.mts';

const card=(key:string,value?:string)=>value===undefined?key.padEnd(80):`${key.padEnd(8)}= ${value}`.padEnd(80);
function fits(unit3='us',extra:readonly string[]=[]){
  const cards=[card('SIMPLE','                    T'),card('BITPIX','                  -32'),card('NAXIS','                    3'),card('NAXIS1','                    4'),card('NAXIS2','                    3'),card('NAXIS3','                    2'),card('CUNIT1',"                 'km'"),card('CRVAL1','                    0'),card('CRPIX1','                    1'),card('CDELT1','                    2'),card('CUNIT2',"                 'km'"),card('CRVAL2','                   10'),card('CRPIX2','                    1'),card('CDELT2','                    3'),card('CUNIT3',`                 '${unit3}'`),card('CRVAL3','                    0'),card('CRPIX3','                    1'),card('CDELT3','               0.0375'),card('BUNIT',"                  '1'"),...extra,card('END')].join(''),header=Buffer.from(cards.padEnd(Math.ceil(cards.length/2880)*2880,' ')),data=Buffer.alloc(24*4);for(let index=0;index<24;index++)data.writeFloatBE(index===13?Number.NaN:index,index*4);return Buffer.concat([header,data,Buffer.alloc((2880-data.length%2880)%2880)]);
}
const qualification=()=>({schema:PLANETARY_GRID_QUALIFICATION_SCHEMA,source:{archiveIdentity:'archive:test-grid',sourceUrl:'https://example.invalid/archive/test-grid',citation:'Synthetic architecture fixture.',license:'CC0-1.0'},sourceClassification:{term:'planetary coordinate grid',vocabulary:'test archive profile',version:'1',status:'mapped' as const},frame:{kind:'projected-body-fixed',name:'test body frame'},quantity:{name:'radar return strength',semantics:'Synthetic scalar used only to test the qualification boundary.',unit:'1'},calibration:{state:'reconstructed' as const,basis:['Synthetic published reconstruction fixture.']},uncertainty:{form:'unknown' as const,basis:'No uncertainty array is supplied by the synthetic fixture.'},axes:[{fitsAxis:1,role:'projected-x' as const,physicalType:'length' as const,unit:'km',reference:'test projection origin',derivation:{state:'archive-derived' as const,assumptions:[]}},{fitsAxis:2,role:'projected-y' as const,physicalType:'length' as const,unit:'km',reference:'test projection origin',derivation:{state:'archive-derived' as const,assumptions:[]}},{fitsAxis:3,role:'delay' as const,physicalType:'time' as const,unit:'us',reference:'two-way delay from the synthetic surface echo',derivation:{state:'observed' as const,assumptions:[]}}],support:{class:'published-reconstruction' as const,domain:{kind:'full-grid' as const,description:'Synthetic reconstructed grid cells.',memberIds:['role:science']},unsupportedRegions:[]},depth:{coordinate:'delay' as const,positiveDirection:'down' as const,datum:'synthetic surface echo',conversion:{state:'unavailable' as const,parameters:[],uncertainty:'No dielectric model is supplied.'}},observability:{measurementOperator:'radar-propagation' as const,coverage:{kind:'tracks' as const,description:'Synthetic contributing tracks.',memberIds:['role:response']},localization:'inversion-dependent' as const},resolution:{state:'estimated' as const,elements:[{axisId:'projected-x',range:[.3,3] as const,unit:'km',description:'Synthetic published response width.'},{axisId:'delay',value:.08,unit:'us',description:'Synthetic pulse response.'}],basis:'Synthetic resolution evidence, deliberately independent of coordinate intervals.',memberIds:['role:response']},inference:{kind:'archive-published' as const,method:'Synthetic archive reconstruction.',assumptions:['No physical claim; architecture test only.'],validation:'The test checks byte, axis, and policy invariants.',memberIds:['role:provenance']}});

test('source-qualified FITS grid publishes semantics and executes through the public dispatcher',async()=>{const root=await mkdtemp(resolve(tmpdir(),'planetary-grid-'));try{const science=fits(),response=Buffer.from('synthetic track closure'),provenance=Buffer.from('synthetic reconstruction record'),sciencePath=resolve(root,'grid.fits');await writeFile(sciencePath,science);await writeFile(resolve(root,'tracks.txt'),response);await writeFile(resolve(root,'method.txt'),provenance);const parsed=parsePlanetaryGridQualification(qualification()),inspection=await inspectPlanetaryDepthGrid({path:sciencePath},parsed);assert.deepEqual(inspection.shape,[4,3,2]);assert.equal(inspection.finiteSamples,23);const product=describePlanetaryDepthGrid({id:'synthetic-depth-grid',members:[member('science','grid.fits','science',science,'application/fits'),member('tracks','tracks.txt','response',response,'text/plain'),member('method','method.txt','provenance',provenance,'text/plain')],scienceMemberId:'science',qualification:parsed,inspection,producingRecord:'synthetic-test',target:'synthetic-body'}),component=product.components[0]!;assert.equal(component.sampling?.axes[0]?.interval,2);assert.equal(component.resolution?.elements[0]?.range?.[1],3);assert.equal(component.inference?.method,'Synthetic archive reconstruction.');assert.equal(planetaryOutputPolicy(component).find(value=>value.output==='body-attachment')?.available,false);const operations=operationsForDescriptor(product),sliceOperation=operations.find(value=>value.id==='depth-grid-slice')!;assert.equal(sliceOperation.available,true);assert.deepEqual(sliceOperation.parameters.find(value=>value.id==='axis')?.choices,['projected-x','projected-y','delay']);const masked={...product,components:[{...component,support:{...component.support!,unsupportedRegions:[{kind:'mask' as const,description:'external mask',memberId:'tracks'}]}}]},maskedSlice=operationsForDescriptor(masked).find(value=>value.id==='depth-grid-slice')!;assert.equal(maskedSlice.available,false);assert.match(maskedSlice.reason,/mask geometry/u);const descriptorPath=resolve(root,'descriptor.json');await writeFile(descriptorPath,JSON.stringify(product));const result=await executeFamilyOperation(descriptorPath,{operationId:'depth-grid-slice',axis:'delay',index:1},resolve(root,'slice')),slice=JSON.parse(await readFile(result.product,'utf8'));assert.deepEqual(slice.slice.shape,[4,3]);assert.deepEqual(slice.slice.axes,['projected-x','projected-y']);assert.equal(slice.slice.values.length,12);assert.equal(slice.slice.valid.filter(Boolean).length,11);}finally{await rm(root,{recursive:true,force:true});}});

test('Astropy WCS normalizes diagonal CD coordinates and physically equivalent axis units to the zero-based shared grid',async()=>{const root=await mkdtemp(resolve(tmpdir(),'planetary-grid-wcs-'));try{const bytes=fits('ns',[card('CUNIT1',"                  'm'"),card('CRVAL1','                 4000'),card('CRPIX1','                    2'),card('CD1_1','                 2000'),card('CUNIT2',"                  'm'"),card('CRVAL2','                10000'),card('CD2_2','                 3000'),card('CRVAL3','                75000'),card('CRPIX3','                    2'),card('CD3_3','                37500')]),path=resolve(root,'grid.fits');await writeFile(path,bytes);const inspection=await inspectPlanetaryDepthGrid({path},parsePlanetaryGridQualification(qualification()));assert.deepEqual(inspection.axes.map(axis=>axis.unit),['km','km','us']);assert.deepEqual(inspection.axes.map(axis=>axis.referenceIndex),[0,0,0]);assert.deepEqual(inspection.axes.map(axis=>axis.referenceValue),[2,10,37.5]);assert.deepEqual(inspection.axes.map(axis=>axis.increment),[2,3,37.5]);const x=inspection.axes[0]!;assert.deepEqual([x.referenceValue,x.referenceValue+2*x.increment,x.referenceValue+3*x.increment],[2,6,8]);}finally{await rm(root,{recursive:true,force:true});}});

test('FITS ownership refuses incompatible physical dimensions, coupled WCS axes, and nonlinear WCS coordinates',async()=>{const root=await mkdtemp(resolve(tmpdir(),'planetary-grid-refuse-'));try{const check=async(name:string,bytes:Buffer,context:unknown=qualification(),pattern=/physical dimension/u)=>{const path=resolve(root,name);await writeFile(path,bytes);await assert.rejects(inspectPlanetaryDepthGrid({path},parsePlanetaryGridQualification(context)),pattern);};await check('unit.fits',fits('m'));const invalidQualified={...qualification(),axes:[...qualification().axes.slice(0,2),{...qualification().axes[2]!,role:'geometric-depth' as const,physicalType:'length' as const}],depth:{...qualification().depth,coordinate:'geometric-depth' as const,conversion:{state:'native' as const,parameters:[],uncertainty:'Synthetic native depth coordinate.'}}};await check('qualified-role.fits',fits(),invalidQualified,/Qualified planetary axis unit/u);await check('coupled.fits',fits('us',[card('PC1_2','                  0.5')]),qualification(),/coupled WCS/u);await check('nonlinear.fits',fits('us',[card('CTYPE1',"          'RA---TAN'"),card('CTYPE2',"          'DEC--TAN'"),card('CUNIT1',"                'deg'"),card('CUNIT2',"                'deg'")]),qualification(),/nonlinear or unsupported WCS CTYPE/u);}finally{await rm(root,{recursive:true,force:true});}});

test('slice refuses every support geometry it cannot apply, including domain and same-member masks',async()=>{const root=await mkdtemp(resolve(tmpdir(),'planetary-grid-mask-'));try{const science=fits(),response=Buffer.from('synthetic track closure'),provenance=Buffer.from('synthetic reconstruction record'),path=resolve(root,'grid.fits');await writeFile(path,science);const inspection=await inspectPlanetaryDepthGrid({path},parsePlanetaryGridQualification(qualification())),product=describePlanetaryDepthGrid({id:'synthetic-depth-grid',members:[member('science','grid.fits','science',science,'application/fits'),member('tracks','tracks.txt','response',response,'text/plain'),member('method','method.txt','provenance',provenance,'text/plain')],scienceMemberId:'science',qualification:qualification(),inspection,producingRecord:'synthetic-test',target:'synthetic-body'}),component=product.components[0]!,available=(value:typeof product)=>operationsForDescriptor(value).find(operation=>operation.id==='depth-grid-slice')!;const domain={...product,components:[{...component,support:{...component.support!,domain:{...component.support!.domain,kind:'mask' as const,memberIds:['tracks']}}}]};assert.equal(available(domain).available,false);assert.match(available(domain).reason,/support-domain geometry/u);const sameMember={...product,components:[{...component,support:{...component.support!,unsupportedRegions:[{kind:'mask' as const,description:'mask in science HDU',memberId:'science'}]}}]};assert.equal(available(sameMember).available,false);assert.match(available(sameMember).reason,/mask geometry/u);}finally{await rm(root,{recursive:true,force:true});}});

test('qualification refuses an implicit physical-depth conversion and incomplete resolution evidence',()=>{const base=qualification();assert.throws(()=>parsePlanetaryGridQualification({...base,depth:{...base.depth,conversion:{state:'derived',parameters:[],uncertainty:'unknown'}}}),/requires a method/u);assert.throws(()=>parsePlanetaryGridQualification({...base,resolution:{...base.resolution,memberIds:[]}}),/evidence member/u);});

test('source qualification carries validated placement into the published descriptor',async()=>{const root=await mkdtemp(resolve(tmpdir(),'planetary-grid-placement-'));try{const science=fits('km'),path=resolve(root,'grid.fits'),base=qualification(),qualified={...base,axes:[...base.axes.slice(0,2),{...base.axes[2]!,role:'geometric-depth' as const,physicalType:'length' as const,unit:'km',reference:'synthetic vertical datum'}],depth:{coordinate:'geometric-depth' as const,positiveDirection:'down' as const,datum:'synthetic vertical datum',conversion:{state:'native' as const,parameters:[],uncertainty:'Native archive coordinate.'}},placement:{kind:'projected-vertical' as const,projectedXAxisId:'projected-x',projectedYAxisId:'projected-y',verticalAxisId:'geometric-depth',projection:'synthetic projected body frame',verticalDatum:'synthetic vertical datum',basis:'Synthetic source qualification.'},resolution:{...base.resolution,elements:base.resolution.elements.filter(element=>element.axisId!=='delay')}};await writeFile(path,science);const parsed=parsePlanetaryGridQualification(qualified),inspection=await inspectPlanetaryDepthGrid({path},parsed),response=Buffer.from('response'),provenance=Buffer.from('provenance'),product=describePlanetaryDepthGrid({id:'placed-grid',members:[member('science','grid.fits','science',science,'application/fits'),member('tracks','tracks.txt','response',response,'text/plain'),member('method','method.txt','provenance',provenance,'text/plain')],scienceMemberId:'science',qualification:parsed,inspection,producingRecord:'synthetic-test',target:'synthetic-body'});assert.deepEqual(product.components[0]?.placement,parsed.placement);assert.equal(planetaryOutputPolicy(product.components[0]!).find(value=>value.output==='body-attachment')?.available,true);}finally{await rm(root,{recursive:true,force:true});}});
