// Generated by tools/generate-comets.mjs. Do not edit.
// JPL Horizons, heliocentric ICRF; epoch 2026-09-03. TDB is approximated as TT (under 2 ms).
export const COMET_FIXTURES = {
  "comet-67p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D67P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=VECTORS&CENTER=%27500%4010%27&TLIST=2461256.5%2C2461286.5%2C2461316.5&TLIST_TYPE=JD&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&VEC_TABLE=2&VEC_CORR=NONE&CSV_FORMAT=YES",
    "rows": [
      {
        "jd": 2461256.5,
        "position": [
          -54363376.75841478,
          -633249080.981398,
          -314089114.3692114
        ],
        "velocity": [
          806355.7018793554,
          442461.4638473794,
          185149.4815071019
        ]
      },
      {
        "jd": 2461286.5,
        "position": [
          -30113288.08054335,
          -619170266.1667022,
          -308134907.108565
        ],
        "velocity": [
          810010.8116800061,
          496567.9829920794,
          212032.1432715231
        ]
      },
      {
        "jd": 2461316.5,
        "position": [
          -5782557.791161827,
          -603426958.3985895,
          -301352280.3019254
        ],
        "velocity": [
          811681.2329729253,
          553480.0198917506,
          240405.9587713359
        ]
      }
    ]
  },
  "comet-103p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D103P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=VECTORS&CENTER=%27500%4010%27&TLIST=2461256.5%2C2461286.5%2C2461316.5&TLIST_TYPE=JD&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&VEC_TABLE=2&VEC_CORR=NONE&CSV_FORMAT=YES",
    "rows": [
      {
        "jd": 2461256.5,
        "position": [
          -710643762.4963741,
          -452912361.9688184,
          -214684360.8473913
        ],
        "velocity": [
          216762.1459988934,
          -563496.8826080211,
          -95280.33217590419
        ]
      },
      {
        "jd": 2461286.5,
        "position": [
          -703662494.3584697,
          -469508002.2185178,
          -217397325.2744258
        ],
        "velocity": [
          248534.3346111468,
          -542799.9830680682,
          -85584.77871267649
        ]
      },
      {
        "jd": 2461316.5,
        "position": [
          -695738718.0410869,
          -485475537.39926,
          -219819429.6276576
        ],
        "velocity": [
          279605.3494228403,
          -521620.9799722568,
          -75887.69068474448
        ]
      }
    ]
  },
  "comet-9p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D9P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=VECTORS&CENTER=%27500%4010%27&TLIST=2461256.5%2C2461286.5%2C2461316.5&TLIST_TYPE=JD&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&VEC_TABLE=2&VEC_CORR=NONE&CSV_FORMAT=YES",
    "rows": [
      {
        "jd": 2461256.5,
        "position": [
          -227158967.2779018,
          466451012.9085498,
          287343754.7532659
        ],
        "velocity": [
          -758908.1191943373,
          -824273.6536382667,
          -285704.6039926552
        ]
      },
      {
        "jd": 2461286.5,
        "position": [
          -249416233.7544568,
          440720650.7538041,
          278148337.8823496
        ],
        "velocity": [
          -723894.3455112666,
          -891328.1179585963,
          -327643.2237266673
        ]
      },
      {
        "jd": 2461316.5,
        "position": [
          -270527450.5695975,
          412956969.8282983,
          267665308.9074917
        ],
        "velocity": [
          -682356.7390222584,
          -959816.3147267728,
          -371567.2224049019
        ]
      }
    ]
  },
  "comet-81p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D81P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=VECTORS&CENTER=%27500%4010%27&TLIST=2461256.5%2C2461286.5%2C2461316.5&TLIST_TYPE=JD&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&VEC_TABLE=2&VEC_CORR=NONE&CSV_FORMAT=YES",
    "rows": [
      {
        "jd": 2461256.5,
        "position": [
          778210012.8942435,
          91552956.8816794,
          2636098.359600365
        ],
        "velocity": [
          -216338.8088429217,
          696563.5472781288,
          277926.4226605412
        ]
      },
      {
        "jd": 2461286.5,
        "position": [
          770997401.9409511,
          112357815.8519602,
          10968714.54258531
        ],
        "velocity": [
          -264561.82332631,
          690193.1908750265,
          277493.5647907647
        ]
      },
      {
        "jd": 2461316.5,
        "position": [
          762332396.0511973,
          132950228.9036938,
          19280351.98534697
        ],
        "velocity": [
          -313175.0634476502,
          682390.1262643285,
          276524.2711845424
        ]
      }
    ]
  }
} as const
