// Generated by tools/generate-asteroids.mjs. Do not edit.
// JPL Horizons, heliocentric ICRF; epoch 2026-09-04. TDB is approximated as TT (under 2 ms).
export const ASTEROID_FIXTURES = {
  "vesta": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%274%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=VECTORS&CENTER=%27500%4010%27&TLIST=2461256.5%2C2461286.5%2C2461316.5&TLIST_TYPE=JD&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&VEC_TABLE=2&VEC_CORR=NONE&CSV_FORMAT=YES",
    "rows": [
      {
        "jd": 2461256.5,
        "position": [
          356786405.8965065,
          26377354.08200404,
          -36233467.2627997
        ],
        "velocity": [
          94199.98870846185,
          1529588.692382679,
          597559.4801138185
        ]
      },
      {
        "jd": 2461286.5,
        "position": [
          356228602.0956475,
          71871380.56799431,
          -18020226.42748141
        ],
        "velocity": [
          -130007.7660674915,
          1498764.992879134,
          614649.0560691417
        ]
      },
      {
        "jd": 2461316.5,
        "position": [
          349084842.8622935,
          116041026.2088699,
          527955.6154189573
        ],
        "velocity": [
          -344345.2300033337,
          1441721.301175407,
          619990.2614373824
        ]
      }
    ]
  }
} as const
