// Generated by tools/generate-comets.mjs. Do not edit.
// JPL Horizons, heliocentric ICRF; epoch 2026-09-03. TDB is approximated as TT (under 2 ms).
export const COMET_FIXTURES = {
  "comet-67p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D67P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=VECTORS&CENTER=%27500%4010%27&TLIST=2461256.5%2C2461286.5%2C2461316.5&TLIST_TYPE=JD&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&VEC_TABLE=2&VEC_CORR=NONE&CSV_FORMAT=YES",
    "rows": [
      {
        "jd": 2461256.5,
        "position": [
          -54363376.75841478,
          -633249080.981398,
          -314089114.3692114
        ],
        "velocity": [
          806355.7018793554,
          442461.4638473794,
          185149.4815071019
        ]
      },
      {
        "jd": 2461286.5,
        "position": [
          -30113288.08054335,
          -619170266.1667022,
          -308134907.108565
        ],
        "velocity": [
          810010.8116800061,
          496567.9829920794,
          212032.1432715231
        ]
      },
      {
        "jd": 2461316.5,
        "position": [
          -5782557.791161827,
          -603426958.3985895,
          -301352280.3019254
        ],
        "velocity": [
          811681.2329729253,
          553480.0198917506,
          240405.9587713359
        ]
      }
    ]
  },
  "comet-103p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D103P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=VECTORS&CENTER=%27500%4010%27&TLIST=2461256.5%2C2461286.5%2C2461316.5&TLIST_TYPE=JD&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&VEC_TABLE=2&VEC_CORR=NONE&CSV_FORMAT=YES",
    "rows": [
      {
        "jd": 2461256.5,
        "position": [
          -710643762.4963741,
          -452912361.9688184,
          -214684360.8473913
        ],
        "velocity": [
          216762.1459988934,
          -563496.8826080211,
          -95280.33217590419
        ]
      },
      {
        "jd": 2461286.5,
        "position": [
          -703662494.3584697,
          -469508002.2185178,
          -217397325.2744258
        ],
        "velocity": [
          248534.3346111468,
          -542799.9830680682,
          -85584.77871267649
        ]
      },
      {
        "jd": 2461316.5,
        "position": [
          -695738718.0410869,
          -485475537.39926,
          -219819429.6276576
        ],
        "velocity": [
          279605.3494228403,
          -521620.9799722568,
          -75887.69068474448
        ]
      }
    ]
  },
  "comet-9p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D9P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=VECTORS&CENTER=%27500%4010%27&TLIST=2461256.5%2C2461286.5%2C2461316.5&TLIST_TYPE=JD&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&VEC_TABLE=2&VEC_CORR=NONE&CSV_FORMAT=YES",
    "rows": [
      {
        "jd": 2461256.5,
        "position": [
          -227158967.2779018,
          466451012.9085498,
          287343754.7532659
        ],
        "velocity": [
          -758908.1191943373,
          -824273.6536382667,
          -285704.6039926552
        ]
      },
      {
        "jd": 2461286.5,
        "position": [
          -249416233.7544568,
          440720650.7538041,
          278148337.8823496
        ],
        "velocity": [
          -723894.3455112666,
          -891328.1179585963,
          -327643.2237266673
        ]
      },
      {
        "jd": 2461316.5,
        "position": [
          -270527450.5695975,
          412956969.8282983,
          267665308.9074917
        ],
        "velocity": [
          -682356.7390222584,
          -959816.3147267728,
          -371567.2224049019
        ]
      }
    ]
  },
  "comet-81p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D81P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=VECTORS&CENTER=%27500%4010%27&TLIST=2461256.5%2C2461286.5%2C2461316.5&TLIST_TYPE=JD&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&VEC_TABLE=2&VEC_CORR=NONE&CSV_FORMAT=YES",
    "rows": [
      {
        "jd": 2461256.5,
        "position": [
          778210012.8942435,
          91552956.8816794,
          2636098.359600365
        ],
        "velocity": [
          -216338.8088429217,
          696563.5472781288,
          277926.4226605412
        ]
      },
      {
        "jd": 2461286.5,
        "position": [
          770997401.9409511,
          112357815.8519602,
          10968714.54258531
        ],
        "velocity": [
          -264561.82332631,
          690193.1908750265,
          277493.5647907647
        ]
      },
      {
        "jd": 2461316.5,
        "position": [
          762332396.0511973,
          132950228.9036938,
          19280351.98534697
        ],
        "velocity": [
          -313175.0634476502,
          682390.1262643285,
          276524.2711845424
        ]
      }
    ]
  },
  "comet-1p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D1P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=VECTORS&CENTER=%27500%4010%27&TLIST=2461256.5%2C2461286.5%2C2461316.5&TLIST_TYPE=JD&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&VEC_TABLE=2&VEC_CORR=NONE&CSV_FORMAT=YES",
    "rows": [
      {
        "jd": 2461256.5,
        "position": [
          -2900307705.81833,
          4355957326.68548,
          280593979.1297408
        ],
        "velocity": [
          80748.2333916095,
          10388.80570853642,
          25321.86977168501
        ]
      },
      {
        "jd": 2461286.5,
        "position": [
          -2897875981.341286,
          4356255061.742536,
          281352581.8807304
        ],
        "velocity": [
          81366.68244333766,
          9460.020316159018,
          25251.56796679913
        ]
      },
      {
        "jd": 2461316.5,
        "position": [
          -2895425737.218017,
          4356524910.371927,
          282109070.2157831
        ],
        "velocity": [
          81982.46012784,
          8529.108680591116,
          25180.70689775376
        ]
      }
    ]
  },
  "comet-8p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D8P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=VECTORS&CENTER=%27500%4010%27&TLIST=2461256.5%2C2461286.5%2C2461316.5&TLIST_TYPE=JD&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&VEC_TABLE=2&VEC_CORR=NONE&CSV_FORMAT=YES",
    "rows": [
      {
        "jd": 2461256.5,
        "position": [
          274020407.574007,
          -1433329349.269649,
          -202330689.4619154
        ],
        "velocity": [
          238146.6839945141,
          -238089.9190379407,
          266561.5153689309
        ]
      },
      {
        "jd": 2461286.5,
        "position": [
          281126726.6044219,
          -1440273149.412387,
          -194306300.5274718
        ],
        "velocity": [
          235603.023808411,
          -224850.9810169547,
          268381.0044727989
        ]
      },
      {
        "jd": 2461316.5,
        "position": [
          288156266.5974924,
          -1446821633.747971,
          -186228815.6955382
        ],
        "velocity": [
          233027.6838098464,
          -211734.9871018456,
          270101.5751753941
        ]
      }
    ]
  },
  "comet-19p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D19P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=VECTORS&CENTER=%27500%4010%27&TLIST=2461256.5%2C2461286.5%2C2461316.5&TLIST_TYPE=JD&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&VEC_TABLE=2&VEC_CORR=NONE&CSV_FORMAT=YES",
    "rows": [
      {
        "jd": 2461256.5,
        "position": [
          -112772188.5831227,
          -718927176.7986113,
          -380245966.4972805
        ],
        "velocity": [
          642982.1574713278,
          365950.231061493,
          -175588.6664400346
        ]
      },
      {
        "jd": 2461286.5,
        "position": [
          -93395796.8261361,
          -707365798.7959863,
          -385202285.0752004
        ],
        "velocity": [
          648635.8507188677,
          404947.3333140073,
          -154656.176218913
        ]
      },
      {
        "jd": 2461316.5,
        "position": [
          -73862879.58955993,
          -694621599.3458495,
          -389514293.5964112
        ],
        "velocity": [
          653405.4792452904,
          444818.03091432,
          -132619.191877404
        ]
      }
    ]
  },
  "comet-137p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D137P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=VECTORS&CENTER=%27500%4010%27&TLIST=2461256.5%2C2461286.5%2C2461316.5&TLIST_TYPE=JD&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&VEC_TABLE=2&VEC_CORR=NONE&CSV_FORMAT=YES",
    "rows": [
      {
        "jd": 2461256.5,
        "position": [
          -425297080.4002727,
          -604957714.9661789,
          -257015881.5860173
        ],
        "velocity": [
          1030728.034076535,
          -9248.294145711678,
          71060.29499112723
        ]
      },
      {
        "jd": 2461286.5,
        "position": [
          -393980767.610754,
          -604660462.9854324,
          -254640638.0034741
        ],
        "velocity": [
          1056989.706143465,
          29502.29290971695,
          87450.15848197704
        ]
      },
      {
        "jd": 2461316.5,
        "position": [
          -361880450.3321167,
          -603160025.3091671,
          -251758759.8799217
        ],
        "velocity": [
          1082975.75880256,
          71008.89376914705,
          104851.3534903237
        ]
      }
    ]
  },
  "comet-143p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D143P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=VECTORS&CENTER=%27500%4010%27&TLIST=2461256.5%2C2461286.5%2C2461316.5&TLIST_TYPE=JD&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&VEC_TABLE=2&VEC_CORR=NONE&CSV_FORMAT=YES",
    "rows": [
      {
        "jd": 2461256.5,
        "position": [
          -415453399.9794281,
          198250036.8168071,
          38672100.5062401
        ],
        "velocity": [
          -490569.026019233,
          -1506563.658018782,
          -619029.4599346948
        ]
      },
      {
        "jd": 2461286.5,
        "position": [
          -428239887.4266514,
          152213832.8231248,
          19953119.36773478
        ],
        "velocity": [
          -360206.5921428028,
          -1560565.504035519,
          -628010.6154477237
        ]
      },
      {
        "jd": 2461316.5,
        "position": [
          -436975700.3066005,
          104743580.2037186,
          1048137.472882138
        ],
        "velocity": [
          -220854.6878456768,
          -1601829.747373639,
          -631330.0686877391
        ]
      }
    ]
  },
  "comet-162p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D162P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=VECTORS&CENTER=%27500%4010%27&TLIST=2461256.5%2C2461286.5%2C2461316.5&TLIST_TYPE=JD&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&VEC_TABLE=2&VEC_CORR=NONE&CSV_FORMAT=YES",
    "rows": [
      {
        "jd": 2461256.5,
        "position": [
          27109059.56050534,
          161126529.8769517,
          166416613.2095471
        ],
        "velocity": [
          -2171039.379617959,
          395119.9135521655,
          1218144.932267686
        ]
      },
      {
        "jd": 2461286.5,
        "position": [
          -38228431.46805947,
          167828237.9053158,
          197400313.2663844
        ],
        "velocity": [
          -2163776.53323268,
          68393.6561527405,
          858125.7477677831
        ]
      },
      {
        "jd": 2461316.5,
        "position": [
          -101842600.1682603,
          166150413.1871009,
          218593800.9485306
        ],
        "velocity": [
          -2067717.1218025,
          -166739.9307778899,
          566124.957336843
        ]
      }
    ]
  },
  "comet-2p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D2P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=VECTORS&CENTER=%27500%4010%27&TLIST=2461256.5%2C2461286.5%2C2461316.5&TLIST_TYPE=JD&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&VEC_TABLE=2&VEC_CORR=NONE&CSV_FORMAT=YES",
    "rows": [
      {
        "jd": 2461256.5,
        "position": [
          394733717.4063793,
          22220074.28510228,
          55833803.43168824
        ],
        "velocity": [
          -1261634.563428233,
          568593.2281531704,
          247561.0515813324
        ]
      },
      {
        "jd": 2461286.5,
        "position": [
          353947480.4418745,
          39060634.17438956,
          62810614.48205598
        ],
        "velocity": [
          -1463793.194489485,
          551762.7551068724,
          215336.1991600925
        ]
      },
      {
        "jd": 2461316.5,
        "position": [
          306436444.4470094,
          55135683.19390734,
          68578505.68629111
        ],
        "velocity": [
          -1713317.610000218,
          515612.0464470301,
          165320.0728400006
        ]
      }
    ]
  },
  "comet-209p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D209P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=VECTORS&CENTER=%27500%4010%27&TLIST=2461256.5%2C2461286.5%2C2461316.5&TLIST_TYPE=JD&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&VEC_TABLE=2&VEC_CORR=NONE&CSV_FORMAT=YES",
    "rows": [
      {
        "jd": 2461256.5,
        "position": [
          622199801.5475527,
          364365603.8322733,
          -12921322.17552794
        ],
        "velocity": [
          -74034.80216689623,
          576295.1774946256,
          412602.7303251446
        ]
      },
      {
        "jd": 2461286.5,
        "position": [
          619246758.3651284,
          381218029.1715986,
          -532953.7700774466
        ],
        "velocity": [
          -122594.0105211518,
          547101.2922838099,
          413124.6000434192
        ]
      },
      {
        "jd": 2461316.5,
        "position": [
          614857772.4709042,
          397185613.9169564,
          11856552.21341
        ],
        "velocity": [
          -169790.9106500333,
          517299.9940106714,
          412685.6110491949
        ]
      }
    ]
  }
} as const
