// Generated by tools/generate-comets.mjs. Do not edit.
// JPL Horizons, heliocentric ICRF; epoch 2026-09-03. TDB is approximated as TT (under 2 ms).
export { COMET_FIXTURES } from '../data/generated/cometFixture.js'
