import { mkdir as ensureReportDirectory } from 'node:fs/promises';
await ensureReportDirectory('output/distant-worlds', {recursive:true});
import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {runtimeAssets} from '../../../tools/runtime-assets.mts';
import {installRuntimeAssets} from '../../../tools/setup.mts';
const root=resolve('output/distant-worlds/fresh-runtime');
await mkdir(root,{recursive:true});
const assets=(await runtimeAssets(process.cwd(),['oumuamua','sedna','gonggong','orcus','salacia','varuna','varda','mani','achlys'])).map(asset=>({...asset,file:resolve(root,asset.id,asset.filename)}));
for(const asset of assets) assert.equal(await readFile(asset.file).then(()=>true, e=>{if(e.code==='ENOENT')return false;throw e;}),false,'Fresh destination must start empty');
const result=await installRuntimeAssets(assets,{concurrency:1});
assert.equal(result.installed,assets.length);assert.equal(result.reused,0);
await writeFile('output/distant-worlds/fresh-install.json',JSON.stringify({checkedAt:new Date().toISOString(),...result,bytes:assets.reduce((sum,a)=>sum+a.bytes,0),scope:'Public content-addressed URLs installed through the standard setup implementation into an empty directory; every downloaded file checked against its expected bytes and SHA-256.',assets:assets.map(({id,filename,url,bytes,sha256})=>({id,filename,url,bytes,sha256}))},null,2)+'\n');
console.log('Fresh remote installation:',result);
