import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { CUBIC_SKY_STANDARD } from "../../../platform/cubic-sky-contract.mjs";
import { PREPARED_MARS_LIGHTING } from "../runtime/preparedLighting.mjs";
import { PREPARED_MARS_SCENE } from "../runtime/preparedScene.mjs";
import { MARS_SOURCE_ROOT } from "./preparation-paths.mjs";
import { validateMarsSourceGroup } from "./source-manifest.mjs";
import {
  MARS_MATERIAL_DEPTH_BIAS,
  prepareMarsMaterialPlaneTransform,
} from "./material-plane.mjs";

const MINIMUM_CONTROL_PITCH_DEGREES = 0;
const MAXIMUM_CONTROL_PITCH_DEGREES = 89;
const MAXIMUM_SCENE_PITCH_DEGREES = 65;
const INITIAL_SCENE_PITCH_DEGREES = 40;
const DEFAULT_CONTROL_PITCH_DEGREES = MAXIMUM_CONTROL_PITCH_DEGREES *
  (1 - INITIAL_SCENE_PITCH_DEGREES / MAXIMUM_SCENE_PITCH_DEGREES);
const DEFAULT_CONTROL_YAW_DEGREES =
  CUBIC_SKY_STANDARD.defaultControlYawDegrees;
const MINIMUM_ZOOM = 0.42;
const MAXIMUM_ZOOM = 4;
const DEFAULT_ZOOM = 1.1;
const LOGICAL_BODY_DIAMETER = PREPARED_MARS_SCENE.geometry.equatorialRadius * 2;
const RESPONSIVE_FIT = Object.freeze({
  model: "continuous-aspect-smoothstep",
  portraitBaseWidthShare: 0.34,
  narrowPortraitWidthShareGain: 0.08,
  landscapeWidthShareGain: 0.02,
  narrowPortraitAspectRatio: 0.46,
  portraitAspectRatio: 0.75,
  squareAspectRatio: 1,
  maximumHeightShare: 0.61,
  maximumMobilePreviewShare: 0.925,
  minimumZoom: 0.42,
  maximumZoom: 2,
});
await validateMarsSourceGroup("camera");
const googleEarthContract = JSON.parse(await readFile(resolve(
  MARS_SOURCE_ROOT,
  "sky/google-earth-pro-contract.json",
), "utf8"));
if (googleEarthContract.schema !==
    "cssmars-google-earth-pro-sky-contract@1") {
  throw new TypeError("Mars Google Earth Pro camera contract is incompatible.");
}

const output = Object.freeze({
  schema: "cssmars-prepared-camera@2",
  model: "google-earth-pro-cubic-sky-unbounded-accumulated-matrix3d",
  cameraModel: "accumulated-matrix3d",
  state: Object.freeze({
    target: Object.freeze([0, 0, 0]),
    rotX: DEFAULT_CONTROL_PITCH_DEGREES,
    rotY: DEFAULT_CONTROL_YAW_DEGREES,
    zoom: DEFAULT_ZOOM,
    distance: 0,
  }),
  minimumControlPitchDegrees: MINIMUM_CONTROL_PITCH_DEGREES,
  maximumControlPitchDegrees: MAXIMUM_CONTROL_PITCH_DEGREES,
  defaultControlPitchDegrees: DEFAULT_CONTROL_PITCH_DEGREES,
  defaultControlYawDegrees: DEFAULT_CONTROL_YAW_DEGREES,
  initialScenePitchDegrees: INITIAL_SCENE_PITCH_DEGREES,
  maximumScenePitchDegrees: MAXIMUM_SCENE_PITCH_DEGREES,
  minimumZoom: MINIMUM_ZOOM,
  maximumZoom: MAXIMUM_ZOOM,
  defaultZoom: DEFAULT_ZOOM,
  logicalBodyDiameter: LOGICAL_BODY_DIAMETER,
  responsiveFit: RESPONSIVE_FIT,
  sceneScale: DEFAULT_ZOOM / 50,
  horizontalOrbit: true,
  pitchBounded: false,
  yawBounded: false,
  runtimeMatrixFormatting: true,
  oracleContract: Object.freeze({
    source: googleEarthContract.sourceProduct,
    sampleCount: googleEarthContract.sampleCount,
    qualification: googleEarthContract.captureQualification,
    nativeStateFields: Object.freeze([
      "latitude",
      "longitude",
      "distance",
      "heading",
      "tilt",
    ]),
    projection: Object.freeze({
      ...googleEarthContract.camera.projection,
      axis: "horizontal",
      runtimeProjection: false,
    }),
    orientation: Object.freeze({
      ...googleEarthContract.camera.orientation,
      cubicRotationResponse:
        googleEarthContract.camera.cubicTransport.rotationResponse,
      cubicZoomResponse:
        googleEarthContract.camera.cubicTransport.zoomResponse,
    }),
  }),
  materialDepthContract: Object.freeze({
    model:
      "prepared-camera-facing-plane-in-shared-moon-depth-context-with-camera-counter-rotation",
    referenceScenePitchDegrees: INITIAL_SCENE_PITCH_DEGREES,
    planeTransform: prepareMarsMaterialPlaneTransform({
      pitchDegrees: INITIAL_SCENE_PITCH_DEGREES,
      yawDegrees: DEFAULT_CONTROL_YAW_DEGREES,
      outputSize: PREPARED_MARS_LIGHTING.presentationFrameSize,
      contentRadius: PREPARED_MARS_LIGHTING.surfaceRadius,
    }),
    depthBias: MARS_MATERIAL_DEPTH_BIAS,
    runtimeGeometry: false,
    runtimeRasterization: false,
  }),
});

await writeFile(
  new URL("../runtime/preparedCamera.mjs", import.meta.url),
  "// Generated by tools/prepare-camera.mjs. Do not edit by hand.\n" +
    `export const PREPARED_MARS_CAMERA = ${JSON.stringify(output)};\n`,
);

console.log("Prepared Mars shared cubic-sky camera contract.");
