import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import sharp from "sharp";
import { packProjectiveSurfaceRaster } from
  "../../../platform/projective-surface-raster.mjs";

import {
  MARS_BODY_LATITUDE_BOUNDS_DEGREES,
  MARS_POLAR_BOUNDARY_LATITUDE_DEGREES,
  marsBodyRasterBands,
} from "./body-geometry.mjs";
import {
  MARS_POLAR_OVERLAP,
  prepareMarsPolarAtlas,
} from "./polar-projection.mjs";
import {
  ensureMarsPreparationDirectories,
  MARS_PUBLIC_ROOT,
  MARS_SOURCE_ROOT,
} from "./preparation-paths.mjs";
import { validateMarsSourceGroup } from "./source-manifest.mjs";

await validateMarsSourceGroup("lenses");
await ensureMarsPreparationDirectories();

const OUTPUT_MODULE = new URL("../runtime/preparedLenses.mjs", import.meta.url);
const BODY_WIDTH = 2_048;
const BODY_HEIGHT = 1_024;
const BODY_2X_WIDTH = 4_096;
const BODY_2X_HEIGHT = 2_048;
const POLAR_TILE_SIZE = 256;
const POLAR_OVERLAP = MARS_POLAR_OVERLAP;
const BODY_LATITUDE_BOUNDS_DEGREES = MARS_BODY_LATITUDE_BOUNDS_DEGREES;
const plans = Object.freeze([
  Object.freeze({
    id: "elevation",
    label: "Elevation",
    shortLabel: "MOLA",
    source: "lenses/mola-pseudocolor-z3.png",
    measurement: "MOLA topographic elevation with shaded relief",
    falseColor: true,
    qualification:
      "USGS MOLA elevation shown with the source pseudo-color shaded-relief palette",
    coveragePreparation: "complete global source mosaic",
  }),
  Object.freeze({
    id: "thermal",
    label: "Thermal IR",
    shortLabel: "IR",
    source: "lenses/themis-ir-day-z3.png",
    measurement: "THEMIS daytime thermal infrared response",
    falseColor: false,
    qualification:
      "USGS and ASU THEMIS daytime infrared response where available; prepared Viking grayscale detail fills source gaps; not a calibrated temperature retrieval",
    coveragePreparation:
      "missing THEMIS samples use histogram-matched Viking grayscale detail for continuous illustrative coverage",
  }),
]);

const controls = [Object.freeze({
  id: "normal",
  label: "Normal",
  shortLabel: "RGB",
  measurement: "Viking MDIM 2.1 visible-color mosaic",
  thumbnailUrl: "/scenes/mars/mars-lens-normal.webp",
  surfaceUrl: "/scenes/mars/mars-surface.webp",
  surface2xUrl: "/scenes/mars/mars-surface@2x.webp",
  polesUrl: "/scenes/mars/mars-poles.webp",
  poles2xUrl: "/scenes/mars/mars-poles@2x.webp",
  falseColor: false,
  qualification: "USGS Viking MDIM 2.1 colorized global mosaic",
})];
await prepareThumbnail(
  resolve(MARS_PUBLIC_ROOT, "mars-surface.webp"),
  resolve(MARS_PUBLIC_ROOT, "mars-lens-normal.webp"),
);
for (const plan of plans) controls.push(await prepareLens(plan));

const descriptor = Object.freeze({
  schema: "cssmars-prepared-lenses@1",
  defaultLens: "normal",
  runtimeFilters: false,
  runtimeRasterization: false,
  controls: Object.freeze(controls),
  provenance: Object.freeze({
    normalAuthority: "USGS Astrogeology Viking MDIM 2.1 colorized global mosaic",
    elevationAuthority: "USGS Astrogeology and NASA Mars Global Surveyor MOLA",
    thermalAuthority:
      "USGS Astrogeology, Arizona State University, and NASA Mars Odyssey THEMIS",
    runtimeAuthorityRequests: false,
  }),
});
await writeFile(
  OUTPUT_MODULE,
  "// Generated by tools/prepare-lenses.mjs. Do not edit by hand.\n" +
    `export const PREPARED_MARS_LENSES = ${JSON.stringify(descriptor)};\n`,
);
console.log(`Prepared ${controls.length} Mars surface lenses.`);

async function prepareLens(plan) {
  const sourcePath = resolve(MARS_SOURCE_ROOT, plan.source);
  const source = await sharp(sourcePath)
    .toColourspace("srgb")
    .removeAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  if (source.info.width !== BODY_2X_WIDTH ||
      source.info.height !== BODY_2X_HEIGHT ||
      source.info.channels !== 3) {
    throw new Error(`${plan.label} Mars lens dimensions changed.`);
  }
  const complete = plan.id === "thermal"
    ? await fillThermalCoverage(source)
    : source;
  const source1x = await sharp(complete.data, { raw: complete.info })
    .resize(BODY_WIDTH, BODY_HEIGHT, { fit: "fill" })
    .raw()
    .toBuffer({ resolveWithObject: true });
  const surfacePath = resolve(MARS_PUBLIC_ROOT, `mars-lens-${plan.id}.webp`);
  const surface2xPath = resolve(
    MARS_PUBLIC_ROOT,
    `mars-lens-${plan.id}@2x.webp`,
  );
  await Promise.all([
    writeProjectiveSurface(source1x, surfacePath),
    writeProjectiveSurface(complete, surface2xPath),
  ]);
  const polar = prepareMarsPolarAtlas(complete, POLAR_TILE_SIZE * 2, {
    boundaryLatitudeDegrees: MARS_POLAR_BOUNDARY_LATITUDE_DEGREES,
    overlap: POLAR_OVERLAP,
    inpaintRadius: 0.9,
  });
  const polesPath = resolve(MARS_PUBLIC_ROOT, `mars-lens-${plan.id}-poles.webp`);
  const poles2xPath = resolve(
    MARS_PUBLIC_ROOT,
    `mars-lens-${plan.id}-poles@2x.webp`,
  );
  await Promise.all([
    sharp(polar.data, {
      raw: { width: polar.width, height: polar.height, channels: 4 },
    }).resize(POLAR_TILE_SIZE * 2, POLAR_TILE_SIZE)
      .webp({ quality: 90, alphaQuality: 100, effort: 6, smartSubsample: true })
      .toFile(polesPath),
    sharp(polar.data, {
      raw: { width: polar.width, height: polar.height, channels: 4 },
    }).webp({ quality: 90, alphaQuality: 100, effort: 6, smartSubsample: true })
      .toFile(poles2xPath),
  ]);
  const thumbnailPath = resolve(
    MARS_PUBLIC_ROOT,
    `mars-lens-${plan.id}-thumbnail.webp`,
  );
  await prepareThumbnail(surfacePath, thumbnailPath);
  const assets = await Promise.all([
    surfacePath,
    surface2xPath,
    polesPath,
    poles2xPath,
    thumbnailPath,
  ].map((path) => readFile(path)));
  return Object.freeze({
    id: plan.id,
    label: plan.label,
    shortLabel: plan.shortLabel,
    measurement: plan.measurement,
    thumbnailUrl: `/scenes/mars/mars-lens-${plan.id}-thumbnail.webp`,
    surfaceUrl: `/scenes/mars/mars-lens-${plan.id}.webp`,
    surface2xUrl: `/scenes/mars/mars-lens-${plan.id}@2x.webp`,
    polesUrl: `/scenes/mars/mars-lens-${plan.id}-poles.webp`,
    poles2xUrl: `/scenes/mars/mars-lens-${plan.id}-poles@2x.webp`,
    falseColor: plan.falseColor,
    qualification: plan.qualification,
    coveragePreparation: plan.coveragePreparation,
    polarPreparation: Object.freeze({
      boundaryLatitudeDegrees: MARS_POLAR_BOUNDARY_LATITUDE_DEGREES,
      singularityStabilization: polar.stabilization,
      runtimeProjection: false,
    }),
    sourceFile: plan.source,
    assetSha256: Object.freeze({
      surface: digest(assets[0]),
      surface2x: digest(assets[1]),
      poles: digest(assets[2]),
      poles2x: digest(assets[3]),
      thumbnail: digest(assets[4]),
    }),
  });
}

async function fillThermalCoverage(source) {
  const output = Buffer.from(source.data);
  const { width, height, channels } = source.info;
  const rowHasData = (row) => {
    for (let column = 0; column < width; column += 16) {
      const offset = (row * width + column) * channels;
      if (output[offset] || output[offset + 1] || output[offset + 2]) return true;
    }
    return false;
  };
  let first = 0;
  while (first < height && !rowHasData(first)) first += 1;
  let last = height - 1;
  while (last >= 0 && !rowHasData(last)) last -= 1;
  if (first !== 24 || last !== 1_655) {
    throw new Error(`THEMIS prepared coverage drifted: ${first}-${last}.`);
  }
  const fallback = await sharp(resolve(
    MARS_SOURCE_ROOT,
    "surface/mars-viking-mdim21-color-1km.jpg",
  ))
    .resize(width, height, { fit: "fill" })
    .greyscale()
    .raw()
    .toBuffer({ resolveWithObject: true });
  const themisRange = channelRange(output, channels, 64);
  const fallbackRange = channelRange(fallback.data, fallback.info.channels, 0);
  const coverage = Buffer.alloc(width * height);
  for (let pixel = 0; pixel < width * height; pixel += 1) {
    coverage[pixel] = pixelHasData(pixel * channels) ? 255 : 0;
  }
  const softenedCoverage = await sharp(coverage, {
    raw: { width, height, channels: 1 },
  }).blur(12).raw().toBuffer();
  for (let pixel = 0; pixel < width * height; pixel += 1) {
    const offset = pixel * channels;
    const sourceValue = fallback.data[pixel * fallback.info.channels];
    const normalized = (sourceValue - fallbackRange.mean) /
      Math.max(fallbackRange.deviation, 1);
    const fallbackValue = Math.max(64, Math.min(224, Math.round(
      themisRange.mean + normalized * themisRange.deviation,
    )));
    const weight = coverage[pixel] === 0 ? 0 : softenedCoverage[pixel] / 255;
    for (let channel = 0; channel < channels; channel += 1) {
      output[offset + channel] = Math.round(
        output[offset + channel] * weight + fallbackValue * (1 - weight),
      );
    }
  }
  return Object.freeze({ data: output, info: source.info });

  function pixelHasData(offset) {
    return output[offset] + output[offset + 1] + output[offset + 2] >= 192;
  }
}

function channelRange(data, channels, minimum) {
  let count = 0;
  let sum = 0;
  let squared = 0;
  for (let offset = 0; offset < data.length; offset += channels) {
    const value = data[offset];
    if (value < minimum) continue;
    count += 1;
    sum += value;
    squared += value * value;
  }
  const mean = sum / count;
  return Object.freeze({
    mean,
    deviation: Math.sqrt(Math.max(0, squared / count - mean * mean)),
  });
}

async function writeProjectiveSurface(source, outputPath) {
  const { width, height, channels } = source.info;
  const packed = packProjectiveSurfaceRaster(source.data, {
    width,
    height,
    channels,
    bands: marsBodyRasterBands(height),
    gutter: height / 16 / 4,
  });
  await sharp(packed.data, { raw: {
    width: packed.packedWidth,
    height: packed.packedHeight,
    channels,
  } })
    .webp({ quality: 90, effort: 6, smartSubsample: true })
    .toFile(outputPath);
}

async function prepareThumbnail(inputPath, outputPath) {
  const metadata = await sharp(inputPath).metadata();
  const width = Math.round(metadata.width * 0.34);
  const height = Math.round(metadata.height * 0.28);
  const left = Math.round((metadata.width - width) * 0.5);
  const top = Math.round((metadata.height - height) * 0.46);
  await sharp(inputPath)
    .extract({ left, top, width, height })
    .resize(112, 64, { fit: "cover", kernel: sharp.kernel.lanczos3 })
    .webp({ quality: 90, effort: 6 })
    .toFile(outputPath);
}

function digest(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}
