import assert from 'node:assert/strict';
import { test } from 'node:test';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createSourceManifest } from '../../../../src/platform/source-manifest.mts';
import { requireArray, requireRecord, requireString, requireFiniteNumber } from '../../../../tools/sources/source-values.mts';
import { loadPdsRadiusTable } from '../../../../tools/objects/terrestrial-layers/obj-shape.mts';
import { authorCeTauri } from '../../../../tools/objects/source-authoring/ce-tauri/author.mts';

const root = resolve(import.meta.dirname, '../../../../src/objects/ce-tauri/source');
const read = async (path: string) => JSON.parse(await readFile(resolve(root, path), 'utf8')) as unknown;
const PARSEC_M = 3.085677581491367e16, MAS_RAD = Math.PI / 180 / 3.6e6;

test('CE Tauri retains source pins and acquisition closure', async () => {
  const source = await createSourceManifest({ planetId: 'ce-tauri', planetName: 'CE Tauri', sourceRoot: root });
  await source.verify();
  const plan = requireRecord(await read('preparation/acquisition.json')), operations = requireArray(plan.operations).map(value => requireRecord(value));
  const downloaded = new Set(operations.map(operation => requireString(operation.path)));
  for (const input of source.manifest.inputs) {
    if (downloaded.has(input.path)) continue;
    const authored = /^(preparation|presentation)\/.*\.json$/u.test(input.path) && input.acquisition === 'checked repository source';
    if (authored) continue;
    assert.match(input.acquisition, /author\.mts/u, `${input.path} is neither downloaded, generated by a named tool nor an authored record`);
  }
  assert.equal(operations.filter(operation => requireString(operation.path).startsWith('observations/oifits/')).length, 16, 'the plan restores the 16 PIONIER files');
  assert.deepEqual(operations.filter(operation => /\.fit$/u.test(requireString(operation.path))).map(operation => operation.url).sort(),
    ['dec_avg', 'dec_err', 'nov_avg', 'nov_err'].map(name => `https://cdsarc.cds.unistra.fr/ftp/J/A+A/614/A12/fits/${name}.fit`), 'and the four published CDS images');
});

test('the reference sphere is the published diameter at the stated distance', async () => {
  const measurements = requireRecord(await read('measurements.json')), shape = requireRecord(measurements.shape);
  const raster = requireRecord(await read('preparation/raster.json'));
  for (const surface of requireArray(raster.surfaces).map(value => requireRecord(value))) {
    const terrain = requireRecord(requireRecord(surface.science).shape);
    assert.equal(requireString(terrain.path), requireString(shape.path));
    const mesh = await loadPdsRadiusTable(resolve(root, requireString(terrain.path)), terrain.grid);
    assert.ok(mesh.positions.every(position => Math.abs(Math.hypot(...position) - requireFiniteNumber(measurements.radiusKm) * 1000) < 1), `${surface.id}: every vertex at the radius`);
  }
  const star = requireRecord(requireRecord(JSON.parse(await readFile(resolve(root, '../../../../packages/astronomy/data/bodies/ce-tauri.json'), 'utf8')) as unknown).star);
  const radiusM = requireFiniteNumber(measurements.radiusKm) * 1000;
  const implied = requireFiniteNumber(measurements.angularDiameterMas) * MAS_RAD / 2 * requireFiniteNumber(star.distanceParsecs) * PARSEC_M;
  assert.ok(Math.abs(implied - radiusM) / radiusM < 1e-6, `the radius is the published diameter at the stated distance: ${implied} against ${radiusM}`);
});

test('the sphere table and the navigation marker are the authoring tool\'s output', async () => {
  const result = await authorCeTauri({ check: true });
  assert.equal(result.width, 32); assert.equal(result.height, 32);
});
