import { PYUVDATA_UVFITS_SCHEMA, parsePyuvdataUvfitsAnswer } from '@cssearth/objects';
import assert from 'node:assert/strict';import {readFile}from 'node:fs/promises';import {resolve}from 'node:path';import{test}from'node:test';import{member}from'./common.mts';import{describeMeasurementSet,describeUvfitsVisibility,F11_MEASUREMENT_SET_HANDLER}from'./f11-measurement-set.mts';
const table=(id:string)=>member(id,`packages/telescope-cli/src/archives/interferometry/fixtures/alma/${id}`,'science',Buffer.from(id));
test('F11 requires the complete MS closure',()=>{const members=['MAIN','FIELD','SPECTRAL_WINDOW','ANTENNA','POLARIZATION'].map(table),tables=Object.fromEntries(members.map(item=>[item.id,item.id]))as any;assert.equal(describeMeasurementSet({id:'local-ms',producingRecord:'fixture',members,tables,archiveQualified:false}).dependencies[0]!.memberIds.length,5);assert.throws(()=>describeMeasurementSet({id:'bad',producingRecord:'x',members:[table('MAIN')],tables:{MAIN:'MAIN'}as any,archiveQualified:false}),/FIELD/u);});
test('F11 keeps the real VLA UVFITS profile distinct from an MS',async()=>{const path=resolve(import.meta.dirname,'fixtures/telescope-families/f11-vla-uvfits/day2_TDEM0003_10s_norx_1src_1spw.uvfits'),bytes=await readFile(path);assert.equal(bytes.byteLength,4253760);const product=describeUvfitsVisibility({id:'vla-day2-tdem0003',producingRecord:'RASG datasets v0.0.5 BSD-2-Clause',member:member('uvfits','day2_TDEM0003_10s_norx_1src_1spw.uvfits','science',bytes,'application/fits'),inspection:{telescope:'EVLA',target:'J1008+0730',rows:1360,channels:64,polarizations:[-1,-2,-3,-4],samples:348160,frequencyHz:{first:36304541952.42,increment:125000}}});assert.match(product.issues[0]!.reason,/not a CASA Measurement Set/u);assert.deepEqual(F11_MEASUREMENT_SET_HANDLER.operations(product).map(op=>op.id),['uvfits-visibility-inspect','uvfits-visibility-export','uvfits-amplitude-phase-diagnostics','uvfits-uv-coverage-diagnostics']);});
test('F11 rejects malformed delegated UVFITS inspection',()=>{assert.throws(()=>describeUvfitsVisibility({id:'bad',producingRecord:'fixture',member:table('uvfits'),inspection:{telescope:'EVLA',target:'J1008+0730',rows:0,channels:64,polarizations:[-1],samples:1,frequencyHz:{first:1,increment:1}}}),/inspection is invalid/u);});

test('the objects parser reads the retained F11 visibility response without changing bytes', async () => {
  const response: unknown = JSON.parse(await readFile(resolve(import.meta.dirname, 'fixtures/telescope-family-examples/artifacts/F11.json'), 'utf8'));
  const parsed = parsePyuvdataUvfitsAnswer(response, { operation: 'uvfits-visibility-export', file: { path: 'fixture.uvfits' }, selection: { field: 'J1008+0730', timeStartJulianDate: 2455312.64023149, timeEndJulianDate: 2455312.64023149, antenna1: 4, antenna2: 8, rowOffset: 0, rowCount: 1, channelStart: 0, channelCount: 2, polarization: -1 } });
  assert.equal(parsed.schema, PYUVDATA_UVFITS_SCHEMA);
  assert.equal(JSON.stringify(parsed), JSON.stringify(response));
});
