import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { projectRoot } from '../../fixtures.mjs';
import { createSourceManifest } from '../../../../src/platform/source-manifest.mjs';
import { readPhysicalFacts, parsePhysicalFacts } from '../../../../tools/objects/static-surface/physical.mjs';
import { decodeElevationGrid as decode, elevationColor as color, elevationRaster as raster } from '../../../../tools/objects/static-surface/elevation.mjs';
import { prepareSurfaceRasterCell as cell, bakeSurfaceRaster as bake } from '../../../../tools/objects/static-surface/inverse-homography.mjs';
const sourceDirectory=resolve(projectRoot,'src/planets/pluto/source');
const read=async path=>JSON.parse(await readFile(resolve(sourceDirectory,path),'utf8'));
const source=await createSourceManifest({planetId:'pluto',planetName:'Pluto',sourceRoot:sourceDirectory});
export const verifyPlutoSourceManifest=()=>source.verify();
const physical=await read('preparation/physical.json');
export const readPlutoFacts=()=>readPhysicalFacts({sourceDirectory,config:physical});
export const parsePlutoFacts=(jpl,nasa)=>parsePhysicalFacts({jpl,nasa:JSON.stringify(nasa)},physical);
const config=await read('preparation/raster.json');
const elevation=config.lenses?.find(lens=>lens.elevation)?.elevation;
export const decodeElevationGrid=bytes=>decode(bytes,elevation);
export const elevationColor=value=>color(value,elevation);
export const elevationRaster=(grid,width,height)=>raster({...grid,recipe:elevation},width,height);
export const PLUTO_SURFACE_ATLAS=(await read('preparation/geometry.json')).rasterAtlas;
export const prepareSurfaceRasterCell=(geometry,index)=>cell(geometry,index,PLUTO_SURFACE_ATLAS);
export const bakeSurfaceRaster=(data,info,cells,density)=>bake(data,info,cells,density,PLUTO_SURFACE_ATLAS);
