import assert from 'node:assert/strict';
import {required} from '../../../../tools/test-values.mts';
import {parseSurfaceRaster,parseSurfaceGeometry,parsePhysicalRecipe} from '../../../../tools/objects/static-surface/source-contract.mts';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { projectRoot } from '../../fixtures.mts';
import { createSourceManifest } from '../../../../src/platform/source-manifest.mts';
import { readPhysicalFacts, parsePhysicalFacts } from '../../../../tools/objects/static-surface/physical.mts';
import { decodeElevationGrid as decode, elevationColor as color, elevationRaster as raster } from '../../../../tools/objects/static-surface/elevation.mts';
import { prepareSurfaceRasterCell as cell, bakeSurfaceRaster as bake } from '../../../../tools/objects/static-surface/inverse-homography.mts';
import type { RasterInfo } from '../../../../tools/objects/static-surface/contracts.mts';
import type { ProjectiveGeometry } from '../../../../src/platform/projective-surface-raster.mts';
const sourceDirectory=resolve(projectRoot,'src/planets/pluto/source');
const read=async (path: string):Promise<unknown>=>JSON.parse(await readFile(resolve(sourceDirectory,path),'utf8'));
const source=await createSourceManifest({planetId:'pluto',planetName:'Pluto',sourceRoot:sourceDirectory});
export const verifyPlutoSourceManifest=()=>source.verify();
const physical=parsePhysicalRecipe(await read('preparation/physical.json'));
export const readPlutoFacts=()=>readPhysicalFacts({sourceDirectory,config:physical});
export const parsePlutoFacts=(jpl: string,nasa: unknown)=>parsePhysicalFacts({jpl,nasa:JSON.stringify(nasa)},physical);
const config=parseSurfaceRaster(await read('preparation/raster.json'));assert.equal(config.kind,'observation-lenses');assert.ok('lenses' in config);
const elevation=required(config.lenses.find(lens=>lens.elevation)?.elevation);
export const decodeElevationGrid=(bytes: Buffer<ArrayBufferLike>)=>decode(bytes,elevation);
export const elevationColor=(value: number)=>color(value,elevation);
export const elevationRaster=(grid: Omit<ReturnType<typeof decode>,"recipe">,width: number,height: number)=>raster({...grid,recipe:elevation},width,height);
const geometry=parseSurfaceGeometry(await read('preparation/geometry.json'));assert.ok(geometry.kind==='disc-poles');
export const PLUTO_SURFACE_ATLAS=required(geometry.rasterAtlas);
export const prepareSurfaceRasterCell=(geometry: ProjectiveGeometry,index: number)=>cell(geometry,index,PLUTO_SURFACE_ATLAS);
export const bakeSurfaceRaster=(data: Uint8Array<ArrayBufferLike>|Buffer<ArrayBuffer>,info: RasterInfo,cells: readonly { width: number; height: number; x: number; y: number; source: { width: number; height: number; backgroundPosition: readonly number[]; backgroundSize: readonly number[]; perspectiveX: number; perspectiveY: number; w: number; padding: number; boundary: number[][]; }; layer: { frameMatrix: string; textureMatrix: string; schema: "polycss-prepared-projective-texture-layer@1"; rasterScale: number; }; }[],density: number)=>bake(data,info,cells,density,PLUTO_SURFACE_ATLAS);
