import { requireArray, requireFiniteNumber, requireRecord, requireString } from '@cssearth/core';

export const PYUVDATA_UVFITS_SCHEMA = 'cssearth-pyuvdata-uvfits@1';

/** pyuvdata owns UVFITS random-group conventions, polarization decoding, UVW and flags. */
export interface PyuvdataUvfitsRequest {
  readonly operation: 'uvfits-visibility-inspect' | 'uvfits-visibility-export' | 'uvfits-amplitude-phase-diagnostics' | 'uvfits-uv-coverage-diagnostics';
  readonly file: { readonly path: string };
  readonly selection?: { readonly field: string; readonly timeStartJulianDate: number; readonly timeEndJulianDate: number; readonly antenna1: number; readonly antenna2: number; readonly rowOffset: number; readonly rowCount: number; readonly channelStart: number; readonly channelCount: number; readonly polarization: number };
}
export interface PyuvdataUvfitsAnswer {
  readonly schema: typeof PYUVDATA_UVFITS_SCHEMA; readonly pyuvdata: string;
  readonly inspection: { readonly telescope: string; readonly target: string; readonly rows: number; readonly channels: number; readonly polarizations: readonly number[]; readonly samples: number; readonly frequencyHz: { readonly first: number; readonly increment: number } };
  readonly notices: readonly string[];
  readonly amplitudePhase?: { readonly unflaggedSamples: number; readonly minimumAmplitude: number; readonly maximumAmplitude: number; readonly meanAmplitude: number; readonly circularMeanPhaseRadians: number };
  readonly uvCoverage?: { readonly unflaggedSamples: number; readonly uMeters: { readonly minimum: number; readonly maximum: number }; readonly vMeters: { readonly minimum: number; readonly maximum: number }; readonly wMeters: { readonly minimum: number; readonly maximum: number } };
  readonly rows?: readonly { readonly row: number; readonly timeJulianDate: number; readonly antenna1: number; readonly antenna2: number; readonly uvwMeters: readonly [number, number, number]; readonly frequencyHz: number; readonly polarization: number; readonly real: number; readonly imaginary: number; readonly weight: number; readonly flagged: boolean }[];
}
function integer(value: unknown, label: string, minimum: number): number { const n = requireFiniteNumber(value, label); if (!Number.isSafeInteger(n) || n < minimum) throw new TypeError(`${label} must be an integer at least ${minimum}.`); return n; }
export function parsePyuvdataUvfitsRequest(request: PyuvdataUvfitsRequest): PyuvdataUvfitsRequest {
  const file = { path: requireString(requireRecord(request.file, 'UVFITS file').path, 'UVFITS file path') }; if (!['uvfits-visibility-inspect', 'uvfits-visibility-export', 'uvfits-amplitude-phase-diagnostics', 'uvfits-uv-coverage-diagnostics'].includes(request.operation)) throw new TypeError('Unsupported pyuvdata UVFITS operation.');
  if (request.operation === 'uvfits-visibility-inspect') { if (request.selection !== undefined) throw new TypeError('UVFITS inspect accepts no selection.'); return { operation: request.operation, file }; }
  const s = requireRecord(request.selection, 'UVFITS selection'), start = requireFiniteNumber(s.timeStartJulianDate, 'UVFITS time start'), end = requireFiniteNumber(s.timeEndJulianDate, 'UVFITS time end'); if (start > end) throw new TypeError('UVFITS time selection is inverted.'); return { operation: request.operation, file, selection: { field: requireString(s.field, 'UVFITS field'), timeStartJulianDate: start, timeEndJulianDate: end, antenna1: integer(s.antenna1, 'antenna1', 0), antenna2: integer(s.antenna2, 'antenna2', 0), rowOffset: integer(s.rowOffset, 'rowOffset', 0), rowCount: integer(s.rowCount, 'rowCount', 1), channelStart: integer(s.channelStart, 'channelStart', 0), channelCount: integer(s.channelCount, 'channelCount', 1), polarization: integer(s.polarization, 'polarization', -8) } };
}
export function parsePyuvdataUvfitsAnswer(value: unknown, request: PyuvdataUvfitsRequest, version = '3.2.4'): PyuvdataUvfitsAnswer {
  const checked = parsePyuvdataUvfitsRequest(request), raw = requireRecord(value, 'pyuvdata UVFITS answer'); if (raw.schema !== PYUVDATA_UVFITS_SCHEMA || raw.pyuvdata !== version) throw new TypeError('pyuvdata answered with the wrong contract or version.');
  const info = requireRecord(raw.inspection, 'pyuvdata UVFITS inspection'), frequency = requireRecord(info.frequencyHz, 'pyuvdata UVFITS frequencies'); const polarizations = requireArray(info.polarizations, 'pyuvdata UVFITS polarizations').map((value, index) => integer(value, `polarization ${index}`, -8));
  const inspection = { telescope: requireString(info.telescope), target: requireString(info.target), rows: integer(info.rows, 'UVFITS rows', 1), channels: integer(info.channels, 'UVFITS channels', 1), polarizations, samples: integer(info.samples, 'UVFITS samples', 1), frequencyHz: { first: requireFiniteNumber(frequency.first, 'UVFITS first frequency'), increment: requireFiniteNumber(frequency.increment, 'UVFITS frequency increment') } };
  if (!inspection.telescope || !inspection.target || !polarizations.length || inspection.frequencyHz.increment === 0 || inspection.samples !== inspection.rows * inspection.channels * polarizations.length) throw new TypeError('Invalid pyuvdata UVFITS inspection.');
  const notices = requireArray(raw.notices, 'pyuvdata UVFITS notices').map((value, index) => requireString(value, `pyuvdata UVFITS notice ${index}`));
  const rows = raw.rows === undefined ? undefined : requireArray(raw.rows, 'pyuvdata UVFITS rows').map((value, index) => { const row = requireRecord(value, `pyuvdata UVFITS row ${index}`), uvw = requireArray(row.uvwMeters, `pyuvdata UVFITS row ${index} UVW`); if (uvw.length !== 3) throw new TypeError('pyuvdata UVFITS UVW must have three metres values.'); return { row: integer(row.row, 'UVFITS row', 0), timeJulianDate: requireFiniteNumber(row.timeJulianDate), antenna1: integer(row.antenna1, 'antenna1', 0), antenna2: integer(row.antenna2, 'antenna2', 0), uvwMeters: uvw.map((entry, axis) => requireFiniteNumber(entry, `UVW axis ${axis}`)) as [number, number, number], frequencyHz: requireFiniteNumber(row.frequencyHz), polarization: integer(row.polarization, 'polarization', -8), real: requireFiniteNumber(row.real), imaginary: requireFiniteNumber(row.imaginary), weight: requireFiniteNumber(row.weight), flagged: (() => { if (typeof row.flagged !== 'boolean') throw new TypeError('UVFITS flag must be boolean.'); return row.flagged; })() }; });
  const range = (value: unknown, label: string) => { const r = requireRecord(value, label), minimum = requireFiniteNumber(r.minimum), maximum = requireFiniteNumber(r.maximum); if (minimum > maximum) throw new TypeError(`${label} is inverted.`); return { minimum, maximum }; };
  const amplitude = raw.amplitudePhase === undefined ? undefined : requireRecord(raw.amplitudePhase, 'pyuvdata amplitude/phase diagnostic'), coverage = raw.uvCoverage === undefined ? undefined : requireRecord(raw.uvCoverage, 'pyuvdata UV coverage diagnostic');
  const amplitudePhase = amplitude ? { unflaggedSamples: integer(amplitude.unflaggedSamples, 'unflagged samples', 1), minimumAmplitude: requireFiniteNumber(amplitude.minimumAmplitude), maximumAmplitude: requireFiniteNumber(amplitude.maximumAmplitude), meanAmplitude: requireFiniteNumber(amplitude.meanAmplitude), circularMeanPhaseRadians: requireFiniteNumber(amplitude.circularMeanPhaseRadians) } : undefined;
  const uvCoverage = coverage ? { unflaggedSamples: integer(coverage.unflaggedSamples, 'unflagged samples', 1), uMeters: range(coverage.uMeters, 'u coverage'), vMeters: range(coverage.vMeters, 'v coverage'), wMeters: range(coverage.wMeters, 'w coverage') } : undefined;
  if (checked.operation === 'uvfits-visibility-inspect' && (rows !== undefined || amplitudePhase !== undefined || uvCoverage !== undefined)) throw new TypeError('UVFITS inspection returned selected data.');
  if (checked.operation === 'uvfits-visibility-export') { if (!rows) throw new TypeError('UVFITS export returned no rows.'); const s = checked.selection!; if (rows.length !== s.rowCount * s.channelCount || rows.some(row => row.polarization !== s.polarization || row.antenna1 !== s.antenna1 || row.antenna2 !== s.antenna2 || row.timeJulianDate < s.timeStartJulianDate || row.timeJulianDate > s.timeEndJulianDate)) throw new TypeError('UVFITS export does not match its bounded selection.'); }
  if (checked.operation === 'uvfits-amplitude-phase-diagnostics' && (rows !== undefined || !amplitudePhase || uvCoverage !== undefined)) throw new TypeError('UVFITS amplitude/phase diagnostic is invalid.'); if (checked.operation === 'uvfits-uv-coverage-diagnostics' && (rows !== undefined || amplitudePhase !== undefined || !uvCoverage)) throw new TypeError('UVFITS UV-coverage diagnostic is invalid.');
  return { schema: PYUVDATA_UVFITS_SCHEMA, pyuvdata: version, inspection, notices, ...(rows ? { rows } : {}), ...(amplitudePhase ? { amplitudePhase } : {}), ...(uvCoverage ? { uvCoverage } : {}) };
}
