import {parseScalarMapLens,shape,text,number} from '../../../../tools/objects/terrestrial-layers/source-records.mts';
import {required} from '../../../../tools/contract/test-values.mts';
import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { gunzipSync } from 'node:zlib';
import sharp from 'sharp';
import { parseScalarMap, scalarMapIndex } from '../../../../tools/objects/terrestrial-layers/pds-scalar-map.mts';
import { colorForValue } from '../../../../tools/objects/terrestrial-layers/scientific-raster.mts';
const root = new URL('../../../../', import.meta.url);
const body = new URL('src/objects/comet-67p/', root);
const json = async (path: string|URL) => JSON.parse((await readFile(new URL(path, body))).toString('utf8'));
const config = await json('source/preparation/terrestrial.json');
const parsed = new Map<string,ReturnType<typeof parseScalarMap>>();
async function map(value: unknown) {
  const lens={...parseScalarMapLens(value),...shape({id:text})(value)};
  if (!parsed.has(lens.id)) parsed.set(lens.id, parseScalarMap(await readFile(new URL('source/' + lens.path, body)),
    await readFile(new URL('source/' + lens.labelPath, body), 'utf8'), lens));
  return required(parsed.get(lens.id));
}

test('67P numeric units and orientation agree with independent published control points', async () => {
  // Filacchione et al. 2016, Table 3 (SSA and slope), Table 4 (band depth).
  // DOI 10.1016/j.icarus.2016.02.055. These are rounded publication values,
  // not values generated by this decoder. The 2019 archive is not identical
  // to every 2016 GCP (see https://github.com/layoutit/cssEarth/blob/cc01831f595e0b73ab6699d6235cf7b466f76cfc/docs/comets/67P-VIRTIS.md); do not claim exact parity.
  const anchors = [
    ['albedo',16.5,24.5,.051,.0005], ['albedo',56,-12.5,.063,.0005], ['albedo',115,-11,.053,.0005],
    ['slope',16.5,24.5,17.99,.5], ['slope',115,-11,20.04,.5],
    ['absorption',56,-12.5,6.9,.05],
  ] as const;
  for (const [id, lon, lat, expected, tolerance] of anchors) {
    const lens = config.raster.scientific.find((l: { id: string|number; }) => l.id === id), { data } = await map(lens);
    assert.ok(Math.abs(data[scalarMapIndex(lon, lat, lens.grid)] - expected) <= tolerance, `${id} ${lon},${lat}: published numeric anchor`);
  }
  const ice = config.raster.scientific.find((l: { id: string; }) => l.id === 'ice'), { data, report } = await map(ice);
  assert.equal(ice.grid.latitudeFirst, -90);
  assert.equal(report.validZeroRows, 70957);
  assert.equal(report.maximum, 4, 'archive optical mixture fraction converts to percent, not 0.04 percent');
  assert.equal(data.filter(Number.isFinite).length, 162839);
});

test('67P VIRTIS atlases retain exact numeric colours and a hash-bound original-row index outside runtime', async () => {
  const { surfaces } = await json('prepared/surfaces.json'), runtime = await readFile(new URL('prepared/object.json', body), 'utf8');
  const assets = await json('inventory.json');
  for (const lens of config.raster.scientific.filter((lens: { format: string; }) => lens.format === 'pds3-scalar-map')) {
    const surface = surfaces.find((s:{id:string}) => s.id === lens.id), ref = surface.scalarMap.sampleSources;
    const bytes = await readFile(new URL('prepared/' + ref.file, body)), index = JSON.parse((bytes).toString('utf8'));
    assert.equal(bytes.length, ref.bytes); assert.equal(createHash('sha256').update(bytes).digest('hex'), ref.sha256);
    assert.equal(index.schema, 'cssearth-atlas-scalar-index@1'); assert.equal(index.encoding, 'gzip-u32le-base64');
    assert.equal(index.source.sha256, surface.source.sha256);
    const codes = gunzipSync(Buffer.from(index.data, 'base64'));
    const rgba = await sharp(new URL('public' + surface.surface.url, root).pathname).ensureAlpha().raw().toBuffer();
    assert.equal(codes.length, index.width * index.height * 4); assert.equal(rgba.length, codes.length);
    const { data } = await map(lens);
    const palette = Array.from({ length: 1024 }, (_, i) => colorForValue(lens.minimum + i / 1023 * (lens.maximum - lens.minimum), lens));
    let accepted = 0, compared = 0, zero = 0;
    for (let offset = 0; offset < codes.length; offset += 4) {
      const code = codes.readUInt32LE(offset); if (!code) continue;
      assert.ok(code <= data.length); const value = data[code - 1]; assert.ok(Number.isFinite(value));
      accepted++; if (value === 0) zero++;
      // Spread exact colour checks through each complete atlas without turning
      // preparation proof into millions of assertion allocations.
      if (accepted % 997 === 0) {
        const color = palette[Math.round(Math.max(0, Math.min(1, (value - lens.minimum) / (lens.maximum - lens.minimum))) * 1023)];
        assert.deepEqual([...rgba.subarray(offset, offset + 3)], color); compared++;
      }
    }
    const transfer = surface.surfaceSampling.transfer;
    assert.equal(accepted, transfer.sampledTexels - transfer.withheldTexels);
    assert.ok(compared > 200); assert.ok(transfer.withheldTriangleInteriorTexels > 0);
    if (lens.id === 'ice') assert.ok(zero > 1000, 'valid zero-ice cells remain visible');
    assert.ok(!runtime.includes(index.data)); assert.ok(!assets.assets.some((a:{filename:string}) => a.filename === ref.file));
    assert.equal(transfer.maximumAcceptedDistanceMeters, 50); assert.ok(transfer.maximumDistanceMeters <= 50);
  }
});
