import { describe, expect, it } from 'vitest'
import { distance, magnitude, scaled } from './__fixtures__/compare.js'
import { HORIZONS, PLAN_MARS_ECLIPTIC } from './__fixtures__/horizons.js'
import { icrfToEclipticJ2000, OBLIQUITY_J2000_RAD, RAD_PER_ARCSEC } from './angles.js'
import { M_PER_AU, M_PER_KM } from './units.js'
import {
  systemBarycentreHeliocentricAu,
  systemBarycentreVelocityAuPerDay,
  VSOP87A_BODY_KEYS,
  VSOP87A_TRUNCATION_BOUND_AU,
  VSOP87A_VALID_FROM_JD,
  VSOP87A_VALID_TO_JD,
  type Vsop87BodyKey,
} from './vsop87.js'

const AU_KM = M_PER_AU / M_PER_KM

/**
 * ERROR BUDGET, per body, in km of heliocentric position over 1900-2100.
 *
 *   budget = truncation bound + theory floor
 *
 * `truncation bound` is `VSOP87A_TRUNCATION_BOUND_AU`, generated by
 * `tools/generate-series.mjs` from the coefficients it dropped. It is the only
 * error this package adds.
 *
 * `theory floor` is how far the UNTRUNCATED VSOP87A series is from Horizons at
 * the seven fixture epochs — computed by evaluating all 4000-7500 terms of the
 * CDS files against the same fixtures. VSOP87 was fitted to DE200 in 1988;
 * Horizons serves DE441. For Mercury through Saturn this is the theory's own
 * residual; for Uranus and Neptune it is dominated by how much DE441 moved
 * those two orbits after 1988, which is why their budgets are the loose ones.
 *
 * Nothing here is tuned to make the test pass: the floor is a measurement of a
 * series this package does not ship, and the truncation bound is derived from
 * dropped coefficients. `REGRESSION_TOLERANCE_KM` below is the separate,
 * deliberately tight regression guard.
 */
const THEORY_FLOOR_KM: Record<Vsop87BodyKey, number> = {
  mercury: 9.3,
  venus: 17.1,
  emb: 19.1,
  mars: 123.0,
  jupiter: 1359.0,
  saturn: 1869.8,
  uranus: 17328.5,
  neptune: 48536.5,
}

/**
 * What this package actually achieves at the fixture epochs, plus 15 percent.
 *
 * The budget above is the claim; this is the guard. A budget alone cannot fail
 * usefully — Neptune's is 69 000 km, and a dropped periodic term would hide
 * inside it forever. These numbers are measured, and any change to the series,
 * the frame rotation or the evaluator moves one of them.
 */
const REGRESSION_TOLERANCE_KM: Record<Vsop87BodyKey, number> = {
  mercury: 67,
  venus: 55,
  emb: 42,
  mars: 125,
  jupiter: 2025,
  saturn: 3251,
  uranus: 23228,
  neptune: 55924,
}

const FIXTURE_OF: Record<Vsop87BodyKey, string> = {
  mercury: 'mercuryBarycentreHeliocentric',
  venus: 'venusBarycentreHeliocentric',
  emb: 'embHeliocentric',
  mars: 'marsBarycentreHeliocentric',
  jupiter: 'jupiterBarycentreHeliocentric',
  saturn: 'saturnBarycentreHeliocentric',
  uranus: 'uranusBarycentreHeliocentric',
  neptune: 'neptuneBarycentreHeliocentric',
}

const budgetKm = (key: Vsop87BodyKey): number => VSOP87A_TRUNCATION_BOUND_AU[key] * AU_KM + THEORY_FLOOR_KM[key]

describe('VSOP87A against JPL Horizons', () => {
  it.each(VSOP87A_BODY_KEYS)('places the %s system barycentre inside its budget', (key) => {
    const fixture = HORIZONS[FIXTURE_OF[key]]!
    expect(fixture.rows.length).toBe(7)
    let worst = 0
    for (const row of fixture.rows) {
      const computed = scaled(systemBarycentreHeliocentricAu(key, row.jdTdb), AU_KM)
      worst = Math.max(worst, distance(computed, row.positionKm))
    }
    expect(worst).toBeLessThan(REGRESSION_TOLERANCE_KM[key])
    // And the guard really is inside the claim, so the claim is not decoration.
    expect(REGRESSION_TOLERANCE_KM[key]).toBeLessThanOrEqual(budgetKm(key))
  })

  it.each(VSOP87A_BODY_KEYS)('matches %s velocity to 0.25 m/s', (key) => {
    const fixture = HORIZONS[FIXTURE_OF[key]]!
    let worstMetresPerSecond = 0
    for (const row of fixture.rows) {
      const computed = scaled(systemBarycentreVelocityAuPerDay(key, row.jdTdb), AU_KM)
      const kmPerDay = distance(computed, row.velocityKmPerDay)
      worstMetresPerSecond = Math.max(worstMetresPerSecond, (kmPerDay * 1000) / 86400)
    }
    // The velocity comes from differentiating the truncated series analytically,
    // so its error is the position error's derivative: dominated by the
    // fastest terms dropped, not by the largest. 0.25 m/s against orbital
    // speeds of 5-48 km/s is 5e-5 relative at worst (Neptune).
    expect(worstMetresPerSecond).toBeLessThan(0.25)
  })

  it('reproduces the two Mars states PLAN.md pins, in the plan\'s own ecliptic frame', () => {
    for (const row of PLAN_MARS_ECLIPTIC.rows) {
      const ecliptic = icrfToEclipticJ2000(systemBarycentreHeliocentricAu('mars', row.jdTdb))
      const errorKm = distance(scaled(ecliptic, AU_KM), scaled(row.positionAu, AU_KM))
      expect(errorKm).toBeLessThan(REGRESSION_TOLERANCE_KM.mars)
      const velocity = icrfToEclipticJ2000(systemBarycentreVelocityAuPerDay('mars', row.jdTdb))
      const velocityErrorMetresPerSecond = (distance(scaled(velocity, AU_KM), scaled(row.velocityAuPerDay, AU_KM)) * 1000) / 86400
      expect(velocityErrorMetresPerSecond).toBeLessThan(0.25)
    }
  })

  it('recovers the obliquity Horizons uses from a pair of its own fixtures', () => {
    // The same Mars state is in the fixtures twice: ICRF equatorial from
    // `marsBarycentreHeliocentric`, ecliptic from PLAN.md. One rotation about
    // +X takes one to the other, and its angle is the obliquity `angles.ts`
    // declares. This is why that constant is 84381.448" and not 84381.406".
    const equatorial = HORIZONS.marsBarycentreHeliocentric!.rows.find((row) => row.jdTdb === 2461041.5)!
    const ecliptic = PLAN_MARS_ECLIPTIC.rows[0]!
    const scaleToKm = AU_KM
    const ey = ecliptic.positionAu[1] * scaleToKm
    const ez = ecliptic.positionAu[2] * scaleToKm
    const recovered = Math.atan2(equatorial.positionKm[2] * ey - equatorial.positionKm[1] * ez, equatorial.positionKm[1] * ey + equatorial.positionKm[2] * ez)
    expect(Math.abs(recovered - OBLIQUITY_J2000_RAD) / RAD_PER_ARCSEC).toBeLessThan(0.001)
  })
})

describe('VSOP87A as a series', () => {
  it('stays inside Mercury\'s perihelion and aphelion over a full orbit', () => {
    // A full Mercury orbit sampled finely: 88 days at 3-hour steps. Perihelion
    // and aphelion are published numbers, and a series with a corrupted term
    // leaves the annulus between them.
    let closest = Infinity
    let farthest = 0
    let previous = systemBarycentreHeliocentricAu('mercury', 2451545)
    let worstStepKm = 0
    for (let i = 1; i <= 704; i++) {
      const epoch = 2451545 + i * 0.125
      const position = systemBarycentreHeliocentricAu('mercury', epoch)
      const r = magnitude(position)
      closest = Math.min(closest, r)
      farthest = Math.max(farthest, r)
      worstStepKm = Math.max(worstStepKm, distance(scaled(position, AU_KM), scaled(previous, AU_KM)))
      previous = position
    }
    expect(closest).toBeGreaterThan(0.3074)
    expect(closest).toBeLessThan(0.3076)
    expect(farthest).toBeGreaterThan(0.4666)
    expect(farthest).toBeLessThan(0.4668)
    // Mercury's fastest speed is 58.98 km/s; 0.125 days of it is 637 000 km.
    // A step above that means the series jumped, which is what a broken
    // frequency looks like.
    expect(worstStepKm).toBeLessThan(637000)
    expect(worstStepKm).toBeGreaterThan(300000)
  })

  it('is continuous in time to the precision of its own derivative', () => {
    // Central difference against the analytic rate, for every body, at an epoch
    // with no special structure. This is what catches a rate expression that is
    // right at alpha = 0 and wrong for the Poisson terms.
    const epoch = 2469807.5
    // A sixteenth of a day, and a power of two on purpose: a Julian Date near
    // 2.47e6 has a float64 spacing of 4.7e-10 days, so `epoch + h` for a step
    // like 1/48 is rounded, and the rounding alone puts a 1.1e-8 floor under
    // any difference quotient. At 1/16 the sum is exact and the floor is gone.
    const h = 1 / 16
    for (const key of VSOP87A_BODY_KEYS) {
      // Five-point stencil. A three-point one is not good enough to be a test:
      // its own O(h^2) truncation error against Mercury's 88-day period is
      // 6e-7 relative, which would swallow a wrong Poisson-term derivative.
      const far = systemBarycentreHeliocentricAu(key, epoch + 2 * h)
      const forward = systemBarycentreHeliocentricAu(key, epoch + h)
      const backward = systemBarycentreHeliocentricAu(key, epoch - h)
      const farBack = systemBarycentreHeliocentricAu(key, epoch - 2 * h)
      const numeric = [0, 1, 2].map((i) => (-far[i]! + 8 * forward[i]! - 8 * backward[i]! + farBack[i]!) / (12 * h))
      const analytic = systemBarycentreVelocityAuPerDay(key, epoch)
      const relative = distance(numeric, analytic) / magnitude(analytic)
      expect(relative).toBeLessThan(1e-9)
    }
  })

  it('declares a validity window that contains every fixture epoch', () => {
    for (const key of VSOP87A_BODY_KEYS) {
      for (const row of HORIZONS[FIXTURE_OF[key]]!.rows) {
        expect(row.jdTdb).toBeGreaterThanOrEqual(VSOP87A_VALID_FROM_JD)
        expect(row.jdTdb).toBeLessThanOrEqual(VSOP87A_VALID_TO_JD)
      }
    }
  })

  it('rejects an unknown body rather than returning the origin', () => {
    expect(() => systemBarycentreHeliocentricAu('pluto' as Vsop87BodyKey, 2451545)).toThrow(/unknown VSOP87A body/)
  })
})
