import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {preparePhotographicAtmosphere} from '../../../../tools/objects/terrestrial-layers/photographic-atmosphere.mts';
import {createEllipsoidGeometry} from '../../../../tools/objects/terrestrial-layers/ellipsoid-geometry.mts';
const sourceDirectory=fileURLToPath(new URL('../../../../src/planets/mars/source/',import.meta.url));
const read=async p=>JSON.parse(await readFile(new URL('../../../../src/planets/mars/'+p,import.meta.url)));
export const runtimeDefinition=await read('prepared/runtime.json'),objectControls=await read('prepared/controls.json');
export const PREPARED_MARS_SCENE=await read('prepared/body.json'),PREPARED_MARS_CAMERA=await read('prepared/camera.json');
export const PREPARED_MARS_LIGHTING=await read('prepared/lighting.json'),PREPARED_MARS_LENSES=await read('prepared/surface-lenses.json');
export const PREPARED_MARS_SKY_SUN=await read('prepared/sun.json'),PREPARED_MARS_STARFIELD=await read('prepared/sky.json');
export const PREPARED_MARS_TITLE=(await read('prepared/content.json')).title,PREPARED_MARS_PANEL=(await read('source/content/object.json')).panel;
const shape=await read('source/preparation/ellipsoid.json'),profile=await read('source/preparation/atmosphere.json');
const a=await preparePhotographicAtmosphere({sourceDirectory,profile,geometry:{...shape,...createEllipsoidGeometry(shape)}});
export const MARS_ATMOSPHERE_COLOR=a.ATMOSPHERE_COLOR,MARS_ATMOSPHERE_PROFILE=a.ATMOSPHERE_PROFILE,MARS_ATMOSPHERE_RESPONSE=a.ATMOSPHERE_RESPONSE;
export const MARS_MATERIAL_COVERAGE_SCALE=a.MATERIAL_COVERAGE_SCALE,MARS_MATERIAL_CONTENT_SCALE=a.MATERIAL_CONTENT_SCALE;
export const MARS_PUBLISHED_ATMOSPHERE_REFERENCE=a.PUBLISHED_ATMOSPHERE_REFERENCE;
export const prepareMarsMaterialFrame=a.prepareMaterialFrame,prepareMarsAtmosphereFrame=a.prepareAtmosphereFrame;
export const MARS_MATERIAL_OUTER_RADIUS=a.MATERIAL_OUTER_RADIUS,MARS_SURFACE_REFERENCE_COLOR=a.SURFACE_REFERENCE_COLOR;
export const applyMarsLinearLight=a.applyLinearLight,measurePublishedMarsAtmosphereReference=a.measurePublishedAtmosphereReference;
export const prepareMarsProjectedSilhouette=a.prepareProjectedSilhouette;
