import {parseTitle,parsePanel} from '../../fixtures/prepared-schemas.mts';
import {shape as recordShape,number,text} from '../../../../tools/objects/terrestrial-layers/source-records.mts';
import {parseMarsScene,parseMarsCamera,parseMarsLighting,parseMarsLenses,parseMarsSkyMetadata,parseMarsSunMetadata} from './prepared-schema.mts';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {validatePreparedCubicSky} from '../../../../src/platform/cubic-sky-contract.mts';
import {validateDirectionalSunPlan} from '../../../../src/platform/directional-sun-contract.mts';
import {requirePreparedData} from '../../../../src/platform/prepared-presentation-contract.mts';
import {parsePreparedObjectRuntime,requireControls} from '../../../../src/renderers/css/dist/index.js';
import {preparePhotographicAtmosphere} from '../../../../tools/objects/terrestrial-layers/photographic-atmosphere.mts';
import {createEllipsoidGeometry} from '../../../../tools/objects/terrestrial-layers/ellipsoid-geometry.mts';
import {parseEllipsoidProfile} from '../../../../tools/objects/terrestrial-layers/ellipsoid-geometry.mts';
import {parsePhotographicAtmosphere} from '../../../../tools/objects/terrestrial-layers/photographic-atmosphere-source.mts';
import {requireFiniteNumber,requireRecord} from '../../../../tools/source-values.mts';
const sourceDirectory=fileURLToPath(new URL('../../../../src/planets/mars/source/',import.meta.url));
const read=async (path:string):Promise<unknown>=>{const value:unknown=JSON.parse(await readFile(new URL('../../../../src/planets/mars/'+path,import.meta.url),'utf8'));requirePreparedData(value,`Mars fixture ${path}`);return value;};
export const runtimeDefinition=parsePreparedObjectRuntime(await read('prepared/runtime.json'));
const checkedControls=(value:unknown)=>{requireControls(value);return value;};
export const objectControls=checkedControls(await read('prepared/controls.json'));
export const PREPARED_MARS_SCENE=parseMarsScene(await read('prepared/body.json')),PREPARED_MARS_CAMERA=parseMarsCamera(await read('prepared/camera.json'));
export const PREPARED_MARS_LIGHTING=parseMarsLighting(await read('prepared/lighting.json')),PREPARED_MARS_LENSES=parseMarsLenses(await read('prepared/surface-lenses.json'));
const sunData=await read('prepared/sun.json'),skyData=await read('prepared/sky.json');
const parsedSun=validateDirectionalSunPlan(sunData),sunMetadata=parseMarsSunMetadata(sunData);
export const PREPARED_MARS_SKY_SUN={...parsedSun,...sunMetadata,asset:{...parsedSun.asset,...sunMetadata.asset},projection:{...parsedSun.projection,...sunMetadata.projection}};
export const PREPARED_MARS_STARFIELD={...validatePreparedCubicSky(skyData,{requireSun:false}),...parseMarsSkyMetadata(skyData)};
const preparedContent=requireRecord(await read('prepared/content.json'),'Mars prepared content'),sourceContent=requireRecord(await read('source/content/object.json'),'Mars source content');
export const PREPARED_MARS_TITLE=parseTitle(preparedContent.title),PREPARED_MARS_PANEL={...parsePanel(sourceContent.panel),...recordShape({schema:text,planetId:text,sources:recordShape({editorial:recordShape({sourceId:number,sourceUrl:text,modified:text}),renderedMoons:recordShape({count:number,physicalParameters:text,meanElements:text})})})(sourceContent.panel)};
const shape=parseEllipsoidProfile(await read('source/preparation/ellipsoid.json')),profile=parsePhotographicAtmosphere(await read('source/preparation/atmosphere.json'));
const a=await preparePhotographicAtmosphere({sourceDirectory,profile,geometry:{...shape,...createEllipsoidGeometry(shape)}});
export const MARS_ATMOSPHERE_COLOR=a.ATMOSPHERE_COLOR,MARS_ATMOSPHERE_PROFILE=a.ATMOSPHERE_PROFILE,MARS_ATMOSPHERE_RESPONSE=a.ATMOSPHERE_RESPONSE;
export const MARS_MATERIAL_COVERAGE_SCALE=a.MATERIAL_COVERAGE_SCALE,MARS_MATERIAL_CONTENT_SCALE=a.MATERIAL_CONTENT_SCALE;
export const MARS_PUBLISHED_ATMOSPHERE_REFERENCE=a.PUBLISHED_ATMOSPHERE_REFERENCE;
export const prepareMarsMaterialFrame=a.prepareMaterialFrame,prepareMarsAtmosphereFrame=a.prepareAtmosphereFrame;
export const MARS_MATERIAL_OUTER_RADIUS=a.MATERIAL_OUTER_RADIUS,MARS_SURFACE_REFERENCE_COLOR=a.SURFACE_REFERENCE_COLOR;
export const applyMarsLinearLight=a.applyLinearLight,measurePublishedMarsAtmosphereReference=a.measurePublishedAtmosphereReference;
export const prepareMarsProjectedSilhouette=a.prepareProjectedSilhouette;
