export const SHELL_ICON_SOURCES = Object.freeze({
  schema: "cssearth-shell-icon-sources@1",
  family: "Wikimedia Commons Unicode symbols",
  recipe: Object.freeze({
    width: 20,
    height: 20,
    fill: "#aaa",
  }),
  icons: Object.freeze([
    Object.freeze({
      key: "facts",
      label: "Factsheet",
      glyph: "▦",
      sourceName: "U+25A6.svg",
      file: "symbol-square-crosshatch-fill.svg",
      outputFile: "icon-facts.svg",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:U%2B25A6.svg",
      author: "Sarang",
      license: "Public domain",
      licenseUrl: "https://commons.wikimedia.org/wiki/File:U%2B25A6.svg#Licensing",
      sourceSha256: "41ff10019ffc54e46f4d143ec531003e9629aaca8cabeafefbee064530781dd8",
    }),
    Object.freeze({
      key: "reflectance",
      label: "Reflectance spectrum",
      glyph: "∿",
      sourceName: "Sine wave.svg",
      file: "symbol-sine-wave.svg",
      outputFile: "icon-reflectance.svg",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Sine_wave.svg",
      author: "Zorgit",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
      sourceSha256: "13d329b1a0eedf3b04535cdb725c502530559aa42f0dddff67daec2e9103ea43",
    }),
    Object.freeze({
      key: "temperaturePressure",
      label: "Temperature–pressure profile",
      glyph: "∝",
      sourceName: "Proportional To in Linux Biolinum Regular - U+221D.svg",
      file: "symbol-proportional-to.svg",
      outputFile: "icon-temperature-pressure.svg",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Proportional_To_in_Linux_Biolinum_Regular_-_U%2B221D.svg",
      author: "Philipp H. Poll; SVG by MS Sakib",
      license: "SIL Open Font License 1.1",
      licenseUrl: "https://openfontlicense.org/open-font-license-official-text/",
      sourceSha256: "7f7f39cce5f6a6cae40d660a94dc88603542c2a2817801576f511d2291aa5972",
    }),
    Object.freeze({
      key: "photometricPhase",
      label: "Photometric phase curve",
      glyph: "◔",
      sourceName: "U+25D4.svg",
      file: "symbol-quarter-phase.svg",
      outputFile: "icon-photometric-phase.svg",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:U%2B25D4.svg",
      author: "Sarang",
      license: "Public domain",
      licenseUrl: "https://commons.wikimedia.org/wiki/File:U%2B25D4.svg#Licensing",
      sourceSha256: "9e82e45de344096d89812070dbeb206e3637e9a335adfcc5058e3b169ad9b515",
    }),
    Object.freeze({
      key: "lenses",
      label: "Surface lens",
      glyph: "◐",
      sourceName: "GNU Unifont - U+25D0.svg",
      file: "symbol-half-black-circle.svg",
      outputFile: "icon-surface-lens.svg",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:GNU_Unifont_-_U%2B25D0.svg",
      author: "Roman Czyborra / Unifoundry; SVG by MS Sakib",
      license: "SIL Open Font License 1.1",
      licenseUrl: "https://openfontlicense.org/open-font-license-official-text/",
      sourceSha256: "a0be132b83f2b7b3a4ef3ec6f9ee159a707eae0d254a2f08db41e3c749bee0e8",
    }),
    Object.freeze({
      key: "resources",
      label: "Sources & Resources",
      glyph: "※",
      sourceName: "Reference Mark in Linux Biolinum Regular - U+203B.svg",
      file: "symbol-reference-mark.svg",
      outputFile: "icon-sources-resources.svg",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Reference_Mark_in_Linux_Biolinum_Regular_-_U%2B203B.svg",
      author: "Philipp H. Poll; SVG by MS Sakib",
      license: "SIL Open Font License 1.1",
      licenseUrl: "https://openfontlicense.org/open-font-license-official-text/",
      sourceSha256: "11e95dcbfcace65fb714d264032c772178ae1dfdfd1bfa31e10e12e2b6bc0556",
    }),
  ]),
});
