export { createObjectRuntime } from './runtime/object-runtime.js';
export { readObjectDiagnostics } from './runtime/object-diagnostics.js';
export type { ObjectRuntimeDiagnostics } from './runtime/object-diagnostics.js';
export type { ObjectRuntimeDefinition, ObjectMountOptions, ObjectRuntimeView, ObjectRuntimeCapabilities } from './runtime/object-runtime-types.js';
export type { ObjectRuntimeServices } from './runtime/object-runtime.js';
export { OBJECT_RUNTIME_SCHEMA, initialObjectSelection, requireObjectControls, requireObjectAction,
  requireObjectRuntimeDefinition, objectCycleStates, reduceObjectSelection } from './runtime/object-contract.js';
export type { ObjectControls, ObjectAction, ObjectSelection, LensControl, SettingControl } from './runtime/object-contract.js';
export type { RuntimePolicy } from './navigation/runtime-policy.js';
export type { CameraPlan, CameraPose } from './navigation/types.js';
export type { PerspectiveWorldContext } from './navigation/perspective-dolly.js';
export { formatSharedView, parseSharedView } from './navigation/view-url.js';
export type { SharedView, SharedPlayback } from './navigation/view-url.js';
export type { PreparedPresentationDefinition, PreparedView, PreparedPresentationPlan } from './rendering/prepared-presentation.js';
export type { PreparedAssets } from './rendering/prepared-residency.js';
export { resolvePreparedAssetUrl, rewritePreparedStyleUrls, parsePreparedAssetOrigin } from './rendering/prepared-asset-origin.js';
export type { PreparedAssetOrigin } from './rendering/prepared-asset-origin.js';
export { CANONICAL_PREPARED_IMAGE_DENSITY } from './rendering/prepared-object-assets.js';
export { loadPreparedCssObject, PREPARED_CSS_OBJECT_FORMAT } from './loader.js';
export type { PreparedCssTransport } from './loader.js';
export { parsePreparedObjectRuntime } from './validation/index.js';
export type { ObjectDatasets } from './runtime/object-scene.js';
export type { ObjectSharedView, ObjectSceneLifecycle } from './runtime/object-scene.js';
export { loadNavigableObject } from './runtime/navigable-object-mount.js';
export { parsePreparedWorldCameraFrame } from './validation/world-frame.js';
export { worldCameraFromCenteredPresentation, presentWorldCamera } from './navigation/world-camera.js';
export { cssCameraAxesFromOrientation, cssViewFromOrientation, validateWorldReflection, worldQuaternionFromRotation, worldRotationFromQuaternion, rotateWorldPosition } from './navigation/world-camera-math.js';
export type { PreparedWorldCameraFrame, WorldCameraPose } from './navigation/world-camera.js';
export type { ObjectWorldNavigation, ObjectWorldNavigationListener } from './runtime/world-navigation-types.js';
export { createWorldSelectionTarget } from './navigation/selection-target.js';
export { preparedObjectCapabilities } from './runtime/capabilities.js';
export { mountSurfaceFeatureLabels } from './labels/surface-feature-labels.js';
export { labelOcclusionFor } from './labels/label-occlusion.js';
export { createOpacityFader } from './stars/opacity-fader.js';
export { parsePreparedSurfaceFeatureCatalog, loadPreparedSurfaceFeatureCatalog, loadPreparedSurfaceFeatureBank, loadPreparedSurfaceFeature } from './labels/surface-feature-catalog.js';
export { surfaceFeatureCaption } from './labels/surface-feature-caption.js';
export { publishPreparedNativeView } from './rendering/prepared-native-view.js';
export type { PreparedSurfaceFeaturePlan, PreparedSurfaceFeatureCatalog, PreparedSurfaceFeature, SurfaceFeatureLayerRuntime, SurfaceFeatureLayerStats, SurfaceFeatureNavigationRuntime } from './labels/surface-feature-types.js';
export { savedWorldCamera } from './navigation/saved-world-camera.js';
export { mountPreparedCssVolume } from './volume/prepared-volume-runtime.js';
export { validatePreparedCssVolume } from './volume/validation.js';
export { loadPreparedCssVolume } from './volume/loader.js';
export { decodePreparedCssPointField, parsePreparedCssPointFieldManifest } from './stars/validation.js';
export { loadPreparedCssPointField } from './stars/loader.js';
export type { PreparedCssPointField, PreparedCssPointFieldManifest, PreparedPointFieldNode, PreparedPointFieldResource, PreparedPointFieldStar, PointFieldRgb, PointFieldVector } from './stars/types.js';
export { createWorldContextObjectRuntime } from './universe/world-context/world-context-runtime.js';
export { worldCameraOf } from './universe/world-camera.js';
export { mountWorldContextPointSource, worldContextPointAppearance, worldContextPointSourceFade, worldContextPointSourceGain } from './universe/world-context/world-context-point-source.js';
export type { PointSourcePublication, WorldContextPointAppearance, WorldContextPointSourceGain } from './universe/world-context/world-context-point-source.js';
export { decodeWorldOrbits, orbitVertices, parsePreparedSystemViews, parsePreparedWorldContext, parsePreparedWorldContextSummary } from './prepared-data/world-context.js';
// Named so declaration builds of site modules that return world-context handles can reference them.
export type { WorldBodyPresentation } from './universe/world-context/world-context-planner.js';
export type { QueuedRequest } from './navigation/world-frame-queue.js';
export type { PreparedContextFocus, PreparedContextPointSource, PreparedWorldContext, PreparedWorldContextGeometry } from './prepared-data/world-context.js';
export type { PreparedCssVolume, PreparedVolumeCameraTransform, PreparedVolumeLeaf, PreparedVolumeLeafStyle, PreparedVolumeMountOptions, PreparedVolumeRuntime, PreparedVolumeStack, VolumeCameraPublication, VolumeAxis } from './volume/types.js';
export { prepareObjectResources } from './runtime/prepared-resource-lease.js';
export { createPreparedObjectNavigation } from './runtime/prepared-object-navigation.js';
export { createPreparedUniverse } from './universe/prepared-universe-runtime.js';
export { parseLensBillboards } from './universe/lens-billboards.js';

export { requireAssets } from './validation/resources-tree.js';
export { requireControls } from './validation/camera-controls.js';

export { PREPARED_INTERIOR_DISC_SIZE } from './rendering/prepared-interior-disc.js';
export { publishDatasetSelection } from './rendering/object-control-binding.js';
