import { fileURLToPath } from 'node:url';

export default {
  entry: {
    'platform/object-orbit': fileURLToPath(new URL('./navigation/object-orbit.ts', import.meta.url)),
    'platform/camera-input': fileURLToPath(new URL('./navigation/camera-input.ts', import.meta.url)),
    'platform/camera-layout': fileURLToPath(new URL('./navigation/camera-layout.ts', import.meta.url)),
    'platform/prepared-wheel-zoom': fileURLToPath(new URL('./navigation/prepared-wheel-zoom.ts', import.meta.url)),
    "platform/prepared-residency": fileURLToPath(new URL("./rendering/prepared-residency.ts", import.meta.url)),
    'platform/object-contract': fileURLToPath(new URL('./runtime/object-contract.ts', import.meta.url)),
    'platform/prepared-image-store': fileURLToPath(new URL('./rendering/prepared-image-store.ts', import.meta.url)),
    'platform/object-selection-runtime': fileURLToPath(new URL('./rendering/object-selection-runtime.ts', import.meta.url)),
    'platform/prepared-presentation': fileURLToPath(new URL('./rendering/prepared-presentation.ts', import.meta.url)),
    'platform/perspective-dolly': fileURLToPath(new URL('./navigation/perspective-dolly.ts', import.meta.url)),
    'platform/solar-view-direction': fileURLToPath(new URL('./solar-system/solar-view-direction.ts', import.meta.url)),
    'platform/prepared-object-assets': fileURLToPath(new URL('./rendering/prepared-object-assets.ts', import.meta.url)),
    'platform/wmts-image': fileURLToPath(new URL('./paging/wmts-image.ts', import.meta.url)),
    'platform/wms-image': fileURLToPath(new URL('./paging/wms-image.ts', import.meta.url)),
    'platform/prepared-block': fileURLToPath(new URL('./prepared-data/prepared-block.ts', import.meta.url)),
    'platform/prepared-camera-runtime': fileURLToPath(new URL('./rendering/prepared-camera-runtime.ts', import.meta.url)),
    'platform/surface-fly-to': fileURLToPath(new URL('./navigation/surface-fly-to.ts', import.meta.url)),
    'platform/directional-sun-coordinate': fileURLToPath(new URL('./solar-system/directional-sun-coordinate.ts', import.meta.url)),
    index: fileURLToPath(new URL('./index.ts', import.meta.url)),
    universe: fileURLToPath(new URL('./universe/index.ts', import.meta.url)),
    navigation: fileURLToPath(new URL('./navigation/index.ts', import.meta.url)),
    preparation: fileURLToPath(new URL('./preparation.ts', import.meta.url)),
    testing: fileURLToPath(new URL('./testing.ts', import.meta.url)),
    'scene-native-waits': fileURLToPath(new URL('./runtime/scene-native-waits.ts', import.meta.url)),
    'world-context-planner-worker': fileURLToPath(new URL('./universe/world-context-planner-worker.ts', import.meta.url)),
    'prepared-object-worker': fileURLToPath(new URL('./prepared-object-worker.ts', import.meta.url)),
  },
  outDir: fileURLToPath(new URL('./dist', import.meta.url)),
  tsconfig: fileURLToPath(new URL('./tsconfig.json', import.meta.url)),
  format: ['esm'],
  external: ['@cssearth/engine', '@cssearth/objects', '@layoutit/polycss'],
  dts: true,
  sourcemap: process.env.CSSEARTH_PERFORMANCE_SOURCEMAPS === '1',
  clean: true,
  target: 'es2022',
};
