import { CHART_ASSETS_SCHEMA } from './presentation-recipe-schemas.ts';
import { parseMeasuredSpectrum, type MeasuredSpectrumRecipe } from './chart-measured-spectrum.ts';
import { parseRetrievedProfile, type RetrievedProfileRecipe } from './chart-retrieved-profile.ts';
import { parseSystemOrbits, type SystemOrbitsRecipe } from './chart-system-orbits.ts';
import { parseSpectrumRecipe, type SpectrumRecipe } from './chart-spectrum.ts';
type JsonMap=Record<string,unknown>;
interface Identity {id:string;title:string;description:string;output:string;metadata:JsonMap;}
type Spectrum=SpectrumRecipe;
interface Pressure extends Identity {kind:'pressure';source:string;layerCount:number;temperatureMinimum:number;temperatureMaximum:number;temperatureRoundingStep?:number;includePressureRangeMetadata?:boolean;pressureTicks:{pressure:number;label:string}[];}
interface Phase extends Identity {kind:'phase';sampleCount:number;maximumAngleDegrees:number;segments:({maximumAngleDegrees:number;coefficients:number[];kind:'polynomialMagnitude'}|{maximumAngleDegrees:number;coefficients:number[];kind:'albedoPolynomialMagnitude';constant:number})[];}
interface FoldedTransit extends Identity {kind:'folded-transit';planet:string;sources:string[];durationHours:number;binMinutes:number;alignMinutes?:number;notes:string[];}
interface LightCurve extends Identity {kind:'light-curve';source:string;timeField:string;fluxField:string;maskField?:string;binMinutes:number;axisLabel:string;events:{time:number;label:string}[];}
export interface ChartAssetRecipe {schema:typeof CHART_ASSETS_SCHEMA;publicBase:string;charts:(Spectrum|Pressure|Phase|LightCurve|FoldedTransit|MeasuredSpectrumRecipe|RetrievedProfileRecipe|SystemOrbitsRecipe)[];gallery?:{source:string;schema:string;itemCount:number};}
function record(value:unknown,label:string):JsonMap {if(!value||typeof value!=='object'||Array.isArray(value))throw new TypeError(`${label} must be an object.`);return value as JsonMap;}
function string(value:unknown,label:string):asserts value is string {if(typeof value!=='string'||!value.trim())throw new TypeError(`${label} must be text.`);}
export function chartSourcePath(value:string):string {if(value.startsWith('/')||value.includes('\\')||value.split('/').includes('..'))throw new TypeError('Unsafe chart source path.');return value;}
function numericArray(value:unknown,label:string):number[]{if(!Array.isArray(value)||value.some(item=>typeof item!=='number'||!Number.isFinite(item)))throw new TypeError(`${label} must contain finite samples.`);return value;}
export function parseChartAssetRecipe(value:unknown):ChartAssetRecipe {
 const recipe=record(value,'charts');if(recipe.schema!==CHART_ASSETS_SCHEMA||!Array.isArray(recipe.charts))throw new TypeError('Unknown chart recipe schema.');string(recipe.publicBase,'publicBase');if(!recipe.publicBase.startsWith('/')||!recipe.publicBase.endsWith('/'))throw new TypeError('Chart asset base must be an absolute URL prefix.');
 for(const value of recipe.charts){const chart=record(value,'chart');for(const key of ['id','title','description','output'])string(chart[key],key);chartSourcePath(String(chart.output));record(chart.metadata,'metadata');if(!['spectrum','pressure','phase','light-curve','measured-spectrum','retrieved-profile','system-orbits','folded-transit'].includes(String(chart.kind)))throw new TypeError(`${String(chart.id)}: unknown chart operator ${String(chart.kind)}.`);
  if(chart.kind==='measured-spectrum')parseMeasuredSpectrum(chart);
  if(chart.kind==='retrieved-profile')parseRetrievedProfile(chart);
  if(chart.kind==='system-orbits')parseSystemOrbits(chart);
  if(chart.kind==='folded-transit'){string(chart.planet,'planet');if(!Array.isArray(chart.sources)||!chart.sources.length)throw new TypeError(`${String(chart.id)}: a folded transit names its light-curve files.`);for(const source of chart.sources){string(source,'light-curve source');chartSourcePath(source);}if(typeof chart.durationHours!=='number'||!(chart.durationHours>0)||typeof chart.binMinutes!=='number'||!(chart.binMinutes>0)||!Array.isArray(chart.notes))throw new TypeError(`${String(chart.id)}: a folded transit needs a positive duration, bin width and notes.`);if(chart.alignMinutes!==undefined&&(typeof chart.alignMinutes!=='number'||!(Math.abs(chart.alignMinutes)<=720)))throw new TypeError(`${String(chart.id)}: alignMinutes is a shift of at most 720 minutes, not ${String(chart.alignMinutes)}.`);}
  if(chart.kind==='light-curve'){for(const key of ['source','timeField','fluxField','axisLabel'])string(chart[key],key);if(chart.maskField!==undefined)string(chart.maskField,'maskField');if(typeof chart.binMinutes!=='number'||!(chart.binMinutes>0)||!Array.isArray(chart.events))throw new TypeError('Invalid light curve profile.');for(const value of chart.events){const event=record(value,'event');if(typeof event.time!=='number'||!Number.isFinite(event.time))throw new TypeError('Invalid light curve event.');string(event.label,'event label');}}
  if(chart.kind==='spectrum')parseSpectrumRecipe(chart, 'chart-assets');
  if(chart.kind==='pressure'){string(chart.source,'source');if(typeof chart.layerCount!=='number'||chart.layerCount<2||typeof chart.temperatureMinimum!=='number'||typeof chart.temperatureMaximum!=='number'||!Array.isArray(chart.pressureTicks)||(chart.temperatureRoundingStep!==undefined&&(typeof chart.temperatureRoundingStep!=='number'||!Number.isFinite(chart.temperatureRoundingStep)||chart.temperatureRoundingStep<=0))||(chart.includePressureRangeMetadata!==undefined&&typeof chart.includePressureRangeMetadata!=='boolean'))throw new TypeError('Invalid pressure profile.');}
  if(chart.kind==='phase'){if(typeof chart.sampleCount!=='number'||!Number.isSafeInteger(chart.sampleCount)||chart.sampleCount<3||typeof chart.maximumAngleDegrees!=='number'||chart.maximumAngleDegrees<=0||chart.maximumAngleDegrees>180||!Array.isArray(chart.segments)||!chart.segments.length)throw new TypeError('Invalid phase model.');let previous=0;for(const value of chart.segments){const segment=record(value,'segment');if(typeof segment.maximumAngleDegrees!=='number'||segment.maximumAngleDegrees<=previous||!['polynomialMagnitude','albedoPolynomialMagnitude'].includes(String(segment.kind)))throw new TypeError('Invalid phase segment.');numericArray(segment.coefficients,'coefficients');if(segment.kind==='albedoPolynomialMagnitude'&&(typeof segment.constant!=='number'||!Number.isFinite(segment.constant)))throw new TypeError('Invalid phase constant.');previous=segment.maximumAngleDegrees;}if(previous!==chart.maximumAngleDegrees)throw new TypeError('Phase segments do not cover the model.');}
 }
 if(recipe.gallery!==undefined){const gallery=record(recipe.gallery,'gallery');string(gallery.source,'gallery.source');string(gallery.schema,'gallery.schema');if(typeof gallery.itemCount!=='number'||!Number.isSafeInteger(gallery.itemCount)||gallery.itemCount<1)throw new TypeError('Gallery item count is invalid.');}
 return recipe as unknown as ChartAssetRecipe;
}
