import fs from 'node:fs';import sharp from 'sharp';import crypto from 'node:crypto';
import {cataloguePixel} from '@cssearth/nebula-reconstruction/registration/fixed-catalogue';
import {fitDensitySimilarity,projectSimilarity,fitScore,type DensityFitInput} from '@cssearth/nebula-reconstruction/registration/density-similarity';
import { validateImageWcs } from '@cssearth/bake/volume';
import {parseDensityVolumeObjectDescriptor} from '@cssearth/objects';
function record(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Expected object');return value as Record<string,unknown>;}
function text(value:unknown):string{if(typeof value!=='string'||!value)throw Error('Expected path/hash');return value;}
function number(value:unknown):number{if(typeof value!=='number'||!Number.isFinite(value))throw Error('Expected finite number');return value;}
function pair(value:unknown):[number,number]{if(!Array.isArray(value)||value.length!==2)throw Error('Expected pair');return [number(value[0]),number(value[1])];}
function triple(value:unknown):[number,number,number]{if(!Array.isArray(value)||value.length!==3)throw Error('Expected triple');return [number(value[0]),number(value[1]),number(value[2])];}
const configPath=process.argv[2];if(!configPath||process.argv[3])throw Error('Usage: fit-density-placement <fit.json>');
const config=record(JSON.parse(fs.readFileSync(configPath,'utf8')));if(config.schema!=='cssearth-density-placement-fit@1')throw Error('Invalid fit schema');
const image=record(config.image),w=record(image.wcs);if(w.projection!=='TAN'||w.coordinateFrame!=='ICRS')throw Error('Fit target requires fixed ICRS TAN WCS');
const source={path:text(image.path),sha256:text(image.sha256),wcs:{projection:'TAN' as const,coordinateFrame:'ICRS' as const,referenceDimension:pair(w.referenceDimension),referencePixel:pair(w.referencePixel),referenceValueDeg:pair(w.referenceValueDeg),scaleDeg:pair(w.scaleDeg),rotationDeg:number(w.rotationDeg)}};
validateImageWcs(source.wcs);const sourceDirectory=text(config.sourceDirectory),particlePath=text(config.particlesPath),outputPath=text(config.outputPath),comparisonPath=text(config.comparisonPath);
const descriptor=parseDensityVolumeObjectDescriptor(JSON.parse(fs.readFileSync(text(config.descriptorPath),'utf8'))).volume;
for(const [path,pin] of [[source.path,source.sha256],[particlePath,text(config.particlesSha256)]])if(crypto.createHash('sha256').update(fs.readFileSync(path!)).digest('hex')!==pin)throw Error('Source hash mismatch');
const {data,info}=await sharp(source.path).resize(1024).greyscale().blur(8).raw().toBuffer({resolveWithObject:true});
const n=number(config.gridSize),extent=number(config.extentKpc),target=new Float32Array(n*n),mask=new Uint8Array(n*n),q=descriptor.localToReferenceXyzw;
function rotate(x:number,y:number){const [qx,qy,qz,qw]=q;const tx=-2*qz*y,ty=2*qz*x,tz=2*(qx*y-qy*x);return [x+qw*tx+qy*tz-qz*ty,y+qw*ty+qz*tx-qx*tz,qw*tz+qx*ty-qy*tx];}
for(let y=0;y<n;y++)for(let x=0;x<n;x++){const local=rotate(((x+.5)/n-.5)*extent,((y+.5)/n-.5)*extent);const ray=local.map((v,i)=>v*descriptor.metersPerUnit+descriptor.originM[i]);const length=Math.hypot(...ray),ra=Math.atan2(ray[1]!,ray[0]!)*180/Math.PI,dec=Math.asin(ray[2]!/length)*180/Math.PI;const p=cataloguePixel(ra,dec,source.wcs,info.width,info.height),px=Math.round(p[0]),py=Math.round(p[1]);if(px>=0&&py>=0&&px<info.width&&py<info.height){mask[y*n+x]=1;target[y*n+x]=data[py*info.width+px]!;}}
const values=[...target].filter((_,i)=>mask[i]).sort((a,b)=>a-b),floor=values[Math.floor(values.length*.15)]!,ceiling=values[Math.floor(values.length*.995)]!;let sum=0,cx=0,cy=0;
for(let y=0;y<n;y++)for(let x=0;x<n;x++){const i=y*n+x;target[i]=mask[i]?Math.max(0,Math.min(target[i]!,ceiling)-floor):0;sum+=target[i]!;cx+=target[i]!*(((x+.5)/n-.5)*extent);cy+=target[i]!*(((y+.5)/n-.5)*extent);}
const bytes=fs.readFileSync(particlePath);const particles=new Float32Array(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength));const pivot=triple(config.pivot);if(particles.length%4||particles.some(v=>!Number.isFinite(v)))throw Error('Invalid particle buffer');
const input:DensityFitInput={particles,pivot,distance:number(config.distance),target,mask,size:n,extent};const initialOffset:[number,number]=[cx/sum,cy/sum];console.log('TARGET_CENTRE',initialOffset,'PIVOT',pivot,'mask',values.length);const result=fitDensitySimilarity(input,initialOffset);console.log('FIT',result);
const beforeInput={...input,pivot:[0,0,0] as [number,number,number]};const before=projectSimilarity(beforeInput,{offset:[0,0],rotationDeg:0,scale:1}),after=projectSimilarity(input,result.best);const centered=projectSimilarity(input,{offset:initialOffset,rotationDeg:0,scale:1});
const hash=(p:string)=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');const recipe={schema:'cssearth-density-placement@1',sourceDirectory,scale:result.best.scale,rotationZDegrees:result.best.rotationDeg,pivotUnits:pivot,translationUnits:[result.best.offset[0]-pivot[0],result.best.offset[1]-pivot[1],-pivot[2]],originalDensity:{path:sourceDirectory+'/source/volume.json',sha256:hash(sourceDirectory+'/source/volume.json')},fit:{method:'Bounded perspective model-only XY similarity against smoothed original '+text(config.imageLabel)+' stellar light; uniform XYZ scale',image:{path:source.path,sha256:source.sha256},particles:{path:particlePath,sha256:hash(particlePath),count:particles.length/4},observerDistanceKpc:number(config.distance),targetProcessing:{resizeWidth:1024,gaussianSigmaPixels:8,backgroundQuantile:.15,clipQuantile:.995,frameExtentKpc:extent,gridSize:n,observedCells:values.length},score:'Pearson correlation on observed footprint only; outside image is unconstrained',beforeCorrelation:fitScore(before,target,mask),centeredOnlyCorrelation:fitScore(centered,target,mask),afterCorrelation:result.score,evaluations:result.evaluations,limitations:['Authored image-to-simulation morphological placement, not astrometry or a recovered physical size/distance.','Original unresolved optical light approximates stellar morphology, with foreground sources/background and age/extinction biases.','All 225000 particles retained; outer tails outside observed footprint are unconstrained, not removed.','This placement changes model coordinates only and cannot prove physical depth or volumetric material quality.']}};
fs.writeFileSync(outputPath,JSON.stringify(recipe,null,2)+'\n');
const out=Buffer.alloc(n*n*3*3);const planes=[before,target,after];for(let panel=0;panel<3;panel++){const values=[...planes[panel]!].sort((a,b)=>a-b),max=values[Math.floor(values.length*.999)]!||1;for(let y=0;y<n;y++)for(let x=0;x<n;x++){const v=Math.round(Math.sqrt(Math.min(1,planes[panel]![y*n+x]!/max))*255),o=((n-1-y)*n*3+panel*n+(n-1-x))*3;out[o]=v;out[o+1]=v;out[o+2]=v;}}
await sharp(out,{raw:{width:n*3,height:n,channels:3}}).resize(n*3*3,n*3,{kernel:'nearest'}).png().toFile(comparisonPath);console.log('RECEIPT',recipe.fit);
