import assert from 'node:assert/strict';
import test from 'node:test';
import { validateDatasetSteps } from '@cssearth/bake/objects/content';
import { surfaceMapFiles } from '../maps/surface-maps.mts';
import { adoptPeriod, measuredPeriod, starMetadata } from '../metadata/star-metadata.mts';
import { BRIGHTNESS_CONSUMER, BRIGHTNESS_MAPS, brightnessChoice, brightnessSourceRecords, mapRange, monthsOf, percent, reducedBrightness, missionDay, shortMonthsOf, tinted, tableDirectory } from './brightness-maps.mts';
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { SAME_STAR_ARCSEC } from '../../archives/tess/methods.mts';
import { SANTOS_2019 } from '../../archives/kepler/santos.mts';
import { NEWTON_2018 } from '../../archives/mearth/newton.mts';
import { CANTO_MARTINS_2020 } from '../../archives/tess/canto-martins.mts';
import { COLMAN_2024 } from '../../archives/tess/published.mts';
import { MATCH_ARCSEC } from '../metadata/rotation-catalogues.mts';
import { BRIGHTNESS_ROUTE, withBrightnessReadme, withMeasuredRotation, withPixelLight } from './brightness.mts';

const TABLE = 'TITLE     = "test"\nVARIABLES = "Longitude [Deg]" "Latitude [Deg]" "Brightness [%]"\nZONE I=2, J=2, K=1, ZONETYPE=Ordered\n';
const HOLCOMB = { id: 'holcomb-2022', citation: 'Holcomb et al. (2022, ApJ 936, 138)', url: 'https://arxiv.org/abs/2206.10629', where: 'Sects. II and III', lightCurve: 'the TESS mission\'s 2-minute light curve of a sector, reduced by its PDC-MAP pipeline and binned to 30 minutes',
  asks: 'the peaks of the light\'s autocorrelation to have a height over a quarter of their width, a width between 0.4 and 0.6 and a parabola fit over 0.9, in at least half the star\'s sectors and in all of them together', reliability: 'On the stars its authors inspected by eye, 4.9% of the periods these criteria accepted were false, and 6.2% on a second set.' };
const SAYS = 'a period of 4.85 d from the autocorrelation, whose peaks have a height of 0.33, a width of 0.43 and a fit of 0.95';
/** A star with one TESS sector, judged by Holcomb et al. (2022) on the mission's 2-minute light curve. */
const receipt = (from: string, source: string) => ({ schema: 'cssearth-tess-rotation@2', star: { id: 'hd-1', name: 'HD 1' }, light: { gaiaDr3: '1', magnitude: 6.8, neighbours: 16, neighbourShare: 0.0029 }, mission: 'TESS', method: HOLCOMB,
  tried: [{ mission: 'TESS', window: 95, method: 'holcomb-2022', analysis: { periodDays: 4.85, height: 0.33, width: 0.43, fit: 0.95, centre: 0.001, range: 0.085 }, says: SAYS, verdict: { detected: true, periodDays: 4.85, amplitude: 0.085 } }],
  rotation: { detected: true, periodDays: 4.85, amplitude: 0.085 } as { detected: boolean; periodDays?: number; lightPeriodDays?: number; amplitude?: number; reason?: string }, toolchain: { id: 'tess-photometry', requirements: ['numpy==2.5.3', 'lightkurve==2.6.0', 'star-privateer==1.3.1', 'spinspotter==0.2.0'] },
  maps: [{ mission: 'TESS', window: 95, table: 'hd-1-s0095.dat', degree: 5, inclinationDegrees: 60, inclinationFrom: from, inclinationSource: source, periodDays: 4.85, residual: 0.00509, noise: 0.00173, darkestPercent: 93.4, brightestPercent: 104.2, starry: '1.2.0' }] });
/** Sector 95's light: 3 August to 29 August 2025 as TESS times. */
const LIGHT = { sector: 95, time: [3890.5, 3903.2, 3916.9], flux: [1.01, 0.99, 1] };
const HOST = () => ({ content: { datasets: { defaultDataset: 'color', controls: [{ id: 'color', label: 'Color' }] } }, text: { datasets: { color: { title: 'Color' } } }, manifest: { inputs: [{ id: 'star-color', path: 'photometry/color.json', consumers: ['datasets'] }] },
  raster: { surfaces: [{ id: 'color', output: 'hd-1-surface-{id}{suffix}.webp', thumbnail: 'hd-1-dataset-{id}.webp', science: { kind: 'stellar-photometric-color' } }, { id: 'radial-field-2007-06', output: 'x', thumbnail: 'y', science: { kind: 'terrestrial-scientific', consumer: 'espadons-zdi' } }] },
  descriptor: { properties: { recipe: { surfaces: [{ id: 'body', datasets: [{ id: 'color', source: 'content', material: 'emission' }, { id: 'radial-field-2007-06', source: 'content', material: 'emission' }] }] } } } });

test('a brightness map becomes the star page\'s records, saying it is made here and what a light curve cannot fix', () => {
  const choice = brightnessChoice('hd-1', 'TESS', 95); assert.deepEqual(choice, { program: 'hd-1-s0095', id: 'brightness-sector-95', label: 'Sector 95' });
  const map = reducedBrightness(choice, receipt('assumed', 'assumed: no tilt of the star is known'), TABLE, LIGHT);
  assert.deepEqual([map.window, map.periodDays, map.tiltFrom, map.codes], [95, 4.85, 'assumed', ['lightkurve 2.6.0', 'SpinSpotter 0.2.0', 'starry 1.2.0']]);
  const { files, report } = surfaceMapFiles(BRIGHTNESS_MAPS, { host: 'hd-1', maps: [choice] }, { id: 'hd-1', name: 'HD 1' }, [map], HOST()), read = (path: string) => JSON.parse(files.get(`src/objects/hd-1/${path}`)!) as Record<string, any>;
  assert.equal(files.get('src/objects/hd-1/source/science/tess/pdcsap/hd-1-s0095.dat'), TABLE); assert.match(report, /1 brightness map on one scale of 92% to 108% \(Sector 95: turns in 4\.85 days, light swings 8\.5%\)/u);
  // A map of another kind on the page is left as it is; the scale is centred on the star's mean surface.
  const surfaces = read('source/preparation/raster.json').surfaces, science = surfaces[2].science;
  assert.deepEqual(surfaces.map((surface: { id: string }) => surface.id), ['color', 'radial-field-2007-06', 'brightness-sector-95']);
  assert.deepEqual([science.variable, science.units, science.minimum, science.maximum, science.labels, science.consumer, science.outlineLatitudes], ['Brightness [%]', '%', 92, 108, ['92%', '100%', '108%'], BRIGHTNESS_CONSUMER, undefined]);
  assert.match(science.description, /turns once in 4\.85 days.*fitted with starry to the TESS mission's own 2-minute light curve of sector 95 \(its PDC-MAP flux\) \(the light varies by 8\.5%; the map's curve leaves a scatter of 0\.51%, the light's own noise being 0\.17%\)\. A light curve fixes how bright each longitude is, not the latitude of what darkens it\. In this sector the method of Holcomb et al\. \(2022, ApJ 936, 138\) finds a period of 4\.85 d from the autocorrelation, whose peaks have a height of 0\.33, a width of 0\.43 and a fit of 0\.95; its criteria accept that as the star's rotation\..*No tilt of this star's axis is known: the map is made at 60°.*Gaia DR3 lists 16 other stars within 63 arcseconds, with 0\.29% of their light and the star's together\. A reduction made in this project, not a published map\./u);
  const control = read('source/content/object.json').datasets.controls[1]; assert.deepEqual([control.label, control.step, control.legend.meta, control.source.id], ['Brightness map', undefined, '%', 'hd-1-tess-map-brightness-sector-95']);
  assert.match(control.notes, /worked out in this project.*The light curve is the mission's own; the criteria of Holcomb et al\. \(2022, ApJ 936, 138\) decide that it shows the star turning, and starry.*their latitudes are not/u); assert.doesNotMatch(control.legendNote, /Black line/u);
  // The table is built here and kept out of git, so it is a generated intermediate of the manifest, not an input.
  assert.equal(read('source/manifest.json').inputs.length, 1); const input = read('source/manifest.json').generatedIntermediates[0]; assert.equal(input.path, 'science/tess/pdcsap/hd-1-s0095.dat'); assert.match(input.credit, /^NASA TESS mission light curve \(PDC-MAP\), sector 95, from MAST; its rotation judged by the criteria of Holcomb et al\. \(2022, ApJ 936, 138\); map made in this project with lightkurve 2\.6\.0, SpinSpotter 0\.2\.0 and starry 1\.2\.0\./u);
  // The table is built here and kept out of git: its input names the command that makes it.
  assert.equal(input.generator, 'packages/telescope-cli/src/archives/tess/reduce.mts'); assert.match(input.acquisition, /Restored from the source cache; not tracked/u);
  assert.deepEqual(input.sourceBinding.references.map((reference: { catalogueId: string }) => reference.catalogueId), ['mast-tess-light-curves', 'arxiv-2206-10629', 'arxiv-1810-06559', 'gaia-2023-dr3']);
  assert.deepEqual([...brightnessSourceRecords('2026-10-06', [map]).keys()], ['src/sources/arxiv-2206-10629.json', 'src/sources/mast-tess-light-curves.json', 'src/sources/arxiv-1810-06559.json']);
  assert.deepEqual(read('object.json').properties.recipe.surfaces[0].datasets.map((one: { id: string }) => one.id), ['color', 'radial-field-2007-06', 'brightness-sector-95']);
  // With the star's color, the page opens on the star in that color at the map's own contrast, then its map, then what it had.
  const colored = surfaceMapFiles(BRIGHTNESS_MAPS, { host: 'hd-1', maps: [choice] }, { id: 'hd-1', name: 'HD 1', colorHex: '#ffc08b' }, [map], HOST()), shown = (path: string) => JSON.parse(colored.files.get(`src/objects/hd-1/${path}`)!) as Record<string, any>;
  assert.equal(colored.opensOn, 'color-brightness'); assert.deepEqual([shown('source/content/object.json').datasets.defaultDataset, shown('source/content/object.json').datasets.controls.map((one: { id: string }) => one.id)], ['color-brightness', ['color-brightness', 'brightness-sector-95', 'color']]);
  const own = shown('source/preparation/raster.json').surfaces.at(-1).science;
  assert.equal(own.limbStrength, 1.5); assert.deepEqual([own.id, own.limbOf, own.minimum, own.maximum, own.colors.length, own.colors.at(-1), shown('source/preparation/raster.json').surfaces.at(-1).falseColor], ['color-brightness', 'color', 92, 108, 5, '#ffc08b', false]);
  // The Brightness map's own scale, from a darker, richer step of the star's hue up to its color; a color with no hue stays neutral.
  assert.deepEqual(own.colors, tinted('#ffc08b')); assert.deepEqual(tinted('#ffc08b'), ['#7f4600', '#9f6423', '#bf8346', '#dfa168', '#ffc08b']); assert.deepEqual(tinted('#ffffff'), ['#808080', '#a0a0a0', '#c0c0c0', '#dfdfdf', '#ffffff']);
  assert.match(shown('source/content/object.json').datasets.controls[0].notes, /in TESS's images of August 2025.*The contrast is drawn far stronger than it is, so the eye can see it: the darkest part gives 10\.4% less light than the brightest, and is drawn as a much darker tone of the star's own hue; the Brightness map's scale has the measured values.*Their latitudes and shapes are not.*No change of color is drawn/u);
  assert.deepEqual(shown('text.json').datasets['color-brightness'], { title: 'Color + brightness, Aug 2025', detail: 'TESS sector 95', summary: 'The star in its own color, darker where its light shows it darker; the contrast is drawn stronger to be seen.' });
  assert.equal(shown('text.json').datasets['brightness-sector-95'].detail, 'Sector 95, mapped here'); assert.equal(shortMonthsOf('2025-12-20', '2026-01-15'), 'Dec 2025 to Jan 2026'); assert.equal(monthsOf('2025-08-29', '2025-09-22'), 'August and September 2025'); assert.equal(monthsOf('2017-03-08', '2017-05-27'), 'March to May 2017'); assert.equal(missionDay(3890.5), '2025-08-03');
  // Written again over its own records, nothing moves and the page is not said to open elsewhere.
  const again = surfaceMapFiles(BRIGHTNESS_MAPS, { host: 'hd-1', maps: [choice] }, { id: 'hd-1', name: 'HD 1', colorHex: '#ffc08b' }, [map], { content: shown('source/content/object.json'), text: shown('text.json'), manifest: shown('source/manifest.json'), raster: shown('source/preparation/raster.json'), descriptor: shown('object.json') });
  assert.equal(again.opensOn, undefined); assert.equal(again.files.get('src/objects/hd-1/source/content/object.json'), colored.files.get('src/objects/hd-1/source/content/object.json')); assert.equal(again.files.get('src/objects/hd-1/source/preparation/raster.json'), colored.files.get('src/objects/hd-1/source/preparation/raster.json'));
  // Only a page that measures the star's axis draws the star at the map's tilt, and outlines what it never shows.
  const drawn = reducedBrightness(choice, receipt('page', 'rotation.json: the measured axis the star\'s page draws'), TABLE, LIGHT), outlined = surfaceMapFiles(BRIGHTNESS_MAPS, { host: 'hd-1', maps: [choice] }, { id: 'hd-1', name: 'HD 1' }, [drawn], HOST());
  assert.deepEqual((JSON.parse(outlined.files.get('src/objects/hd-1/source/preparation/raster.json')!) as Record<string, any>).surfaces[2].science.outlineLatitudes, [-60]);
  assert.throws(() => reducedBrightness(choice, { ...receipt('page', 'x'), rotation: { detected: false, reason: 'Too faint.' } }, TABLE, LIGHT), /rotation is not seen \(Too faint\.\)/u);
  // A light that repeats twice a turn says so.
  const twice = reducedBrightness(choice, { ...receipt('assumed', 'assumed'), rotation: { detected: true, periodDays: 4.85, lightPeriodDays: 2.42, amplitude: 0.0075 } }, TABLE, LIGHT);
  assert.match(BRIGHTNESS_MAPS.words(twice, { star: { id: 'hd-1', name: 'HD 1' }, count: 1, epochs: '1 epoch', tilt: 60, outlined: false }).notes, /The light repeats every 2\.42 days, half the rotation period the catalogues print/u);
  assert.throws(() => reducedBrightness(brightnessChoice('hd-1', 'TESS', 27), receipt('page', 'x'), TABLE, LIGHT), /holds no map of that window/u);
});

test('a map made at an inclination a paper publishes says so, and the page keeps its conventional axis', () => {
  const source = '47 ± 7 degrees from the line of sight, Klein et al. (2021), MNRAS 500, 1844 (src/objects/hd-1/source/measurements.json, spinInclinationPublishedDegrees)';
  const choice = brightnessChoice('hd-1', 'TESS', 95), published = receipt('published', source), map = reducedBrightness(choice, { ...published, maps: [{ ...published.maps[0]!, inclinationDegrees: 47 }] }, TABLE, LIGHT);
  assert.deepEqual([map.tiltFrom, map.inclinationDegrees, map.inclinationSource, BRIGHTNESS_MAPS.outlines!(map)], ['published', 47, source, false]);
  const { files } = surfaceMapFiles(BRIGHTNESS_MAPS, { host: 'hd-1', maps: [choice] }, { id: 'hd-1', name: 'HD 1' }, [map], HOST());
  // Its table takes a path of its own, under the tilt: the mirror keeps the table the star had at the assumed tilt.
  assert.equal(files.get('src/objects/hd-1/source/science/tess/pdcsap/tilt-47/hd-1-s0095.dat'), TABLE); assert.equal(files.has('src/objects/hd-1/source/science/tess/pdcsap/hd-1-s0095.dat'), false);
  assert.deepEqual([tableDirectory('MEarth', TABLE, 47), tableDirectory('K2', TABLE, 62.25)], ['science/mearth/tilt-47', 'science/k2/pdcsap/tilt-62.3']);
  const surfaces = (JSON.parse(files.get('src/objects/hd-1/source/preparation/raster.json')!) as { surfaces: { science: { description?: string } }[] }).surfaces;
  assert.match(surfaces.map(surface => surface.science.description ?? '').join(' '), /The map is made at a tilt of 47°, the inclination published for the star's axis\./u);
  const readme = withBrightnessReadme('# HD 1\n\n## Sources\n\nGaia.\n\n## Evidence\n\nRun.\n\n## Known problems\n\n- None.\n', map, 15);
  assert.match(readme, /The map is made at a tilt of 47°, the inclination published for the star's axis: 47 ± 7 degrees from the line of sight, Klein et al\. \(2021\), MNRAS 500, 1844 \(src\/objects\/hd-1\/source\/measurements\.json, spinInclinationPublishedDegrees\)\. The page draws the axis by convention\./u);
  assert.doesNotMatch(readme, /No tilt of the axis is known/u);
  assert.throws(() => reducedBrightness(choice, receipt('paper', source), TABLE, LIGHT), /its receipt does not say where the map's tilt comes from/u);
});

test('a K2 map is of the mission\'s own light curve and names the published method that judged it a rotation', () => {
  // K2-136 in campaign 13: the receipt names Reinhold & Hekker (2020), the light curve they use and what their three methods measured.
  const k2 = { ...receipt('record', 'measurements.json, spinInclinationDegrees'), light: { gaiaDr3: '1', magnitude: 10.1, neighbours: 0, neighbourShare: 0 }, rotation: { detected: true, periodDays: 14.46, amplitude: 0.0067 },
    toolchain: { id: 'tess-photometry', requirements: ['lightkurve==2.6.0', 'star-privateer==1.3.1'] },
    method: { id: 'reinhold-hekker-2020', citation: 'Reinhold & Hekker (2020, A&A 635, A43)', url: 'https://arxiv.org/abs/2001.08214', where: 'Sects. 2 and 3', lightCurve: 'the K2 mission\'s long-cadence light curve of a campaign, reduced by its PDC-MAP pipeline', asks: 'the periodogram, the wavelet and the autocorrelation to give periods within a day of each other under 10 days, two days to 20 and five beyond, with a periodogram peak over 0.3',
      reliability: 'Of the paper\'s stars observed in two campaigns, 75.7% gave periods within 20% of each other.' },
    tried: [{ mission: 'K2', window: 5, verdict: { detected: false } }, { mission: 'K2', window: 13, method: 'reinhold-hekker-2020', says: 'periodogram 15.00 d, wavelet 14.63 d, autocorrelation 13.75 d; periodogram peak 0.56', analysis: { spanDays: 80.5, variabilityRange: 0.0067, peakHeight: 0.561, lombScargleDays: 15.002, waveletDays: 14.629, autocorrelationDays: 13.75 } }],
    mission: 'K2', maps: [{ ...receipt('record', 'x').maps[0]!, mission: 'K2', window: 13, table: 'hd-1-c13.dat', periodDays: 14.46, inclinationFrom: 'record', inclinationSource: 'measurements.json, spinInclinationDegrees' }] };
  const choice = brightnessChoice('hd-1', 'K2', 13); assert.deepEqual(choice, { program: 'hd-1-c13', id: 'brightness-campaign-13', label: 'Campaign 13' });
  // K2's clock starts at BJD 2,454,833: day 2988.5 is 9 March 2017.
  const map = reducedBrightness(choice, k2, TABLE, { time: [2988.5, 3030, 3068.5], flux: [1, 1, 1] });
  assert.deepEqual([map.mission, map.window, map.fromUtc, map.toUtc, map.method!.periodsDays, map.codes], ['K2', 13, '2017-03-09', '2017-05-28', [15.002, 14.629, 13.75], ['lightkurve 2.6.0', 'star-privateer 1.3.1', 'starry 1.2.0']]);
  const { files } = surfaceMapFiles(BRIGHTNESS_MAPS, { host: 'hd-1', maps: [choice] }, { id: 'hd-1', name: 'HD 1' }, [map], HOST()), read = (path: string) => JSON.parse(files.get(`src/objects/hd-1/${path}`)!) as Record<string, any>;
  // Its table, surface and input carry K2's own names, and its input is bound to the mission's light curves, the method's paper and starry's.
  assert.equal(files.get('src/objects/hd-1/source/science/k2/pdcsap/hd-1-c13.dat'), TABLE); const surface = read('source/preparation/raster.json').surfaces[2].science, input = read('source/manifest.json').generatedIntermediates[0];
  assert.equal(surface.consumer, 'k2-starry'); assert.match(surface.description, /fitted with starry to the K2 mission's own light curve of campaign 13 \(its PDC-MAP flux\) \(the light varies by 0\.67%;.*The period is the mean of three methods' periods \(periodogram 15\.00 d, wavelet 14\.63 d, autocorrelation 13\.75 d; periodogram peak 0\.56\), accepted by the criteria of Reinhold & Hekker \(2020, A&A 635, A43\).*Gaia DR3 lists no other star within 16 arcseconds of it\. A reduction made/u);
  assert.equal(input.id, 'hd-1-k2-map-brightness-campaign-13'); assert.match(input.credit, /^NASA K2 mission light curve \(PDC-MAP\), campaign 13, from MAST; its rotation judged by the criteria of Reinhold & Hekker \(2020, A&A 635, A43\); map made in this project with lightkurve 2\.6\.0, star-privateer 1\.3\.1 and starry 1\.2\.0\./u);
  assert.match(read('source/content/object.json').datasets.controls[1].notes, /The light curve is the mission's own; the criteria of Reinhold & Hekker \(2020, A&A 635, A43\) decide that it shows the star turning, and starry finds the map/u);
  assert.deepEqual(input.sourceBinding.references.map((reference: { catalogueId: string; role: string }) => [reference.catalogueId, reference.role]), [['mast-k2-light-curves', 'material'], ['arxiv-2001-08214', 'method'], ['arxiv-1810-06559', 'method'], ['gaia-2023-dr3', 'reference']]);
  assert.deepEqual([...brightnessSourceRecords('2026-10-06', [map]).keys()], ['src/sources/arxiv-2001-08214.json', 'src/sources/mast-k2-light-curves.json', 'src/sources/arxiv-1810-06559.json']);
  // The README's evidence is the method's: its three periods, its peak, what it asks and how reliable its paper found it.
  const readme = withBrightnessReadme('# HD 1\n\n## Sources\n\nGaia.\n\n## Evidence\n\nRun.\n\n## Known problems\n\n- None.\n', map, 15);
  assert.match(readme, /\*\*Brightness from K2\.\*\* The Color \+ brightness and Brightness map datasets are made in this project from the K2 mission's own light curve of campaign 13 \(March to May 2017; its PDC-MAP flux, kept at \[MAST\].*It is the light curve \[Reinhold & Hekker \(2020, A&A 635, A43\)\]\(https:\/\/arxiv\.org\/abs\/2001\.08214\) use, and their criteria decide whether it shows the star turning: astropy and star-privateer compute their three periods, and starry \(Luger et al\. 2019\) makes the map/su);
  assert.match(readme, /In K2 campaign 13 the light varies by 0\.67% \(the range between its 5th and 95th percentiles\)\. The periodogram, the wavelet and the autocorrelation give 15\.00, 14\.63 and 13\.75 d, and the periodogram's peak has a height of 0\.56: within what Reinhold & Hekker \(2020, A&A 635, A43\) ask of a rotation \(the three within two days of each other, a peak over 0\.3\)\. The period is their mean, 14\.46 d\. Of the paper's stars observed in two campaigns, 75\.7%.*The star's record holds 15 d from the catalogues.*Gaia DR3 lists no other star within 16 arcseconds\./su);
  assert.match(String(withMeasuredRotation({ shape: 'sphere' }, map).rotationPeriodMeasuredSource), /from the K2 mission's own light curve of campaign 13 \(.*reduce\.mts\), by the method and criteria of Reinhold & Hekker \(2020, A&A 635, A43\): 14\.46 d/u);
  // A star observed in two campaigns has one period, the mean of theirs, and its texts say so.
  const two = { ...k2, rotation: { detected: true, periodDays: 14.2, amplitude: 0.006 }, tried: [...k2.tried.slice(1), { mission: 'K2', window: 18, method: 'reinhold-hekker-2020', says: 'periodogram 14.10 d, wavelet 13.90 d, autocorrelation 13.80 d; periodogram peak 0.48', analysis: { spanDays: 50.8, variabilityRange: 0.0053, peakHeight: 0.48, lombScargleDays: 14.1, waveletDays: 13.9, autocorrelationDays: 13.8 } }],
    maps: [{ ...k2.maps[0]!, periodDays: 14.2 }, { ...k2.maps[0]!, window: 18, table: 'hd-1-c18.dat', periodDays: 14.2 }] };
  const later = brightnessChoice('hd-1', 'K2', 18), both = [reducedBrightness(choice, two, TABLE, { time: [2988.5, 3068.5], flux: [1, 1] }), reducedBrightness(later, two, TABLE, { time: [3419.5, 3470.3], flux: [1, 1] })];
  assert.equal(both[1]!.method!.campaigns, 2); assert.match(BRIGHTNESS_MAPS.words(both[1]!, { star: { id: 'hd-1', name: 'HD 1' }, count: 2, epochs: '2 epochs', tilt: 60, outlined: false }).description, /This campaign's three methods give its period \(periodogram 14\.10 d, wavelet 13\.90 d, autocorrelation 13\.80 d; periodogram peak 0\.48\), accepted by the criteria of Reinhold & Hekker.*the star's period is the mean of its 2 accepted campaigns/u);
  const twice = withBrightnessReadme('# HD 1\n\n## Sources\n\nGaia.\n\n## Evidence\n\nRun.\n\n## Known problems\n\n- None.\n', both[1]!, 15, both);
  assert.match(twice, /the K2 mission's own light curves of campaigns 13 and 18 \(the newest of May to July 2018; their PDC-MAP flux.*They are the light curves \[Reinhold & Hekker.*decide whether each shows the star turning/su);
  assert.match(twice, /K2 observed the star in campaigns 13 and 18, and the light of each meets what Reinhold & Hekker \(2020, A&A 635, A43\) ask of a rotation.*: campaign 13 gives 15\.00, 14\.63 and 13\.75 d with a peak of 0\.56; campaign 18 gives 14\.10, 13\.90 and 13\.80 d with a peak of 0\.48\. The star's period is the mean of the campaigns' 14\.46 and 13\.93 d: 14\.2 d, as the paper takes it for a star observed more than once\./su);
  assert.match(String(withMeasuredRotation({ shape: 'sphere' }, both[1]!, both).rotationPeriodMeasuredSource), /light curves of campaigns 13 and 18 \(.*\), by the method and criteria of Reinhold & Hekker \(2020, A&A 635, A43\): 14\.2 d, the mean of the campaigns' 14\.46 and 13\.93 d,/u);
  // A K2 receipt that names no method is of an earlier reduction; one without Gaia's count of neighbours says nothing of them.
  assert.throws(() => reducedBrightness(choice, { ...k2, method: undefined }, TABLE, { time: [2988.5, 3068.5], flux: [1, 1] }), /names no published method/u);
  assert.equal(reducedBrightness(choice, { ...k2, light: undefined }, TABLE, { time: [2988.5, 3068.5], flux: [1, 1] }).neighbours, undefined);
});

test('the period measured on the way goes into the star\'s record, and counts among its catalogued periods', () => {
  const seen = reducedBrightness(brightnessChoice('hd-1', 'TESS', 95), receipt('assumed', 'assumed'), TABLE, LIGHT), record = withMeasuredRotation({ schema: 'cssearth-uniform-disc-star@1', radiusKm: 600000, shape: 'sphere' }, seen);
  assert.deepEqual(Object.keys(record), ['schema', 'radiusKm', 'rotationPeriodMeasuredDays', 'rotationPeriodMeasuredSource', 'rotationLightSwingPercent', 'shape']);
  assert.deepEqual([record.rotationPeriodMeasuredDays, record.rotationLightSwingPercent], [4.85, 8.5]); assert.match(String(record.rotationPeriodMeasuredSource), /from the TESS mission's own 2-minute light curve of sector 95 \(.*\), by the method and criteria of Holcomb et al\. \(2022, ApJ 936, 138\): 4\.85 d, the light swinging by 8\.5%/u);
  // Written again, the record does not grow.
  assert.deepEqual(withMeasuredRotation(record, seen), record);
  const measured = measuredPeriod(record)!; assert.equal(measured.days, 4.85);
  // Alone it is adopted; between two catalogued periods that disagree it sides with the one it matches.
  assert.equal(starMetadata({ measuredAxis: false }, undefined, undefined, undefined, [], measured).rotationPeriodDays, 4.85);
  const disputed = [{ days: 4.9, source: 'Table A' }, { days: 2.4, source: 'Table B' }]; assert.equal(adoptPeriod(disputed), undefined);
  const settled = starMetadata({ measuredAxis: false }, undefined, undefined, undefined, disputed, measured);
  assert.equal(settled.rotationPeriodDays, 4.85); assert.match(String(settled.rotationPeriodSource), /The middle of 3 periods, catalogued and measured here, 2 of them within 20% of it/u);
});

test('the star\'s README says what its brightness datasets are made from, once', () => {
  const map = reducedBrightness(brightnessChoice('hd-1', 'TESS', 95), receipt('assumed', 'assumed'), TABLE, LIGHT);
  const readme = '# HD 1\n\n## Sources\n\n**Placement.** Gaia.\n\n## Evidence\n\nRun of today.\n\n## Known problems\n\n- The radius is a model value.\n\n[Investigation ledger](investigations.json) · [Inputs](source/manifest.json)\n';
  const written = withBrightnessReadme(readme, map, 4.9), sections = written.split(/^## /mu);
  assert.match(sections[1]!, /^Sources\n\n\*\*Placement\.\*\* Gaia\.\n\n\*\*Brightness from TESS\.\*\* The Color \+ brightness and Brightness map datasets are made in this project from the TESS mission's own 2-minute light curve of sector 95 \(August 2025; its PDC-MAP flux.*It is the light curve \[Holcomb et al\. \(2022, ApJ 936, 138\)\]\(https:\/\/arxiv\.org\/abs\/2206\.10629\) use, and their criteria decide whether it shows the star turning: SpinSpotter, their code, measures it, and starry.*restored from the source cache\.\n\n$/su);
  assert.match(sections[2]!, /Holcomb et al\. \(2022, ApJ 936, 138\) ask the peaks of the light's autocorrelation to have a height over a quarter of their width.*together\. Sector 95 gives a period of 4\.85 d from the autocorrelation, whose peaks have a height of 0\.33, a width of 0\.43 and a fit of 0\.95\. The star's period is 4\.85 d\. The light varies by 8\.5% \(the range between its 5th and 95th percentiles\)\. On the stars its authors inspected by eye, 4\.9%.*The star's record holds 4\.9 d from the catalogues\. The map's light curve leaves a scatter of 0\.51%.*16 other stars/su);
  assert.match(sections[3]!, /- The radius is a model value\.\n\n- \*\*Brightness from TESS\.\*\*.*made at 60°, the middle tilt.*\n\n\[Investigation ledger\]/su);
  assert.equal(withBrightnessReadme(written, map, 4.9), written); assert.equal(withBrightnessReadme('# HD 1\n\nNo sections.\n', map), '# HD 1\n\nNo sections.\n');
});

test('every star the reduction looked at carries what its light showed, or why it was not read', () => {
  const record = { schema: 'cssearth-uniform-disc-star@1', radiusKm: 600000, shape: 'sphere' };
  // A star read and quiet: the reduction's own sentence, the sector and the scatter of the kept light curve.
  const quiet = withPixelLight(record, { rotation: { detected: false, reason: 'No period stands out: the strongest, 4.13 d, has a periodogram power of 0.03, under the 0.3 a rotation asks for.' }, tried: [{ sector: 42, lightCurve: 'x.curve.json' }] }, { flux: [1.002, 0.998, 1.002, 0.998] });
  assert.deepEqual(Object.keys(quiet), ['schema', 'radiusKm', 'pixelLight', 'pixelLightMission', 'pixelLightWindow', 'pixelLightScatterPercent', 'pixelLightSource', 'shape']);
  assert.deepEqual([quiet.pixelLightMission, quiet.pixelLightWindow, quiet.pixelLightScatterPercent], ['TESS', 42, 0.2]); assert.match(String(quiet.pixelLight), /^No period stands out/u); assert.match(String(quiet.pixelLightSource), /TESS light curves of sector 42.*standard deviation of the light in 30-minute bins/u);
  // A K2 star names its campaign.
  const campaign = withPixelLight(record, { rotation: { detected: false, reason: 'No period stands out.' }, tried: [{ mission: 'K2', window: 13 }] }); assert.deepEqual([campaign.pixelLightMission, campaign.pixelLightWindow], ['K2', 13]); assert.match(String(campaign.pixelLightSource), /K2 light curves of campaign 13/u);
  // A star with a rotation says so; one refused before any pixel was fetched keeps the reason and names no sector.
  assert.match(String(withPixelLight(record, receipt('assumed', 'assumed')).pixelLight), /rotation is seen: 4\.85 d, the light swinging by 8\.5%/u);
  const shared = withPixelLight(quiet, { rotation: { detected: false, reason: 'Other stars give 50% of the light within 63 arcseconds of the star.' }, tried: [] });
  assert.deepEqual([shared.pixelLightWindow, shared.pixelLightScatterPercent], [undefined, undefined]); assert.match(String(shared.pixelLightSource), /the star's pixels were not read/u);
  assert.deepEqual(withPixelLight(quiet, { rotation: { detected: false, reason: 'No period stands out: the strongest, 4.13 d, has a periodogram power of 0.03, under the 0.3 a rotation asks for.' }, tried: [{ sector: 42 }] }, { flux: [1.002, 0.998, 1.002, 0.998] }), quiet);
});

test('a star whose light swings by a hundredth of a percent still gets a scale, and no measured value is printed as zero', () => {
  // The receipt gives a map's range to a tenth of a percent, so this map reads 100 to 100 there; its table holds 99.992 to 100.01.
  const rows = `${TABLE}DATAPACKING=POINT\nDT=(SINGLE SINGLE SINGLE)\n      0.00000    -90.00000    100.00000\n      5.00000    -90.00000     99.99200\n     10.00000    -90.00000    100.01000\n`;
  const faint = { ...receipt('assumed', 'assumed'), rotation: { detected: true, periodDays: 0.73, amplitude: 0.00013 }, maps: [{ ...receipt('assumed', 'assumed').maps[0]!, periodDays: 0.73, residual: 0.00004, noise: 0.00002, darkestPercent: 100, brightestPercent: 100 }] };
  const choice = brightnessChoice('hd-1', 'TESS', 95), map = reducedBrightness(choice, faint, rows, LIGHT); assert.deepEqual([map.darkestPercent, map.brightestPercent], [99.992, 100.01]);
  const { files, report } = surfaceMapFiles(BRIGHTNESS_MAPS, { host: 'hd-1', maps: [choice] }, { id: 'hd-1', name: 'HD 1', colorHex: '#ffc08b' }, [map], HOST()), surfaces = (JSON.parse(files.get('src/objects/hd-1/source/preparation/raster.json')!) as Record<string, any>).surfaces;
  const gray = surfaces.find((surface: { id: string }) => surface.id === 'brightness-sector-95').science, own = surfaces.find((surface: { id: string }) => surface.id === 'color-brightness').science;
  assert.deepEqual([gray.minimum, gray.maximum, gray.labels, own.minimum, own.maximum], [99.99, 100.01, ['99.99%', '100%', '100.01%'], 99.99, 100.01]); assert.match(report, /on one scale of 99\.99% to 100\.01% \(Sector 95: turns in 17\.5 hours, light swings 0\.01%\)/u);
  assert.match(gray.description, /the light varies by 0\.01%; the map's curve leaves a scatter of 0\.004%, the light's own noise being 0\.002%/u); assert.match(own.description, /the map's scale, 99\.99% to 100\.01% of the mean surface.*the darkest part gives 0\.018% less light than the brightest/u);
  // A range the receipt does give is the receipt's, whatever the table holds; a table with no rows leaves it as it is.
  assert.deepEqual([mapRange(93.4, 104.2, rows), mapRange(100, 100.1, rows), mapRange(100, 100, TABLE)], [[93.4, 104.2], [100, 100.1], [100, 100]]);
  assert.deepEqual([0.085, 0.0051, 0.00051, 0.00005, 0.00004, 0.000004].map(percent), ['8.5', '0.51', '0.05', '0.01', '0.004', 'under 0.001']);
});

test('a table that holds its map to seven decimals of the mean is filed under its own directory, and any other where it was', () => {
  // Five decimals of the mean leave the last two decimals of a percent at zero; Shangcheng's map of sector 52, written again, does not.
  const fine = `${TABLE}DATAPACKING=POINT\nDT=(SINGLE SINGLE SINGLE)\n      0.00000    -90.00000    100.00000\n      5.00000    -90.00000     99.99537\n     10.00000    -90.00000    100.00463\n`;
  const wide = fine.replace('99.99537', '99.99500').replace('100.00463', '100.00500');
  assert.deepEqual([tableDirectory('TESS', fine), tableDirectory('K2', fine), tableDirectory('TESS', wide), tableDirectory('K2', wide), tableDirectory('TESS', TABLE)], ['science/tess/pdcsap/fine', 'science/k2/pdcsap/fine', 'science/tess/pdcsap', 'science/k2/pdcsap', 'science/tess/pdcsap']);
  const faint = { ...receipt('assumed', 'assumed'), rotation: { detected: true, periodDays: 0.73, amplitude: 0.00013 }, maps: [{ ...receipt('assumed', 'assumed').maps[0]!, periodDays: 0.73, residual: 0.00004, noise: 0.00002, darkestPercent: 100, brightestPercent: 100 }] };
  const choice = brightnessChoice('hd-1', 'TESS', 95), map = reducedBrightness(choice, faint, fine, LIGHT); assert.deepEqual([map.darkestPercent, map.brightestPercent], [99.99537, 100.00463]);
  const { files } = surfaceMapFiles(BRIGHTNESS_MAPS, { host: 'hd-1', maps: [choice] }, { id: 'hd-1', name: 'HD 1', colorHex: '#ffc08b' }, [map], HOST()), read = (path: string) => JSON.parse(files.get(`src/objects/hd-1/${path}`)!) as Record<string, any>;
  assert.equal(files.get('src/objects/hd-1/source/science/tess/pdcsap/fine/hd-1-s0095.dat'), fine); assert.equal(read('source/manifest.json').generatedIntermediates[0].path, 'science/tess/pdcsap/fine/hd-1-s0095.dat');
  const surfaces = read('source/preparation/raster.json').surfaces.filter((surface: { science: { consumer?: string } }) => surface.science.consumer === 'tess-starry');
  assert.deepEqual(surfaces.map((surface: { source: string; science: { path: string; minimum: number; maximum: number } }) => [surface.source, surface.science.path, surface.science.minimum, surface.science.maximum]), [['science/tess/pdcsap/fine/hd-1-s0095.dat', 'science/tess/pdcsap/fine/hd-1-s0095.dat', 99.995, 100.005], ['science/tess/pdcsap/fine/hd-1-s0095.dat', 'science/tess/pdcsap/fine/hd-1-s0095.dat', 99.995, 100.005]]);
});

test('a page that already files a dataset or a group under the steps\' own id gives the maps\' steps another, which the bake accepts', () => {
  const choices = [brightnessChoice('hd-1', 'TESS', 95), brightnessChoice('hd-1', 'TESS', 96)], two = { ...receipt('assumed', 'assumed'), tried: [...receipt('assumed', 'assumed').tried, { ...receipt('assumed', 'assumed').tried[0]!, window: 96 }], maps: [receipt('assumed', 'assumed').maps[0]!, { ...receipt('assumed', 'assumed').maps[0]!, window: 96, table: 'hd-1-s0096.dat' }] };
  const maps = choices.map(choice => reducedBrightness(choice, two, TABLE, LIGHT)), star = { id: 'hd-1', name: 'HD 1', colorHex: '#ffc08b' };
  const written = (host: ReturnType<typeof HOST>) => { const { files } = surfaceMapFiles(BRIGHTNESS_MAPS, { host: 'hd-1', maps: choices }, star, maps, host), content = JSON.parse(files.get('src/objects/hd-1/source/content/object.json')!) as { datasets: { controls: { id: string; step?: { group: string; label: string } }[] } };
    validateDatasetSteps('hd-1', content.datasets.controls); return { files, controls: content.datasets.controls, groups: [...new Set(content.datasets.controls.flatMap(control => control.step && control.id.startsWith('brightness-sector') ? [control.step.group] : []))] }; };
  // Any other page keeps the kind's own group id.
  assert.deepEqual(written(HOST()).groups, ['brightness']);
  // A published map filed as the dataset `brightness`: the bake refuses a group of that id, so the steps take another.
  const published = HOST(); published.content.datasets.controls.push({ id: 'brightness', label: 'Brightness' }); published.raster.surfaces.push({ id: 'brightness', output: 'x', thumbnail: 'y', science: { kind: 'terrestrial-scientific', consumer: 'doppler-imaging' } });
  assert.throws(() => validateDatasetSteps('hd-1', [...published.content.datasets.controls, { id: 'a', step: { group: 'brightness', label: 'A' } }, { id: 'b', step: { group: 'brightness', label: 'B' } }]), /must not be a dataset id/u);
  const beside = written(published); assert.deepEqual(beside.groups, ['brightness-maps']); assert.deepEqual(beside.controls.map(control => control.id), ['color-brightness', 'brightness-sector-95', 'brightness-sector-96', 'color', 'brightness']);
  // Written again over its own records, the steps keep that id.
  const records = (path: string) => JSON.parse(beside.files.get(`src/objects/hd-1/${path}`)!) as Record<string, any>;
  assert.deepEqual(written({ content: records('source/content/object.json'), text: records('text.json'), manifest: records('source/manifest.json'), raster: records('source/preparation/raster.json'), descriptor: records('object.json') } as ReturnType<typeof HOST>).groups, ['brightness-maps']);
  // Published maps of two epochs stepped under the group `brightness`: the light-curve maps do not join their steps.
  const stepped = HOST(); stepped.content.datasets.controls.push({ id: 'brightness-2013', label: 'Brightness', step: { group: 'brightness', label: 'Sep 2013' } } as never, { id: 'brightness-2017', label: 'Brightness', step: { group: 'brightness', label: 'Dec 2017' } } as never);
  assert.deepEqual(written(stepped).groups, ['brightness-maps']);
});

test('a paper\'s own verdict is worded as the paper\'s, and brings no period measured here', async () => {
  // BE Ceti as reduce.mts wrote it on 2026-10-06: SpinSpotter finds no peaks in its one sector, and Colman et al.'s table lists the star.
  const none = 'SpinSpotter finds no repeating peaks in the autocorrelation of sector 3.', row = COLMAN_2024.parse([{ TIC: '184281898', Rvar: '0.0206', Prot: '7.76', f_Prot: '0', Sector: '1', Prot2: '7.71', ProtACF: '7.69' }]).get(184281898)!, said = COLMAN_2024.judge(row, [3]).verdict;
  const paper = { id: COLMAN_2024.id, citation: COLMAN_2024.citation, url: COLMAN_2024.url, where: COLMAN_2024.where, lightCurve: COLMAN_2024.lightCurve, asks: COLMAN_2024.asks, reliability: COLMAN_2024.reliability, published: COLMAN_2024.table };
  const listed = { ...receipt('page', 'rotation.json: the measured axis the star\'s page draws'), method: paper, rotation: said, refused: [{ mission: 'TESS', method: HOLCOMB, rotation: { detected: false, reason: none } }],
    tried: [{ mission: 'TESS', window: 3, method: 'holcomb-2022', analysis: { periodDays: null, height: 0.29, width: 0.38, fit: 0.95, centre: 0.004, range: 0.0205 }, says: 'no repeating peaks in the autocorrelation', verdict: { detected: false, reason: none } },
      { mission: 'TESS', window: 3, method: 'colman-2024', analysis: COLMAN_2024.measures(row), says: COLMAN_2024.says(row), verdict: said }], maps: [{ ...receipt('page', 'x').maps[0]!, window: 3, table: 'hd-1-s0003.dat', periodDays: 7.76 }] };
  // Sector 3: 20 September to 17 October 2018. What is read of the window is the paper's row, not the refusing method's measure of the same light.
  const choice = brightnessChoice('hd-1', 'TESS', 3), map = reducedBrightness(choice, listed, TABLE, { time: [1382.5, 1409.4], flux: [1, 1] });
  assert.deepEqual([map.method.published, map.method.read, map.periodDays, map.amplitude, map.periodSource], ['VizieR J/AJ/167/189/fig12', 1, 7.76, 0.0206, 'published by Colman et al. (2024, AJ 167, 189) (VizieR J/AJ/167/189/fig12)']); assert.match(map.method.says, /^a rotation period of 7\.76 d/u);
  assert.deepEqual(map.method.refused, [{ citation: HOLCOMB.citation, mission: 'TESS', reason: none }]);
  const { files } = surfaceMapFiles(BRIGHTNESS_MAPS, { host: 'hd-1', maps: [choice] }, { id: 'hd-1', name: 'HD 1' }, [map], HOST()), read = (path: string) => JSON.parse(files.get(`src/objects/hd-1/${path}`)!) as Record<string, any>;
  const science = read('source/preparation/raster.json').surfaces[2].science, input = read('source/manifest.json').generatedIntermediates[0];
  assert.match(science.description, /turns once in 7\.76 days, fitted with starry to the TESS mission's own 2-minute light curve of sector 3 \(its PDC-MAP flux\) \(the light varies by 2\.1%;.*Colman et al\. \(2024, AJ 167, 189\) list the star as a rotator in their table \(VizieR J\/AJ\/167\/189\/fig12\): a rotation period of 7\.76 d, the highest peak of the Lomb-Scargle periodogram of the star's one sector among sectors 1 to 26, which passed both of the paper's classifiers\. The rotation and its period are theirs, taken as published; no criteria were applied to them here\..*A reduction made in this project, not a published map\./u);
  assert.match(input.credit, /^NASA TESS mission light curve \(PDC-MAP\), sector 3, from MAST; its rotation and period as published by Colman et al\. \(2024, AJ 167, 189\); map made in this project with lightkurve 2\.6\.0, SpinSpotter 0\.2\.0 and starry 1\.2\.0\./u);
  assert.match(read('source/content/object.json').datasets.controls[1].notes, /The light curve is the mission's own; Colman et al\. \(2024, AJ 167, 189\) found the star's rotation in it, and starry finds the map that reproduces it at their period\./u);
  assert.deepEqual(input.sourceBinding.references.map((reference: { catalogueId: string }) => reference.catalogueId), ['mast-tess-light-curves', 'arxiv-2402-14954', 'arxiv-1810-06559', 'gaia-2023-dr3']);
  const record = JSON.parse(brightnessSourceRecords('2026-10-06', [map]).get('src/sources/arxiv-2402-14954.json')!) as Record<string, any>; assert.deepEqual(record.identifiers, [{ type: 'arXiv', value: '2402.14954' }, { type: 'DOI', value: '10.3847/1538-3881/ad2c86' }]);
  // The README says whose verdict it is, what the table gives, and that the method run here on the star's light refuses.
  const readme = withBrightnessReadme('# HD 1\n\n## Sources\n\nGaia.\n\n## Evidence\n\nRun.\n\n## Known problems\n\n- None.\n', map, 7.78);
  assert.match(readme, /light curve of sector 3 \(September and October 2018; its PDC-MAP flux.*It is among the light curves \[Colman et al\. \(2024, AJ 167, 189\)\]\(https:\/\/arxiv\.org\/abs\/2402\.14954\) searched for rotation, and the star's row in their table \(VizieR J\/AJ\/167\/189\/fig12\) is their verdict that it shows the star turning: the period is theirs and nothing is judged here, and starry \(Luger et al\. 2019\) makes the map/su);
  assert.match(readme, /Colman et al\. \(2024, AJ 167, 189\) ask a sector's light to pass both of the paper's random-forest classifiers.*Their table \(VizieR J\/AJ\/167\/189\/fig12\) gives a rotation period of 7\.76 d.*: the star's period is 7\.76 d, as published, and no criteria were applied to it here\. The light varies by 2\.1% \(the range between its 5th and 95th percentiles, as the table prints it\)\. On the paper's blind test set.*The criteria of Holcomb et al\. \(2022, ApJ 936, 138\), applied here to the star's TESS light, are not met: SpinSpotter finds no repeating peaks in the autocorrelation of sector 3\. The star's record holds 7\.78 d from the catalogues\./su);
  // A published period is not a measured one: the star's record is left as it is, and only its README is written.
  const root = await mkdtemp(join(tmpdir(), 'published-'));
  try { await mkdir(join(root, 'src/objects/hd-1/source'), { recursive: true }); await writeFile(join(root, 'src/objects/hd-1/source/measurements.json'), '{"shape":"sphere"}\n'); await writeFile(join(root, 'src/objects/hd-1/README.md'), '# HD 1\n\n## Sources\n\nGaia.\n');
    assert.deepEqual([...(await BRIGHTNESS_ROUTE.starRecords!(root, 'hd-1', [map])).keys()], ['src/objects/hd-1/README.md']);
    assert.deepEqual([...(await BRIGHTNESS_ROUTE.starRecords!(root, 'hd-1', [reducedBrightness(brightnessChoice('hd-1', 'TESS', 95), receipt('assumed', 'assumed'), TABLE, LIGHT)])).keys()], ['src/objects/hd-1/source/measurements.json', 'src/objects/hd-1/README.md']); }
  finally { await rm(root, { recursive: true, force: true }); }
});

test('a verdict whose table prints no swing says the swing is measured here, over every sector mapped', () => {
  // HD 110082 as reduce.mts wrote it on 2026-10-07: Holcomb et al.'s criteria refuse its eight sectors, and Canto Martins et al.'s Table 1 lists the star, on its sectors 12 and 13.
  const none = 'A valid period is found in 3 of the star\'s 8 sectors, and Holcomb et al. (2022) ask for at least 4.', row = CANTO_MARTINS_2020.parse([{ TIC: '383390264', Prot: '2.149', e_Prot: '0.044', tSPAN: '52', Ncyc: '24.2', table: '0' }]).get(383390264)!, said = CANTO_MARTINS_2020.judge(row, [12, 13, 27]).verdict;
  const paper = { id: CANTO_MARTINS_2020.id, citation: CANTO_MARTINS_2020.citation, url: CANTO_MARTINS_2020.url, where: CANTO_MARTINS_2020.where, lightCurve: CANTO_MARTINS_2020.lightCurve, asks: CANTO_MARTINS_2020.asks, reliability: CANTO_MARTINS_2020.reliability, published: CANTO_MARTINS_2020.table, swing: CANTO_MARTINS_2020.swing };
  const own = (window: number) => ({ mission: 'TESS', window, method: 'canto-martins-2020', analysis: CANTO_MARTINS_2020.measures(row), says: CANTO_MARTINS_2020.says(row), verdict: said }), one = receipt('record', 'measurements.json, spinInclinationDegrees').maps[0]!;
  const listed = { ...receipt('record', 'x'), method: paper, rotation: { ...said, amplitude: 0.004896 }, refused: [{ mission: 'TESS', method: HOLCOMB, rotation: { detected: false, reason: none } }], tried: [own(12), own(13)],
    maps: [{ ...one, window: 12, table: 'hd-1-s0012.dat', periodDays: 2.149 }, { ...one, window: 13, table: 'hd-1-s0013.dat', periodDays: 2.149 }] };
  // Sector 13: 19 June to 17 July 2019.
  const choices = [brightnessChoice('hd-1', 'TESS', 12), brightnessChoice('hd-1', 'TESS', 13)], maps = [reducedBrightness(choices[0]!, listed, TABLE, { time: [1625, 1652], flux: [1, 1] }), reducedBrightness(choices[1]!, listed, TABLE, { time: [1653.9, 1682.3], flux: [1, 1] })], map = maps[1]!;
  assert.deepEqual([map.method.published, map.method.swing, map.method.campaigns, map.periodDays, map.amplitude, map.periodSource], ['VizieR J/ApJS/250/20, table 1', 'measured here over the sectors mapped; the table prints none', 2, 2.149, 0.004896, 'published by Canto Martins et al. (2020, ApJS 250, 20) (VizieR J/ApJS/250/20, table 1)']);
  const { files } = surfaceMapFiles(BRIGHTNESS_MAPS, { host: 'hd-1', maps: choices }, { id: 'hd-1', name: 'HD 1' }, maps, HOST()), read = (path: string) => JSON.parse(files.get(`src/objects/hd-1/${path}`)!) as Record<string, any>;
  assert.match(read('source/preparation/raster.json').surfaces[3].science.description, /turns once in 2\.15 days, fitted with starry to the TESS mission's own 2-minute light curve of sector 13 \(its PDC-MAP flux\) \(the light varies by 0\.49%;.*Canto Martins et al\. \(2020, ApJS 250, 20\) list the star as a rotator in their table \(VizieR J\/ApJS\/250\/20, table 1\): a rotation period of 2\.149 ± 0\.044 d, the peak of the wavelet's global spectrum of 52 days of the star's light in sectors 1 to 22 \(24\.2 cycles\), which the paper lists among its unambiguous rotation periods\. The rotation and its period are theirs, taken as published; no criteria were applied to them here\./u);
  assert.deepEqual(read('source/manifest.json').generatedIntermediates[1].sourceBinding.references.map((reference: { catalogueId: string }) => reference.catalogueId), ['mast-tess-light-curves', 'arxiv-2007-03079', 'arxiv-1810-06559', 'gaia-2023-dr3']);
  const record = JSON.parse(brightnessSourceRecords('2026-10-07', maps).get('src/sources/arxiv-2007-03079.json')!) as Record<string, any>; assert.deepEqual(record.identifiers, [{ type: 'arXiv', value: '2007.03079' }, { type: 'DOI', value: '10.3847/1538-4365/aba73f' }]);
  // The README names both sectors, the paper's own words for what it asks, and where the swing comes from.
  const readme = withBrightnessReadme('# HD 1\n\n## Sources\n\nGaia.\n\n## Evidence\n\nRun.\n\n## Known problems\n\n- None.\n', map, 2.34, maps);
  assert.match(readme, /light curves of sectors 12 and 13 \(the newest of June and July 2019; their PDC-MAP flux.*They are among the light curves \[Canto Martins et al\. \(2020, ApJS 250, 20\)\]\(https:\/\/arxiv\.org\/abs\/2007\.03079\) searched for rotation, and the star's row in their table \(VizieR J\/ApJS\/250\/20, table 1\) is their verdict that each shows the star turning: the period is theirs and nothing is judged here/su);
  assert.match(readme, /ask the Lomb-Scargle periodogram, the fast Fourier transform and the wavelet map of a star's light to show one period.*: the star's period is 2\.149 d, as published, and no criteria were applied to it here\. The light varies by 0\.49% \(the range between its 5th and 95th percentiles, measured here over the sectors mapped; the table prints none\)\..*The criteria of Holcomb et al\. \(2022, ApJ 936, 138\), applied here to the star's TESS light, are not met: A valid period is found in 3 of the star's 8 sectors.*The star's record holds 2\.34 d from the catalogues\./su);
});

test('a Kepler star\'s map is of a quarter of its KEPSEISMIC light curve, on the rotation Santos et al. published', () => {
  // Kepler-186 as reduce.mts wrote it on 2026-10-07: Holcomb et al.'s method refuses its TESS light, and its row in Table 3 of Santos et al. (2019) is a rotation.
  const none = 'A valid period is found in 0 of the star\'s 7 sectors, and Holcomb et al. (2022) ask for at least 4.', short = 'Quarter 1 holds 33.5 days of the star\'s light, less than one turn of 33.75 d: not every longitude faced Kepler in it.';
  const note = 'The papers read a period of 33.75 d in the star\'s light filtered at 55 days, and that is the light curve mapped. 3 of the star\'s 17 quarters have no map. The papers\' rule on a quarter\'s variance (García et al. 2014) removes quarter 13, whose variance is 4.4 times the median of the star\'s quarters. Quarters 1 and 17 hold less than one turn of the star.';
  const row = SANTOS_2019.parse([{ KIC: '8120608', Q: '1-17', Fl1: '', Fl2: '0', Fl3: '0', Fl4: '0', Fl5: '0', DMK: '', Prot: '33.75', E_Prot: '2.40', Sph: '2186.4', E_Sph: '52.6', table: '0' }]).get(8120608)!, file = { pipeline: 'KADACS V5', filterDays: 55 };
  const paper = { id: SANTOS_2019.id, citation: SANTOS_2019.citation, url: SANTOS_2019.url, where: SANTOS_2019.where, lightCurve: SANTOS_2019.lightCurve, asks: SANTOS_2019.asks, reliability: SANTOS_2019.reliability, published: SANTOS_2019.table, swing: SANTOS_2019.swing };
  const quarter = (window: number, verdict: Record<string, unknown>) => ({ mission: 'Kepler', window, method: 'santos-2019', lightCurveFile: file, analysis: SANTOS_2019.measures(row), says: SANTOS_2019.says(row), verdict });
  const listed = { ...receipt('assumed', 'assumed: no tilt of the star is known'), star: { id: 'kepler-186', name: 'Kepler-186' }, mission: 'Kepler', method: paper, published: { id: paper.id, kic: 8120608, note }, rotation: { detected: true, periodDays: 33.75, amplitude: 0.008003 }, refused: [{ mission: 'TESS', method: HOLCOMB, rotation: { detected: false, reason: none } }],
    tried: [{ mission: 'TESS', window: 41, method: 'holcomb-2022', analysis: { periodDays: null }, says: 'no repeating peaks in the autocorrelation', verdict: { detected: false, reason: 'none' } },
      quarter(1, { detected: false, reason: short }), quarter(9, { detected: true, periodDays: 33.75, amplitude: 0.005594 }), quarter(16, { detected: true, periodDays: 33.75, amplitude: 0.004857 })],
    maps: [{ ...receipt('assumed', 'assumed: no tilt of the star is known').maps[0]!, mission: 'Kepler', window: 9, table: 'kepler-186-q09.dat', periodDays: 33.75 }, { ...receipt('assumed', 'x').maps[0]!, mission: 'Kepler', window: 16, table: 'kepler-186-q16.dat', periodDays: 33.75 }] };
  const choice = brightnessChoice('kepler-186', 'Kepler', 9); assert.deepEqual(choice, { program: 'kepler-186-q09', id: 'brightness-quarter-9', label: 'Quarter 9' });
  // Quarter 9: 21 March to 26 June 2011, on the Kepler mission's clock. The file is read by this repository's own reader, so starry is the one code.
  const map = reducedBrightness(choice, listed, TABLE, { time: [808.52, 905.92], flux: [1, 1] });
  assert.deepEqual([map.mission, map.window, map.fromUtc, map.toUtc, map.periodDays, map.amplitude, map.codes, map.periodSource], ['Kepler', 9, '2011-03-21', '2011-06-26', 33.75, 0.008003, ['starry 1.2.0'], 'published by Santos et al. (2019, ApJS 244, 21) (VizieR J/ApJS/244/21, table 3)']);
  assert.deepEqual([map.method.published, map.method.read, map.method.note, map.method.refused], ['VizieR J/ApJS/244/21, table 3', 3, note, [{ citation: HOLCOMB.citation, mission: 'TESS', reason: none }]]);
  const { files } = surfaceMapFiles(BRIGHTNESS_MAPS, { host: 'kepler-186', maps: [choice] }, { id: 'kepler-186', name: 'Kepler-186' }, [map], HOST()), read = (path: string) => JSON.parse(files.get(`src/objects/kepler-186/${path}`)!) as Record<string, any>;
  assert.equal(files.get('src/objects/kepler-186/source/science/kepler/kepseismic/kepler-186-q09.dat'), TABLE);
  const science = read('source/preparation/raster.json').surfaces[2].science, input = read('source/manifest.json').generatedIntermediates[0], control = read('source/content/object.json').datasets.controls[1];
  assert.equal(science.consumer, 'kepler-starry'); assert.equal(input.id, 'kepler-186-kepler-map-brightness-quarter-9');
  assert.match(science.description, /turns once in 33\.8 days, fitted with starry to the measured points of quarter 9 of the star's KEPSEISMIC light curve, which its authors make from the Kepler mission's pixels \(the light varies by 0\.80%;.*Santos et al\. \(2019, ApJS 244, 21\) list the star as a rotator in their table \(VizieR J\/ApJS\/244\/21, table 3\): a rotation period of 33\.75 ± 2\.4 d and a photometric activity \(S_ph, the scatter of the light over five rotations\) of 2186 parts per million\. The rotation and its period are theirs, taken as published; no criteria were applied to them here\./u);
  assert.match(input.credit, /^KEPSEISMIC light curve of the NASA Kepler mission's pixels \(Mathur, Santos & García\), quarter 9, from MAST; its rotation and period as published by Santos et al\. \(2019, ApJS 244, 21\); map made in this project with starry 1\.2\.0\. This work includes data collected by the Kepler mission/u);
  assert.match(input.title, /from its light curve in Kepler quarter 9, KEPSEISMIC's: brightness/u); assert.match(input.acquisition, /from the light curve of the quarter published by its authors as a high-level science product and kept at MAST\./u);
  assert.equal(control.qualification, 'Mapped in this project · KEPSEISMIC light curve of Kepler, quarter 9'); assert.match(control.notes, /in Kepler quarter 9.*The light curve is KEPSEISMIC's; Santos et al\. \(2019, ApJS 244, 21\) found the star's rotation in it, and starry finds the map that reproduces it at their period\./u);
  assert.deepEqual(input.sourceBinding.references.map((reference: { catalogueId: string }) => reference.catalogueId), ['mast-kepseismic-light-curves', 'arxiv-1908-05222', 'arxiv-1810-06559', 'gaia-2023-dr3']);
  const records = brightnessSourceRecords('2026-10-07', [map]), product = JSON.parse(records.get('src/sources/mast-kepseismic-light-curves.json')!) as Record<string, any>;
  assert.deepEqual(product.identifiers, [{ type: 'DOI', value: '10.17909/t9-mrpw-gc07' }]); assert.deepEqual((JSON.parse(records.get('src/sources/arxiv-1908-05222.json')!) as Record<string, any>).identifiers, [{ type: 'arXiv', value: '1908.05222' }, { type: 'DOI', value: '10.3847/1538-4365/ab3b56' }]);
  // The README names the quarters mapped, whose verdict the rotation is, where the swing comes from, the filter read and why a quarter has no map.
  const later = reducedBrightness(brightnessChoice('kepler-186', 'Kepler', 16), listed, TABLE, { time: [1471.1, 1556.96], flux: [1, 1] });
  const readme = withBrightnessReadme('# Kepler-186\n\n## Sources\n\nGaia.\n\n## Evidence\n\nRun.\n\n## Known problems\n\n- None.\n', later, 34.29, [map, later]);
  assert.match(readme, /\*\*Brightness from Kepler\.\*\* The Color \+ brightness and Brightness map datasets are made in this project from quarters 9 and 16 of the star's KEPSEISMIC light curve \(the newest of January to April 2013\), which its authors make from the Kepler mission's pixels and keep at \[MAST\]\(https:\/\/archive\.stsci\.edu\/hlsp\/kepseismic\) \(\[source record\]\(\.\.\/\.\.\/sources\/mast-kepseismic-light-curves\.json\)\)\. It is the light curve \[Santos et al\. \(2019, ApJS 244, 21\)\]\(https:\/\/arxiv\.org\/abs\/1908\.05222\) judge, and the star's row in their table \(VizieR J\/ApJS\/244\/21, table 3\) is their verdict that it shows the star turning: the period is theirs and nothing is judged here, and starry/u);
  assert.match(readme, /the star's period is 33\.75 d, as published, and no criteria were applied to it here\. The light varies by 0\.80% \(the range between its 5th and 95th percentiles, measured here over the quarters mapped; the table prints another measure of it, S_ph\)\. The papers read a period of 33\.75 d in the star's light filtered at 55 days, and that is the light curve mapped\. 3 of the star's 17 quarters have no map\. The papers' rule on a quarter's variance \(García et al\. 2014\) removes quarter 13, whose variance is 4\.4 times the median of the star's quarters\. Quarters 1 and 17 hold less than one turn of the star\. For the 11,209 stars.*The criteria of Holcomb et al\. \(2022, ApJ 936, 138\), applied here to the star's TESS light, are not met: A valid period is found in 0 of the star's 7 sectors.*The star's record holds 34\.29 d from the catalogues\./su);
  // What the reduction found is recorded for a Kepler star as for any other: the quarter last read.
  const looked = withPixelLight({ shape: 'sphere' }, listed); assert.deepEqual([looked.pixelLightMission, looked.pixelLightWindow], ['Kepler', 16]); assert.match(String(looked.pixelLightSource), /^Read in this project from the Kepler KEPSEISMIC light curve of quarter 16/u);
});

test('a star K2\'s method refused is read from its TESS windows, and a value its record lacked is named', () => {
  // K2 campaign 8 and TESS sector 8 are two windows: the map of sector 8 reads what the TESS method measured, and the README keeps K2's refusal.
  const low = 'The periodogram\'s highest peak, at 16.50 d, has a height of 0.08, not over the 0.3 that Reinhold & Hekker (2020) ask of a rotation.', own = receipt('assumed', 'assumed');
  const after = { ...own, refused: [{ mission: 'K2', method: { id: 'reinhold-hekker-2020', citation: 'Reinhold & Hekker (2020, A&A 635, A43)' }, rotation: { detected: false, reason: low } }],
    inputCatalogue: { name: 'TESS Input Catalog', version: '8.2', tic: 256364928, fills: ['surfaceGravityLogg'], says: 'The TESS Input Catalog (v8.2), in the header of the star\'s sector 41 light curve, gives 5023 K and log g 4.58.' },
    tried: [{ mission: 'K2', window: 9, verdict: { detected: false, reason: 'not campaign 9' } }, { mission: 'K2', window: 8, method: 'reinhold-hekker-2020', says: 'periodogram 16.50 d, wavelet 14.00 d, autocorrelation 9.00 d; periodogram peak 0.08', analysis: { peakHeight: 0.08, lombScargleDays: 16.5, waveletDays: 14, autocorrelationDays: 9 }, verdict: { detected: false, reason: low } },
      { ...own.tried[0]!, window: 8 }, { ...own.tried[0]!, window: 9, says: 'no repeating peaks in the autocorrelation', verdict: { detected: false, reason: 'none' } }], maps: [{ ...own.maps[0]!, window: 8, table: 'hd-1-s0008.dat' }] };
  const map = reducedBrightness(brightnessChoice('hd-1', 'TESS', 8), after, TABLE, LIGHT);
  assert.deepEqual([map.mission, map.method.id, map.method.says, map.method.read, map.method.periodsDays], ['TESS', 'holcomb-2022', SAYS, 2, undefined]);
  const readme = withBrightnessReadme('# HD 1\n\n## Sources\n\nGaia.\n\n## Evidence\n\nRun.\n\n## Known problems\n\n- None.\n', map);
  assert.match(readme, /Sector 8 gives a period of 4\.85 d.*; 1 more of the star's 2 sectors does not meet the criteria\..*On the stars its authors inspected by eye.*The criteria of Reinhold & Hekker \(2020, A&A 635, A43\), applied here to the star's K2 light, are not met: The periodogram's highest peak, at 16\.50 d, has a height of 0\.08.*The star's record holds no surface gravity: the TESS Input Catalog \(v8\.2\), in the header of the star's sector 41 light curve, gives 5023 K and log g 4\.58, and that is what decides whether the method is for this kind of star\. The star's record holds no catalogued rotation period/su);
  // A star whose record held both values says nothing of the catalog; a catalogue's row of a star is matched as the metadata pass matches one.
  assert.equal(reducedBrightness(brightnessChoice('hd-1', 'TESS', 95), own, TABLE, LIGHT).kindFrom, undefined); assert.equal(SAME_STAR_ARCSEC, MATCH_ARCSEC);
});

test('a star MEarth watched is mapped a season, to the first degree, on the rotation Newton et al. published', () => {
  // Proxima Centauri as reduce.mts wrote it on 2026-10-08: its TESS target is blended, so no method read it, and its row in Table 1 of Newton et al. (2018) is a grade A rotation.
  const short = 'The star\'s 2018 season holds 81.9 days of its MEarth light, less than one turn of 88.977 d: not every longitude faced the telescope in it.';
  const note = 'The light curve mapped is the star\'s longest dataset in the MEarth release, that of telescope 11: 601 nights before 2 March 2018, where the paper\'s table prints 600 for its longest. The paper\'s model, fitted to it here at 88.977 d by its authors\' code, gives the sinusoid a semi-amplitude of 0.0073 mag, where the table prints 0.0073. The star\'s 2018 season holds less than one turn of it and has no map.';
  const row = NEWTON_2018.parse([{ Type: 'A', twomass: '14294291-6240465', RAJ2000: '217.42925', DEJ2000: '-62.67963889', Per: '88.977', Amp: '0.0073', e_Amp: '0.0067', Flag: '', NPts: '6009', NDays: '600', ftest: '2893' }]).get('14294291-6240465')!;
  const paper = { id: NEWTON_2018.id, citation: NEWTON_2018.citation, url: NEWTON_2018.url, where: NEWTON_2018.where, lightCurve: NEWTON_2018.lightCurve, asks: NEWTON_2018.asks, reliability: NEWTON_2018.reliability, published: NEWTON_2018.table, swing: NEWTON_2018.swing };
  const file = { url: 'https://lweb.cfa.harvard.edu/MEarth/DR11/south2014-2022/lc/2MASSJ14294291-6240465_tel11_2014-2022.txt', bytes: 18470000, pipeline: 'Data Release 11', telescope: 'tel11', filter: 'RG715', aperturePixels: 8.485, deblended: false };
  const season = (window: number, verdict: Record<string, unknown>) => ({ mission: 'MEarth', window, method: 'newton-2018', lightCurveFile: file, frames: 204, analysis: { ...NEWTON_2018.measures(row), datasetNights: 601, fittedSemiAmplitudeMag: 0.007261, commonModeScale: 1.3672 }, says: NEWTON_2018.says(row), verdict });
  const made = receipt('assumed', 'assumed: no tilt of the star is known').maps[0]!, seen = { detected: true, periodDays: 88.977, amplitude: 0.013447 };
  const listed = { ...receipt('assumed', 'x'), star: { id: 'proxima-centauri', name: 'Proxima Centauri' }, light: { gaiaDr3: '5853498713190525696', magnitude: 7.57, neighbours: 2, neighbourShare: 0.0004 }, mission: 'MEarth', method: paper, published: { id: paper.id, twomass: row.twomass, note }, rotation: seen,
    tried: [season(2016, seen), season(2017, seen), season(2018, { detected: false, reason: short })], toolchain: { id: 'mearth-photometry', requirements: ['numpy==2.5.3', 'sfit @ git+https://github.com/mdwarfgeek/sfit@84c8bc2254387d6171758ba86eb1c37a8d246406'] },
    maps: [{ ...made, mission: 'MEarth', window: 2016, table: 'proxima-centauri-y2016.dat', degree: 1, periodDays: 88.977, darkestPercent: 98.2, brightestPercent: 101.8 }, { ...made, mission: 'MEarth', window: 2017, table: 'proxima-centauri-y2017.dat', degree: 1, periodDays: 88.977, darkestPercent: 99.7, brightestPercent: 100.3 }] };
  const choice = brightnessChoice('proxima-centauri', 'MEarth', 2016); assert.deepEqual(choice, { program: 'proxima-centauri-y2016', id: 'brightness-season-2016', label: 'Season 2016' });
  // The 2016 season: 1 January to 29 September 2016, as barycentric Julian dates less 2450000. The file is read by this repository's own reader; sfit prepares it and starry maps it.
  const map = reducedBrightness(choice, listed, TABLE, { time: [7388.6, 7660.6], flux: [1, 1] });
  assert.deepEqual([map.mission, map.window, map.fromUtc, map.toUtc, map.periodDays, map.amplitude, map.codes, map.periodSource], ['MEarth', 2016, '2016-01-01', '2016-09-29', 88.977, 0.013447, ['sfit (commit 84c8bc2)', 'starry 1.2.0'], 'published by Newton et al. (2018, AJ 156, 217) (VizieR J/AJ/156/217/table1)']);
  assert.deepEqual([map.method.published, map.method.swing, map.method.read, map.method.note, map.method.refused], ['VizieR J/AJ/156/217/table1', 'twice the semi-amplitude of the sinusoid the table prints', 3, note, undefined]);
  // A receipt that does not name the pinned fitting code is of another toolchain.
  assert.throws(() => reducedBrightness(choice, { ...listed, toolchain: receipt('assumed', 'x').toolchain }, TABLE, { time: [7388.6, 7660.6], flux: [1, 1] }), /does not name the pinned sfit/u);
  const { files } = surfaceMapFiles(BRIGHTNESS_MAPS, { host: 'proxima-centauri', maps: [choice] }, { id: 'proxima-centauri', name: 'Proxima Centauri' }, [map], HOST()), read = (path: string) => JSON.parse(files.get(`src/objects/proxima-centauri/${path}`)!) as Record<string, any>;
  assert.equal(files.get('src/objects/proxima-centauri/source/science/mearth/proxima-centauri-y2016.dat'), TABLE);
  const science = read('source/preparation/raster.json').surfaces[2].science, input = read('source/manifest.json').generatedIntermediates[0], control = read('source/content/object.json').datasets.controls[1];
  assert.equal(science.consumer, 'mearth-starry'); assert.equal(input.id, 'proxima-centauri-mearth-map-brightness-season-2016');
  assert.match(science.description, /turns once in 89 days, fitted with starry to the star's MEarth light curve of its 2016 season, one point a night \(each night's median\), after the segment baselines and the common mode of the model of Newton et al\. \(2016, 2018\) are taken off it by that model's own code, sfit; the map is of the first degree, one brighter and one darker side, which is what the sinusoid of that model fixes \(the light varies by 1\.3%;.*Newton et al\. \(2018, AJ 156, 217\) list the star as a rotator in their table \(VizieR J\/AJ\/156\/217\/table1\): a grade A rotation period of 88\.977 d, with a sinusoid of semi-amplitude 0\.0073 mag in the star's longest dataset, of 600 nights\. The rotation and its period are theirs, taken as published; no criteria were applied to them here\..*Gaia DR3 lists 2 other stars within 8 arcseconds/u);
  assert.match(input.credit, /^MEarth Project light curve \(Data Release 11; Berta et al\. 2012, AJ 144, 145\), season 2016, from the project's public data release; its rotation and period as published by Newton et al\. \(2018, AJ 156, 217\); map made in this project with sfit \(commit 84c8bc2\) and starry 1\.2\.0\. This paper makes use of data from the MEarth Project, which is a collaboration between Harvard University and the Smithsonian Astrophysical Observatory\./u);
  assert.equal(input.displayCredit, 'MEarth Project · mapped here'); assert.match(input.license, /^Public MEarth Project data, used with the citation and the acknowledgement its release asks for/u); assert.deepEqual(input.licenseEvidence, ['https://lweb.cfa.harvard.edu/MEarth/DataDR11.html']);
  assert.match(input.title, /from its light curve in MEarth season 2016, the MEarth Project's: brightness/u); assert.match(input.acquisition, /from the light curve of the season published by the MEarth Project in its Data Release 11\./u);
  assert.equal(control.qualification, 'Mapped in this project · MEarth Project light curve, season 2016'); assert.match(control.notes, /in MEarth season 2016.*The light curve is the MEarth Project's; Newton et al\. \(2018, AJ 156, 217\) found the star's rotation in it, and starry finds the map that reproduces it at their period\./u);
  assert.deepEqual(input.sourceBinding.references.map((reference: { catalogueId: string }) => reference.catalogueId), ['mearth-light-curves', 'arxiv-1807-09365', 'arxiv-1810-06559', 'gaia-2023-dr3']);
  // The release has no DOI: its record holds none, one link, and the acknowledgement the release asks for.
  const records = brightnessSourceRecords('2026-10-08', [map]), product = JSON.parse(records.get('src/sources/mearth-light-curves.json')!) as Record<string, any>;
  assert.deepEqual(product.identifiers, []); assert.deepEqual(product.links, [{ role: 'landing', url: 'https://lweb.cfa.harvard.edu/MEarth/DataDR11.html', label: 'MEarth Project photometric Data Release 11: light curves of the M dwarf targets, 2008 to 2022' }]);
  assert.equal(product.evidence[0].url, 'https://lweb.cfa.harvard.edu/MEarth/DR11/README.txt'); assert.match(product.statements[0].text, /^This paper makes use of data from the MEarth Project.*the John Templeton Foundation\.$/u); assert.match(product.publisher, /^The MEarth Project/u);
  assert.deepEqual((JSON.parse(records.get('src/sources/arxiv-1807-09365.json')!) as Record<string, any>).identifiers, [{ type: 'arXiv', value: '1807.09365' }, { type: 'DOI', value: '10.3847/1538-3881/aad73b' }]);
  // The README names the seasons mapped, whose verdict the rotation is, that the swing is the table's sinusoid, the dataset read and the season without a map.
  const later = reducedBrightness(brightnessChoice('proxima-centauri', 'MEarth', 2017), listed, TABLE, { time: [7720.8, 8026.4], flux: [1, 1] });
  const readme = withBrightnessReadme('# Proxima Centauri\n\n## Sources\n\nGaia.\n\n## Evidence\n\nRun.\n\n## Known problems\n\n- None.\n', later, 83.5, [map, later]);
  assert.match(readme, /\*\*Brightness from MEarth\.\*\* The Color \+ brightness and Brightness map datasets are made in this project from the star's MEarth light curve of its 2016 and 2017 seasons \(the newest of November 2016 to September 2017\), from the MEarth Project's \[Data Release 11\]\(https:\/\/lweb\.cfa\.harvard\.edu\/MEarth\/DataDR11\.html\): one point a night, after the segment baselines and the common mode of the paper's model are taken off it by that model's own code \(\[source record\]\(\.\.\/\.\.\/sources\/mearth-light-curves\.json\)\)\. It is the light curve \[Newton et al\. \(2018, AJ 156, 217\)\]\(https:\/\/arxiv\.org\/abs\/1807\.09365\) judge, and the star's row in their table \(VizieR J\/AJ\/156\/217\/table1\) is their verdict that it shows the star turning: the period is theirs and nothing is judged here, and starry/u);
  assert.match(readme, /the star's period is 88\.977 d, as published, and no criteria were applied to it here\. The light varies by 1\.3% \(twice the semi-amplitude of the sinusoid the table prints\)\. The light curve mapped is the star's longest dataset in the MEarth release, that of telescope 11: 601 nights before 2 March 2018, where the paper's table prints 600 for its longest\..*The star's 2018 season holds less than one turn of it and has no map\. The paper estimates the errors of its rotation periods at about 10%\. The star's record holds 83\.5 d from the catalogues\..*Gaia DR3 lists 2 other stars within 8 arcseconds/su);
  // What the reduction found is recorded as for any other star: the season last read.
  const looked = withPixelLight({ shape: 'sphere' }, listed); assert.deepEqual([looked.pixelLightMission, looked.pixelLightWindow], ['MEarth', 2018]); assert.match(String(looked.pixelLightSource), /^Read in this project from the MEarth light curve of season 2018/u);
});
