import type { Connect, Plugin } from 'vite';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import searchRoute from '../../netlify/edge-functions/search-route.ts';
import { handleSearchRequest } from '../../site/search-response.mts';
import { handleFindRequest } from '../../site/find.mts';
import { FIND_PATH } from '../../site/find-protocol.mts';
import { parseFeaturePin } from '../../site/feature-search.mts';

/** Exercise Netlify's exact routing and handler in Astro dev and static preview. */
export function searchServer(): Plugin {
  const middleware: Connect.NextHandleFunction = (request, response, next) => {
    if (!request.url || !request.headers.host) return next();
    const url = new URL(request.url, `http://${request.headers.host}`);
    if (url.pathname === FIND_PATH) {
      // Read at request time: the pin is regenerated by prepare-feature-index while dev runs.
      void readFile(resolve(import.meta.dirname, '../../site/prepared-feature-index.json'), 'utf8').then(async pin => {
        const featurePin = parseFeaturePin(pin);
        if (!featurePin) { response.writeHead(404); response.end(); return; }
        const result = await handleFindRequest(new Request(url, { method: request.method }), featurePin);
        response.writeHead(result.status, Object.fromEntries(result.headers));
        response.end(Buffer.from(await result.arrayBuffer()));
      }).catch(next);
      return;
    }
    const route = searchRoute(new Request(url));
    if (!route) return next();
    void handleSearchRequest(new Request(route, { method: request.method })).then(async result => {
      response.writeHead(result.status, Object.fromEntries(result.headers));
      response.end(Buffer.from(await result.arrayBuffer()));
    }).catch(next);
  };
  return { name: 'cssearth-native-search', configureServer(server) { server.middlewares.use(middleware); },
    configurePreviewServer(server) { server.middlewares.use(middleware); } };
}
