import { sha256 } from '../../../src/platform/sha256.mts';
import { matchesPreparationGenerator } from '../../prepare/preparation-generator.mts';
import type { RadialState, RadialMaterialConfig, RadialMaterialSurface } from './solid-contract.mts';
import type { PreparedTriangle, SourceSurfaceSample, SciencePalette } from './contracts.mts';
import type { createSourceManifest } from '../../../src/platform/source-manifest.mts';
import { requireArray, requireString, requireRecord, requireFiniteNumber } from '../../sources/source-values.mts';
import { parseRadialSnapshot } from './radial-source.mts';
import { requireTerrainMesh } from './radial-mesh.mts';
import { resolve, dirname } from 'node:path';
import { gzipSync } from 'node:zlib';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import sharp from 'sharp';
import { BASE_TILE } from '@layoutit/polycss';
import { closestTrianglePoint } from './obj-shape.mts';
import { createSourceSurfacePainter } from './scientific-raster.mts';
import { missingCoverageColor } from '../../../src/platform/prepare-missing-coverage.mts';
import { createRasterEmitter } from './raster-output.mts';
import { renderRadialSnapshot } from './radial-snapshot.mts';
import { createSourceMeshLighting } from './source-mesh-lighting.mts';
import { linearToSrgb, srgbToLinear } from '../color-transfer.mts';
import { prepareNativePhotographicAtlas } from './native-photograph.mts';
import { neutralShapeAtlas, shapeFillIllumination } from './shape-material.mts';

interface ObservationTransfer {
  interiorTexels: number; counts: Record<string, number>; sources?: Record<string, number>;
  maximumSourceDistanceMeters: number; maximumPixelSeparationMeters: number; maximumPhotometricGain: number; method: string;
}

/** Scales a photograph's encoded sRGB byte by an illumination factor in linear light. */
const litByte = (byte: number, illumination: number) => Math.round(255 * linearToSrgb(srgbToLinear(byte / 255) * illumination));

const sub = (a: readonly number[], b: readonly number[]) => a.map((v, i) => v - b[i]);
const dot = (a: readonly number[], b: readonly number[]) => a.reduce((sum, v, i) => sum + v * b[i], 0);

/** Shared by the retained atlas and prepare-only context image. Coordinates
 * enter in display units and are immediately restored to physical metres. */
export function createRadialScienceColorSampler<T extends SourceSurfaceSample>(sourceSurface: {samplePoint(point: readonly number[]): T | null}, lens: SciencePalette, config: {geometry: {radiusKm: number; radius: number}; raster: {width: number}}) {
  const paint = createSourceSurfacePainter(lens);
  const metersPerUnit = config.geometry.radiusKm * 1000 / config.geometry.radius;
  return (point: readonly number[]) => {
    const sample = sourceSurface.samplePoint(point.map(n => n * metersPerUnit));
    if (sample) return { ...sample, color: paint(sample) };
    const longitude = Math.atan2(point[1], point[0]) * 180 / Math.PI;
    const latitude = Math.atan2(point[2], Math.hypot(point[0], point[1])) * 180 / Math.PI;
    return { color: missingCoverageColor(longitude, latitude, 360 / config.raster.width) };
  };
}

/** Replace a reviewed generated intermediate with regenerated bytes. */
async function replaceReviewedImage(sourceDirectory: string, path: string, bytes: Uint8Array) {
  const manifest = requireRecord(JSON.parse(await readFile(resolve(sourceDirectory, 'manifest.json'), 'utf8')));
  const entries = requireArray(manifest.generatedIntermediates).map(value => requireRecord(value)).filter(entry => entry.path === path);
  if (entries.length !== 1) throw new TypeError(`Reviewed image ${path} needs exactly one manifest entry.`);
  await writeFile(resolve(sourceDirectory, path), bytes);
}

/** Bake opaque triangle rasters, coordinates and fixed-epoch Sun illumination. The
 * renderer switches between these prepared banks through ordinary variants.
 */
export async function prepareRadialMaterials({ radial, surfaces, config, source, sourceDirectory, publicDirectory, outputDirectory, sunDirection,
  artifactId = null, snapshotEntries = source.manifest.generatedIntermediates, replaceReviewedImages = false }: {
    radial: Pick<RadialState,'width'|'height'|'faces'|'observationSurfaces'|'completion'|'coverage'|'simplification'> & {scientificSurfaces?:ReadonlyMap<string,{samplePoint?:(point:readonly number[])=>SourceSurfaceSample|null;report?:unknown}>;grid?:RadialState['grid'];plans:readonly {face:PreparedTriangle;rect:{x:number;y:number;width:number;height:number};matrix:readonly number[];geometry:{leafWidth:number;leafHeight:number}}[]}; surfaces: RadialMaterialSurface[]; config: RadialMaterialConfig;
    source: Pick<Awaited<ReturnType<typeof createSourceManifest>>, 'manifest'>;
    sourceDirectory?: string; publicDirectory: string; outputDirectory: string; sunDirection: readonly number[]; artifactId?: string | null;
    snapshotEntries?: Awaited<ReturnType<typeof createSourceManifest>>['manifest']['generatedIntermediates'];
    /** Write mode: a regenerated reviewed image replaces the source copy and its manifest pin; review it in the diff. */
    replaceReviewedImages?: boolean;
  }) {
  if (artifactId !== null && !/^[a-z][a-z0-9-]*$/.test(artifactId)) throw new TypeError('Invalid surface model artifact id.');
  const suffix = artifactId ? `-${artifactId}` : '';
  const { width: canonicalWidth, height: canonicalHeight } = radial;
  const lightingRecipe = config.geometry.radialTerrain.sourceLighting;
  const lighting = lightingRecipe ? createSourceMeshLighting(requireTerrainMesh(radial.grid ?? (()=>{throw new TypeError("Source lighting requires the original mesh.");})()), lightingRecipe,
    config.geometry.radiusKm * 1000 / config.geometry.radius, sunDirection) : null;
  // Every surface at a given scale uses these exact plans, points and normals.
  // Keep double-precision results across banks; ray tracing depends on geometry,
  // never on the selected photograph or scientific colour.
  const lightingByScale = new Map();
  let reusedLightingSamples = 0;
  const emit = createRasterEmitter(publicDirectory, config.publicBase);
  for (const surface of surfaces) {
    const neutralShape = surface.material && requireRecord(surface.material).kind === 'unobserved-neutral';
    if (neutralShape && !lighting && !surface.textureScale &&
        !config.geometry.radialTerrain.thumbnail && !radial.faces.some(face => face.estimated) && !radial.grid?.imageGrid) {
      const { flood, shadow } = neutralShapeAtlas(radial, sunDirection);
      const raw = { width: canonicalWidth, height: canonicalHeight, channels: 4 as const };
      // No quality: the emitter writes it in the lossy lane (lossy-lane.ts).
      const encoding = { alphaQuality: 100, effort: 4 };
      surface.surface = await emit(`${config.namespace}-${surface.id}-surface@2x.webp`, sharp(flood, { raw }), encoding);
      surface.shadowSurface = await emit(`${config.namespace}-${surface.id}-shadow@2x.webp`, sharp(shadow, { raw }), encoding);
      surface.polesUrl = surface.surface.url;
      surface.layout = { kind: 'triangle-atlas', width: canonicalWidth, height: canonicalHeight, faceCount: radial.faces.length };
      continue;
    }
    const photograph=config.raster.observations?.find(observation=>observation.id===surface.id);
    if(photograph?.nativePhotographicSampling) {
      if(!sourceDirectory || lightingRecipe || artifactId || surface.textureScale || radial.observationSurfaces?.has(surface.id) || radial.scientificSurfaces?.has(surface.id)) {
        throw new Error('Native photograph refresh requires the existing cylindrical-map terrain and lighting.');
      }
      const input=source.manifest.inputs.find(entry=>requireRecord(entry).lensId===surface.id && entry.consumers.includes('surfaces'));
      if(!input)throw new Error(`No pinned photograph for ${surface.id}.`);
      Object.assign(surface,await prepareNativePhotographicAtlas({radial,sourceDirectory,source:input,validity:photograph.validity,
        sampling:photograph.nativePhotographicSampling,publicDirectory,publicBase:config.publicBase,id:`${config.namespace}-${surface.id}`,
        sunDirection,mapWidth:config.raster.width}));
      continue;
    }
    // The retained CSS background size stays canonical. Only prepared image
    // pixels and atlas rectangles scale; each normalized UV keeps its owner.
    const scale = surface.textureScale ?? 1;
    const width = canonicalWidth * scale, height = canonicalHeight * scale;
    if (![1,.5,.25,.125].includes(scale) || ![width,height].every(n=>Number.isSafeInteger(n) && n>0)) {
      throw new TypeError('Scaled radial atlas dimensions must remain integral.');
    }
    const flood = Buffer.alloc(width * height * 4), shadow = Buffer.alloc(width * height * 4);
    let cachedLighting = lightingByScale.get(scale);
    if (lighting && !cachedLighting) {
      cachedLighting = new Float64Array(width * height * 2).fill(NaN);
      lightingByScale.set(scale, cachedLighting);
    }
    const nearest = surface.displaySampling === 'nearest';
    const sourceSurface = radial.scientificSurfaces?.get(surface.id);
    const scientific = sourceSurface && (config.raster.scientific ?? []).find(lens => lens.id === surface.id);
    if (sourceSurface && (!scientific || !sourceSurface.samplePoint || !scientific.surfaceSampling)) throw new Error('Terrain science requires its source-point sampler and bound profile.');
    const sampleScience = scientific && sourceSurface?.samplePoint
      ? createRadialScienceColorSampler({samplePoint: sourceSurface.samplePoint}, scientific, config) : null;
    const scalarSources = ['pds3-scalar-map', 'facet-scalars', 'vtk-cell-categories', 'obj-uv-fits'].includes(scientific?.format ?? '') && Buffer.alloc(width * height * 4);
    const observation = radial.observationSurfaces?.get(surface.id);
    // Direct source samplers never consume the flat preview, including its
    // withheld radial directions. Keep that map only for previews/minimaps.
    let map, info;
    if (!sourceSurface && !observation) {
      ({ data: map, info } = await sharp(resolve(publicDirectory, requireString(surface.map.url.split('/').at(-1))))
        .ensureAlpha().raw().toBuffer({ resolveWithObject: true }));
    }
    const observedFrames = observation && requireArray(requireRecord(observation.report).frames);
    // Only a mosaic needs a source index; a single photograph's coverage mask already names its one source.
    const frames = observedFrames && observedFrames.length > 1 ? observedFrames.map(value => {const frame=requireRecord(value);return {...frame,id:requireString(frame.id)};}) : null;
    const sampleSources = frames && Buffer.alloc(width * height);
    const observationTransfer: ObservationTransfer | undefined = observation && { interiorTexels: 0, counts: {}, maximumSourceDistanceMeters: 0,
      maximumPixelSeparationMeters: 0, maximumPhotometricGain: 0,
      method: 'Closest full-source triangle point; all bilinear observation contributors checked before interpolation; atlas bleed clamped to retained face.' };
    const transfer = sourceSurface && scientific?.surfaceSampling && { sampledTexels: 0, withheldTexels: 0, maximumDistanceMeters: 0,
      includesAtlasBleed: true, triangleInteriorTexels: 0, withheldTriangleInteriorTexels: 0,
      maximumAcceptedDistanceMeters: scientific.surfaceSampling.maximumDistanceMeters,
      method: scalarSources ? requireRecord(sourceSurface.report).registration : 'Closest full-source triangle point in 3D; source barycentric radius and normal. No radial branch selection.' };
    for (const { face, rect, geometry, matrix: m } of radial.plans) {
      const [a, b, c] = face.vertices, ab = sub(b, a), ac = sub(c, a), aa = dot(ab, ab), bb = dot(ac, ac), abac = dot(ab, ac);
      const denominator = aa * bb - abac * abac;
      const rectWidth = rect.width * scale, rectHeight = rect.height * scale;
      const [n0, n1, n2] = face.vertexNormals;
      // The leaf clips its rectangle to the triangle it draws, base along the bottom and apex at the top centre, seam overlap included.
      // A texel is drawn only inside it or within the few texels filtering reads across an edge; texels farther out are not sampled,
      // and each takes the nearest sampled texel in its row. Distances are in leaf pixels, one texel each at scale 1.
      const W = geometry.leafWidth, H = geometry.leafHeight, slant = Math.hypot(W / 2, H), marginPixels = UNDRAWN_MARGIN_TEXELS * Math.max(W / rectWidth, H / rectHeight);
      const undrawn = new Uint8Array(rectWidth * rectHeight);
      for (let py = 0; py < rectHeight; py++) for (let px = 0; px < rectWidth; px++) {
        const x = (px + .5) * geometry.leafWidth / rectWidth, y = (py + .5) * geometry.leafHeight / rectHeight;
        const w = m[3] * x + m[7] * y + m[15];
        const point = [(m[1] * x + m[5] * y + m[13]) / w / BASE_TILE, (m[0] * x + m[4] * y + m[12]) / w / BASE_TILE, (m[2] * x + m[6] * y + m[14]) / w / BASE_TILE];
        // Scalar forms of dot, sub and unit in their exact operation order (dot's reduce starts from 0), so every texel is bit-identical.
        const ap0 = point[0] - a[0], ap1 = point[1] - a[1], ap2 = point[2] - a[2];
        const apab = 0 + ap0 * ab[0] + ap1 * ab[1] + ap2 * ab[2], apac = 0 + ap0 * ac[0] + ap1 * ac[1] + ap2 * ac[2];
        const u = (apab * bb - apac * abac) / denominator, v = (apac * aa - apab * abac) / denominator;
        // Outward distance past the left edge (0, H)–(W/2, 0) and the right edge (W/2, 0)–(W, H).
        const beyond = Math.max((H * (W / 2 - x) - (W / 2) * y) / slant, (H * (x - W / 2) - (W / 2) * y) / slant);
        if (beyond > marginPixels) { undrawn[py * rectWidth + px] = 1; continue; }
        // PolyCSS's native u primitive owns triangle coverage. Fill its entire
        // raster so antialiasing never samples a transparent triangle edge.
        const nx = n0[0] * (1 - u - v) + n1[0] * u + n2[0] * v, ny = n0[1] * (1 - u - v) + n1[1] * u + n2[1] * v, nz = n0[2] * (1 - u - v) + n1[2] * u + n2[2] * v;
        const length = Math.hypot(nx, ny, nz), normal = [nx / length, ny / length, nz / length];
        // Fixed-epoch directional illumination is baked in the body's frame.
        const lightIndex = ((rect.y * scale + py) * width + rect.x * scale + px) * 2;
        let light;
        if (!face.estimated && lighting) {
          if (Number.isNaN(cachedLighting[lightIndex])) {
            light = lighting.sample(point, normal);
            cachedLighting[lightIndex] = light.flood;
            cachedLighting[lightIndex + 1] = light.shadow;
          } else {
            light = { flood: cachedLighting[lightIndex], shadow: cachedLighting[lightIndex + 1] };
            reusedLightingSamples++;
          }
        }
        const sunDot = 0 + normal[0] * sunDirection[0] + normal[1] * sunDirection[1] + normal[2] * sunDirection[2];
        let illumination = light?.shadow ?? (.12 + .88 * Math.max(0, sunDot));
        const offset = ((rect.y * scale + py) * width + rect.x * scale + px) * 4;
        const clampedPoint = radial.grid?.imageGrid && closestTrianglePoint(point, a, ab, ac).point;
        const sourceMeters = config.geometry.radiusKm * 1000 / config.geometry.radius;
        const outsideSource = clampedPoint && (radial.grid?.heightAt ?? (() => {throw new Error("Image DEM lacks a source height sampler");}))(clampedPoint[0] * sourceMeters, clampedPoint[1] * sourceMeters) === null;
        if (face.estimated || outsideSource) {
          const color = missingCoverageColor(Math.atan2(point[1], point[0]) * 180 / Math.PI,
            Math.atan2(point[2], Math.hypot(point[0], point[1])) * 180 / Math.PI, 360 / config.raster.width);
          const interior = u >= 0 && v >= 0 && u + v <= 1;
          if (observationTransfer && interior) {
            observationTransfer.interiorTexels++;
            const reason = face.estimated ? 'estimated-geometry' : 'outside-source-footprint';
            observationTransfer.counts[reason] = (observationTransfer.counts[reason] ?? 0) + 1;
          }
          if (transfer) {
            transfer.sampledTexels++; transfer.withheldTexels++;
            if (interior) { transfer.triangleInteriorTexels++; transfer.withheldTriangleInteriorTexels++; }
          }
          for (let channel = 0; channel < 3; channel++) {
            flood[offset + channel] = color[channel];
            shadow[offset + channel] = observation ? litByte(color[channel], illumination) : Math.round(color[channel] * illumination);
          }
          flood[offset + 3] = shadow[offset + 3] = 255;
          continue;
        }
        if (observation && observationTransfer) {
          const sample = observation.samplePoint(closestTrianglePoint(point, a, ab, ac).point);
          if (sampleSources) sampleSources[offset / 4] = sample.reason !== undefined ? 0 : requireFiniteNumber(sample.frameIndex) + 1;
          const interior = u >= 0 && v >= 0 && u + v <= 1;
          if (interior) {
            observationTransfer.interiorTexels++;
            const key = sample.reason ?? 'accepted';
            observationTransfer.counts[key] = (observationTransfer.counts[key] ?? 0) + 1;
            if (sample.reason === undefined) {
              if (sample.frameId) {
                observationTransfer.sources ??= {};
                observationTransfer.sources[sample.frameId] = (observationTransfer.sources[sample.frameId] ?? 0) + 1;
              }
              observationTransfer.maximumSourceDistanceMeters = Math.max(observationTransfer.maximumSourceDistanceMeters, requireFiniteNumber(sample.distanceMeters));
              observationTransfer.maximumPixelSeparationMeters = Math.max(observationTransfer.maximumPixelSeparationMeters, requireFiniteNumber(sample.separationMeters));
              observationTransfer.maximumPhotometricGain = Math.max(observationTransfer.maximumPhotometricGain, requireFiniteNumber(sample.gain));
            }
          }
          for (let channel = 0; channel < 3; channel++) {
            // The observation's authored photometric treatment is already prepared. Uniform flood
            // preserves its measured detail on every side of the source mesh.
            flood[offset + channel] = sample.color[channel];
            // A photograph is light: its shading multiplies decoded linear light, never the encoded byte.
            shadow[offset + channel] = litByte(sample.color[channel], illumination);
          }
          flood[offset + 3] = shadow[offset + 3] = 255;
          continue;
        }
        if (sourceSurface && sampleScience && transfer && scientific) {
          // Clamp the raster bleed to this retained triangle, never to an
          // unrelated surface beyond its edge. Runtime primitive coverage is
          // unchanged; source projection and color are entirely prepared here.
          const clamped = closestTrianglePoint(point, a, ab, ac).point;
          const sample = sampleScience(clamped);
          if (scalarSources && 'sourceCell' in sample && sample.sourceCell !== undefined) scalarSources.writeUInt32LE(sample.sourceCell + 1, offset);
          transfer.sampledTexels++;
          const interior = u >= 0 && v >= 0 && u + v <= 1;
          if (interior) transfer.triangleInteriorTexels++;
          const color = sample.color;
          if ('radius' in sample) {
            if (scientific.format !== 'pds3-scalar-map') illumination = .12 + .88 * Math.max(0, dot(sample.normal, sunDirection));
            transfer.maximumDistanceMeters = Math.max(transfer.maximumDistanceMeters, sample.distanceMeters);
          } else {
            transfer.withheldTexels++;
            if (interior) transfer.withheldTriangleInteriorTexels++;
          }
          for (let channel = 0; channel < 3; channel++) {
            flood[offset + channel] = color[channel];
            shadow[offset + channel] = Math.round(color[channel] * illumination);
          }
          flood[offset + 3] = shadow[offset + 3] = 255;
          continue;
        }
        if (!info || !map) throw new Error('Terrain texture lacks its decoded source map.');
        const lon = (Math.atan2(point[1], point[0]) / (2 * Math.PI) + 1) % 1;
        const lat = Math.atan2(point[2], Math.hypot(point[0], point[1]));
        const sx = lon * info.width - .5, sy = Math.max(0, Math.min(info.height - 1, (.5 - lat / Math.PI) * info.height - .5));
        const x0 = (Math.floor(sx) + info.width) % info.width, x1 = (x0 + 1) % info.width, y0 = Math.floor(sy), y1 = Math.min(info.height - 1, y0 + 1), tx = sx - Math.floor(sx), ty = sy - y0;
        const nearestX = Math.floor(lon * info.width) % info.width;
        const nearestY = Math.max(0, Math.min(info.height - 1, Math.floor((.5 - lat / Math.PI) * info.height)));
        const fillIllumination = neutralShape ? shapeFillIllumination(sunDot) : (light ? light.flood : 1);
        for (let channel = 0; channel < 3; channel++) {
          const top = map[(y0 * info.width + x0) * 4 + channel] * (1 - tx) + map[(y0 * info.width + x1) * 4 + channel] * tx;
          const bottom = map[(y1 * info.width + x0) * 4 + channel] * (1 - tx) + map[(y1 * info.width + x1) * 4 + channel] * tx;
          const color = nearest ? map[(nearestY * info.width + nearestX) * 4 + channel] : top * (1 - ty) + bottom * ty;
          flood[offset + channel] = Math.round(color * fillIllumination);
          shadow[offset + channel] = Math.round((light ? color : Math.round(color)) * illumination);
        }
        flood[offset + 3] = shadow[offset + 3] = 255;
      }
      fillUndrawnTexels(undrawn, rectWidth, rectHeight, (py, from, to) => {
        const row = (rect.y * scale + py) * width + rect.x * scale, target = (row + to) * 4, source = (row + from) * 4;
        flood.copyWithin(target, source, source + 4); shadow.copyWithin(target, source, source + 4);
        if (scalarSources) scalarSources.copyWithin(target, source, source + 4);
        if (sampleSources) sampleSources[row + to] = sampleSources[row + from];
      });
    }
    // Scientific colours retain exact palette values; the numeric source index is preparation-only.
    // Photographs keep full chroma detail through sharp's smart subsampling.
    const encoding = scalarSources || nearest || scientific?.format === 'image-plane-dem' ? { lossless: true, effort: 4 }
      : { alphaQuality: 100, effort: 4 };
    surface.surface = await emit(`${config.namespace}-${surface.id}-surface@2x.webp`, sharp(flood, { raw: { width, height, channels: 4 } }), encoding);
    // A photograph that keeps its acquisition lighting has no second, epoch-lit atlas: Shadows shows it as photographed.
    if (observation?.retainsIllumination) delete surface.shadowSurface;
    else surface.shadowSurface = await emit(`${config.namespace}-${surface.id}-shadow@2x.webp`, sharp(shadow, { raw: { width, height, channels: 4 } }), encoding);
    surface.polesUrl = surface.surface.url;
    surface.layout = { kind: 'triangle-atlas', width, height, faceCount: radial.faces.length };
    if (config.geometry.radialTerrain.thumbnail && !observation && !sourceSurface) {
      const snapshot = await renderRadialSnapshot({ ...parseRadialSnapshot(config.geometry.radialTerrain.thumbnail), faces: radial.faces,
        map: resolve(publicDirectory, requireString(surface.map.url.split('/').at(-1))) });
      surface.thumbnail = await emit(`${config.namespace}-${surface.id}-thumbnail.webp`, sharp(snapshot).resize(48, 48)
        .extend({ left: 24, right: 24, top: 0, bottom: 0, background: { r: 0, g: 0, b: 0, alpha: 0 } }));
    }
    if (scientific?.format === 'image-plane-dem') {
      const snapshot = await renderRadialSnapshot({ ...parseRadialSnapshot(config.geometry.radialTerrain.thumbnail),
        faces: radial.faces, sampleSurface: sampleScience ?? undefined, ambient: 1, diffuse: 0 });
      surface.thumbnail = await emit(`${config.namespace}-${surface.id}-thumbnail.webp`, sharp(snapshot).resize(48, 48)
        .extend({ left: 24, right: 24, top: 0, bottom: 0, background: { r: 0, g: 0, b: 0, alpha: 0 } }));
    }
    if (transfer) requireRecord(surface.surfaceSampling).transfer = transfer;
    if (scalarSources && scientific) {
      const bytes = Buffer.from(JSON.stringify({ schema: 'cssearth-atlas-scalar-index@1', width, height,
        encoding: 'gzip-u32le-base64', layout: scientific.format === 'vtk-cell-categories'
          ? (scientific.symbols ? 'row-major; 0 withheld, 1 mapped background, otherwise SBMT feature ID + 1; includes atlas bleed' : 'row-major; 0 withheld, otherwise original VTK face ID + 1; includes atlas bleed')
          : 'row-major; 0 withheld, otherwise original table row (1-based); includes atlas bleed',
        source: surface.source, data: gzipSync(scalarSources, { level: 9 }).toString('base64') }) + '\n');
      const file = `${surface.id}-source-index.json`;
      await writeFile(resolve(outputDirectory, file), bytes);
      requireRecord(surface.scalarMap).sampleSources = { file, bytes: bytes.length, sha256: sha256(bytes), width, height };
      const nearest = scientific.format === 'facet-scalars' || scientific.displaySampling === 'nearest';
      const snapshot = await renderRadialSnapshot({ faces: radial.faces, sampleSurface: sampleScience ?? undefined, size: 96,
        longitudeDegrees: 30, latitudeDegrees: 30, ambient: 1, diffuse: 0,
        ...(nearest ? { displaySampling: 'nearest' } : {}) });
      surface.thumbnail = await emit(`${config.namespace}-${surface.id}-thumbnail.webp`, sharp(snapshot).resize(48, 48,
        { kernel: nearest ? 'nearest' : 'lanczos3' })
        .extend({ left: 24, right: 24, top: 0, bottom: 0, background: { r: 0, g: 0, b: 0, alpha: 0 } }));
    }
    if (observationTransfer) requireRecord(surface.observation).transfer = observationTransfer;
    if (sampleSources && frames) {
      const codes = { 0: 'no-qualified-observation', ...Object.fromEntries(frames.map((frame, i) => [i + 1, frame.id])) };
      const bytes = Buffer.from(JSON.stringify({ schema: 'cssearth-atlas-observation-index@1', width, height, codes,
        encoding: 'gzip-u8-base64', layout: 'row-major; one source code per atlas texel; includes triangle bleed',
        data: gzipSync(sampleSources, { level: 9 }).toString('base64') }) + '\n');
      const file = `${surface.id}-source-index.json`;
      await writeFile(resolve(outputDirectory, file), bytes);
      requireRecord(surface.observation).sampleSources = { file, bytes: bytes.length, sha256: sha256(bytes),
        width, height, includesAtlasBleed: true, codes };
    }
  }
  if (lighting) await writeFile(resolve(outputDirectory, `source-lighting${suffix}.json`), JSON.stringify({ ...lighting.report, reusedLightingSamples, recipe: lightingRecipe }) + '\n');
  for (const entry of snapshotEntries.filter(entry =>
    matchesPreparationGenerator(entry.generator, 'tools/objects/terrestrial-layers/radial-snapshot.mts'))) {
    const surface = surfaces.find(surface => surface.id === requireRecord(requireRecord(entry).recipe).lensId);
    if (!surface) throw new TypeError('Radial snapshot requires a prepared source lens.');
    const science = radial.scientificSurfaces?.get(surface.id);
    const observation = radial.observationSurfaces?.get(surface.id);
    const lens = science && (config.raster.scientific ?? []).find(lens => lens.id === surface.id);
    if (science && (!science.samplePoint || !lens)) throw new Error('Terrain snapshot requires its source-point sampler and bound profile.');
    const scienceSnapshot = science?.samplePoint && lens ? createRadialScienceColorSampler({samplePoint:science.samplePoint}, lens, config) : undefined;
    const png = await renderRadialSnapshot({ ...parseRadialSnapshot(requireRecord(entry).recipe), faces: radial.faces,
      ...(scienceSnapshot && lens ? { sampleSurface: scienceSnapshot,
        ...((lens.format === 'facet-scalars' || lens.displaySampling === 'nearest') ? { displaySampling: 'nearest' } : {}) } : {}),
      ...(observation ? { sampleSurface: observation.samplePoint } : {}),
      map: resolve(publicDirectory, requireString(surface.map.url.split('/').at(-1))) });
    const reviewed = sourceDirectory ? await readFile(resolve(sourceDirectory, entry.path)).catch(() => null) : null;
    if (reviewed && Buffer.compare(reviewed, png) === 0) continue;
    if (replaceReviewedImages && sourceDirectory) {
      await replaceReviewedImage(sourceDirectory, entry.path, png);
      console.log(`Replaced reviewed image source/${entry.path} (${png.length} bytes); review it in the diff.`);
      continue;
    }
    // The reviewed snapshot is tracked. Keep the regenerated bytes where an owner can inspect them.
    const review = resolve(process.cwd(), 'output/source-context', config.namespace, entry.path.split('/').at(-1) ?? 'context.png');
    await mkdir(dirname(review), { recursive: true });
    await writeFile(review, png);
    throw new Error(`Regenerated ${entry.path} differs from the reviewed image. The regenerated image is at ${review}; review it and copy it to source/${entry.path}.`);
  }
  await writeFile(resolve(outputDirectory, `terrain${suffix}.json`), JSON.stringify({ schema: 'cssearth-prepared-radial-terrain@1',
    source: config.geometry.radialTerrain, faces: radial.faces, width: canonicalWidth, height: canonicalHeight,
    ...(radial.completion ? { completion: radial.completion } : {}),
    ...(radial.coverage ? { coverage: radial.coverage } : {}),
    ...(radial.simplification ? { simplification: radial.simplification } : {}) }) + '\n');
  return surfaces;
}

/** Texels beyond a triangle that are still sampled: bilinear filtering reads one across an edge, and the second keeps a minified
 * edge from averaging in a copied colour. */
const UNDRAWN_MARGIN_TEXELS = 2;

/** Give each unsampled texel of a rectangle the nearest sampled texel in its row, the left one on a tie. */
export function fillUndrawnTexels(undrawn: Uint8Array, width: number, height: number, copy: (row: number, from: number, to: number) => void) {
  for (let y = 0; y < height; y++) {
    const row = y * width;
    let left = -1;
    for (let x = 0; x < width; x++) {
      if (!undrawn[row + x]) { left = x; continue; }
      let right = x + 1;
      while (right < width && undrawn[row + right]) right++;
      if (left < 0 && right >= width) throw new Error('A raster atlas row has no sampled texel.');
      for (let fill = x; fill < right; fill++) copy(y, left >= 0 && (right >= width || fill - left <= right - fill) ? left : right, fill);
      x = right - 1;
    }
  }
}
