import { sha256 } from '../../src/platform/sha256.mts';
import { isArray } from '../../src/platform/is-array.mts';
import assert from "node:assert/strict";
import { randomUUID } from 'node:crypto';
import { readFile, rename, rm, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { hasErrorCode } from "@cssearth/core";
import { SCENE_OBJECTS } from "../../site/objects.mts";
import { requireObjectControls } from "../../site/scene/scene-contract.mts";

const projectRoot = resolve(import.meta.dirname, "../..");

// JSON drops own undefined properties and changes -0. Emit only literal data
// and preserve the recipes' existing frozen arrays and records as well.
export function serializeObjectControls(controls: unknown) {
  const ancestors = new Set<object>();
  function literal(value: unknown, depth = 0): string {
    if (value === undefined) return "undefined";
    if (value === null || typeof value === "boolean" || typeof value === "string") return JSON.stringify(value);
    if (typeof value === "number") {
      assert.ok(Number.isFinite(value), "Prepared controls require finite numbers");
      return Object.is(value, -0) ? "-0" : String(value);
    }
    assert.ok(value !== null && typeof value === "object", "Prepared controls cannot contain executable values");
    const array = isArray(value);
    assert.equal(Object.getPrototypeOf(value), array ? Array.prototype : Object.prototype,
      "Prepared controls require plain data records and arrays");
    assert.ok(!ancestors.has(value), "Prepared controls cannot contain cycles");
    ancestors.add(value);
    const names = Reflect.ownKeys(value).filter(name => !(array && name === "length"));
    for (const name of names) {
      assert.equal(typeof name, "string", "Prepared controls cannot contain symbol keys");
      assert.notEqual(name, "__proto__", "Prepared control keys cannot change object prototypes");
      const descriptor = Object.getOwnPropertyDescriptor(value, name);
      assert.ok(descriptor?.enumerable && Object.hasOwn(descriptor, "value"),
        "Prepared controls cannot contain getters or hidden values");
    }
    if (array) assert.deepEqual(names, Array.from({ length: value.length }, (_, index) => String(index)),
      "Prepared control arrays must contain explicit ordered values");
    const indentation = "  ".repeat(depth + 1), closing = "  ".repeat(depth);
    const entries = names.map(name => `${indentation}${array ? "" : `${JSON.stringify(name)}: `}${literal(Object.getOwnPropertyDescriptor(value, name)?.value, depth + 1)}`);
    const data = `${array ? "[" : "{"}${entries.length ? `\n${entries.join(",\n")}\n${closing}` : ""}${array ? "]" : "}"}`;
    ancestors.delete(value);
    return Object.isFrozen(value) ? `Object.freeze(${data})` : data;
  }
  const data = literal(controls);
  return `// Generated by tools/prepare-object-controls.mts. Edit control-content.source.mjs.\n` +
    `export const objectControls = ${Object.isFrozen(controls) ? data : `Object.freeze(${data})`};\n`;
}

export async function prepareObjectControls({ root = projectRoot, objectIds = SCENE_OBJECTS.map(({ id }) => id) } = {}) {
  assert.ok(isArray(objectIds) && objectIds.length > 0 && new Set(objectIds).size === objectIds.length &&
    objectIds.every(id => SCENE_OBJECTS.some(object => object.id === id)), "Select unique objects from SCENE_OBJECTS");
  const results = [];
  for (const id of objectIds) {
    const recipePath = resolve(root, `src/objects/${id}/site/control-content.source.mjs`);
    const outputPath = resolve(root, `src/objects/${id}/site/control-content.mjs`);
    const recipe = await readFile(recipePath, "utf8");
    const recipeUrl = pathToFileURL(recipePath);
    recipeUrl.searchParams.set("source", sha256(recipe));
    const { objectControls } = await import(recipeUrl.href);
    requireObjectControls(objectControls);
    const source = serializeObjectControls(objectControls);
    const generated: unknown = await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`);
    assert.ok(generated && typeof generated === 'object' && 'objectControls' in generated);
    assert.deepEqual(generated.objectControls, objectControls,
      `${id}: prepared literals must preserve every recipe value, including undefined`);
    assert.equal(await readFile(recipePath, "utf8"), recipe, `${id}: control recipe changed during preparation`);
    let previous = null;
    try { previous = await readFile(outputPath, "utf8"); }
    catch (error) { if (!hasErrorCode(error, "ENOENT")) throw error; }
    if (source !== previous) {
      const temporary = `${outputPath}.${randomUUID()}.tmp`;
      try {
        await writeFile(temporary, source, { flag: "wx" });
        await rename(temporary, outputPath);
      } finally { await rm(temporary, { force: true }); }
    }
    results.push({ id, source: recipePath, output: outputPath, changed: source !== previous,
      bytes: Buffer.byteLength(source), sha256: sha256(source), exactValues: true });
  }
  return results;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const objectIds = [];
  for (const argument of process.argv.slice(2)) {
    if (argument === "--all" || argument === "--") continue;
    if (!argument.startsWith("--object=")) throw new Error(`Unknown control preparation argument: ${argument}`);
    objectIds.push(argument.slice("--object=".length));
  }
  console.log(JSON.stringify(await prepareObjectControls(objectIds.length ? { objectIds } : {}), null, 2));
}
