import { readFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { parseAst } from 'vite';
import type { ClassDeclaration, ImportDeclaration } from 'estree';
import { requireRecord } from '@cssearth/core';
import { sourceStart, sourceEnd, nodeName } from '../ci/runtime-ast.mts';

const require = createRequire(import.meta.url);
const version = requireRecord(JSON.parse(await readFile(require.resolve('@cesium/engine/package.json'), 'utf8'))).version;
if (version !== '26.3.0') throw new Error('Review the minimap excerpts before updating Cesium.');

// Copy only the upstream methods computeViewRectangle uses. The complete
// classes also import image loading and renderer feature detection.
const excerpts = [
  { name: 'BoundingSphere', imports: ['Cartesian3', 'Check', 'Intersect'],
    methods: ['constructor', 'static:intersectPlane', 'intersectPlane'] },
  { name: 'Rectangle', imports: ['Check', 'defined', 'CesiumMath'],
    methods: ['constructor', 'width', 'height', 'static:computeWidth', 'static:computeHeight', 'static:fromCartographicArray'],
    constant: 'Rectangle.MAX_VALUE' },
];

export async function cesiumMinimapExcerpts() {
  const output = new Map<string, string>();
  for (const { name, imports, methods, constant } of excerpts) {
    const source = await readFile(require.resolve(`@cesium/engine/Source/Core/${name}.js`), 'utf8');
    const ast = parseAst(source);
    const declaration = ast.body.find((node): node is ClassDeclaration => node.type === 'ClassDeclaration' && nodeName(node.id) === name);
    if (!declaration) throw new Error(`Missing Cesium class ${name}`);
    const selected = methods.map(key => {
      const method = declaration.body.body.find(node => `${'static' in node && node.static ? 'static:' : ''}${'key' in node ? nodeName(node.key) : undefined}` === key);
      if (!method) throw new Error(`Missing Cesium method ${name}.${key}`);
      return source.slice(sourceStart(method), sourceEnd(method));
    });
    const dependencies = imports.map(name => {
      const entry = ast.body.find((node): node is ImportDeclaration => node.type === 'ImportDeclaration' && node.specifiers.some(specifier => specifier.local.name === name));
      if (!entry || typeof entry.source.value !== 'string') throw new Error(`Missing Cesium import ${name}`);
      return `import ${name} from ${JSON.stringify(`@cesium/engine/Source/Core/${entry.source.value.slice(2)}`)};`;
    });
    let tail = '';
    if (constant) {
      const statement = ast.body.find(node => node.type === 'ExpressionStatement' &&
        node.expression.type === 'AssignmentExpression' && source.slice(sourceStart(node.expression.left), sourceEnd(node.expression.left)) === constant);
      if (!statement) throw new Error(`Missing Cesium constant ${constant}`);
      tail = `${source.slice(sourceStart(statement), sourceEnd(statement))}\n`;
    }
    output.set(`cesium-${name}.mjs`, `/**
 * Copyright 2011-2024 CesiumJS Contributors. Apache-2.0; see cesium-LICENSE.md.
 * Generated by tools/prepare/prepare-cesium-minimap.mts from @cesium/engine ${version}.
 * https://github.com/CesiumGS/cesium/blob/1.145/packages/engine/Source/Core/${name}.js
 * Selected methods are copied verbatim; unrelated methods are omitted.
 */
${dependencies.join('\n')}

export default class ${name} {
  ${selected.join('\n\n  ')}
}

${tail}`.trimEnd() + '\n');
  }
  return output;
}
