#!/usr/bin/env node

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";

import { SHELL_TITLE_SOURCES } from "../../site/source/titles/manifest.mts";

const SAFE_FILE = /^title-[a-z0-9-]+\.svg$/u;
const SAFE_KEY = /^[a-z][A-Za-z0-9]*$/u;
const SVG_ROOT = /<svg\b[^>]*\bviewBox="0 0 ([0-9.]+) ([0-9.]+)"[^>]*\bwidth="([0-9.]+)"[^>]*\bheight="([0-9.]+)"[^>]*>/u;
const SVG_METADATA = /<metadata>([^<]+)<\/metadata>/u;

export async function prepareShellTitles({
  sourceRoot = resolve(import.meta.dirname, "../../site/source/titles"),
  publicRoot = resolve(import.meta.dirname, "../../public/shell"),
  moduleOutput = resolve(import.meta.dirname, "../../site/prepared-shell-titles.mjs"),
} = {}) {
  validateManifest();
  await mkdir(publicRoot, { recursive: true });
  const prepared: Record<string, Readonly<Record<string, string | number>>> = {};
  for (const descriptor of SHELL_TITLE_SOURCES.titles) {
    const sourcePath = resolve(sourceRoot, descriptor.file);
    const bytes = await readFile(sourcePath);
    const svg = bytes.toString("utf8");
    const root = svg.match(SVG_ROOT);
    const metadataMatch = svg.match(SVG_METADATA);
    if (!root || !metadataMatch) {
      throw new Error(`Shell title source is malformed: ${descriptor.file}.`);
    }
    const metadata: unknown = JSON.parse(metadataMatch[1]);
    if (metadata === null || typeof metadata !== 'object' ||
        !('source' in metadata) || !('text' in metadata) || !('weight' in metadata) ||
        !('fontSize' in metadata) || !('letterSpacing' in metadata) || metadata.source !== SHELL_TITLE_SOURCES.font.source ||
        metadata.text !== descriptor.vectorText ||
        metadata.weight !== SHELL_TITLE_SOURCES.recipe.weight ||
        metadata.fontSize !== SHELL_TITLE_SOURCES.recipe.fontSize ||
        metadata.letterSpacing !== SHELL_TITLE_SOURCES.recipe.letterSpacing) {
      throw new Error(`Shell title source identity drifted: ${descriptor.file}.`);
    }
    const [, viewBoxWidth, viewBoxHeight, width, height] = root;
    if (viewBoxWidth !== width || viewBoxHeight !== height ||
        Number(height) !== SHELL_TITLE_SOURCES.recipe.viewBoxHeight) {
      throw new Error(`Shell title dimensions drifted: ${descriptor.file}.`);
    }
    await writeFile(resolve(publicRoot, descriptor.file), bytes);
    prepared[descriptor.key] = Object.freeze({
      label: descriptor.label,
      src: `/shell/${descriptor.file}`,
      width: Number(width),
      height: Number(height),
      source: SHELL_TITLE_SOURCES.font.source,
      sourceUrl: SHELL_TITLE_SOURCES.font.sourceUrl,
      fontSize: SHELL_TITLE_SOURCES.recipe.fontSize,
      generator: "tools/prepare/prepare-shell-titles.mts",
    });
  }
  const moduleSource = [
    "// Generated from site/source/titles. Do not edit this file directly.",
    `export const PREPARED_SHELL_TITLES = deepFreeze(${JSON.stringify(prepared)});`,
    "",
    "function deepFreeze(value) {",
    "  for (const child of Object.values(value)) Object.freeze(child);",
    "  return Object.freeze(value);",
    "}",
    "",
  ].join("\n");
  await mkdir(dirname(moduleOutput), { recursive: true });
  // An unchanged module keeps its time, so the preparation bundle that imports it is not rebuilt on every run.
  if (await readFile(moduleOutput, "utf8").catch(() => null) !== moduleSource) await writeFile(moduleOutput, moduleSource);
  return Object.freeze({ prepared: Object.freeze(prepared), moduleSource });
}

function validateManifest() {
  if (SHELL_TITLE_SOURCES.schema !== "cssearth-shell-title-sources@1" ||
      SHELL_TITLE_SOURCES.recipe.fontSize !== 17 ||
      SHELL_TITLE_SOURCES.recipe.viewBoxHeight !== 23) {
    throw new TypeError("Shell title source manifest is incompatible.");
  }
  const keys = new Set();
  const files = new Set();
  for (const descriptor of SHELL_TITLE_SOURCES.titles) {
    if (!SAFE_KEY.test(descriptor.key) || !SAFE_FILE.test(descriptor.file) ||
        !descriptor.label || !descriptor.vectorText || keys.has(descriptor.key) ||
        files.has(descriptor.file)) {
      throw new TypeError("Shell title source descriptor is invalid.");
    }
    keys.add(descriptor.key);
    files.add(descriptor.file);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  await prepareShellTitles();
}
