import type {PreparedPresentationContract} from '../../src/platform/prepared-presentation-contract.mts';
import type {MaterialSourcePlan} from './prepare-materials.mts';
import type {PreparedVariant} from '../../src/renderers/css/rendering/prepared-presentation.ts';
import type {PreparedMaterialSelection} from '../../src/renderers/css/rendering/prepared-material.ts';
type SourceMaterialSelection=Omit<PreparedMaterialSelection,'mode'>&{mode:PreparedMaterialSelection['mode']|'default-pose'};
export type AuthoredPresentation=Omit<PreparedPresentationContract,'materials'|'variants'>&MaterialSourcePlan&{variants:readonly (Omit<PreparedVariant,'materials'>&{materials:readonly SourceMaterialSelection[]})[]};
import { updateObjectJsonForPresentation } from './prepare-object-json.mts';
import { prepareMaterialTracks } from "./prepare-materials.mts";
import { writeFile } from "node:fs/promises";
import { requirePreparedPresentation } from "../../src/platform/prepared-presentation-contract.mts";
import { requirePreparedResourceCatalog } from "../contract/object-runtime-contract.mts";

function preparedPresentation(plan:AuthoredPresentation, controls:unknown) {
  const prepared = { ...plan, materials: prepareMaterialTracks(plan), variants: plan.variants.map(variant => ({ ...variant,
    materials: variant.materials.map(material => ({ ...material, mode: material.mode === "default-pose" ? "frames" : material.mode })) })) };
  const validated=requirePreparedPresentation(prepared, { controls });
  requirePreparedResourceCatalog(validated.assets);
  return validated;
}
export function serializePreparedPresentation(plan:AuthoredPresentation, controls:unknown) {
  const prepared = preparedPresentation(plan, controls);
  return `// Generated by tools/prepare-presentation.mts. Do not edit.\nexport const PREPARED_PRESENTATION = Object.freeze(${JSON.stringify(prepared)});\n`;
}
export async function writePreparedPresentation(path:string|URL, plan:AuthoredPresentation, controls:unknown) {
  const prepared = preparedPresentation(plan, controls);
  await writeFile(path, serializePreparedPresentation(plan, controls));
  await updateObjectJsonForPresentation(path, prepared, controls);
}
