#!/usr/bin/env node

import { sha256 } from '../../src/platform/sha256.mts';
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

import * as fontkit from "fontkit";

import { OBJECT_TITLE_RECIPE } from
  "../../src/platform/object-title-recipe.mts";

interface WordmarkSegment {label: string; text?: string; weight: number; tail?: {text: string; weight: number}; renderedHeight: number;}

const projectRoot = resolve(import.meta.dirname, "../..");
const outputPath = resolve(
  projectRoot,
  "site/source/branding/wordmark-rail-segments.mjs",
);

export const WORDMARK_RAIL_RECIPE = Object.freeze({
  source: OBJECT_TITLE_RECIPE.source,
  sourceUrl: OBJECT_TITLE_RECIPE.sourceUrl,
  checkedFontPath: OBJECT_TITLE_RECIPE.checkedFontPath,
  fontSize: 22,
  opticalSize: 22,
  letterSpacing: 0.1,
  baseline: 23,
  segments: Object.freeze([
    Object.freeze({
      label: "css",
      text: "css",
      weight: 400,
      tail: Object.freeze({ text: ".", weight: 300 }),
      renderedHeight: 14.25,
    }),
    Object.freeze({ label: "earth", weight: 300, renderedHeight: 16.25 }),
  ]),
});

export async function prepareWordmarkRail({
  fontPath = resolve(projectRoot, WORDMARK_RAIL_RECIPE.checkedFontPath),
  writeSource = (moduleSource: string) => writeFile(outputPath, moduleSource),
}: {fontPath?: string; writeSource?: (moduleSource: string) => Promise<void>} = {}) {
  const fontBytes = await readFile(fontPath);

  const baseFont = fontkit.openSync(fontPath);
  if (!("getVariation" in baseFont)) throw new TypeError("The pinned wordmark font must be one font face.");
  const segments = WORDMARK_RAIL_RECIPE.segments.map((segment) =>
    createWordmarkSegment(segment, baseFont));
  const moduleSource = serializeWordmarkSegments(segments);
  await writeSource(moduleSource);
  return Object.freeze(segments);
}

export function createWordmarkSegment({
  label,
  text = label,
  weight,
  tail,
  renderedHeight,
}: WordmarkSegment, baseFont: fontkit.Font) {
  const parts = [{ text, weight }, ...(tail ? [tail] : [])];
  const scale = WORDMARK_RAIL_RECIPE.fontSize / baseFont.unitsPerEm;
  const paths = [];
  let penX = 0;
  let penY = 0;
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;

  for (const [partIndex, part] of parts.entries()) {
    const font = baseFont.getVariation({
      wght: part.weight,
      opsz: WORDMARK_RAIL_RECIPE.opticalSize,
    });
    const run = font.layout(part.text);
    for (const [index, glyph] of run.glyphs.entries()) {
      const position = run.positions[index];
      const path = glyph.path
        .scale(scale, -scale)
        .translate(
          penX + position.xOffset * scale,
          WORDMARK_RAIL_RECIPE.baseline - penY - position.yOffset * scale,
        );
      const box = path.bbox;
      minX = Math.min(minX, box.minX);
      minY = Math.min(minY, box.minY);
      maxX = Math.max(maxX, box.maxX);
      maxY = Math.max(maxY, box.maxY);
      paths.push(path);
      penX += position.xAdvance * scale;
      penY += position.yAdvance * scale;
      const isLastGlyph = partIndex === parts.length - 1 &&
        index === run.glyphs.length - 1;
      if (!isLastGlyph) {
        penX += WORDMARK_RAIL_RECIPE.letterSpacing;
      }
    }
  }

  const width = stableNumber(maxX - minX);
  const height = stableNumber(maxY - minY);
  const renderedWidth = stableNumber(
    width * renderedHeight / height,
  );
  return Object.freeze({
    label,
    text: parts.map((part) => part.text).join(""),
    weight,
    tailWeight: tail?.weight,
    fontSize: WORDMARK_RAIL_RECIPE.fontSize,
    opticalSize: WORDMARK_RAIL_RECIPE.opticalSize,
    width,
    height,
    renderedWidth,
    renderedHeight,
    viewBox: `0 ${stableNumber(minY)} ${width} ${height}`,
    path: paths.map((path) => path.translate(-minX, 0).toSVG()).join(""),
    source: WORDMARK_RAIL_RECIPE.source,
    sourceGenerator: "tools/prepare/prepare-wordmark-rail.mts",
  });
}

export function serializeWordmarkSegments(segments: readonly ReturnType<typeof createWordmarkSegment>[]) {
  const entries = segments.map((segment) =>
    `  Object.freeze(${JSON.stringify(segment)}),`).join("\n");
  return [
    "// Generated from the pinned Inter font. Do not edit this file directly.",
    "export const WORDMARK_RAIL_SEGMENTS = Object.freeze([",
    entries,
    "]);",
    "",
  ].join("\n");
}

function stableNumber(value: number) {
  return Number(value.toFixed(4));
}

if (process.argv[1] &&
    import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  await prepareWordmarkRail();
}
