import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, relative, resolve, sep } from 'node:path';
import { pathToFileURL } from 'node:url';
import { defineObjects } from '../../site/object-schema.mts';
import { catalogEntry } from '../../site/object-catalog.mts';
import type { CatalogEntry } from '../../site/object-catalog.mts';
import { hasErrorCode, isRecord } from '../sources/source-values.mts';
import { prepareSceneDistance, readPreparedFocusObjects } from './prepare-navigation-destinations.mts';

import { prepareObjectDiscovery } from './prepare-object-discovery.mts';
import { BODIES } from '@cssearth/astronomy';
import { assetOrigin } from '../../site/asset-origin.mts';
import { readInventory } from '../../src/platform/runtime-asset-closure.mts';

const root = resolve(import.meta.dirname, '../..');
const byOrder = (a: CatalogEntry, b: CatalogEntry) => (a.order ?? Number.MAX_SAFE_INTEGER) - (b.order ?? Number.MAX_SAFE_INTEGER) || a.id.localeCompare(b.id, 'en');

/** A folder alone is not a published destination. Its descriptor must opt in. */
export async function readCatalog(objectsDirectory = resolve(root, 'src/objects')) {
  const entries: CatalogEntry[] = [];
  for (const directory of await readdir(objectsDirectory, { withFileTypes: true })) {
    if (!directory.isDirectory()) continue;
    let descriptor: unknown;
    try { descriptor = JSON.parse(await readFile(resolve(objectsDirectory, directory.name, 'object.json'), 'utf8')); }
    catch (error) { if (hasErrorCode(error, 'ENOENT')) continue; throw error; }
    if (!isRecord(descriptor) || !isRecord(descriptor.properties) || descriptor.properties.catalog === undefined) continue;
    if (descriptor.id !== directory.name) throw new TypeError(`Catalogue identity differs: ${directory.name}.`);
    entries.push(catalogEntry(descriptor, async () => { throw new Error('Catalogue preparation cannot mount a scene.'); }, prepareSceneDistance(descriptor)));
  }
  entries.sort(byOrder);
  defineObjects(entries.map(({ order, context, ...object }) => object));
  return entries;
}

/** Registered descriptors without a catalog entry are application context: the world loads their prepared resources directly. */
export async function readContextObjects(objectsDirectory = resolve(root, 'src/objects')) {
  const contexts: { id: string; type: string }[] = [];
  for (const directory of await readdir(objectsDirectory, { withFileTypes: true })) {
    if (!directory.isDirectory()) continue;
    let descriptor: unknown;
    try { descriptor = JSON.parse(await readFile(resolve(objectsDirectory, directory.name, 'object.json'), 'utf8')); }
    catch (error) { if (hasErrorCode(error, 'ENOENT')) continue; throw error; }
    if (!isRecord(descriptor) || !isRecord(descriptor.properties) || descriptor.properties.catalog !== undefined) continue;
    if (descriptor.id !== directory.name || typeof descriptor.type !== 'string') throw new TypeError(`Context object identity differs: ${directory.name}.`);
    contexts.push({ id: directory.name, type: descriptor.type });
  }
  return contexts.sort((a, b) => a.id.localeCompare(b.id, 'en'));
}

/** Every object shares one folder, so the application globs only the context objects it loads, each by name. */
export function contextObjectModule(contexts: readonly { id: string; type: string }[], remoteAssets: Readonly<Record<string, string>> = {}) {
  const list = (patterns: readonly string[]) => `[${patterns.map(pattern => `'${pattern}'`).join(', ')}]`;
  const folder = (id: string) => `../src/objects/${id}`;
  // A point field's binary star bank is a preparation input, never an application asset.
  const assets = [...contexts.map(({ id }) => `${folder(id)}/prepared/**/*.{json,png,webp,bin}`),
    ...contexts.filter(({ type }) => type === 'point-field').map(({ id }) => `!${folder(id)}/prepared/*.bin`)];
  const assetExpression = Object.keys(remoteAssets).length
    ? JSON.stringify(remoteAssets)
    : `import.meta.glob(${list(assets)}, { query: '?url&no-inline', import: 'default', eager: true })`;
  return '// Generated by tools/prepare-catalog.mts. Context objects are registered descriptors without a catalog entry.\n' +
    `export const CONTEXT_OBJECT_DESCRIPTORS: Record<string, unknown> = import.meta.glob(${list(contexts.map(({ id }) => `${folder(id)}/object.json`))}, { eager: true, import: 'default' });\n` +
    // These URLs are serialized into every object's prepared-focus shell. Vite's
    // default URL handling inlines small JSON assets as data URLs, turning the
    // otherwise tiny resolver map into a megabyte of eager HTML and JavaScript.
    // Keep every prepared resource as an independently cached, demand-loaded
    // asset; the existing loaders still decide which bank is fetched.
    `export const CONTEXT_OBJECT_ASSET_URLS: Record<string, unknown> = ${assetExpression};\n` +
    `export const CONTEXT_OBJECT_PREPARED_JSON: Record<string, unknown> = import.meta.glob(${list(contexts.map(({ id }) => `${folder(id)}/prepared/*.json`))}, { eager: true, import: 'default' });\n`;
}

/** An asset-origin build resolves context resources exclusively from committed inventories. It neither needs nor
 * discovers the prepared payload on disk, so a deploy cannot silently regenerate a second package identity. */
export async function contextObjectAssetUrls(contexts: readonly { id: string }[], projectRoot: string, origin: string | null) {
  if (!origin) return {};
  const siteRoot = resolve(projectRoot, 'site'), entries: (readonly [string, string])[] = [];
  for (const { id } of contexts) {
    const directory = resolve(projectRoot, 'src/objects', id);
    const inventory = await readInventory(id, directory);
    for (const asset of inventory?.assets.filter(asset => asset.location === 'prepared') ?? []) entries.push([
      relative(siteRoot, resolve(directory, 'prepared', asset.filename)).split(sep).join('/'),
      `${origin}/runtime-assets/${asset.sha256}/${asset.filename}`,
    ]);
  }
  return Object.fromEntries(entries.sort(([left], [right]) => left.localeCompare(right, 'en')));
}

/** The frame of every volume a body shows through one of its lenses, so an opening camera can fit it. */
async function readLensVolumes(entries: readonly CatalogEntry[], projectRoot: string) {
  const volumes: Record<string, unknown> = {};
  for (const { id } of entries) {
    let content: unknown;
    try { content = JSON.parse(await readFile(resolve(projectRoot, 'src/objects', id, 'source/content/object.json'), 'utf8')); }
    catch (error) { if (hasErrorCode(error, 'ENOENT')) continue; throw error; }
    const controls = isRecord(content) && isRecord(content.lenses) && Array.isArray(content.lenses.controls) ? content.lenses.controls : [];
    for (const control of controls) {
      const volumeId = isRecord(control) && isRecord(control.volume) ? control.volume.objectId : undefined;
      if (typeof volumeId !== 'string' || volumes[volumeId]) continue;
      const descriptor: unknown = JSON.parse(await readFile(resolve(projectRoot, 'src/objects', volumeId, 'object.json'), 'utf8'));
      if (!isRecord(descriptor) || !isRecord(descriptor.properties) || !isRecord(descriptor.properties.frame)) {
        throw new TypeError(`src/objects/${volumeId}/object.json: the volume ${id} shows has no properties.frame.`);
      }
      volumes[volumeId] = descriptor.properties.frame;
    }
  }
  return volumes;
}

async function writeGenerated(output: string, text: string) {
  await mkdir(dirname(output), { recursive: true });
  try { if (await readFile(output, 'utf8') === text) return; }
  catch (error) { if (!hasErrorCode(error, 'ENOENT')) throw error; }
  await writeFile(output, text);
}

export async function prepareCatalog({ projectRoot = root } = {}) {
  const entries = await readCatalog(resolve(projectRoot, 'src/objects'));
  const host = entries.find(entry => entry.classification === 'star' && entry.distance.meters === 0);
  if (!host) throw new TypeError('Prepared focus destinations need a shared world host.');
  const focuses = await readPreparedFocusObjects(resolve(projectRoot, 'src/objects'), host.id);
  defineObjects<{ id: string; route: string }>([...entries, ...focuses]);
  const lines = entries.map(({ id }, index) => `import body${index} from '../src/objects/${id}/object.json' with { type: 'json' };`);
  const text = '// Generated by tools/prepare-catalog.mts. Edit each body object.json.\n' + lines.join('\n') +
    `\nexport const OBJECT_DESCRIPTORS: readonly unknown[] = [${entries.map((_, index) => `body${index}`).join(', ')}];\n`;
  await writeGenerated(resolve(projectRoot, 'site/prepared-object-catalog.mts'), text);
  const discoveries = await Promise.all(entries.map(async ({ id }) => {
    const folder = resolve(projectRoot, 'src/objects', id);
    return [id, await prepareObjectDiscovery(JSON.parse(await readFile(resolve(folder, 'object.json'), 'utf8')), folder)] as const;
  }));
  // A star without imagery of its own stays on the map when a body with imagery orbits it (a placed star's planet).
  const withImagery = new Set(discoveries.filter(([, discovery]) => discovery.imagery).map(([id]) => id));
  const parents = BODIES as Readonly<Record<string, { readonly parent: string | null }>>;
  for (const [id, discovery] of discoveries) {
    const entry = entries.find(candidate => candidate.id === id)!;
    if (entry.classification !== 'star' || discovery.imagery) continue;
    if ([...withImagery].some(child => parents[child]?.parent === id)) discovery.hostsImagery = true;
  }
  await writeGenerated(resolve(projectRoot, 'site/prepared-object-discovery.json'), JSON.stringify(Object.fromEntries(discoveries)) + '\n');
  await writeGenerated(resolve(projectRoot, 'site/prepared-object-distances.json'), JSON.stringify(Object.fromEntries(entries.map(entry => [entry.id, entry.distance]))) + '\n');
  await writeGenerated(resolve(projectRoot, 'site/prepared-focus-objects.json'), JSON.stringify(focuses) + '\n');
  await writeGenerated(resolve(projectRoot, 'site/prepared-lens-volumes.json'), JSON.stringify(await readLensVolumes(entries, projectRoot)) + '\n');
  const contexts = await readContextObjects(resolve(projectRoot, 'src/objects'));
  await writeGenerated(resolve(projectRoot, 'site/prepared-context-objects.mts'), contextObjectModule(contexts,
    await contextObjectAssetUrls(contexts, projectRoot, assetOrigin())));
  return entries;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) await prepareCatalog();
