export type { JsonValue, JsonRecord, ObjectDescriptor, PreparedAssetReference, PreparedObject } from './descriptor.js';
export { parseObjectDescriptor } from './parse.js';
export { objectPageCss } from './page-style.js';
export { parseImageLayerBankDescriptor } from './image-layer-bank.js';
export type { ImageLayerBankDescriptor } from './image-layer-bank.js';
export { parseCataloguePointBankDescriptor } from './catalogue-point-bank.js';
export type { CataloguePointBankDescriptor } from './catalogue-point-bank.js';
export { parseDensityVolumeFrame, parseDensityVolumeObjectDescriptor } from './density-volume.js';
export { CATALOGUE_CELL_POINTS, CATALOGUE_POINTS_SCHEMA, MAX_CATALOGUE_POINTS, catalogueCells, cataloguePointSpread, parseCatalogueCells, parseCataloguePointSpread } from './catalogue-points.js';
export type { CatalogueCells, CataloguePointSpread } from './catalogue-points.js';
export type { DensityVolumeFrame, DensityVolumeObjectDescriptor, DensityVolumePreparationReference, VolumeQuaternion, VolumeVector } from './density-volume.js';
export { parseAuthoredObjectDescriptor, parseAuthoredRecipe } from './authored.js';
export type { AuthoredObjectDescriptor, AuthoredRecipe, CutawayRecipe, DestinationsRecipe, FeaturesRecipe, FrameBankRecipe, LayerRecipe, DatasetRecipe, MaterialRecipe, MotionRecipe, ShapeKind, ShapeRecipe, SourceReference, SurfaceRecipe, WorldFrameRecipe } from './authored.js';
export * from './baking/index.js';
export * from './geometry/index.js';
export { prepareObject, readPreparedObject } from './preparation.js';
export type { ObjectPreparation } from './preparation.js';
export * from './registry/index.js';
export { PREPARED_BINARY_MAGIC, shufflePreparedBinary, unshufflePreparedBinary } from './prepared-binary.js';
export type { PreparedBinaryRegion } from './prepared-binary.js';
export * from './volume/cloud-density-filter.js';
export * from './volume/compiler-bake.js';
export * from './volume/coordinates.js';
export * from './volume/joint-volume.js';
export * from './volume/layer-optimization-report.js';
export * from './volume/render-element-budget.js';
export * from './volume/shape-scene.js';
export * from './volume/volume-layer-plan.js';
export * from './volume/authored-shapes.js';
export * from './volume/compiler-controls.js';
export * from './volume/compiler-star-input.js';
export * from './volume/joint-parameters.js';
export * from './volume/observation-photo.js';
export * from './volume/prepared-catalogue-stars.js';
export * from './volume/sampled-emission-fit.js';
export * from './volume/sampled-recipe.js';
export * from './volume/volume-recipe.js';
export * from './volume/volume-slices.js';
export { PREPARED_CSS_OBJECT_FORMAT } from './prepared-data/object-format.js';
export { expandWorldContextSummary, expandWorldSystem } from './prepared-data/world-context-summary.js';
export type { Cancellation } from './volume/cancellation.js';
export type { ObservationMapping } from './volume/observation-mapping.js';
export type { SimulationDepthPrior } from './volume/simulation-prior.js';
export { parsePreparedWorldContext, parsePreparedWorldContextSummary, parsePreparedWorldContextPlan, worldContextGeometry, orbitVertices, parsePreparedWorldSystem, extendWorldContext, parseCompleteWorldContext } from './prepared-data/world-context.js';
export type { PreparedContextPoint, PreparedContextPointSource, PreparedContextBody, PreparedContextOrbit, PreparedContextOrbitGeometry, PreparedContextCameraPresentation, PreparedVolumeOpacityProfile, PreparedWorldContext, PreparedWorldSystem, PreparedWorldContextGeometry } from './prepared-data/world-context.js';
export { worldCameraOf, parsePreparedWorldCamera } from './prepared-data/world-camera.js';
export { parsePreparedWorldCameraFrame } from './prepared-data/world-frame.js';
export type { PreparedWorldCameraFrame } from './prepared-data/world-frame.js';
export { decodeWorldOrbitBank, decodeWorldOrbits } from './prepared-data/world-orbit-bank.js';
export { parsePreparedSystemView } from './prepared-data/world-system-view.js';
export type { PreparedSystemViewCandidate, PreparedSystemView } from './prepared-data/world-system-view.js';
export { worldOrbitBankRegions } from './prepared-data/world-orbit-bank-regions.js';
export { worldOrbitBanks } from './prepared-data/world-orbit-encoder.js';
export type { PreparedWorldContextData, PreparedOrbitDataLod } from './prepared-data/world-context-data.js';
export type { LevelOfDetailPlan, OrbitLineFade } from './prepared-data/world-presentation.js';
export type { PreparedOrbitCenter } from './prepared-data/prepared-orbit-centers.js';

export { PREPARED_WORLD_CONTEXT_SCHEMA, PREPARED_WORLD_CONTEXT_SUMMARY_SCHEMA, PREPARED_WORLD_SYSTEM_SCHEMA, PREPARED_WORLD_SYSTEM_VIEW_SCHEMA, PREPARED_WORLD_ORBITS_SCHEMA } from './prepared-data/world-schemas.js';

export { CATALOGUE_BANK_BINARY_MAGIC, CATALOGUE_POSITION_SCALE, encodeCatalogueBankBinary, decodeCatalogueBankBinary } from './prepared-data/catalogue-bank-binary.js';
export { PREPARED_CSS_POINT_FIELD_SCHEMA, PREPARED_CSS_POINT_FIELD_MANIFEST_SCHEMA, POINT_FIELD_BANK_ENCODING } from './stars/point-field-schemas.js';
export { POINT_FIELD_BANK_MAGIC, POINT_FIELD_BANK_VERSION, POINT_FIELD_BANK_HEADER_BYTES, POINT_FIELD_MAGNITUDE_DIVISOR, POINT_FIELD_MAGNITUDE_BOUND, POINT_FIELD_BANK_QUANTIZATION, decodeStarMagnitude, pointFieldBankLayout, pointFieldBankHeader, pointFieldBankRegions, decodePointFieldBank } from './stars/point-field-bank.js';
export { parsePreparedCssPointFieldManifest, decodePreparedCssPointField } from './stars/point-field-validation.js';
export type { PreparedCssPointField, PreparedCssPointFieldManifest, PreparedPointFieldStar, PreparedPointFieldNode, PreparedPointFieldResource, PreparedPointFieldBank, PreparedPointFieldQuantization, PreparedPointAppearance } from './stars/point-field-types.js';
