import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { defineObjects } from '../site/object-schema.mts';
import { catalogEntry } from '../site/object-catalog.mts';
import type { CatalogEntry } from '../site/object-catalog.mts';
import { hasErrorCode, isRecord } from './source-values.mts';
import { prepareSceneDistance, readPreparedFocusObjects } from './prepare-navigation-destinations.mts';

const root = resolve(import.meta.dirname, '..');
const byOrder = (a: CatalogEntry, b: CatalogEntry) => (a.order ?? Number.MAX_SAFE_INTEGER) - (b.order ?? Number.MAX_SAFE_INTEGER) || a.id.localeCompare(b.id, 'en');

/** A folder alone is not a published destination. Its descriptor must opt in. */
export async function readCatalog(objectsDirectory = resolve(root, 'src/objects')) {
  const entries: CatalogEntry[] = [];
  for (const directory of await readdir(objectsDirectory, { withFileTypes: true })) {
    if (!directory.isDirectory()) continue;
    let descriptor: unknown;
    try { descriptor = JSON.parse(await readFile(resolve(objectsDirectory, directory.name, 'object.json'), 'utf8')); }
    catch (error) { if (hasErrorCode(error, 'ENOENT')) continue; throw error; }
    if (!isRecord(descriptor) || !isRecord(descriptor.properties) || descriptor.properties.catalog === undefined) continue;
    if (descriptor.id !== directory.name) throw new TypeError(`Catalogue identity differs: ${directory.name}.`);
    entries.push(catalogEntry(descriptor, async () => { throw new Error('Catalogue preparation cannot mount a scene.'); }, prepareSceneDistance(descriptor)));
  }
  entries.sort(byOrder);
  defineObjects(entries.map(({ order, context, ...object }) => object));
  return entries;
}

/** Registered descriptors without a catalog entry are application context: the world loads their prepared resources directly. */
export async function readContextObjects(objectsDirectory = resolve(root, 'src/objects')) {
  const contexts: { id: string; type: string }[] = [];
  for (const directory of await readdir(objectsDirectory, { withFileTypes: true })) {
    if (!directory.isDirectory()) continue;
    let descriptor: unknown;
    try { descriptor = JSON.parse(await readFile(resolve(objectsDirectory, directory.name, 'object.json'), 'utf8')); }
    catch (error) { if (hasErrorCode(error, 'ENOENT')) continue; throw error; }
    if (!isRecord(descriptor) || !isRecord(descriptor.properties) || descriptor.properties.catalog !== undefined) continue;
    if (descriptor.id !== directory.name || typeof descriptor.type !== 'string') throw new TypeError(`Context object identity differs: ${directory.name}.`);
    contexts.push({ id: directory.name, type: descriptor.type });
  }
  return contexts.sort((a, b) => a.id.localeCompare(b.id, 'en'));
}

/** Every object shares one folder, so the application globs only the context objects it loads, each by name. */
export function contextObjectModule(contexts: readonly { id: string; type: string }[]) {
  const list = (patterns: readonly string[]) => `[${patterns.map(pattern => `'${pattern}'`).join(', ')}]`;
  const folder = (id: string) => `../src/objects/${id}`;
  // A point field's binary star bank is a preparation input, never an application asset.
  const assets = [...contexts.map(({ id }) => `${folder(id)}/prepared/**/*.{json,png,webp,bin}`),
    ...contexts.filter(({ type }) => type === 'point-field').map(({ id }) => `!${folder(id)}/prepared/*.bin`)];
  return '// Generated by tools/prepare-catalog.mts. Context objects are registered descriptors without a catalog entry.\n' +
    `export const CONTEXT_OBJECT_DESCRIPTORS: Record<string, unknown> = import.meta.glob(${list(contexts.map(({ id }) => `${folder(id)}/object.json`))}, { eager: true, import: 'default' });\n` +
    `export const CONTEXT_OBJECT_ASSET_URLS: Record<string, unknown> = import.meta.glob(${list(assets)}, { query: '?url', import: 'default', eager: true });\n` +
    `export const CONTEXT_OBJECT_PREPARED_JSON: Record<string, unknown> = import.meta.glob(${list(contexts.map(({ id }) => `${folder(id)}/prepared/*.json`))}, { eager: true, import: 'default' });\n`;
}

async function writeGenerated(output: string, text: string) {
  await mkdir(dirname(output), { recursive: true });
  try { if (await readFile(output, 'utf8') === text) return; }
  catch (error) { if (!hasErrorCode(error, 'ENOENT')) throw error; }
  await writeFile(output, text);
}

export async function prepareCatalog({ projectRoot = root } = {}) {
  const entries = await readCatalog(resolve(projectRoot, 'src/objects'));
  const host = entries.find(entry => entry.classification === 'star' && entry.distance.meters === 0);
  if (!host) throw new TypeError('Prepared focus destinations need a shared world host.');
  const focuses = await readPreparedFocusObjects(resolve(projectRoot, 'src/objects'), host.id);
  defineObjects<{ id: string; route: string }>([...entries, ...focuses]);
  const lines = entries.map(({ id }, index) => `import body${index} from '../src/objects/${id}/object.json' with { type: 'json' };`);
  const text = '// Generated by tools/prepare-catalog.mts. Edit each body object.json.\n' + lines.join('\n') +
    `\nexport const OBJECT_DESCRIPTORS: readonly unknown[] = [${entries.map((_, index) => `body${index}`).join(', ')}];\n`;
  await writeGenerated(resolve(projectRoot, 'site/prepared-object-catalog.mts'), text);
  await writeGenerated(resolve(projectRoot, 'site/prepared-object-distances.json'), JSON.stringify(Object.fromEntries(entries.map(entry => [entry.id, entry.distance]))) + '\n');
  await writeGenerated(resolve(projectRoot, 'site/prepared-focus-objects.json'), JSON.stringify(focuses) + '\n');
  await writeGenerated(resolve(projectRoot, 'site/prepared-context-objects.mts'), contextObjectModule(await readContextObjects(resolve(projectRoot, 'src/objects'))));
  return entries;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) await prepareCatalog();
