import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { defineObjects } from '../site/object-schema.mts';
import { catalogEntry } from '../site/object-catalog.mts';
import type { CatalogEntry } from '../site/object-catalog.mts';
import { hasErrorCode, isRecord } from './source-values.mts';

const root = resolve(import.meta.dirname, '..');
const byOrder = (a: CatalogEntry, b: CatalogEntry) => (a.order ?? Number.MAX_SAFE_INTEGER) - (b.order ?? Number.MAX_SAFE_INTEGER) || a.id.localeCompare(b.id, 'en');

/** A folder alone is not a published destination. Its descriptor must opt in. */
export async function readCatalog(objectsDirectory = resolve(root, 'src/objects')) {
  const entries: CatalogEntry[] = [];
  for (const directory of await readdir(objectsDirectory, { withFileTypes: true })) {
    if (!directory.isDirectory()) continue;
    let descriptor: unknown;
    try { descriptor = JSON.parse(await readFile(resolve(objectsDirectory, directory.name, 'object.json'), 'utf8')); }
    catch (error) { if (hasErrorCode(error, 'ENOENT')) continue; throw error; }
    if (!isRecord(descriptor) || !isRecord(descriptor.properties) || descriptor.properties.catalog === undefined) continue;
    if (descriptor.id !== directory.name) throw new TypeError(`Catalogue identity differs: ${directory.name}.`);
    entries.push(catalogEntry(descriptor, async () => { throw new Error('Catalogue preparation cannot mount a scene.'); }));
  }
  entries.sort(byOrder);
  defineObjects(entries.map(({ order, context, ...object }) => object));
  return entries;
}

export async function prepareCatalog({ projectRoot = root } = {}) {
  const entries = await readCatalog(resolve(projectRoot, 'src/objects'));
  const lines = entries.map(({ id }, index) => `import body${index} from '../src/objects/${id}/object.json' with { type: 'json' };`);
  const text = '// Generated by tools/prepare-catalog.mts. Edit each body object.json.\n' + lines.join('\n') +
    `\nexport const OBJECT_DESCRIPTORS: readonly unknown[] = [${entries.map((_, index) => `body${index}`).join(', ')}];\n`;
  const output = resolve(projectRoot, 'site/prepared-object-catalog.mts');
  await mkdir(dirname(output), { recursive: true });
  try { if (await readFile(output, 'utf8') === text) return entries; }
  catch (error) { if (!hasErrorCode(error, 'ENOENT')) throw error; }
  await writeFile(output, text);
  return entries;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) await prepareCatalog();
