import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { defineObject, defineObjects } from '../site/object-schema.mjs';

const root = resolve(import.meta.dirname, '..');
const byOrder = (a, b) => (a.order ?? Number.MAX_SAFE_INTEGER) - (b.order ?? Number.MAX_SAFE_INTEGER) || a.id.localeCompare(b.id, 'en');

/** A folder alone is not a published destination. Its descriptor must opt in. */
export async function readCatalog(objectsDirectory = resolve(root, 'src/planets')) {
  const entries = [];
  for (const directory of await readdir(objectsDirectory, { withFileTypes: true })) {
    if (!directory.isDirectory()) continue;
    let descriptor;
    try { descriptor = JSON.parse(await readFile(resolve(objectsDirectory, directory.name, 'object.json'), 'utf8')); }
    catch (error) { if (error.code === 'ENOENT') continue; throw error; }
    const catalog = descriptor.properties?.catalog;
    if (!catalog) continue;
    if (descriptor.id !== directory.name || descriptor.schema !== 'cssearth-object@1') throw new TypeError(`Catalogue identity differs: ${directory.name}.`);
    const { order, context, ...metadata } = catalog;
    for (const value of [order, context?.order]) {
      if (value !== undefined && (!Number.isSafeInteger(value) || value < 0)) throw new TypeError(`Invalid catalogue order: ${descriptor.id}.`);
    }
    const object = defineObject({ ...metadata, id: descriptor.id, route: `/${descriptor.id}/`,
      worldFrame: descriptor.properties.worldFrame ?? null, loadScene: async () => {} });
    entries.push({ ...object, order, ...(context ? { context } : {}) });
  }
  entries.sort(byOrder);
  defineObjects(entries.map(({ order, context, ...object }) => object));
  return entries;
}

export async function prepareCatalog({ projectRoot = root } = {}) {
  const entries = await readCatalog(resolve(projectRoot, 'src/planets'));
  const lines = entries.map(({ id }, index) => `import body${index} from '../src/planets/${id}/object.json' with { type: 'json' };`);
  const text = '// Generated by tools/prepare-catalog.mjs. Edit each body object.json.\n' + lines.join('\n') +
    `\nexport const OBJECT_DESCRIPTORS = [${entries.map((_, index) => `body${index}`).join(', ')}];\n`;
  const output = resolve(projectRoot, 'site/prepared-object-catalog.mjs');
  await mkdir(dirname(output), { recursive: true });
  try { if (await readFile(output, 'utf8') === text) return entries; }
  catch (error) { if (error.code !== 'ENOENT') throw error; }
  await writeFile(output, text);
  return entries;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) await prepareCatalog();
