import {requireRecord} from '../../../../tools/source-values.mts';
import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import { parseAuthoredObjectDescriptor } from '@cssearth/objects';
const root = new URL('../../../../src/planets/haumea/', import.meta.url);
const json = async (path: string|URL) => JSON.parse(await readFile(new URL(path, root), 'utf8'));

test('Haumea retains its measured triaxial shape and ring within the actual leaf budget', async () => {
  const descriptor = parseAuthoredObjectDescriptor(await json('object.json'));
  assert.deepEqual(descriptor.recipe.shape, { kind: 'ellipsoid', radiusKm: 1161, secondaryRadiusKm: 852, polarRadiusKm: 513 });
  const scene = await json('prepared/scene.json');
  assert.equal(scene.bodyLeaves.length, 1444);
  assert.equal(scene.ringCoverage.sourceFaceCount, 128);
  assert.equal(scene.ringCoverage.sourceFaces.length, 128);
  assert.equal(scene.ringCoverage.preparedTileCount, scene.ringLeaves.length);
  assert.equal(scene.ringLeaves.length, 16);
  const runtime = await json('prepared/runtime.json');
  assert.equal(runtime.tree.nodes.filter((node: { tag: string; }) => node.tag === 's').length, 1461);
  assert.ok(runtime.tree.nodes.filter((node: { tag: string; }) => node.tag === 's').length <= 2000);
  assert.deepEqual([scene.model.ring.innerRadiusKm, scene.model.ring.outerRadiusKm], [2252, 2322]);
});
test('the NASA illustration stays evenly lit with an identified model dataset and no shadow control', async () => {
  const runtime = await json('prepared/runtime.json');
  assert.equal(runtime.controls.lenses.defaultLens, 'illustration');
  assert.deepEqual(runtime.controls.lenses.controls.map((lens:unknown) => requireRecord(lens).label), ['Illustrative model']);
  const lens = (await json('prepared/lenses.json')).controls[0];
  assert.ok(lens.surfaceUrl && lens.polesUrl);
  assert.equal(Object.keys(lens).some(key => /2x/u.test(key)), false);
  const { images } = await json('prepared/minimaps.json');
  assert.equal(images.length, 1);
  assert.equal(images[0].id, lens.id);
  assert.deepEqual([images[0].width, images[0].height], [640, 320]);
  assert.equal(images[0].attribution.url, lens.source.url);
  assert.ok((await readFile(new URL('prepared/' + images[0].path, root))).length < 100_000);
  assert.deepEqual(runtime.controls.settings.controls, []);
  assert.deepEqual(runtime.variants.map((v:unknown) => requireRecord(v).when), [{ lensId: 'illustration' }]);
  assert.ok(runtime.assets.entries.some((a: { key: string; }) => a.key === 'surface'));
  assert.ok(runtime.assets.entries.every((a: { key: string|string[]; }) => !a.key.includes('lit-')));
  const material = runtime.materials[0];
  assert.equal(material.rotation.kind, 'ellipsoid');
  assert.equal(material.rotation.projection.bodyMeshMatrix[0], 852 / 1161);
  assert.equal(runtime.variants[0].materials[0].rotationEnabled, false);
  let parent = runtime.tree.nodes[material.target].parent;
  while (parent >= 0 && parent !== runtime.tree.scene) parent = runtime.tree.nodes[parent].parent;
  assert.equal(parent, runtime.tree.scene, 'lighting shares body/ring depth ordering');
});
