import {requireRecord} from '../../../../tools/sources/source-values.mts';
import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import { parseAuthoredObjectDescriptor } from '@cssearth/objects';
const root = new URL('../../../../src/objects/haumea/', import.meta.url);
const json = async (path: string|URL) => JSON.parse(await readFile(new URL(path, root), 'utf8'));

test('Haumea retains its measured triaxial shape and ring within the actual leaf budget', async () => {
  const descriptor = parseAuthoredObjectDescriptor(await json('object.json'));
  assert.deepEqual(descriptor.recipe.shape, { kind: 'ellipsoid', radiusKm: 1161, secondaryRadiusKm: 852, polarRadiusKm: 513 });
  const scene = await json('prepared/scene.json');
  assert.equal(scene.bodyLeaves.length, 1444);
  assert.equal(scene.ringCoverage.sourceFaceCount, 128);
  assert.equal(scene.ringCoverage.sourceFaces.length, 128);
  assert.equal(scene.ringCoverage.preparedTileCount, scene.ringLeaves.length);
  assert.equal(scene.ringLeaves.length, 16);
  const runtime = await json('prepared/runtime.json');
  assert.equal(runtime.tree.nodes.filter((node: { tag: string; }) => node.tag === 's').length, 1461);
  assert.ok(runtime.tree.nodes.filter((node: { tag: string; }) => node.tag === 's').length <= 2000);
  assert.deepEqual([scene.model.ring.innerRadiusKm, scene.model.ring.outerRadiusKm], [2252, 2322]);
});
test('the measured colour lens is the default beside a non-default illustration, evenly lit, with no shadow control', async () => {
  const runtime = await json('prepared/runtime.json');
  assert.equal(runtime.controls.lenses.defaultLens, 'color');
  assert.deepEqual(runtime.controls.lenses.controls.map((lens:unknown) => requireRecord(lens).label), ['Color', 'Illustration']);
  const lens = (await json('prepared/lenses.json')).controls[0];
  assert.ok(lens.surfaceUrl && lens.polesUrl);
  assert.equal(lens.surfaceUrl, lens.surface2xUrl);
  assert.equal(lens.polesUrl, lens.poles2xUrl);
  const { images } = await json('prepared/minimaps.json');
  assert.equal(images.length, 2);
  assert.equal(images[0].id, lens.id);
  assert.deepEqual([images[0].width, images[0].height], [640, 320]);
  assert.equal(images[0].attribution.url, lens.source.url);
  assert.ok((await readFile(new URL('prepared/' + images[0].path, root))).length < 100_000);
  assert.deepEqual(runtime.controls.settings.controls, []);
  assert.deepEqual(runtime.variants.map((v:unknown) => requireRecord(v).when), [{ lensId: 'color' }, { lensId: 'illustration' }]);
  // The default lens mounts with the body; the illustration decodes only when selected.
  assert.deepEqual(runtime.assets.startup.filter((key: string) => key.includes(':')), ['surface:color', 'poles:color']);
  assert.ok(runtime.assets.entries.some((a: { key: string; pool: string }) => a.key === 'surface:illustration' && a.pool === 'lenses'));
  assert.ok(runtime.assets.entries.every((a: { key: string|string[]; }) => !a.key.includes('lit-')));
  const material = runtime.materials[0];
  assert.equal(material.rotation.kind, 'ellipsoid');
  assert.equal(material.rotation.projection.bodyMeshMatrix[0], 852 / 1161);
  assert.equal(runtime.variants[0].materials[0].rotationEnabled, false);
  let parent = runtime.tree.nodes[material.target].parent;
  while (parent >= 0 && parent !== runtime.tree.scene) parent = runtime.tree.nodes[parent].parent;
  assert.equal(parent, runtime.tree.scene, 'lighting shares body/ring depth ordering');
});
