/** The Cepheid light curve a package installs (light-curve.mts), on a generated star package's files and S Vul's Gaia DR3
 * vari_cepheid row. */
import { parsePresentationProfile } from '@cssearth/objects';
import assert from 'node:assert/strict';
import { resolve } from 'node:path';
import { sourceTest } from '@cssearth/objects/node/source-test';
import { installLightCurve, LIGHT_CURVE_MODEL } from './light-curve.mts';
import { loadSolarEpoch } from './solar-epoch.mts';

const test = sourceTest(), epoch = await loadSolarEpoch(resolve(import.meta.dirname, '../../../..'));
const o = 'src/objects/s-vul', s = `${o}/source`;
// The files the installer edits, as the generator writes them for a star (generate.mts).
const generated = (): [string, string][] => [
  [`${s}/preparation/acquisition.json`, JSON.stringify({ schema: 'cssearth-acquisition-plan@1', operations: [] })],
  [`${s}/manifest.json`, JSON.stringify({ schema: 'cssearth-authoritative-sources@3', inputs: [], generatedIntermediates: [], documents: [] })],
  [`${s}/preparation/presentation.json`, JSON.stringify({ schema: 'cssearth-css-presentation-profile@2', namespace: 's-vul', mode: 'emissive' })],
  [`${o}/NOTICE.md`, '# S Vul credits\n\nPlacement: Gaia DR3.\n'],
  [`${o}/README.md`, ['# S Vul', '', '## Sources', '', 'A Cepheid.', '', '**Limb.** None.', '', '## Evidence', '', 'Generated by new-object.mts.', '', '## Known problems', '', '- **Not shown.** Pulsation.', '', '[Inputs](source/manifest.json)', ''].join('\n')],
];
const csv = ['source_id,pf,pf_error,fund_freq1,reference_time_g,zp_mag_g,num_harmonics_for_p1_g,fund_freq1_harmonic_ampl_g,fund_freq1_harmonic_phase_g,epoch_g,epoch_g_error,peak_to_peak_g,r21_g,phi21_g,mode_best_classification,type_best_classification',
  `2027971514401523456,69.467416955503,0.04627568,0.014395237995397827,1796.4225877192143,8.083196,2,"(0.19668083, 0.04891441${', NaN'.repeat(14)})","(5.454763, 3.7024179${', 0.0'.repeat(14)})",1626.505285846054,0.06544369,0.42478037,0.24869943,5.3592625,FUNDAMENTAL,DCEP`].join('\n');

test('a Cepheid package gains the row, its acquisition, the profile field and its account, once', () => {
  const files = new Map<string, string | Buffer>(generated());
  const result = installLightCurve(files, { id: 's-vul', name: 'S Vul', sourceId: '2027971514401523456', csv }, epoch);
  assert.equal(result.model.amplitudesMag.length, 2);
  const manifest = JSON.parse(String(files.get(`${s}/manifest.json`))) as { inputs: { path: string; consumers: string[]; sourceBinding: { references: { catalogueId: string }[] } }[] };
  const input = manifest.inputs.find(entry => entry.path === LIGHT_CURVE_MODEL);
  assert.ok(input, 'the row is a declared input'); assert.deepEqual(input.consumers, ['presentation']);
  assert.equal(input.sourceBinding.references[0]!.catalogueId, 'source-s-vul-gaia-dr3-vari-cepheid');
  assert.ok(files.has('src/sources/gaia-dr3-vari-cepheid-s-vul.json'));
  const plan = JSON.parse(String(files.get(`${s}/preparation/acquisition.json`))) as { operations: { path: string; form: { QUERY: string } }[] };
  assert.match(plan.operations.find(step => step.path === LIGHT_CURVE_MODEL)!.form.QUERY, /FROM gaiadr3\.vari_cepheid WHERE source_id = 2027971514401523456$/u);
  assert.deepEqual(parsePresentationProfile(JSON.parse(String(files.get(`${s}/preparation/presentation.json`)))).lightCurve, { model: LIGHT_CURVE_MODEL });
  const readme = String(files.get(`${o}/README.md`));
  assert.ok(readme.indexOf('**Brightness.**') < readme.indexOf('## Evidence') && readme.indexOf('- **Brightness.**') > readme.indexOf('## Known problems'));
  assert.match(readme, /2 harmonics of a 69\.47-day period .* swings 0\.425 mag, so at minimum the star gives 68% of its peak light/u);
  const once = new Map(files);
  installLightCurve(files, { id: 's-vul', name: 'S Vul', sourceId: '2027971514401523456', csv }, epoch);
  for (const [path, value] of once) assert.equal(String(files.get(path)), String(value), `${path} is unchanged by a second install`);
  // A page that names the stills of its light curve keeps the name through another install.
  files.set(`${s}/preparation/presentation.json`, JSON.stringify({ schema: 'cssearth-css-presentation-profile@2', namespace: 's-vul', mode: 'emissive', lightCurve: { model: LIGHT_CURVE_MODEL, stills: 'pulsation' } }));
  installLightCurve(files, { id: 's-vul', name: 'S Vul', sourceId: '2027971514401523456', csv }, epoch);
  assert.deepEqual(parsePresentationProfile(JSON.parse(String(files.get(`${s}/preparation/presentation.json`)))).lightCurve, { model: LIGHT_CURVE_MODEL, stills: 'pulsation' });
});
