import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const packageRoot = resolve(import.meta.dirname, '..');
const order = (a, b) => (a.order ?? Number.MAX_SAFE_INTEGER) - (b.order ?? Number.MAX_SAFE_INTEGER) || a.id.localeCompare(b.id, 'en');
const kinds = { planet: 'PLANET_IDS', 'dwarf-planet': 'DWARF_PLANET_IDS', asteroid: 'ASTEROID_IDS',
  'trans-neptunian': 'TRANS_NEPTUNIAN_IDS', interstellar: 'INTERSTELLAR_IDS', comet: 'COMET_IDS' };
const models = {
  asteroid: ['ASTEROID_ELEMENTS', "import type { KeplerianElements } from '../../kepler.js'", '{ query: string; elements: KeplerianElements }'],
  comet: ['COMET_ELEMENTS', "import type { KeplerianElements } from '../../kepler.js'", '{ query: string; elements: KeplerianElements }'],
  dwarfPlanet: ['DWARF_PLANET_ELEMENTS', "import type { DwarfPlanetRecord } from '../dwarfPlanetElements.data.js'", 'DwarfPlanetRecord'],
  satellite: ['SATELLITE_ELEMENTS', "import type { SatelliteRecord } from '../satelliteElements.data.js'", 'SatelliteRecord'],
  sceneSatellite: ['SCENE_SATELLITE_STATES', "import type { SceneSatelliteRecord } from '../../sceneSatellites.js'", 'SceneSatelliteRecord'],
  asteroidFixture: ['ASTEROID_FIXTURES', '', ''],
  cometFixture: ['COMET_FIXTURES', '', ''],
};

export async function readBodyRecords(root = packageRoot) {
  const records = [];
  for (const file of (await readdir(resolve(root, 'data/bodies'))).sort()) {
    if (!file.endsWith('.json')) continue;
    const record = JSON.parse(await readFile(resolve(root, 'data/bodies', file), 'utf8'));
    if (!/^[a-z][a-z0-9-]*$/.test(record.id) || file !== `${record.id}.json`) throw new TypeError(`Invalid astronomy identity: ${file}.`);
    if (![...Object.keys(kinds), 'star', 'satellite'].includes(record.classification)) throw new TypeError(`Invalid astronomy classification: ${record.id}.`);
    for (const value of [record.order, record.classificationOrder]) {
      if (value !== undefined && (!Number.isSafeInteger(value) || value < 0)) throw new TypeError(`Invalid astronomy order: ${record.id}.`);
    }
    const p = record.physical;
    if (!p || typeof p.name !== 'string' || !p.name || !(p.meanRadiusKm > 0) ||
      !Number.isFinite(p.meanRadiusKm) || !Number.isFinite(p.gravitationalParameterKm3PerS2) || p.gravitationalParameterKm3PerS2 < 0 ||
      !(p.horizonsCode === null || typeof p.horizonsCode === 'string') || !(p.parent === null || typeof p.parent === 'string')) {
      throw new TypeError(`Invalid physical data: ${record.id}.`);
    }
    records.push(record);
  }
  const ids = new Set(records.map(record => record.id));
  if (!ids.size) throw new TypeError('Astronomy records are empty.');
  for (const record of records) {
    if (record.physical.parent !== null && !ids.has(record.physical.parent)) throw new TypeError(`Missing astronomy parent: ${record.id}.`);
  }
  return records.sort(order);
}

export async function writeBodyRecord(record, root = packageRoot) {
  if (!/^[a-z][a-z0-9-]*$/.test(record.id)) throw new TypeError('Invalid astronomy identity.');
  await writeChanged(resolve(root, 'data/bodies', `${record.id}.json`), `${JSON.stringify(record, null, 2)}\n`);
}

async function writeChanged(path, text) {
  try { if (await readFile(path, 'utf8') === text) return; }
  catch (error) { if (error.code !== 'ENOENT') throw error; }
  await writeFile(path, text);
}

/** Compile portable package inputs. No application checkout or network is needed. */
export async function prepareBodyRecords(root = packageRoot) {
  const records = await readBodyRecords(root), output = resolve(root, 'src/data/generated');
  await mkdir(output, { recursive: true });
  const header = '// Generated by tools/body-records.mjs from data/. Do not edit.\n';
  const json = value => JSON.stringify(value);
  const ids = records.map(record => record.id);
  let bodySource = header + "import type { BodyData } from '../../bodies.js'\n" + `export const BODY_IDS = ${json(ids)} as const\n`;
  for (const [kind, symbol] of Object.entries(kinds)) {
    const members = records.filter(record => record.classification === kind).sort((a, b) => order(
      { id: a.id, order: a.classificationOrder }, { id: b.id, order: b.classificationOrder }));
    bodySource += `export const ${symbol} = ${json(members.map(record => record.id))} as const\n`;
  }
  bodySource += `export const BODIES: Record<typeof BODY_IDS[number], BodyData> = ${json(Object.fromEntries(records.map(({ id, physical }) => [id, { id, ...physical }])))}\n`;
  await writeChanged(resolve(output, 'bodies.ts'), bodySource);
  for (const [key, [symbol, imports, type]] of Object.entries(models)) {
    const entries = records.filter(record => record[key] !== undefined);
    const keys = entries.map(record => JSON.stringify(record.id)).join(' | ') || 'never';
    const annotation = type ? `: Readonly<Record<${keys}, ${type}>>` : '';
    await writeChanged(resolve(output, `${key}.ts`), header + imports + '\n' +
      `export const ${symbol}${annotation} = ${json(Object.fromEntries(entries.map(record => [record.id, record[key]])))} as const\n`);
  }
  const fixtures = {};
  for (const file of (await readdir(resolve(root, 'data/fixtures'))).sort()) {
    if (file.endsWith('.json')) fixtures[file.slice(0, -5)] = JSON.parse(await readFile(resolve(root, 'data/fixtures', file), 'utf8'));
  }
  await writeChanged(resolve(output, 'horizons.ts'), header + "import type { HorizonsFixture } from '../../__fixtures__/horizons.js'\n" +
    `export const HORIZONS = ${json(fixtures)} as const satisfies Record<string, HorizonsFixture>\n`);
  return records;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) await prepareBodyRecords();
