#!/usr/bin/env node
// Single-epoch osculating elements and independent Horizons vector fixtures.
import { writeFileSync } from 'node:fs';
import { elementsUrl, vectorsUrl, horizons, parseElements, parseVectors } from './lib/horizons.mjs';

const epochJdTt = 2461286.5;
const bodies = [['comet-67p', 'DES=67P;CAP;'], ['comet-103p', 'DES=103P;CAP;'], ['comet-9p', 'DES=9P;CAP;'], ['comet-81p', 'DES=81P;CAP;'], ['comet-1p', 'DES=1P;CAP;']];
const records = {}, fixtures = {};
for (const [id, command] of bodies) {
  const query = elementsUrl({ command, center: '500@10', startJd: epochJdTt, stopJd: epochJdTt + 1, stepDays: 1 });
  const row = parseElements(await horizons(query, `comet-elements-${id}`), id)[0];
  const rad = Math.PI / 180;
  records[id] = { query, elements: { epochJdTt,
    semiMajorAxisKm: row.semiMajorAxisKm, eccentricity: row.eccentricity,
    inclinationRad: row.inclinationDeg * rad, ascendingNodeRad: row.nodeDeg * rad,
    argumentOfPeriapsisRad: row.periapsisDeg * rad, meanAnomalyAtEpochRad: row.meanAnomalyDeg * rad,
    meanMotionRadPerDay: row.meanMotionDegPerDay * rad } };
  const vectorQuery = vectorsUrl({ command, center: '500@10', epochsJdTdb: [epochJdTt - 30, epochJdTt, epochJdTt + 30], outUnits: 'KM-D' });
  fixtures[id] = { query: vectorQuery, rows: parseVectors(await horizons(vectorQuery, `comet-vectors-${id}`), id) };
}
const header = '// Generated by tools/generate-comets.mjs. Do not edit.\n' +
  '// JPL Horizons, heliocentric ICRF; epoch 2026-09-03. TDB is approximated as TT (under 2 ms).\n';
writeFileSync(new URL('../src/data/cometElements.data.ts', import.meta.url), header +
  "import type { KeplerianElements } from '../kepler.js'\n" +
  `export const COMET_ELEMENTS = ${JSON.stringify(records, null, 2)} satisfies Record<string, {query: string; elements: KeplerianElements}>\n`);
writeFileSync(new URL('../src/__fixtures__/horizons.comets.ts', import.meta.url), header +
  `export const COMET_FIXTURES = ${JSON.stringify(fixtures, null, 2)} as const\n`);
