#!/usr/bin/env node
// Single-epoch osculating elements and independent Horizons vector fixtures.
import { writeFileSync } from 'node:fs';
import { elementsUrl, vectorsUrl, horizons, parseElements, parseVectors } from './lib/horizons.mts';

import { readVectorFixture, recordMap } from './lib/generator-records.mts';
import type { ElementRecord, VectorFixture } from './lib/generator-records.mts';
const epochJdTt = 2461286.5;
const bodies = [['comet-67p', 'DES=67P;CAP;'], ['comet-103p', 'DES=103P;CAP;'], ['comet-9p', 'DES=9P;CAP;'], ['comet-81p', 'DES=81P;CAP;'], ['comet-1p', 'DES=1P;CAP;'], ['comet-8p', 'DES=8P;CAP;'], ['comet-19p', 'DES=19P;CAP;'], ['comet-137p', 'DES=137P;CAP;'], ['comet-143p', 'DES=143P;CAP;'], ['comet-162p', 'DES=162P;CAP;'], ['comet-2p', 'DES=2P;CAP;'], ['comet-209p', 'DES=209P;CAP;'], ['comet-17p', 'DES=17P;CAP;'], ['comet-21p', 'DES=21P;CAP;'], ['comet-26p', 'DES=26P;CAP;'], ['comet-29p', 'DES=29P;CAP;'], ['comet-46p', 'DES=46P;CAP;'], ['comet-55p', 'DES=55P;CAP;'], ['comet-96p', 'DES=96P;CAP;'], ['comet-109p', 'DES=109P;CAP;'], ['comet-167p', 'DES=167P;CAP;'], ['comet-153p', 'DES=153P;CAP;'], ['comet-c1983-h1', 'DES=C/1983 H1;CAP;'], ['comet-c1956-r1', 'DES=C/1956 R1;CAP;'], ['comet-c1973-e1', 'DES=C/1973 E1;CAP;'], ['comet-c1995-o1', 'DES=C/1995 O1;CAP;'], ['comet-c1996-b2', 'DES=C/1996 B2;CAP;'], ['comet-c2006-p1', 'DES=C/2006 P1;CAP;'], ['comet-c2013-a1', 'DES=C/2013 A1;CAP;'], ['comet-c2014-un271', 'DES=C/2014 UN271;CAP;'], ['comet-c2020-f3', 'DES=C/2020 F3;CAP;'], ['comet-c2023-a3', 'DES=C/2023 A3;CAP;']];
const formatOnly = process.argv.includes('--format-only');
const records: Record<string, ElementRecord> = {};
const fixtures: Record<string, VectorFixture> = formatOnly
  ? recordMap((await import('../src/__fixtures__/horizons.comets.ts')).COMET_FIXTURES, readVectorFixture) : {};
for (const [id, command] of formatOnly ? [] : bodies) {
  const query = elementsUrl({ command, center: '500@10', startJd: epochJdTt, stopJd: epochJdTt + 1, stepDays: 1 });
  const row = parseElements(await horizons(query, `comet-elements-${id}`), id)[0];
  const rad = Math.PI / 180;
  records[id] = { query, elements: { epochJdTt,
    semiMajorAxisKm: row.semiMajorAxisKm, eccentricity: row.eccentricity,
    inclinationRad: row.inclinationDeg * rad, ascendingNodeRad: row.nodeDeg * rad,
    argumentOfPeriapsisRad: row.periapsisDeg * rad, meanAnomalyAtEpochRad: row.meanAnomalyDeg * rad,
    meanMotionRadPerDay: row.meanMotionDegPerDay * rad } };
  const vectorQuery = vectorsUrl({ command, center: '500@10', epochsJdTdb: [epochJdTt - 30, epochJdTt, epochJdTt + 30], outUnits: 'KM-D' });
  fixtures[id] = { query: vectorQuery, rows: parseVectors(await horizons(vectorQuery, `comet-vectors-${id}`), id) };
}
const header = '// Generated by tools/generate-comets.mts. Do not edit.\n' +
  '// JPL Horizons, heliocentric ICRF; epoch 2026-09-03. TDB is approximated as TT (under 2 ms).\n';
if (!formatOnly) writeFileSync(new URL('../src/data/cometElements.data.ts', import.meta.url), header +
  "import type { KeplerianElements } from '../kepler.js'\n" +
  `export const COMET_ELEMENTS = ${JSON.stringify(records, null, 2)} satisfies Record<string, {query: string; elements: KeplerianElements}>\n`);
// Keep each vector observation together, matching the asteroid fixture writer.
// --format-only retains the pinned observations and performs no acquisition.
const serialized = JSON.stringify(fixtures, null, 2)
  .replace(/\{\n\s+"jd":([\s\S]*?)\n\s+\}/g, (_, fields: string) => '{ "jd":' + fields.trim().replace(/\s*\n\s*/g, ' ') + ' }')
  .replace(/"rows": \[\n\s+/g, '"rows": [ ').replace(/ \}\n    \]/g, ' } ]');
const fixtureText = header + `export const COMET_FIXTURES = ${serialized} as const\n`;
if (fixtureText.trimEnd().split('\n').length > 600) throw new Error('Generated comet fixtures exceed 600 lines');
writeFileSync(new URL('../src/__fixtures__/horizons.comets.ts', import.meta.url), fixtureText);
