import {array,shape,number,text} from '../../../../tools/objects/terrestrial-layers/source-records.mts';
import {required} from '../../../../tools/contract/test-values.mts';
import { sourceTest } from '../../source-test.mts';
const test = sourceTest('quaoar');
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {parsePdsRadiusTable} from '../../../../tools/objects/terrestrial-layers/obj-shape.mts';
const root=new URL('../../../../src/objects/quaoar/source/',import.meta.url);
test('Quaoar uses published three-dimensional axes and separately qualified two-ring dimensions',async()=>{
 const config=JSON.parse((await readFile(new URL('preparation/terrestrial.json',root))).toString('utf8'));
 const mesh=parsePdsRadiusTable(await readFile(new URL('shape/ellipsoid.tab',root),'utf8'),config.geometry.radialTerrain.grid);
 for(const [lon,lat,r]of [[0,0,566100],[90,0,566100],[0,90,511200]] as const)assert.ok(Math.abs(required(mesh.sample(lon,lat))-r)<1e-5);
 const rings=array(shape({innerRadiusKm:number,outerRadiusKm:number,qualification:text}))(config.rings.bands);
 assert.equal(config.geometry.camera.framingScale,config.geometry.radiusKm/Math.max(...rings.map(r=>r.outerRadiusKm)));
 assert.deepEqual(rings.map(r=>(r.innerRadiusKm+r.outerRadiusKm)/2),[4057.2,2520]);
 assert.ok(Math.abs(rings[0].outerRadiusKm-rings[0].innerRadiusKm-76.4)<1e-8);
 assert.equal(rings[1].outerRadiusKm-rings[1].innerRadiusKm,10);
 assert.match(rings[0].qualification,/true width varies with azimuth/);
 const rotation=JSON.parse((await readFile(new URL('preparation/rotation.json',root))).toString('utf8'));
 assert.match(rotation.qualification,/ring-plane prior/);assert.equal(rotation.periodHours,undefined);
 const content=JSON.parse((await readFile(new URL('content/object.json',root))).toString('utf8'));
 assert.ok(content.settings.controls.every((c: { checked: boolean; })=>c.checked===false));
});
