import type {DirectionalSunPresentation} from './directional-sun-contract.mts';
export interface DirectionalSunAsset { url: string; width: number; height: number; bytes: number; sha256: string; }
export interface DirectionalSunPreparationOptions {
  objectId: string; publicRoot: string; preparedModulePath?: URL; ensureDirectories(): void | Promise<unknown>;
  meanHeliocentricDistanceAu: number; presentation?: DirectionalSunPresentation;
  planMetadata?: Readonly<Record<string, unknown>>; writeModule?: boolean;
}
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import sharp from "sharp";

import {
  DIRECTIONAL_SUN_DISTANCE_STANDARD,
  DIRECTIONAL_SUN_PRESENTATION_STANDARD,
  DIRECTIONAL_SUN_SPRITE_PIXELS,
  PREPARED_DIRECTIONAL_SUN_SCHEMA,
  validateDirectionalSunPlan,
  validateDirectionalSunPresentationStandard,
} from "./directional-sun-contract.mts";

export async function preparePlanetDirectionalSun({
  objectId,
  publicRoot,
  preparedModulePath,
  ensureDirectories,
  meanHeliocentricDistanceAu,
  presentation = DIRECTIONAL_SUN_PRESENTATION_STANDARD,
  planMetadata = Object.freeze({}),
  writeModule = true,
}: DirectionalSunPreparationOptions) {
  validateDirectionalSunPresentationStandard(presentation);
  if (!/^[a-z][a-z0-9-]*$/u.test(objectId) ||
      typeof publicRoot !== "string" ||
      (writeModule && !(preparedModulePath instanceof URL)) ||
      typeof ensureDirectories !== "function" ||
      !Number.isFinite(meanHeliocentricDistanceAu) ||
      meanHeliocentricDistanceAu <= 0 ||
      planMetadata === null || typeof planMetadata !== "object") {
    throw new TypeError("Planet directional Sun preparation is invalid.");
  }
  await ensureDirectories();
  const size = DIRECTIONAL_SUN_SPRITE_PIXELS * 2;
  const filename = `${objectId}-directional-sun@2x.webp`;
  const path = resolve(publicRoot, filename);
  await sharp(prepareCleanRoomSun(size, presentation), {
    raw: { width: size, height: size, channels: 4 },
  }).webp({ lossless: true, effort: 6 }).toFile(path);
  const bytes = await readFile(path);
  const asset: DirectionalSunAsset = Object.freeze({
    url: `/scenes/${objectId}/${filename}`,
    width: size,
    height: size,
    bytes: bytes.byteLength,
    sha256: createHash("sha256").update(bytes).digest("hex"),
  });
  const googleEarthMarsSpriteViewportWidthShare =
    presentation.projection.apparentViewportWidthShare;
  const observerDistanceKilometers = meanHeliocentricDistanceAu *
    DIRECTIONAL_SUN_DISTANCE_STANDARD.astronomicalUnitKilometers;
  const angularRadiusRadians = Math.atan(
    DIRECTIONAL_SUN_DISTANCE_STANDARD.nominalSolarRadiusKilometers /
      observerDistanceKilometers,
  );
  const angularDiameterDegrees = angularRadiusRadians * 2 * 180 / Math.PI;
  const physicalDiskViewportWidthShare = presentation.projection.focalX *
    Math.tan(angularRadiusRadians);
  const spriteOpaqueCoreDiameterShare =
    presentation.appearance.analyticRadialFit.coreRadiusPixels * 2 /
      DIRECTIONAL_SUN_SPRITE_PIXELS;
  const apparentViewportWidthShare = physicalDiskViewportWidthShare /
    spriteOpaqueCoreDiameterShare;
  const halfExtentOverCenter = apparentViewportWidthShare /
    presentation.projection.focalX;
  const projection = Object.freeze({
    ...presentation.projection,
    halfExtentOverFar: halfExtentOverCenter *
      presentation.projection.centerDistanceOverFar,
    halfExtentOverCenter,
    apparentViewportWidthShare,
  });
  const output = Object.freeze({
    schema: PREPARED_DIRECTIONAL_SUN_SCHEMA,
    model: "cssearth-standard-clean-room-retained-billboard",
    billboard: true,
    bakedIntoStarfield: false,
    localDirection: Object.freeze([...presentation.localDirection]),
    referenceViewDirection:
      Object.freeze([...presentation.referenceViewDirection]),
    asset: Object.freeze({
      sourcePixels: "repository-authored-clean-room-raster",
      generator: "src/platform/prepare-directional-sun.mts",
      googlePixelsRedistributed: false,
      ...asset,
    }),
    appearance: presentation.appearance,
    projection,
    distanceScaling: Object.freeze({
      ...DIRECTIONAL_SUN_DISTANCE_STANDARD,
      meanHeliocentricDistanceAu,
      observerDistanceKilometers,
      angularDiameterDegrees,
      physicalDiskViewportWidthShare,
      spriteOpaqueCoreDiameterShare,
      googleEarthMarsSpriteViewportWidthShare,
      physicalToGoogleEarthMarsSpriteScale:
        apparentViewportWidthShare /
          googleEarthMarsSpriteViewportWidthShare,
    }),
    culling: presentation.culling,
    provenance: Object.freeze({
      source: presentation.source,
      sourcePath: presentation.sourcePath,
      qualification: presentation.qualification,
    }),
    ...planMetadata,
    runtimeRasterization: false,
  });
  validateDirectionalSunPlan(output);
  if (writeModule) await writeFile(
    preparedModulePath!,
    "// Generated by src/platform/prepare-directional-sun.mts. Do not edit by hand.\n" +
      `export const PREPARED_${objectId.toUpperCase()}_SKY_SUN = ` +
      `Object.freeze(${JSON.stringify(output)});\n`,
  );
  return output;
}

function prepareCleanRoomSun(size: number, presentation: DirectionalSunPresentation) {
  const pixels = Buffer.alloc(size * size * 4);
  const half = size / 2;
  const density = size / 128;
  const radialFit = presentation.appearance.analyticRadialFit;
  for (let y = 0; y < size; y += 1) {
    for (let x = 0; x < size; x += 1) {
      const dx = (x + 0.5 - half) / density;
      const dy = (y + 0.5 - half) / density;
      const radius = Math.hypot(dx, dy);
      const falloffDistance = Math.max(
        0,
        radius - radialFit.coreRadiusPixels,
      );
      const radiance = Math.exp(-Math.pow(
        falloffDistance / radialFit.falloffScalePixels,
        radialFit.falloffExponent,
      ));
      const green = 1 - 0.1 *
        (1 - Math.exp(-falloffDistance / 10));
      const blue = 1 - 0.34 *
        (1 - Math.exp(-falloffDistance / 8));
      const offset = (y * size + x) * 4;
      pixels[offset] = 255;
      pixels[offset + 1] = Math.round(255 * green);
      pixels[offset + 2] = Math.round(255 * blue);
      pixels[offset + 3] = Math.round(255 * radiance);
    }
  }
  return pixels;
}
