#!/usr/bin/env node

import { access, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { MERCURY_PUBLIC_ROOT } from "./preparation-paths.mjs";
import { validateMercurySourceGroup } from "./source-manifest.mjs";

await validateMercurySourceGroup("lenses");
const controls = Object.freeze([
  Object.freeze({
    id: "normal",
    label: "750 nm",
    falseColor: false,
    filter: "MESSENGER MDIS BDR global 750 nm monochrome basemap",
    thumbnailUrl: "/scenes/mercury/mercury-lens-normal.webp",
    surfaceUrl: "/scenes/mercury/mercury-surface-normal.webp",
    surface2xUrl: "/scenes/mercury/mercury-surface-normal@2x.webp",
    view: "exterior",
  }),
  Object.freeze({
    id: "enhanced",
    label: "Enhanced",
    falseColor: true,
    filter: "NASA Trek/USGS MESSENGER enhanced-color mosaic with qualified prepared coverage completion",
    thumbnailUrl: "/scenes/mercury/mercury-lens-enhanced.webp",
    surfaceUrl: "/scenes/mercury/mercury-surface-enhanced.webp",
    surface2xUrl: "/scenes/mercury/mercury-surface-enhanced@2x.webp",
    view: "exterior",
  }),
  Object.freeze({
    id: "topography",
    label: "Topography",
    falseColor: true,
    filter: "USGS MESSENGER global color shaded relief",
    thumbnailUrl: "/scenes/mercury/mercury-lens-topography.webp",
    surfaceUrl: "/scenes/mercury/mercury-surface-topography.webp",
    surface2xUrl: "/scenes/mercury/mercury-surface-topography@2x.webp",
    view: "exterior",
  }),
  Object.freeze({
    id: "interior",
    label: "Interior",
    falseColor: false,
    filter: "NASA-dimensioned retained 3D metallic-core cutaway",
    thumbnailUrl: "/scenes/mercury/mercury-lens-interior.webp",
    surfaceUrl: "/scenes/mercury/mercury-interior-section.webp",
    surface2xUrl: "/scenes/mercury/mercury-interior-section@2x.webp",
    view: "interior",
  }),
]);
for (const lens of controls) {
  await Promise.all([
    access(resolve(MERCURY_PUBLIC_ROOT, lens.thumbnailUrl.split("/").at(-1))),
    access(resolve(MERCURY_PUBLIC_ROOT, lens.surfaceUrl.split("/").at(-1))),
    access(resolve(MERCURY_PUBLIC_ROOT, lens.surface2xUrl.split("/").at(-1))),
  ]);
}
await writeFile(
  resolve(import.meta.dirname, "../runtime/preparedLenses.mjs"),
  "// Generated by tools/prepare-lenses.mjs from declared local sources.\n" +
    `export const PREPARED_MERCURY_LENSES = Object.freeze(${JSON.stringify({
      schema: "cssmercury-prepared-lenses@1",
      defaultLens: "normal",
      controls,
      runtimeRasterization: false,
    })});\n`,
);
