// Generated by tools/generate-asteroids.mjs. Do not edit.
// JPL Horizons, heliocentric ICRF; epoch 2026-09-04. TDB is approximated as TT (under 2 ms).
import type { KeplerianElements } from '../kepler.js'
export const ASTEROID_ELEMENTS = {
  "vesta": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%274%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 353241789.0791284,
      "eccentricity": 0.09022581855691808,
      "inclinationRad": 0.39738641912913136,
      "ascendingNodeRad": 0.3175044936283746,
      "argumentOfPeriapsisRad": 4.160708929219614,
      "meanAnomalyAtEpochRad": 1.8251361828380008,
      "meanMotionRadPerDay": 0.004740907108686701
    }
  }
} satisfies Record<string, {query: string; elements: KeplerianElements}>
