// Generated by tools/generate-asteroids.mjs. Do not edit.
// JPL Horizons, heliocentric ICRF; epoch 2026-09-03. TDB is approximated as TT (under 2 ms).
import type { KeplerianElements } from '../kepler.js'
export const ASTEROID_ELEMENTS_5 = {
  "asteroid-2001-sn263": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27153591%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": { "epochJdTt": 2461286.5, "semiMajorAxisKm": 297355187.3686203, "eccentricity": 0.4800137722742203, "inclinationRad": 0.5096246481503587, "ascendingNodeRad": 6.148172996495786, "argumentOfPeriapsisRad": 2.543366494877694, "meanAnomalyAtEpochRad": 3.920606672080197, "meanMotionRadPerDay": 0.006138415485349885 }
  },
  "dinkinesh": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27152830%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": { "epochJdTt": 2461286.5, "semiMajorAxisKm": 327847266.1608174, "eccentricity": 0.1126841676722353, "inclinationRad": 0.4433091933929112, "ascendingNodeRad": 0.031000781753280148, "argumentOfPeriapsisRad": 1.5109846507300149, "meanAnomalyAtEpochRad": 0.9738785694303402, "meanMotionRadPerDay": 0.005302274527319834 }
  }
} satisfies Record<string, {query: string; elements: KeplerianElements}>
