// Generated by tools/generate-asteroids.mjs. Do not edit.
// JPL Horizons, heliocentric ICRF; epoch 2026-09-03. TDB is approximated as TT (under 2 ms).
import type { KeplerianElements } from '../kepler.js'
export const ASTEROID_ELEMENTS = {
  "vesta": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%274%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 353241789.0791284,
      "eccentricity": 0.09022581855691808,
      "inclinationRad": 0.39738641912913136,
      "ascendingNodeRad": 0.3175044936283746,
      "argumentOfPeriapsisRad": 4.160708929219614,
      "meanAnomalyAtEpochRad": 1.8251361828380008,
      "meanMotionRadPerDay": 0.004740907108686701
    }
  },
  "eros": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27433%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 218152656.0367733,
      "eccentricity": 0.2228518228719326,
      "inclinationRad": 0.5373523236310609,
      "ascendingNodeRad": 5.975009968278837,
      "argumentOfPeriapsisRad": 2.425386835869384,
      "meanAnomalyAtEpochRad": 1.9311121966209601,
      "meanMotionRadPerDay": 0.009768520722574765
    }
  },
  "itokawa": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%2725143%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 198081254.0762722,
      "eccentricity": 0.2801452299666735,
      "inclinationRad": 0.4199817908053783,
      "ascendingNodeRad": 0.06484320167824523,
      "argumentOfPeriapsisRad": 3.988261881102914,
      "meanAnomalyAtEpochRad": 3.9495529360009645,
      "meanMotionRadPerDay": 0.01129027432162477
    }
  },
  "bennu": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27101955%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 168434643.7391782,
      "eccentricity": 0.2036779989413211,
      "inclinationRad": 0.514338910352613,
      "ascendingNodeRad": 0.007331634255098149,
      "argumentOfPeriapsisRad": 1.1866717037229826,
      "meanAnomalyAtEpochRad": 2.502985135056867,
      "meanMotionRadPerDay": 0.014398671584115664
    }
  },
  "ryugu": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27162173%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 178156966.6407499,
      "eccentricity": 0.191045050637039,
      "inclinationRad": 0.38786290766569487,
      "ascendingNodeRad": 6.024339953664644,
      "argumentOfPeriapsisRad": 2.034648998185454,
      "meanAnomalyAtEpochRad": 2.2264734587205286,
      "meanMotionRadPerDay": 0.013236261696412763
    }
  },
  "ida": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27243%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 428227850.1923914,
      "eccentricity": 0.04616448944575747,
      "inclinationRad": 0.42511042456400683,
      "ascendingNodeRad": 6.25475656479662,
      "argumentOfPeriapsisRad": 1.3584324087644835,
      "meanAnomalyAtEpochRad": 1.1793401613664845,
      "meanMotionRadPerDay": 0.003551871100818331
    }
  },
  "gaspra": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27951%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 330550195.6427701,
      "eccentricity": 0.1738926259725353,
      "inclinationRad": 0.393759454228351,
      "ascendingNodeRad": 6.103851933477968,
      "argumentOfPeriapsisRad": 0.5653445348175159,
      "meanAnomalyAtEpochRad": 2.422395861017539,
      "meanMotionRadPerDay": 0.0052373721167424565
    }
  },
  "mathilde": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27253%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 395995778.8622339,
      "eccentricity": 0.2643618862750068,
      "inclinationRad": 0.29145750923914276,
      "ascendingNodeRad": 0.0036128293358736554,
      "argumentOfPeriapsisRad": 5.879157515755841,
      "meanAnomalyAtEpochRad": 5.117847950673388,
      "meanMotionRadPerDay": 0.0039942360281778645
    }
  },
  "lutetia": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%2721%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 364208318.1601056,
      "eccentricity": 0.164793711438368,
      "inclinationRad": 0.42074609249306666,
      "ascendingNodeRad": 0.129576148031942,
      "argumentOfPeriapsisRad": 5.653201103528145,
      "meanAnomalyAtEpochRad": 5.604337396766025,
      "meanMotionRadPerDay": 0.004528399866387203
    }
  },
  "steins": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%272867%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 353530724.3909022,
      "eccentricity": 0.1468217649089243,
      "inclinationRad": 0.5262091008737869,
      "ascendingNodeRad": 0.2859848524182343,
      "argumentOfPeriapsisRad": 5.097274036108311,
      "meanAnomalyAtEpochRad": 5.214100931795791,
      "meanMotionRadPerDay": 0.004735096288897001
    }
  },
  "didymos": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%2765803%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 245755226.3516789,
      "eccentricity": 0.3831095842544825,
      "inclinationRad": 0.43010247263357104,
      "ascendingNodeRad": 0.13698763891758428,
      "argumentOfPeriapsisRad": 0.4431500052276978,
      "meanAnomalyAtEpochRad": 5.255612258468524,
      "meanMotionRadPerDay": 0.008169875074163675
    }
  },
  "kleopatra": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27216%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 418185540.2158697,
      "eccentricity": 0.2501294725593166,
      "inclinationRad": 0.25679864268705427,
      "ascendingNodeRad": 5.740610341002806,
      "argumentOfPeriapsisRad": 1.1276149306311842,
      "meanAnomalyAtEpochRad": 4.85202372339527,
      "meanMotionRadPerDay": 0.0036805781335163996
    }
  },
  "toutatis": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%274179%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 380435723.6137681,
      "eccentricity": 0.624593306583785,
      "inclinationRad": 0.4046141629939425,
      "ascendingNodeRad": 0.01620131644151384,
      "argumentOfPeriapsisRad": 0.7395425180638752,
      "meanAnomalyAtEpochRad": 2.555625513721982,
      "meanMotionRadPerDay": 0.004241774946887509
    }
  },
  "pallas": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%272%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 414298050.9469351,
      "eccentricity": 0.2307039180980224,
      "inclinationRad": 0.2092293442452665,
      "ascendingNodeRad": 2.7932020818479297,
      "argumentOfPeriapsisRad": 5.66711013061156,
      "meanAnomalyAtEpochRad": 4.75819916824603,
      "meanMotionRadPerDay": 0.003732503505592261
    }
  },
  "hygiea": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%2710%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 471369499.2946311,
      "eccentricity": 0.106208457934494,
      "inclinationRad": 0.42891506637467874,
      "ascendingNodeRad": 6.1262438095406635,
      "argumentOfPeriapsisRad": 4.255501583354545,
      "meanAnomalyAtEpochRad": 4.661214672896547,
      "meanMotionRadPerDay": 0.00307558223343509
    }
  },
  "juno": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%273%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 399578971.1877511,
      "eccentricity": 0.2556642677508948,
      "inclinationRad": 0.1900437402970651,
      "ascendingNodeRad": 0.21204916964208986,
      "argumentOfPeriapsisRad": 0.8032366731871569,
      "meanAnomalyAtEpochRad": 4.924423632497095,
      "meanMotionRadPerDay": 0.0039406296708299066
    }
  },
  "psyche": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%2716%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 437743715.2126479,
      "eccentricity": 0.1352790628797994,
      "inclinationRad": 0.3632044910186994,
      "ascendingNodeRad": 0.07628060562792996,
      "argumentOfPeriapsisRad": 0.27949434426536507,
      "meanAnomalyAtEpochRad": 1.6861127642341796,
      "meanMotionRadPerDay": 0.0034366846272664915
    }
  }
} satisfies Record<string, {query: string; elements: KeplerianElements}>
