// Generated by tools/generate-asteroids.mjs. Do not edit.
// JPL Horizons, heliocentric ICRF; epoch 2026-09-03. TDB is approximated as TT (under 2 ms).
import type { KeplerianElements } from '../kepler.js'
export const ASTEROID_ELEMENTS_5 = {
  "ixion": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%2728978%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": { "epochJdTt": 2461286.5, "semiMajorAxisKm": 5886824805.784227, "eccentricity": 0.2433614704963976, "inclinationRad": 0.6083327295123849, "ascendingNodeRad": 0.5905809153270738, "argumentOfPeriapsisRad": 5.96478239853011, "meanAnomalyAtEpochRad": 5.154549493886427, "meanMotionRadPerDay": 0.00006968637806002992 }
  },
  "huya": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%2738628%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": { "epochJdTt": 2461286.5, "semiMajorAxisKm": 5874730748.893751, "eccentricity": 0.2740796874132537, "inclinationRad": 0.1517491233189223, "ascendingNodeRad": 0.3347326109900191, "argumentOfPeriapsisRad": 3.807653610902565, "meanAnomalyAtEpochRad": 0.29954780317623186, "meanMotionRadPerDay": 0.00006990167932128004 }
  },
  "asteroid-2003-vs2": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%2784922%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": { "epochJdTt": 2461286.5, "semiMajorAxisKm": 5935874101.43714, "eccentricity": 0.08037471109618877, "inclinationRad": 0.5874857752972727, "ascendingNodeRad": 5.886441524007453, "argumentOfPeriapsisRad": 1.3668989859102614, "meanAnomalyAtEpochRad": 0.5189280466748213, "meanMotionRadPerDay": 0.00006882441647547886 }
  },
  "asteroid-2002-tc302": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%2784522%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": { "epochJdTt": 2461286.5, "semiMajorAxisKm": 8338647010.898899, "eccentricity": 0.2988623680599504, "inclinationRad": 0.9974944864074645, "ascendingNodeRad": 0.28001297651560025, "argumentOfPeriapsisRad": 1.6993597451740687, "meanAnomalyAtEpochRad": 5.797780944146898, "meanMotionRadPerDay": 0.0000413357835919822 }
  },
  "asteroid-2002-tx300": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%2755636%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": { "epochJdTt": 2461286.5, "semiMajorAxisKm": 6490882692.44619, "eccentricity": 0.1210826820484857, "inclinationRad": 0.817563773519545, "ascendingNodeRad": 5.930447449487393, "argumentOfPeriapsisRad": 5.64321145295147, "meanAnomalyAtEpochRad": 1.4763964203973572, "meanMotionRadPerDay": 0.000060188555288798626 }
  },
  "deedee": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%272014+UZ224%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": { "epochJdTt": 2461286.5, "semiMajorAxisKm": 16403330408.75162, "eccentricity": 0.6491581096539483, "inclinationRad": 0.35636437344928973, "ascendingNodeRad": 1.3311861561611606, "argumentOfPeriapsisRad": 1.5333569541984338, "meanAnomalyAtEpochRad": 5.6508391362031265, "meanMotionRadPerDay": 0.000014982059249137538 }
  }
} satisfies Record<string, {query: string; elements: KeplerianElements}>
