// Generated by tools/generate-asteroids.mjs. Do not edit.
// JPL Horizons, heliocentric ICRF; epoch 2026-09-03. TDB is approximated as TT (under 2 ms).
import type { KeplerianElements } from '../kepler.js'
import { ASTEROID_ELEMENTS_1 } from './asteroidElements-1.data.js'
import { ASTEROID_ELEMENTS_2 } from './asteroidElements-2.data.js'
import { ASTEROID_ELEMENTS_3 } from './asteroidElements-3.data.js'
import { ASTEROID_ELEMENTS_4 } from './asteroidElements-4.data.js'

export const ASTEROID_ELEMENTS = {
  ...ASTEROID_ELEMENTS_1,
  ...ASTEROID_ELEMENTS_2,
  ...ASTEROID_ELEMENTS_3,
  ...ASTEROID_ELEMENTS_4,
} satisfies Record<string, {query: string; elements: KeplerianElements}>
