// Generated by tools/generate-comets.mjs. Do not edit.
// JPL Horizons, heliocentric ICRF; epoch 2026-09-03. TDB is approximated as TT (under 2 ms).
import type { KeplerianElements } from '../kepler.js'
export const COMET_ELEMENTS = {
  "comet-67p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D67P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 517457775.964017,
      "eccentricity": 0.649500606688622,
      "inclinationRad": 0.4651023102990574,
      "ascendingNodeRad": 0.08909430897751994,
      "argumentOfPeriapsisRad": 0.9407123849046125,
      "meanAnomalyAtEpochRad": 4.720146165629012,
      "meanMotionRadPerDay": 0.0026739740187083326
    }
  },
  "comet-103p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D103P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 520091230.1888589,
      "eccentricity": 0.6930749113280099,
      "inclinationRad": 0.27044094852158845,
      "ascendingNodeRad": 5.685242088603389,
      "argumentOfPeriapsisRad": 1.2841931240460038,
      "meanAnomalyAtEpochRad": 2.8048181852335885,
      "meanMotionRadPerDay": 0.0026536904617999787
    }
  },
  "comet-9p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D9P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 494463131.3416593,
      "eccentricity": 0.4650861803315108,
      "inclinationRad": 0.508025658699576,
      "ascendingNodeRad": 0.3506041571019779,
      "argumentOfPeriapsisRad": 4.072228291215336,
      "meanAnomalyAtEpochRad": 4.775241161972018,
      "meanMotionRadPerDay": 0.002862652865708085
    }
  },
  "comet-81p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D81P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 516140872.3134995,
      "eccentricity": 0.5381149425846179,
      "inclinationRad": 0.3703158125659412,
      "ascendingNodeRad": 0.10844161692070235,
      "argumentOfPeriapsisRad": 3.0005076824537538,
      "meanAnomalyAtEpochRad": 3.6405540595306167,
      "meanMotionRadPerDay": 0.00268421427923224
    }
  },
  "comet-1p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D1P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 2671731646.301095,
      "eccentricity": 0.9680223772461172,
      "inclinationRad": 2.780866707620557,
      "ascendingNodeRad": 2.3008355977493737,
      "argumentOfPeriapsisRad": 3.2790938595511947,
      "meanAnomalyAtEpochRad": 3.3761493625927756,
      "meanMotionRadPerDay": 0.00022791888287730061
    }
  },
  "comet-8p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D8P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 853719822.6913047,
      "eccentricity": 0.8207472932534728,
      "inclinationRad": 1.0174340149135428,
      "ascendingNodeRad": 4.987042077216135,
      "argumentOfPeriapsisRad": 3.134735656548832,
      "meanAnomalyAtEpochRad": 2.3099389373351933,
      "meanMotionRadPerDay": 0.0012618173983111104
    }
  },
  "comet-19p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D19P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 539894127.7220751,
      "eccentricity": 0.637453325548034,
      "inclinationRad": 0.7270674696332426,
      "ascendingNodeRad": 0.7874463180154027,
      "argumentOfPeriapsisRad": 0.47437659436456125,
      "meanAnomalyAtEpochRad": 4.199034138463935,
      "meanMotionRadPerDay": 0.002509034620289767
    }
  }
} satisfies Record<string, {query: string; elements: KeplerianElements}>
