// Generated by tools/generate-comets.mjs. Do not edit.
// JPL Horizons, heliocentric ICRF; epoch 2026-09-03. TDB is approximated as TT (under 2 ms).
import type { KeplerianElements } from '../kepler.js'
export const COMET_ELEMENTS = {
  "comet-67p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D67P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 517457775.964017,
      "eccentricity": 0.649500606688622,
      "inclinationRad": 0.4651023102990574,
      "ascendingNodeRad": 0.08909430897751994,
      "argumentOfPeriapsisRad": 0.9407123849046125,
      "meanAnomalyAtEpochRad": 4.720146165629012,
      "meanMotionRadPerDay": 0.0026739740187083326
    }
  },
  "comet-103p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D103P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 520091230.1888589,
      "eccentricity": 0.6930749113280099,
      "inclinationRad": 0.27044094852158845,
      "ascendingNodeRad": 5.685242088603389,
      "argumentOfPeriapsisRad": 1.2841931240460038,
      "meanAnomalyAtEpochRad": 2.8048181852335885,
      "meanMotionRadPerDay": 0.0026536904617999787
    }
  },
  "comet-9p": {
    "query": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27DES%3D9P%3BCAP%3B%27&OBJ_DATA=NO&MAKE_EPHEM=YES&EPHEM_TYPE=ELEMENTS&CENTER=%27500%4010%27&START_TIME=%27JD2461286.5%27&STOP_TIME=%27JD2461287.5%27&STEP_SIZE=%271d%27&TIME_TYPE=TDB&OUT_UNITS=KM-D&REF_PLANE=FRAME&REF_SYSTEM=ICRF&CSV_FORMAT=YES",
    "elements": {
      "epochJdTt": 2461286.5,
      "semiMajorAxisKm": 494463131.3416593,
      "eccentricity": 0.4650861803315108,
      "inclinationRad": 0.508025658699576,
      "ascendingNodeRad": 0.3506041571019779,
      "argumentOfPeriapsisRad": 4.072228291215336,
      "meanAnomalyAtEpochRad": 4.775241161972018,
      "meanMotionRadPerDay": 0.002862652865708085
    }
  }
} satisfies Record<string, {query: string; elements: KeplerianElements}>
