// Generated by tools/generate-scene-satellites.mjs from validated object-owned source states.
import type { SceneSatelliteRecord } from '../sceneSatellites.js'

export const SCENE_SATELLITE_STATES = {
  "hiiaka": {
    "epochJdTt": 2461286.5,
    "positionKm": [
      -33281.96333993582,
      -22828.13175945297,
      -33532.59403386706
    ],
    "velocityKmPerDay": [
      -4057.630802926777,
      -409.3179756773064,
      4337.365604762798
    ],
    "centerBodyId": "haumea",
    "gravitationalParametersKm3PerS2": {
      "body": 1.151,
      "parent": 264.413,
      "combined": 265.564
    },
    "systemGmKm3PerS2": 265.564,
    "parentHeliocentricState": {
      "positionKm": [
        -5487487239.17944,
        -4698328457.056636,
        1797316425.25533
      ],
      "velocityKmPerDay": [
        210094.2578290008,
        -230096.3537848578,
        -123974.8700480089
      ],
      "provenance": {
        "model": "Horizons geometric state at prepared epoch",
        "epochJdTt": 2461286.5,
        "referenceFrame": "ICRF",
        "target": 920136108,
        "center": 10,
        "source": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=920136108&CENTER=500%4010&EPHEM_TYPE=VECTORS&TIME_TYPE=UT&REF_PLANE=FRAME&REF_SYSTEM=ICRF&OUT_UNITS=KM-D&VEC_CORR=NONE&VEC_TABLE=2&CSV_FORMAT=YES&TLIST_TYPE=JD&TLIST=2461286.499199259",
        "sourcePath": "src/planets/hiiaka/source/orbit/haumea-epoch.txt",
        "sha256": "3337cf80561af77c3a24e634c5f0a58a258197b55a8c9faad3f43f8113c6d08f",
        "solution": "tnosat_v001b_20136108_jpl110_20221014",
        "limitations": [
          "Horizons solution uses 33 observations from 2005–2008 and reports a 900 km primary-relative position uncertainty at 2025-Jan-01; this is not a measured uncertainty at the 2026 scene epoch.",
          "This is the retained JPL solution, not the newer Proudfoot et al. 2024 interacting solution; phase accuracy is limited.",
          "The solution GM values define this orbit calculation and are separate from the occultation shape/size measurements."
        ],
        "timeQualification": "UTC request converted to the exact TT scene epoch using TT−UTC = 69.184 s; no extrapolation."
      }
    },
    "provenance": {
      "model": "Horizons geometric state at prepared epoch",
      "epochJdTt": 2461286.5,
      "referenceFrame": "ICRF",
      "target": 120136108,
      "center": 920136108,
      "source": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=120136108&CENTER=500%40920136108&EPHEM_TYPE=VECTORS&TIME_TYPE=UT&REF_PLANE=FRAME&REF_SYSTEM=ICRF&OUT_UNITS=KM-D&VEC_CORR=NONE&VEC_TABLE=2&CSV_FORMAT=YES&TLIST_TYPE=JD&TLIST=2461286.499199259",
      "sourcePath": "src/planets/hiiaka/source/orbit/hiiaka-epoch.txt",
      "sha256": "5c2d93c8540488799fa2e147849419e234138732a845c479b24af0385b608288",
      "solution": "tnosat_v001b_20136108_jpl110_20221014",
      "limitations": [
        "Horizons solution uses 33 observations from 2005–2008 and reports a 900 km primary-relative position uncertainty at 2025-Jan-01; this is not a measured uncertainty at the 2026 scene epoch.",
        "This is the retained JPL solution, not the newer Proudfoot et al. 2024 interacting solution; phase accuracy is limited.",
        "The solution GM values define this orbit calculation and are separate from the occultation shape/size measurements."
      ],
      "timeQualification": "UTC request converted to the exact TT scene epoch using TT−UTC = 69.184 s; no extrapolation."
    }
  },
  "menoetius": {
    "epochJdTt": 2461286.5,
    "positionKm": [
      -646.3389934806856,
      157.1377313775592,
      182.9291042344346
    ],
    "velocityKmPerDay": [
      228.7920070413377,
      988.1548728191091,
      -54.07113307946982
    ],
    "centerBodyId": "patroclus",
    "gravitationalParametersKm3PerS2": {
      "body": 0.020917,
      "parent": 0.0740606,
      "combined": 0.09497760000000001
    },
    "systemGmKm3PerS2": 0.09497760000000001,
    "parentHeliocentricState": {
      "positionKm": [
        219530347.7320293,
        587045097.8743559,
        408156964.6816921
      ],
      "velocityKmPerDay": [
        -1023130.592430021,
        209778.8583424715,
        535080.2656559118
      ],
      "provenance": {
        "model": "Horizons geometric state at prepared epoch",
        "epochJdTt": 2461286.5,
        "referenceFrame": "ICRF",
        "target": 920000617,
        "center": 10,
        "source": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=920000617&CENTER=500%4010&EPHEM_TYPE=VECTORS&TIME_TYPE=UT&REF_PLANE=FRAME&REF_SYSTEM=ICRF&OUT_UNITS=KM-D&VEC_CORR=NONE&VEC_TABLE=2&CSV_FORMAT=YES&TLIST_TYPE=JD&TLIST=2461286.499199259",
        "sourcePath": "src/planets/menoetius/source/orbit/patroclus-epoch.txt",
        "sha256": "427924d795a0887115acb4ee033f42f7a2c254d63a9a2d6abe51b421c9132a97",
        "solution": "tnosat_v001_20000617_jpl082_20230601",
        "limitations": [
          "The JPL satellite solution uses its own JPL#82 barycenter, not the current integrated 617; orbit.",
          "The response contains no covariance or scene-epoch uncertainty bound; do not infer one from printed digits.",
          "The primary response contains an inconsistent satellite provisional-designation note; target and center numeric IDs plus the Menoetius response establish identity."
        ],
        "timeQualification": "UTC request converted to the exact TT scene epoch using TT−UTC = 69.184 s; no extrapolation."
      }
    },
    "provenance": {
      "model": "Horizons geometric state at prepared epoch",
      "epochJdTt": 2461286.5,
      "referenceFrame": "ICRF",
      "target": 120000617,
      "center": 920000617,
      "source": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=120000617&CENTER=500%40920000617&EPHEM_TYPE=VECTORS&TIME_TYPE=UT&REF_PLANE=FRAME&REF_SYSTEM=ICRF&OUT_UNITS=KM-D&VEC_CORR=NONE&VEC_TABLE=2&CSV_FORMAT=YES&TLIST_TYPE=JD&TLIST=2461286.499199259",
      "sourcePath": "src/planets/menoetius/source/orbit/menoetius-epoch.txt",
      "sha256": "f6469c4b2b71cf87e87f1965c8dccf57960669e0843fae1928f41a66d1b38b9b",
      "solution": "tnosat_v001_20000617_jpl082_20230601",
      "limitations": [
        "The JPL satellite solution uses its own JPL#82 barycenter, not the current integrated 617; orbit.",
        "The response contains no covariance or scene-epoch uncertainty bound; do not infer one from printed digits.",
        "The primary response contains an inconsistent satellite provisional-designation note; target and center numeric IDs plus the Menoetius response establish identity."
      ],
      "timeQualification": "UTC request converted to the exact TT scene epoch using TT−UTC = 69.184 s; no extrapolation."
    }
  },
  "squannit": {
    "epochJdTt": 2461286.5,
    "positionKm": [
      -2.000074054122205,
      -1.1687593303004233,
      -1.0611359035782697
    ],
    "velocityKmPerDay": [
      -10.394350942443587,
      19.32329253062684,
      -1.6914014518029203
    ],
    "centerBodyId": "moshup",
    "gravitationalParametersKm3PerS2": {
      "body": 8.971515858775238e-9,
      "parent": 1.5637019863480103e-7,
      "combined": 1.6534171449357626e-7
    },
    "systemGmKm3PerS2": 1.6534171449357626e-7,
    "provenance": {
      "model": "Published mutual-orbit model evaluated once at prepared epoch",
      "epochJdTt": 2461286.5,
      "referenceFrame": "ICRF",
      "source": "https://arxiv.org/abs/1912.06456v2",
      "sourcePath": "src/planets/squannit/source/orbit/published-parameters.json",
      "sha256": "0061b2a8a915b03b9cd65cb4216fb757249ae868face4c8014e95cdbb86bb2bf",
      "timeQualification": "The paper defines JD 2455305.0 as asterocentric (light-time-corrected), without naming UTC/TT/TDB. This preparation treats that numerical epoch as TT; a clock-scale ambiguity up to 70 seconds contributes less than 0.41 degree of phase, separate from the much larger source-parameter/extrapolation uncertainty. No light-time correction is applied to the resulting geometric vector.",
      "limitations": [
        "The 2026 position extrapolates the 2000–2019 photometric drift fit. It is context, not an observed or precisely predicted current position.",
        "The sum of the individual phase-sensitivity ranges is about 55 degrees at this scene epoch; future drift changes and missing covariance can increase actual uncertainty.",
        "J2000 equatorial axes are treated as ICRF at this coarse precision; the small frame bias is negligible relative to source pole errors.",
        "No present-epoch attitude or libration prediction is inferred from this mutual orbit.",
        "The original 2006 Beta mesh scale is retained independently of the 2021 photometric preference for a secondary about 130% as large."
      ]
    }
  },
  "romulus": {
    "epochJdTt": 2461286.5,
    "positionKm": [
      169.91109416443356,
      1329.085919271818,
      -43.2342372805489
    ],
    "velocityKmPerDay": [
      -2275.493744412642,
      300.28342981731714,
      288.44839802409075
    ],
    "centerBodyId": "sylvia",
    "gravitationalParametersKm3PerS2": {
      "body": 0,
      "parent": 0.9610069228988848,
      "combined": 0.9610069228988848
    },
    "systemGmKm3PerS2": 0.9610069228988848,
    "parentHeliocentricState": {
      "positionKm": [
        -303715339.4835702,
        392807937.420781,
        259332875.2341258
      ],
      "velocityKmPerDay": [
        -1091984.678341611,
        -661020.912473434,
        -108839.3132098869
      ],
      "provenance": {
        "model": "Horizons numbered-asteroid geometric state at prepared epoch",
        "epochJdTt": 2461286.5,
        "referenceFrame": "ICRF",
        "target": 87,
        "targetKind": "numbered-asteroid",
        "center": 10,
        "source": "https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=87%3B&EPHEM_TYPE=VECTORS&TIME_TYPE=UT&REF_PLANE=FRAME&REF_SYSTEM=ICRF&OUT_UNITS=KM-D&VEC_TABLE=3&CSV_FORMAT=YES&TLIST_TYPE=JD&TLIST=2461286.499199259&CENTER=500%4010&VEC_CORR=NONE",
        "sourcePath": "src/planets/romulus/source/orbit/sylvia-heliocentric.txt",
        "sha256": "52d6187949be5192c1a56d5e47186335d05a6800c42a87f6cd3aa9408d795118",
        "qualification": [
          "This is an extrapolation of rounded 2021 published elements to 2026-09-03, beyond the retained 2002–2018 astrometry; current phase is approximate.",
          "The full model covariance and an explicit time scale for the printed pericenter epoch are absent. Quoted independent parameter uncertainties must not be treated as a scene covariance.",
          "The six independent Miriade 2024-solution projections differ by 23–63 mas, including about 42 mas (140 km on the sky plane) at the scene epoch; this is measured disagreement, not a guaranteed error bound.",
          "The printed parameters differ from six reported paper-fit positions by 7–62 mas with the documented geometric projection. The paper’s 9.85 mas fit RMS is not achieved or asserted for this illustration.",
          "Miriade permits orbit computation from 1990 to 2030, but its position-error service stops at 2026-Jan-01; empty errors at this scene date are unavailable, not zero.",
          "Sky-plane checks do not independently determine the line-of-sight component, and geocentric projection omits observatory parallax and differential aberration.",
          "No current phase offset is fitted; no continuous runtime ephemeris or out-of-epoch propagation is supported."
        ]
      }
    },
    "provenance": {
      "model": "Published mutual-orbit model evaluated once at prepared epoch",
      "epochJdTt": 2461286.5,
      "referenceFrame": "ICRF",
      "source": "https://www.aanda.org/articles/aa/pdf/2021/06/aa40342-21.pdf",
      "sourcePath": "src/planets/romulus/source/orbit/published-parameters.json",
      "sha256": "8a1e50f6040b207756bec082d48d03537da1dcc8a466a5b363e184e73b4e6362",
      "timeQualification": "Table 3 labels tp as JD without a time scale. TT is an explicit preparation convention; the CDS observed timestamps are UTC. Choosing UTC instead would shift this phase by about one minute, smaller than the quoted 0.10085-day epoch uncertainty, but this does not establish a source-owned exact time scale.",
      "limitations": [
        "This is an extrapolation of rounded 2021 published elements to 2026-09-03, beyond the retained 2002–2018 astrometry; current phase is approximate.",
        "The full model covariance and an explicit time scale for the printed pericenter epoch are absent. Quoted independent parameter uncertainties must not be treated as a scene covariance.",
        "The six independent Miriade 2024-solution projections differ by 23–63 mas, including about 42 mas (140 km on the sky plane) at the scene epoch; this is measured disagreement, not a guaranteed error bound.",
        "The printed parameters differ from six reported paper-fit positions by 7–62 mas with the documented geometric projection. The paper’s 9.85 mas fit RMS is not achieved or asserted for this illustration.",
        "Miriade permits orbit computation from 1990 to 2030, but its position-error service stops at 2026-Jan-01; empty errors at this scene date are unavailable, not zero.",
        "Sky-plane checks do not independently determine the line-of-sight component, and geocentric projection omits observatory parallax and differential aberration.",
        "No current phase offset is fitted; no continuous runtime ephemeris or out-of-epoch propagation is supported."
      ]
    }
  }
} as const satisfies Record<string, SceneSatelliteRecord>
