// Generated by packages/astronomy/cli/generate-scene-satellites.mts from validated object-owned source states.
import type { SceneSatelliteRecord } from '../sceneSatellites.js'

export { SCENE_SATELLITE_STATES } from './generated/sceneSatellite.js'
