// The prepared catalogue: every navigable object once, as `prepare:catalog` writes it and the application registry
// (`site/objects.mts`) reads it. Preparation needs the same object list without the shell, so `readPreparedObjects` decodes
// the same entries with the same contracts and binds no scene loader. It is a read of the one registry, never a second list.
import { createRequire } from 'node:module';
import { resolve } from 'node:path';
import { isRecord } from '@cssearth/core';
import { catalogueObject, defineObjects, isHostedDescriptor, isPlacedObject, isSceneObject } from '../registry/index.js';
import type { NavigableObject, NavigationDistance, ObjectDiscovery, ObjectEntry, PlacedFields } from '../registry/index.js';

/** The catalogue files, relative to the checkout. `entries` is a module: each scene object's descriptor, as its folder's
 * object.json holds it, with its distance and discovery, then each package the world's host draws, in registry order. The overviews are apart because every
 * page's object directory reads them (`site/object-directory.mts`) and a page never loads the whole registry. */
export const PREPARED_CATALOGUE = Object.freeze({
  entries: 'site/prepared-catalogue.mjs',
  overviews: 'site/prepared-overview-objects.json',
});

/** One row of the prepared catalogue: a package's descriptor, with its distance and discovery when it is placed and the scene
 * that draws it when it has none of its own. Every object's row has this shape (`catalogueObject` reads it). */
export interface PreparedCatalogueRow { descriptor: unknown; distance?: NavigationDistance; discovery?: ObjectDiscovery; sceneHostId?: string }

/** The catalogue module `prepare:catalog` writes at `PREPARED_CATALOGUE.entries`. */
export function preparedCatalogueModule(rows: readonly PreparedCatalogueRow[]) {
  // Each descriptor is read here and written into the module as one JSON string: a module that imported every package's
  // object.json was 3,756 module requests, past the dev server's 60 s module-fetch limit (2026-09-30).
  return '// Generated by pnpm prepare:catalog. Edit each object.json.\n' +
    `export const CATALOGUE_ENTRIES = Object.freeze(JSON.parse(${JSON.stringify(JSON.stringify(rows))}));\n`;
}

/** A scene object as preparation sees it: every registry field, and a scene loader that refuses to mount. */
export type PreparedSceneObject = ObjectEntry<never, AbortSignal>;
export type PreparedNavigableObject = NavigableObject<never, AbortSignal>;
export interface PreparedObjectRegistry {
  /** The catalogue entries as written, then the overviews, in registry order. */
  readonly entries: readonly Readonly<Record<string, unknown>>[];
  /** Every navigable object, as `OBJECTS` lists them. */
  readonly objects: readonly PreparedNavigableObject[];
  /** The scene objects, as `SCENE_OBJECTS` lists them. */
  readonly sceneObjects: readonly PreparedSceneObject[];
  /** Every placed object the world draws: the scenes and the packages the world's host draws (galaxies, nebulae, clusters). */
  readonly worldObjects: readonly (PreparedNavigableObject & PlacedFields)[];
  requireSceneObject(id: string): PreparedSceneObject;
}

const registries = new Map<string, PreparedObjectRegistry>();

/** The registry of the checkout at `root`, read once per process. The catalogue is loaded as a module, as the application
 * registry loads it. */
export function readPreparedObjects(root: string): PreparedObjectRegistry {
  const checkout = resolve(root);
  let registry = registries.get(checkout);
  if (!registry) registries.set(checkout, registry = decodeRegistry(checkout));
  return registry;
}

function decodeRegistry(checkout: string): PreparedObjectRegistry {
  // Loaded on behalf of the application registry module, as that module imports it: the preparation trace then counts only
  // the registry fields of another body's descriptor it reached.
  const load = createRequire(resolve(checkout, 'site/objects.mts'));
  const module: unknown = load(resolve(checkout, PREPARED_CATALOGUE.entries));
  const catalogue = isRecord(module) ? module.CATALOGUE_ENTRIES : undefined;
  if (!Array.isArray(catalogue)) throw new TypeError(`Invalid prepared catalogue: ${PREPARED_CATALOGUE.entries} exports no CATALOGUE_ENTRIES array.`);
  const overviews: unknown = load(resolve(checkout, PREPARED_CATALOGUE.overviews));
  if (!Array.isArray(overviews)) throw new TypeError(`Invalid prepared catalogue overviews: ${PREPARED_CATALOGUE.overviews}.`);
  const entries: Readonly<Record<string, unknown>>[] = [...catalogue, ...overviews].map(entry => {
    if (!isRecord(entry)) throw new TypeError(`Invalid prepared catalogue entry in ${PREPARED_CATALOGUE.entries}.`);
    return entry;
  });
  const refuse = () => async (): Promise<never> => { throw new Error('Preparation cannot mount a scene.'); };
  const objects = defineObjects<PreparedNavigableObject>(entries.map(entry => catalogueObject<never, AbortSignal>(entry, refuse)));
  // Preparation's scene objects are the bodies its lanes bake. A bank package's body-less scene is written from its bank
  // (site/build/prepare/prepare-bank-scene.mts), so no body lane, marker or recipe reads it as one.
  const banks = new Set(entries.flatMap(entry => isHostedDescriptor(entry.descriptor) && isRecord(entry.descriptor) ? [entry.descriptor.id] : []));
  const sceneObjects = Object.freeze(objects.filter(isSceneObject).filter(object => !banks.has(object.id)));
  for (const object of objects) if (!isSceneObject(object) && !sceneObjects.some(host => host.id === object.sceneHostId)) {
    throw new TypeError(`Scene host is not a registered scene: ${object.id}`);
  }
  // Every object with a place in the world, whatever else it is.
  const worldObjects = Object.freeze(objects.filter(isPlacedObject));
  return Object.freeze({ entries: Object.freeze(entries), objects, sceneObjects, worldObjects, requireSceneObject(id: string) {
    const object = objects.find(candidate => candidate.id === id);
    if (!object) throw new Error(`Unknown cssEarth object: ${id}`);
    if (!isSceneObject(object) || banks.has(id)) throw new TypeError(`Object ${id} has no body of its own to prepare.`);
    return object;
  } });
}
