// The prepared catalogue: every navigable object once, as `prepare:catalog` writes it and the application registry
// (`site/objects.mts`) reads it. Preparation needs the same object list without the shell, so `readPreparedObjects` decodes
// the same entries with the same contracts and binds no scene loader. It is a read of the one registry, never a second list.
import { createRequire } from 'node:module';
import { resolve } from 'node:path';
import { isRecord } from '@cssearth/core';
import { catalogueObject, checkObjectTree, defineObjects } from '../registry/index.js';
import type { NavigableObject, NavigationDistance, ObjectDiscovery, ObjectEntry, WorldBody } from '../registry/index.js';

/** The catalogue file, relative to the checkout: a module of each object's descriptor, as its folder's object.json holds
 * it, with its distance and discovery, in registry order. A page never loads it: it reads one entry at a time. */
export const PREPARED_CATALOGUE = Object.freeze({
  entries: 'site/prepared-catalogue.mjs',
});

/** One row of the prepared catalogue: a package's descriptor with its distance and discovery. Every object's row has this
 * shape (`catalogueObject` reads it). */
export interface PreparedCatalogueRow { descriptor: unknown; distance?: NavigationDistance; discovery?: ObjectDiscovery }

/** The catalogue module `prepare:catalog` writes at `PREPARED_CATALOGUE.entries`. */
export function preparedCatalogueModule(rows: readonly PreparedCatalogueRow[]) {
  // Each descriptor is read here and written into the module as one JSON string: a module that imported every package's
  // object.json was 3,756 module requests, past the dev server's 60 s module-fetch limit (2026-09-30).
  return '// Generated by pnpm prepare:catalog. Edit each object.json.\n' +
    `export const CATALOGUE_ENTRIES = Object.freeze(JSON.parse(${JSON.stringify(JSON.stringify(rows))}));\n`;
}

/** A scene object as preparation sees it: every registry field, and a scene loader that refuses to mount. */
export type PreparedSceneObject = ObjectEntry<never, AbortSignal>;
export type PreparedNavigableObject = NavigableObject<never, AbortSignal>;
export interface PreparedObjectRegistry {
  /** The catalogue entries as written, in registry order. */
  readonly entries: readonly Readonly<Record<string, unknown>>[];
  /** Every object, as `OBJECTS` lists them, the systems included. */
  readonly objects: readonly PreparedNavigableObject[];
  /** The objects with a scene of their own, which the body lanes read: every object but a system. */
  readonly sceneObjects: readonly PreparedSceneObject[];
  /** What the world context draws and names: every object with a scene; a system's host stands for it. */
  readonly worldObjects: readonly WorldBody[];
  requireSceneObject(id: string): PreparedSceneObject;
}

const registries = new Map<string, PreparedObjectRegistry>();

/** The registry of the checkout at `root`, read once per process. The catalogue is loaded as a module, as the application
 * registry loads it. */
export function readPreparedObjects(root: string): PreparedObjectRegistry {
  const checkout = resolve(root);
  let registry = registries.get(checkout);
  if (!registry) registries.set(checkout, registry = decodeRegistry(checkout));
  return registry;
}

function decodeRegistry(checkout: string): PreparedObjectRegistry {
  // Loaded on behalf of the application registry module, as that module imports it: the preparation trace then counts only
  // the registry fields of another body's descriptor it reached.
  const load = createRequire(resolve(checkout, 'site/objects.mts'));
  const module: unknown = load(resolve(checkout, PREPARED_CATALOGUE.entries));
  const catalogue = isRecord(module) ? module.CATALOGUE_ENTRIES : undefined;
  if (!Array.isArray(catalogue)) throw new TypeError(`Invalid prepared catalogue: ${PREPARED_CATALOGUE.entries} exports no CATALOGUE_ENTRIES array.`);
  const rows = (list: readonly unknown[], path: string): Readonly<Record<string, unknown>>[] => list.map(entry => {
    if (!isRecord(entry)) throw new TypeError(`Invalid prepared catalogue entry in ${path}.`);
    return entry;
  });
  const entries = rows(catalogue, PREPARED_CATALOGUE.entries);
  const refuse = () => async (): Promise<never> => { throw new Error('Preparation cannot mount a scene.'); };
  const objects = defineObjects<PreparedNavigableObject>(entries.map(entry => catalogueObject<never, AbortSignal>(entry, refuse)));
  checkObjectTree(objects);
  // A system is an object with a page and an address, and nothing to prepare or place: it mounts its host's scene and
  // the world draws its host. Preparation steps that walk the scenes or the world's bodies do not see it.
  const scenes = Object.freeze(objects.filter(object => !object.system));
  const worldObjects = scenes;
  return Object.freeze({ entries: Object.freeze(entries), objects, sceneObjects: scenes, worldObjects, requireSceneObject(id: string) {
    const object = scenes.find(candidate => candidate.id === id);
    if (object) return object;
    throw new Error(`Unknown cssEarth object: ${id}`);
  } });
}
