/** Canonical cssEarth retained-volume binding shared by the lab's prepared viewers. */
import type { VolumeViewerBackend } from '@cssearth/volume-viewer/scene/backend';
import { mountPreparedCssVolume } from '../../../../../../../src/renderers/css/volume/prepared-volume-runtime';
import { validatePreparedCssVolume } from '../../../../../../../src/renderers/css/volume/validation';
import type { PreparedCssVolume, VolumeCameraPublication } from '../../../../../../../src/renderers/css/volume/types';
import { shapeCloudOrthographicCamera } from './shape-cloud-camera';
const legacyAngularFrame = (frame: PreparedCssVolume['frame']) => ['lab-sky-angular', 'lab-image-relative-unscaled'].includes(frame.referenceFrame);
/** Rename the runtime-only transported frame; source receipts retain their original frame and pins. */
export function physicalLabFrame(frame: PreparedCssVolume['frame']): PreparedCssVolume['frame'] {
  if (!legacyAngularFrame(frame)) return frame;
  return { ...frame, referenceFrame: frame.referenceFrame === 'lab-sky-angular' ? 'lab-sky-west-north-toward' : 'lab-image-west-north-toward',
    boundsUnits: { min: [frame.boundsUnits.min[0], frame.boundsUnits.min[1], -frame.boundsUnits.max[2]],
      max: [frame.boundsUnits.max[0], frame.boundsUnits.max[1], -frame.boundsUnits.min[2]] } };
}
/** Historical angular and image-relative Lab banks store source west/north/away coordinates. Transport their retained
 * matrices into the same physical west/north/toward basis as current prepared banks. No pixels,
 * vertices, texture layout, or correspondence are generated by this compatibility transport. */
export function physicalLabBank(bank: PreparedCssVolume): PreparedCssVolume {
  if (!legacyAngularFrame(bank.frame)) return bank;
  return { ...bank, frame: physicalLabFrame(bank.frame), stacks: bank.stacks.map(stack => ({ ...stack, ...(stack.normalUnits ? { normalUnits: [stack.normalUnits[0], stack.normalUnits[1], -stack.normalUnits[2]] as const } : {}), leaves: stack.leaves.map(leaf => {
    const match = /^matrix3d\(([^)]+)\)$/.exec(leaf.style.transform);
    const matrix = match?.[1]?.split(',').map(Number);
    if (!matrix || matrix.length !== 16 || !matrix.every(Number.isFinite)) throw new TypeError('Invalid historical compiler transform.');
    for (const index of [2, 6, 10, 14]) matrix[index] = -matrix[index]!;
    const b = leaf.boundsCssPixels;
    return { ...leaf, centerUnits: [leaf.centerUnits[0], leaf.centerUnits[1], -leaf.centerUnits[2]] as const,
      ...(b ? { boundsCssPixels: { min: [b.min[0], b.min[1], -b.max[2]] as const, max: [b.max[0], b.max[1], -b.min[2]] as const } } : {}),
      style: { ...leaf.style, transform: `matrix3d(${matrix.join(',')})` } };
  }) })) };
}

export const volumeRenderer: VolumeViewerBackend<PreparedCssVolume, VolumeCameraPublication> = {
  validateBank: validatePreparedCssVolume,
  resources: bank => bank.resources,
  frame: bank => bank.frame,
  texturePaths: bank => (['x', 'y', 'z'] as const).flatMap(axis => bank.stacks.find(stack => stack.axis === axis)!
    .leaves.map(leaf => leaf.texturePath)),
  mount(host, before, payload, resolveResource) {
    const mounted = mountPreparedCssVolume({ host, before, payload: physicalLabBank(payload), resolveResource });
    const cameras = [...host.querySelectorAll<HTMLElement>('.css-volume-camera')];
    const scenes = [...host.querySelectorAll<HTMLElement>('.css-volume-scene')];
    const materials = mounted.roots.flatMap((axisRoot, index) => {
      const axis = (['x', 'y', 'z'] as const)[index]!, stack = payload.stacks.find(item => item.axis === axis)!;
      const nodes = [...axisRoot.querySelectorAll<HTMLElement>('.css-volume-mesh s')];
      if (nodes.length !== stack.leaves.length * 3) throw new Error('Compiler leaves do not match the prepared material layout.');
      return stack.leaves.map((leaf, leafIndex) => ({ nodes: nodes.slice(leafIndex * 3, leafIndex * 3 + 3), texturePath: leaf.texturePath }));
    });
    return { materials, setTextures: urls => mounted.setTextures(urls),
      publish(camera) {
        mounted.publish({ world: camera.publication.world, viewport: { focalPixels: camera.publication.viewport.focalPixels,
          principalOffsetPixels: camera.publication.viewport.principalOffsetPixels } });
        for (const node of cameras) node.style.perspective = 'none';
        for (const node of scenes) node.style.transform = camera.transform;
      },
      destroy() { mounted.destroy(); },
    };
  },
  camera(frame, image, viewport, framing, yaw, pitch) { return shapeCloudOrthographicCamera(physicalLabFrame(frame), image, viewport, framing, yaw, pitch); },
};
