/** The archive clients, reducers and ledger builders are generic: which shipped bodies a ledger names or searches by name is data
 * beside that archive's programs or code (`src/archives/<archive>/`), never a string or key
 * in this package's code.
 *
 * This is a heuristic scan, not a proof. It catches a shipped id written as a whole string or template segment, as any word of
 * one (paths, queries, space-separated lists, sentences), as the leading parts of a hyphenated word (a program id built on a
 * body id, `comet-1p-nnsn1121`) and as a property key, quoted or not, in any case. It does not catch a
 * name it cannot see as one id: a multi-word spelling ('WASP-43 b', 'Alpha Centauri A'), a name built from pieces, or one read
 * from anywhere but this package's code. The exemptions below are holes by design: an exact listed string (a label, a guide
 * sentence) may name its listed ids, and a listed field is exempt on its owning type. Every exemption names one module and an
 * exact site, never a word or a whole module. */
import assert from 'node:assert/strict';
import { readdir, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import test from 'node:test';
import ts from 'typescript';
import { WORKSPACE } from '@cssearth/telescope/node';
// Plain node:test, not sourceTest: the scan reads only tracked code and body directory names, and an offender quoting an
// unrestored-input message ("is not restored", "not installed") must fail rather than turn the guard into a skip.

/** Ledger and program field names that are ordinary words and also a shipped id, by module, owning type and exact spelling. The
 * exemption covers only that type's member and the properties of an object literal written as that type (a `: Type` variable,
 * `satisfies Type` or `as Type`, `Omit<Type, …>` included), quoted or not; any other key with the same spelling still counts.
 * A Gemini Galilean row's `moon` is the member of the focus group it describes and is part of the published ledger; an HST
 * slit-scan program's Horizons `sun` is the illumination source it queries and is part of its program files. A TSO program's `S2`
 * is Eureka!'s Stage 2 control file. */
const FIELDS = [
  { module: 'gemini/archive-ledger.mts', owner: 'MoonRow', field: 'moon' },
  { module: 'hst/slit-scan-reduction.mts', owner: 'ScanHorizons', field: 'sun' },
  // Eureka!'s Stage 2, not the star S2 around Sgr A*.
  { module: 'jwst/reduce-tso.mts', owner: 'TsoStages', field: 'S2' },
] as const;

/** Strings that must keep a word that is also a shipped id, by module and an excerpt of their text, with the ids they may
 * name: guide and ledger sentences whose rendered pages stay byte-identical, embedded Python and shell whose `astropy.io` or
 * `echo` is a library or command, and validation labels. An excerpt of up to 24 characters is the whole string; a longer one
 * is a passage the string contains. Such a string may name its listed ids and no other. */
const PROSE: Readonly<Record<string, readonly { readonly excerpt: string; readonly ids: readonly string[] }[]>> = {
  'hst/psf-subtract.mts': [
    { excerpt: 'from astropy.io import fits', ids: ['io'] }, // embedded Python: astropy.io
  ],
  'hst/slit-scan-reduction.mts': [
    { excerpt: 'An IAU pole model names its NAIF body code.', ids: ['iau'] }, // IAU pole model error
    { excerpt: 'The rotation model is an IAU text PCK.', ids: ['iau'] }, // IAU text PCK error
    { excerpt: 'sun', ids: ['sun'] }, // label of the listed sun field
    { excerpt: 'iau-pck', ids: ['iau'] }, // IAU text PCK kind
  ],
  // The Juno archive and spacecraft share their name with the shipped asteroid 3 Juno: the archive's own paths, PDS volume root,
  // telescope name and software name say Juno the mission, never the body.
  'programs.mts': [
    { excerpt: 'juno', ids: ['juno'] }, // the Juno archive's name among the moved archives
  ],
  'juno/archive-ledger.mts': [
    { excerpt: 'Generated by `node packages/telescope-cli/src/archives/juno/archive-ledger.mts`', ids: ['juno'] }, // guide: generator and ledger paths
    { excerpt: 'data/juno/ledger.json', ids: ['juno'] }, // ledger path
  ],
  'juno/archive.mts': [
    { excerpt: 'https://planetarydata.jpl.nasa.gov/img/data/juno/', ids: ['juno'] }, // PDS Juno volume root
    { excerpt: 'juno', ids: ['juno'] }, // kernel bank name; the archive whose programs are read
  ],
  'juno/measure.mts': [
    { excerpt: 'cssearth tools/objects/juno/measure.mts', ids: ['juno'] }, // software name: the identity serialized before the archive code moved into telescope-cli
    { excerpt: 'Juno', ids: ['juno'] }, // telescope name in the run record
    { excerpt: "Each image's lit limb was fitted to the target's IAU ellipsoid", ids: ['iau'] }, // registration evidence sentence
    { excerpt: ', the triaxial IAU ellipsoid the text PCK states', ids: ['iau'] }, // IAU ellipsoid note
  ],
  'jwst/archive-ledger.mts': [
    { excerpt: "WASP-43b's NIRSpec map is fitted from the authors' deposited light curve", ids: ['wasp-43b'] }, // JWST mode note
    { excerpt: '## Limits\n\n- A target is matched by the name its proposer typed', ids: ['titan', 'dione', 'moon'] }, // JWST guide Limits section
  ],
  'jwst/cubes/resolution.mts': [
    { excerpt: 'from astropy.io import fits', ids: ['io'] }, // embedded Python: astropy.io
  ],
  'jwst/reduce-tso.mts': [
    { excerpt: 'S2_', ids: ['s2'] }, // Eureka! Stage 2 control-file name prefix
  ],
  'jwst/klip/reduce.mts': [
    { excerpt: 'from astropy.io import fits', ids: ['io'] }, // embedded Python: astropy.io
  ],
  'keck/archive-ledger.mts': [
    { excerpt: 'KOA publishes only JPEG quick-looks for DEIMOS', ids: ['deimos'] }, // Keck DEIMOS mode note
    { excerpt: 'KAI 2.0.1 (2026-08-18) is BSD-3-Clause', ids: ['europa'] }, // Keck KAI mode note
    { excerpt: 'PypeIt 2.0.1 supports keck_nirspec_high', ids: ['europa'] }, // Keck PypeIt mode note
    { excerpt: "carrying the same number, so 52 Europa is not Jupiter's moon.", ids: ['europa', 'jupiter', 'moon'] }, // Keck guide: minor-planet numbers
  ],
  'naco/archive-ledger.mts': [
    { excerpt: " of this project's objects appear as a NACO science target.", ids: ['europa'] }, // NACO guide intro
  ],
  // The Julia language's release folder, not the asteroid 89 Julia.
  'interferometry/toolchain.mts': [
    { excerpt: 'julia-1.12.7', ids: ['julia'] }, // the unpacked Julia 1.12.7 release
  ],
  'naco/reduce.mts': [
    { excerpt: ' 2>/dev/null && echo applied', ids: ['echo'] }, // shell echo
  ],
};
/** The ids a string of a module may name: those of every listed excerpt it is (up to 24 characters) or contains (longer). */
const allowedIds = (file: string, text: string): readonly string[] => (PROSE[file] ?? [])
  .filter(entry => entry.excerpt.length > 24 ? text.includes(entry.excerpt) : text === entry.excerpt).flatMap(entry => entry.ids);

/** Every leading run of a hyphenated word's parts: a program id built on a body id (`comet-1p-nnsn1121`) names that body. */
const hyphenPrefixes = (word: string) => word.split('-').slice(1).map((_, index, rest) => word.split('-').slice(0, index + 1).join('-'))
  .filter(prefix => prefix.length > 0 && prefix !== word);
const compact = (text: string) => text.toLowerCase().replace(/[^a-z0-9]/gu, '');
const PROPERTY_NAMES = [ts.isPropertyAssignment, ts.isShorthandPropertyAssignment, ts.isPropertySignature, ts.isPropertyDeclaration,
  ts.isMethodDeclaration, ts.isEnumMember, ts.isGetAccessor, ts.isSetAccessor] as const;

/** Whether a type annotation refers to `owner` (`MoonRow`, `Omit<MoonRow, 'frames'>`, `readonly MoonRow[]`). */
function mentionsType(type: ts.TypeNode | undefined, owner: string): boolean {
  let found = false;
  const visit = (node: ts.Node): void => {
    if (ts.isTypeReferenceNode(node) && ts.isIdentifier(node.typeName) && node.typeName.text === owner) found = true;
    ts.forEachChild(node, visit);
  };
  if (type) visit(type);
  return found;
}

/** The type a property's name belongs to, written in the code: the interface or type alias that declares it, or the annotation an
 * object literal holding it is written as. */
function isMemberOf(property: ts.Node, owner: string): boolean {
  const holder = property.parent;
  if (ts.isInterfaceDeclaration(holder)) return holder.name.text === owner;
  if (ts.isTypeLiteralNode(holder)) return ts.isTypeAliasDeclaration(holder.parent) && holder.parent.name.text === owner;
  if (!ts.isObjectLiteralExpression(holder)) return false;
  let expression: ts.Node = holder.parent;
  while (ts.isParenthesizedExpression(expression)) expression = expression.parent;
  if (ts.isSatisfiesExpression(expression) || ts.isAsExpression(expression)) return mentionsType(expression.type, owner);
  return ts.isVariableDeclaration(expression) && mentionsType(expression.type, owner);
}

/** Every shipped id a module's code names, in any case: as a whole string literal or template-literal segment, as any word of one
 * (a path, a query, a list split on spaces, a sentence), or as a property key, quoted or not (`MERCURY:`, `{ europa }`,
 * `'io':`). A URL's host is a site, not a name. Comments are not code. */
function bodyMentions(file: string, text: string, bodies: ReadonlySet<string>): string[] {
  const byCompact = new Map([...bodies].map(id => [compact(id), id]));
  const exemptField = (name: ts.Node, spelling: string) => PROPERTY_NAMES.some(is => is(name.parent)) && (name.parent as ts.NamedDeclaration).name === name
    && FIELDS.some(entry => entry.module === file && entry.field === spelling && isMemberOf(name.parent, entry.owner));
  const found: string[] = [];
  const visit = (node: ts.Node): void => {
    if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node) || ts.isTemplateHead(node) || ts.isTemplateMiddle(node) || ts.isTemplateTail(node)) {
      const lower = node.text.trim().toLowerCase();
      const unhosted = lower.replace(/\b[a-z][a-z0-9+.-]*:\/\/[^/?#\s]*/gu, ' ');
      const words = [lower, ...unhosted.split(/[^a-z0-9_-]+/u).map(part => part.replace(/^[_-]+|[_-]+$/gu, ''))];
      const named = [...new Set(words.flatMap(word => [word, ...hyphenPrefixes(word)]).filter(word => bodies.has(word)))];
      const allowed = allowedIds(file, node.text);
      const keyExempt = ts.isStringLiteral(node) && exemptField(node, node.text);
      for (const id of named) if (!allowed.includes(id) && !keyExempt) found.push(`${file}: ${JSON.stringify(node.text)} names ${id}`);
    } else if (ts.isIdentifier(node) && PROPERTY_NAMES.some(is => is(node.parent)) && (node.parent as ts.NamedDeclaration).name === node) {
      const id = byCompact.get(compact(node.text));
      if (id && !exemptField(node, node.text)) found.push(`${file}: key ${node.text} names ${id}`);
    }
    ts.forEachChild(node, visit);
  };
  visit(ts.createSourceFile(file, text, ts.ScriptTarget.Latest, true));
  return found;
}

test('no archive module names a shipped body; the bodies a ledger is about are data beside its programs', async () => {
  const bodies = new Set((await readdir(resolve(WORKSPACE, 'src/objects'), { withFileTypes: true })).filter(entry => entry.isDirectory()).map(entry => entry.name));
  const offenders: string[] = [];
  for (const entry of await readdir(import.meta.dirname, { recursive: true })) {
    if (!entry.endsWith('.mts') || entry.endsWith('.test.mts')) continue;
    offenders.push(...bodyMentions(entry, await readFile(resolve(import.meta.dirname, entry), 'utf8'), bodies));
  }
  assert.deepEqual(offenders, []);
});

test('the scope scan catches a body in every place code can name it, and nothing in comments', () => {
  const bodies = new Set(['io', 'europa', 'mercury', 'callisto', 'ganymede', 'alpha-centauri-a', 'moon']);
  const scan = (text: string, file = 'fixture.mts') => bodyMentions(file, text, bodies);
  assert.equal(scan("const scope = ['io', 'EUROPA'];").length, 2, 'quoted strings in any case');
  assert.equal(scan('const table = { europa: 1 };').length, 1, 'an unquoted object key');
  assert.equal(scan("const table = { 'Europa': 1, \"io\": 2 };").length, 2, 'a quoted object key');
  assert.equal(scan('const table = { MERCURY: 199, Callisto: 504 };').length, 2, 'identifier keys in any case');
  assert.equal(scan('const europa = 1; const table = { europa };').length, 1, 'a shorthand key');
  assert.equal(scan('interface Row { readonly AlphaCentauriA: number }').length, 1, 'a key that spells a hyphenated id');
  assert.equal(scan('const name = `${prefix}Europa`; const other = `${a} GANYMEDE ${b}`;').length, 2, 'template-literal segments');
  assert.equal(scan("const path = 'src/objects/europa/prepared'; const flag = `--callisto=${x}`;").length, 2, 'a part of a string with no spaces');
  assert.equal(scan("const cite = 'https://jwst-pipeline.readthedocs.io/en/latest'; const map = 'https://example.org/europa/map.fits';").length, 1,
    'a URL host is not a name, and a body in its path is');
  assert.equal(scan("const adql = \"SELECT * FROM ivoa.obscore WHERE target_name='europa'\";").length, 1, 'a word of an ADQL string');
  assert.equal(scan('const query = `SELECT obs_id FROM caom2.Observation WHERE target_name = ${quote} AND o.instrument_name LIKE \'%\' OR target_name = \'Ganymede\'`;').length, 1,
    'a word of a template query');
  assert.equal(scan("const targets = 'io europa ganymede'.split(' ');").length, 3, 'each word of a space-separated list');
  assert.equal(scan("const program = 'europa-1250'; const pair = 'alpha-centauri-a-b1';").length, 2, 'a program id built on a body id');
  assert.equal(scan("const model = 'ionosphere-model'; const kind = 'moonlight-io2';").length, 0, 'a body id is a whole hyphen-separated part, not any substring');
  assert.equal(scan("const note = 'Europa is an example here';").length, 1, 'a sentence is read word by word');
  assert.equal(scan("// 'callisto'\n/* { europa: 1 } */ const row = { moon: 'x' };").length, 1, 'comments are not names; an ordinary field is one');
});

test('an exemption covers only the listed field of its owning type, or the exact listed string', () => {
  const bodies = new Set(['moon', 'europa', 'sun']);
  const scan = (file: string, text: string) => bodyMentions(file, text, bodies);
  const gemini = 'gemini/archive-ledger.mts';
  assert.deepEqual(scan(gemini, [
    'interface MoonRow { readonly moon: string; readonly "moon2": string }', "type Other = { moon: string };",
    "const a: MoonRow = { moon: 'x' }; const b = { 'moon': 'y' } satisfies Omit<MoonRow, 'frames'>; const c = ({ moon } as MoonRow);",
    "const table = { moon: '301' }; const quoted = { 'moon': '301' }; const loose: Record<string, string> = { moon: 'x' };",
    "const value = { id: 'moon' } satisfies MoonRow; const upper: MoonRow = { MOON: 'x' };",
  ].join('\n')), [
    `${gemini}: key moon names moon`, `${gemini}: key moon names moon`, `${gemini}: "moon" names moon`,
    `${gemini}: key moon names moon`, `${gemini}: "moon" names moon`, `${gemini}: key MOON names moon`,
  ], 'the MoonRow member and MoonRow-typed literals only; another type, an untyped table, a value and another spelling still count');
  assert.equal(scan('keck/other.mts', 'interface MoonRow { readonly moon: string }').length, 1, 'only in the listed module');
  assert.equal(scan('hst/slit-scan-reduction.mts', "requireString(row.sun, 'sun'); requireString(row.sun, 'Sun');").length, 1,
    'a listed string is exempt byte for byte, and only that string');
  assert.equal(scan('keck/archive-ledger.mts', "const s = 'carrying the same number, so 52 Europa is not Jupiter\\'s moon.';").length, 0,
    'a listed sentence may name its listed ids');
  assert.equal(scan('keck/archive-ledger.mts', "const s = 'carrying the same number, so 52 Europa is not Jupiter\\'s moon!';").length, 2,
    'an edited sentence is an offender again');
});
